### ISSUE TITLE
Unable to do large Deletes Supabase Storage Hosted supabase.com

### ISSUE THREAD

**Issue by j-mendez** [supabase/supabase#28015] opened 2024-07-16 10:25 UTC
Hi, when you try to use Supabase storage to delete any record that is moderate in size like a zip file with 100k files zipped etc ( 300mb). Using the UI you cannot delete massive records at once. It fails and you just need to re-try over and over until it is finished watching the system. 

When you perform a recursive delete since we have to list all the files first and delete one by one, we will get rate limited by cloudflare for anything beyond a gig or two for a 520 error or 502. 

Supabase storage is not usable for production with this limitations, is it recommended to use the S3 key directly?

**Comment by j-mendez** [comment] 2024-07-16 15:51
Theres also an infinite loop that happens when you delete a folder from the UI. It just fired 500k request trying to retry.

**Comment by j-mendez** [comment] 2024-07-16 15:59
https://github.com/user-attachments/assets/07983ef8-9810-4bba-b02a-e09862d61a8c

**Comment by j-mendez** [comment] 2024-07-16 16:00
@encima tagging for clarity ^ posted a critical bug on supabase production hosted.

**Comment by j-mendez** [comment] 2024-07-16 16:22
Looks like an update was rolled out I can now see a progress bar upon deleting files. This was not working earlier.

![supabase progress bar working on deleting files for storage](https://github.com/user-attachments/assets/aca3f860-c2eb-40c9-8393-9c328908df16)

**Comment by encima** [comment] 2024-07-16 16:27
Thanks for reporting. I was not able to reproduce and, for larger requests/long running SQL statements, it is recommended to use the API directly or direct connections to the database.

As you can now see the progress bar, I think we can go ahead and close this one.

**Closed by encima** 2024-07-16 16:27 UTC
Labels: bug, external-issue, to-triage

**Comment by j-mendez** [comment] 2024-07-16 17:34
> Thanks for reporting. I was not able to reproduce and, for larger requests/long running SQL statements, it is recommended to use the API directly or direct connections to the database.
> 
> As you can now see the progress bar, I think we can go ahead and close this one.

No problem, It still does not work often from the GUI. Maybe someone with access if they can clone the data from my account to reproduce. The experience is really underpar since it is so slow when it does work too. I bumped up my instance larger just to perform the deletes and it still takes a long time. Please keep the issue open until this is fixed with confirmation.

**Comment by encima** [comment] 2024-07-16 17:41
I think longer operations are expected to take time and timeouts from Cloudflare are sadly unavoidable. 

If others are experiencing this then we can reopen if there are enough comments. 

Increasing the instance size would not have a huge impact as the storage API is only inserting into your DB. 

For any production use case, Storage would be accessed through the API or via S3 as customers would not have access to your project. 

I would suggest you open a support ticket as the team can most likely help to optimise your use case or provide other advice.
