### ISSUE TITLE
BUG: Realtime DELETE updates not being fired

### ISSUE THREAD

**Issue by Monu18765** [supabase/supabase#30027] opened 2024-10-22 12:22 UTC
Hello @kiwicopple  and @w3b6x9, I am facing this weird issue with real-time. Earlier, it used to work, but suddenly, DELETE eventType stopped working for real-time listeners. I am receiving events for `UPDATE` and `INSERT` but not for `DELETE`. 

https://github.com/user-attachments/assets/6c1f2e1b-e423-4513-8218-181cacf04ab5

My Event Listener Code-
```
useEffect(() => {
  const cards = supabase
    .channel('card-all-channel')
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
        table: 'cards',
        filter: `board_id=eq.${params.id}`
      },
      (payload) => {
        console.log('Card Change received!', payload)
        if (payload.eventType === 'UPDATE') {
          setCards((prevData) => {
            const newData: CardRow[] = []
            prevData.forEach((list) => {
              if (list.id === payload.new.id) {
                newData.push(payload.new as CardRow)
              } else {
                newData.push(list)
              }
            })
            return newData
          })
        } else if (payload.eventType === 'INSERT') {
          setCards((prevData) => {
            return [...prevData, payload.new as CardRow]
          })
        } else if (payload.eventType === 'DELETE') {
          setCards((prevData) => {
            const newData = prevData.filter(
              (list) => list.id !== payload.old.id
            )
            return newData
          })
        }
      }
    )
    .subscribe()

  return () => {
    cards
      .unsubscribe()
      .then((message) =>
        console.log(`${message} - Card realtime listener removed.`)
      )
  }
}, [])
```

**Comment by barrownicholas** [comment] 2024-10-22 18:31
Hey! I saw your post in https://github.com/supabase/realtime/issues/1114#issuecomment-2429899763, can you post your RLS policies for that table? Do you have one covering `DELETE` events? By default, if RLS is `ON` and no policy covers `DELETE`, I believe you won't recieve delete events

**Comment by Monu18765** [comment] 2024-10-22 18:55
@barrownicholas here is my policy for the cards table. Deletion is working fine, I am just not getting realtime event.

<img width="1440" alt="Screenshot 2024-10-23 at 12 21 52 AM" src="https://github.com/user-attachments/assets/0222e2ba-fc19-462d-a7f7-03f2cb3d1526">

**Comment by barrownicholas** [comment] 2024-10-22 19:13
My best guess, although @filipecabaco might have some more insight, is if the call to the private schema is somehow getting affected by the `authenticated` user (which performs RLS checks, if I'm not mistaken). If you take a peak in the Docker logs if running via CLI, Docker Desktop > Containers > supabase_realtime_[project name] (or, via Supabase-hosted, https://supabase.com/dashboard/project/______project_id_here______/logs/realtime-logs) does anything weird/anomalous show up?

**Comment by barrownicholas** [comment] 2024-10-22 19:17
Also, @Monu18765 this may get better insights in the https://github.com/supabase/realtime repo ; maybe @filipecabaco can transfer it there?

**Comment by Monu18765** [comment] 2024-10-22 19:29
@barrownicholas my project is using Supabase hosted version and not local development.

**Comment by filipecabaco** [comment] 2024-10-23 06:16
@Monu18765 cod you open a support ticket with prod access so I can get more details?

https://supabase.com/dashboard/support/new

**Comment by Monu18765** [comment] 2024-10-23 13:50
Cool @filipecabaco opening

**Comment by Monu18765** [comment] 2024-10-23 14:01
Hello, @filipecabaco opened a ticket. I have asked the support team to pass the ticket to you.

Thanks

**Comment by Hallidayo** [comment] 2024-10-24 15:02
Hi @Monu18765 - Going to close this one but anything else please feel free to open!

**Closed by Hallidayo** 2024-10-24 15:02 UTC
Labels: bug, external-issue, to-triage

**Comment by Monu18765** [comment] 2024-10-24 16:08
No worries, @Hallidayo. Can you ping @filipecabaco to check my ticket (Support Ticket ID: 15701510055) and reply? I have not received a response.

**Comment by Monu18765** [comment] 2024-10-25 18:21
@Hallidayo and @filipecabaco I am still waiting for a response on my ticket.

**Comment by barrownicholas** [comment] 2024-10-25 18:45
A few helpful points, as it looks like you're new to the Supabase community. 

1. As I mentioned, even if you are using a Supabase-hosted cloud, you can view the logs at this url by placing your Supabase Project ID where `______project_id_here______` is

> or, via Supabase-hosted, https://supabase.com/dashboard/project/______project_id_here______/logs/realtime-logs

Despite the fact that I gave you this, you either failed to read my message entirely or just plainly ignored it:

> @barrownicholas my project is using Supabase hosted version and not local development.

2. You're using a custom schema; if the permissions for the `authenticated` role do not line up between your custom schema (named `private`) and the default schema (`public`) this is likely the cause. However, it is impossible to debug this because you have not provided a minimal reproducible example. Simply copy-pasting your JS client is **not** a minimum reproducible example. We would need to see:
- your schema diff(s) that creates the `private` schema
- your schema diff(s) that creates the tables within the `private` schema
- your schema diff(s) that create the RLS policies on the tables within the `private` schema

3. Support in the `Free` and `Pro` plans is limited in scope (https://supabase.com/support-policy#scope). Your use-case with a custom schema, to me, seems beyond the scope, and thus see 4, infra. 

4. If you want faster support, you need to pay for it (see `Team` and above): https://supabase.com/pricing

5. All of this notwithstanding, Supabase has a great open source community of people who aim to help for free, simply to improve the Supabase ecosystem. Netiquette goes a long way.

6.   You've only mentioned @filipecabaco because I did, first. And that is because I have had a great working relationship debugging a few Realtime issues in the past... but it took effort from **both** @filipecabaco and myself. The tone you use

> @Hallidayo and @filipecabaco I am still waiting for a response on my ticket.

is just honestly inappropiate and I now regret mentioning @filipecabaco 's name at all. 

### ALSO
You're not even listening to the right schema for changes:

`schema: 'public',`

Should be `schema: 'private',` on line 7 of your example. Before blasting @filipecabaco and @Hallidayo , maybe debug your code a bit.

**Comment by Monu18765** [comment] 2024-10-25 20:24
@barrownicholas Fixed it, man. I apologize for my harsh behavior because I have been stuck on this issue for the past 4 days. 
So the bug is I am using a filter for the `DELETE` event. I am pretty sure you didn't also realize. It is very hard for me or anyone to guess that coming from Firebase or NoSQL database.

<img width="790" alt="Screenshot 2024-10-26 at 1 44 47 AM" src="https://github.com/user-attachments/assets/1c191782-407c-42ed-9caa-1820e5c283b5">

Hope you pardon me and fix the documentation. `*` event doesn't make really sense to me if you are using the filter because it will not work for the `DELETE` event. Please move the above alert to the top so that people can be alerted quickly.

**Comment by filipecabaco** [comment] 2024-10-29 10:43
@Monu18765 sorry for the delay, been a bit full of work.

and you are right, this is a very tricky pitfall. we want to redo our docs so we will try to make this more visible

**Comment by clod44** [comment] 2025-02-23 16:17
I want to add this here to expose more alternative solutions to google for people like me.

### Supabase realtime subscription DELETE events do work with filters if you;
`ALTER TABLE public.TableNameHere REPLICA IDENTITY FULL;`

**there are probably some consequences** of replica identity alterification. for my case, it wasn't important so i didn't dive into it.
