### ISSUE TITLE
Cannot destructure property 'data'

### ISSUE THREAD

**Issue by Thecuber337** [supabase/supabase#3942] opened 2021-11-18 11:37 UTC
Hi i dont know if this is a bug or some error with my code so pls dont mind me.

this is the error that is shown:
```TypeError: Cannot destructure property 'data' of '(intermediate value)' as it is undefined.```

I am trying to make a api that stores the user's settings through post request 

This is the section from where the error is occurring (according to my terminal)
```js
let { data, error } = await supabase
		.from('test')
		.insert({ username: "test", setting: "test" })
		.then(val => { 
       return res.send(`Your profile "${name}" has been added`)
      , console.log(`New setting added with name ${name}`)
    })

	if (error) {
		console.error(error)
		return res.send(error)
	}
```

I use JS btw
Thank you in advance.

**Comment by kiwicopple** [comment] 2021-11-20 10:59
Hey @Thecuber337 - it looks like this could be an error with axios somewhere in your code:

https://stackoverflow.com/questions/65695158/axios-post-not-returning-data-from-server-cannot-destructure-property-data-o

I'll close this for now but feel free to comment here if it looks like it's caused by supabase-js!

**Comment by AndrianBalanescu** [comment] 2022-05-07 01:41
![image](https://user-images.githubusercontent.com/37745667/167232913-ef8aa0c0-4baa-45d9-9831-5a687633cc07.png)
![image](https://user-images.githubusercontent.com/37745667/167232973-b2a47909-102b-4eca-abc4-eb028c6e55db.png)

same error here  and is not axios supabase storage js node modules is using cross-fetch

**Comment by kiwicopple** [comment] 2022-05-23 07:39
Hey @AndrianBalanescu  - can you please try to update your code to this?

```
let { data, error } = await supabase
	.from('test')
	.insert({ username: "test", setting: "test" })

	if (error) {
		console.error(error)
		return res.send(error)
	}

	console.log(`New setting added with name ${name}`)
	return res.send(`Your profile "${name}" has been added`)
```

Basically - try removing the `then()` statement (since you are awaiting the data response)

**Closed** 2022-09-26 18:52 UTC
Labels: bug
