### ISSUE TITLE
Email confirmation still required even after disabling email confirmations

### ISSUE THREAD

**Issue by itsycrm** [supabase/supabase#7451] opened 2022-06-27 05:15 UTC
# Bug report

## Describe the bug

With supabase.auth.signUp it's still requiring verification of email even after disabling email confirmations. 

## Expected behavior

It's expected that with email confirmations disabled, the user should be able to sign in without confirming their email.

## Screenshots
![Screen Shot 2022-06-27 at 1 10 03 AM](https://user-images.githubusercontent.com/108031138/175864880-872e884e-f611-4aa8-b809-c39d52e94460.png)

![Screen Shot 2022-06-27 at 1 10 14 AM](https://user-images.githubusercontent.com/108031138/175864894-5e736179-7452-4d2b-8dd3-fc4202279bb5.png)

**Comment by kiwicopple** [comment] 2022-06-28 19:11
looks like this one is a duplicate of this issue: https://github.com/supabase/supabase/issues/5113

I'll close this and track there 👍

**Closed by kiwicopple** 2022-06-28 19:11 UTC
Labels: bug
