### ISSUE TITLE
Date type column is filled with timestamp value instead of NULL when add a new record.

### ISSUE THREAD

**Issue by peterkimzz** [supabase/supabase#2861] opened 2021-08-17 05:46 UTC
Here is my `deleted_at` column that has default value `NULL` and `timestamp` type.

![image](https://user-images.githubusercontent.com/20244536/129669286-8adfb12a-3c48-44cb-b6c2-fa52795af97d.png)

The problem is that when I add a new record without setting `deleted_at` value, supabase automatically filling value with current datetime. Below is the issue.

![Animation1](https://user-images.githubusercontent.com/20244536/129669951-a697e031-a6db-43ae-836c-fe20e19030db.gif)

Right, after insert a new record, just remove all datetime value with blank. But it is really annoying..

If it is hard to resolve this issue immediately, I just want a **Set Null value** button only for a column that has date, timestamp type when open **edit a row** popup.

**Comment by darora** [comment] 2021-08-17 07:50
Hi @peterkimzz - this is really strange; I just tested it out, and while we provide the current timestamp as a default in the field to insert a new row, if you delete the default, it does get inserted as null for me.

I wonder if this is related to localization? @phamhieu

**Comment by phamhieu** [comment] 2021-08-17 09:31
i think the problem is: 
- @peterkimzz set the default to NULL
- but the sidepanel show row creation with default to NOW()

**Comment by joshenlim** [comment] 2021-09-28 04:18
Hey there @peterkimzz! This issue has been addressed and the fix has been pushed out :) Do give it a spin and feel free to reopen this issue if you do run into any other issues.

**Closed by joshenlim** 2021-09-28 04:18 UTC
Labels: enhancement
