### ISSUE TITLE
Long table titles are truncated

### ISSUE THREAD

**Issue by madsbuch** [supabase/supabase#12834] opened 2023-03-06 13:25 UTC
# Bug report

## Describe the bug
It is not possible to read the long title of the sidebar when exploring tables.

## To Reproduce

Navigate into the Table editor and see that the left sidebar containing the list of tables can not be expanded.

## Expected behavior

When hovering the mouse on the edge I would expect to be able to resize that sidebar.

## Screenshots

<img width="446" alt="Screenshot 2023-03-06 at 13 23 24" src="https://user-images.githubusercontent.com/1612807/223122565-f31fc676-68f9-4a84-92a6-b89e41aee176.png">

**Comment by GaryAustin1** [comment] 2023-03-06 15:12
This is a duplicate of this still open issue:  https://github.com/supabase/supabase/issues/9910

**Comment by saltcod** [comment] 2023-03-14 09:38
Hey @madsbuch thanks for the report. Just had a look through and see that its still possible to reveal the full name by hovering the truncated name there. Going to mark this as closed, as we have no immediate plans for allowing expanding of the sidebar there in the layout.

**Closed by saltcod** 2023-03-14 09:38 UTC
Labels: bug, duplicate, dashboard

**Comment by madsbuch** [comment] 2023-03-14 11:27
@saltcod yes, I see that there is the title attribute set. however, this is extremely wonky and the title is often not being shown on hover.

all in all, the current setup yields terrible developer ergonomics when working with tables that has long titles.

I am sad to see that you choose to ignore this issue. especially given that it should be considered low lift to allow resizing the sidebar.
