### ISSUE TITLE
Can't delete rows from Supabase UI

### ISSUE THREAD

**Issue by Sulomus** [supabase/supabase#5444] opened 2022-02-13 18:50 UTC
# Bug report

## Describe the bug

I am unable to delete rows via dashboard (using cloud version of Supabase not selfhosted). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to table editor > tables > your table
2. Click on 'delete rows'
3. refresh

## Expected behavior

The rows should be deleted

## Video

https://user-images.githubusercontent.com/49107150/153769989-16ad1e35-5f1a-4aef-b25e-50f9e587b4dd.mp4

## System information

- OS: Windows 11
- Browser: Chrome
- Version of supabase-js: cloud dashboard

**Comment by joshenlim** [comment] 2022-02-14 01:58
Hey @Sulomus! would you mind checking the network tab (and adding a screenshot here of it) to see if the request went through when you tried to delete the rows?

**Comment by MildTomato** [comment] 2022-05-03 09:57
Closing this issue as it seems fixed.

@Sulomus If you're still getting this issue please feel free to reopen

**Closed by MildTomato** 2022-05-03 09:57 UTC
Labels: bug

**Comment by jahilldev** [comment] 2022-07-21 20:58
@MildTomato I've just run into this, I was deleting large numbers of rows in a table, but reached a final three that just won't delete using the UI. 

I've tried multiple times, but they're still there.

**Comment by Johnrobmiller** [comment] 2023-06-04 03:28
this is still a bug, please reopen

**Comment by gregnr** [comment] 2023-06-05 20:18
@jahilldev @Johnrobmiller any chance you have some sample migrations/data to reproduce? Just tried to reproduce by deleting rows in the cloud dashboard and everything appears to delete successfully (note it looks like rows currently need a PK to delete/update using the dashboard, otherwise you'll see an error in the top right)

**Comment by nawed2611** [comment] 2023-08-20 07:28
Hey, I seem to be facing this as well. I'm not getting any option to delete rows on the UI

**Comment by Mihai-github** [comment] 2023-08-23 10:00
+1

**Comment by shobhamrj** [comment] 2023-09-18 07:25
+1

**Comment by Levelleor** [comment] 2024-02-12 20:13
Yup. Still a bug. I was able to delete all entries from table via SQL `DELETE FROM table_name` but the UI returned with an error that there are persisting relations (which were not a thing as I deleted the linking table with all contents as well).

**Comment by joshenlim** [comment] 2024-02-13 03:15
hey there @Abdalla-Mon and @Levelleor, would you mind providing some screen recordings to reproduce this issue? and also check the network tab real quick to see if the API requests are failing (and if so, what are the corresponding errors messages)

**Comment by Levelleor** [comment] 2024-02-13 16:44
@joshenlim sorry, I've already deleted the whole table from the console manually. If I see it again I'll let you know. For more context, just in case, I also tried disabling browser cache and deleting it before deleting the entries which changed nothing for me, assuming that the issue most likely is not in the frontend side of things. The fact that the `DELETE` command worked probably means the UI performs some additional checks or executes the command differently which brought up an error. 

Also. One more weird thing. I was able to remove one of the tables 1 page at a time. There were something like 10k entries and I removed all of them in batches per page. But when I tried cleaning the whole table with all 10k selected it was showing me the error that there are unresolved references. Could it be that the error message is just wrong and Supabase basically hangs on such large operations?

**Comment by joshenlim** [comment] 2024-02-14 07:58
> I removed all of them in batches per page
How did you do this? Through the table editor or SQL editor?

> showing me the error that there are unresolved references
Do you have a screenshot for this?

> Could it be that the error message is just wrong basically hangs on such large operations
Not really - you can verify as well by checking the network requests tab, the error that the dashboard shows will be what's reflected from the request. "Unresolved references" -> I'm not too sure exactly what this refers to (sounds like foreign key reference?) Does your table have a foreign key to another table?

If you could provide some screen recordings or screenshots it'll help us greatly in debugging! 🙏  Once you have them ready let's create a new ticket then and not continue this thread on a closed ticket 🙏

**Comment by sp88011** [comment] 2024-02-16 22:03
Running into the same issue. Deleting 100 at a time works, but when I select all 20k rows and hit delete I get this error `ERROR:  0A000: cannot truncate a table referenced in a foreign key constraint.....` Screenshot of network tab attached

<img width="1494" alt="image" src="https://github.com/supabase/supabase/assets/5287078/0fc31dd2-eb68-4841-b124-c068a8eae662">

**Comment by AC40** [comment] 2024-02-20 12:45
I have a similar issue. When I try to delete any number of rows in my Dashboard, I recive a success toast notification, but the rows are still there. In the moment of deletetion, the console shows four failed network requests:

<img width="1090" alt="Screenshot 2024-02-20 at 13 44 18" src="https://github.com/supabase/supabase/assets/81184358/4d80ed58-f5c2-4170-bc5f-a7088732cee7">

Any help or pointers would be greatly appreciated.

**Comment by jdc20181** [comment] 2024-03-10 20:54
I have this issue as well. I noticed it is labeled as "won't fix" but I don't quite understand why it won't be fixed as it is a crucial function of database management. Toggling RLS did not seem to fix this either. My other table is deleting just fine. Its a strange bug for sure.

**Comment by Yassdrk** [comment] 2024-04-03 09:05
hello, it's a big bug omg why it's not fixed ?

**Comment by joshenlim** [comment] 2024-04-03 09:34
hey everyone - for those running into this issue, could you please provide some details for us to reproduce? As I'm not able to reproduce this in the hosted platform. 

- Are you running into this on the hosted platform or local/self-hosted?
- Are there any network requests from the network tab that's error-ing out?
- Any videos to reproduce this issue is really appreciated as it'll help us target any potential issues much faster 🙏 

@sp88011 The error in the network request does show what's wrong "ERROR:  0A000: cannot truncate a table referenced in a foreign key constraint" - this indicates that one of your rows is being referenced by another table by a foreign key relation, hence why it cannot be deleted. You will need to remove the reference first in the other table before being able to delete that row.

@AC40 these are all red-herrings unfortunately, could you add some screenshots from the network tab instead?

**Comment by jdc20181** [comment] 2024-04-03 11:47
The issue seems to be random in nature. I was able to do delete on Day A but on Day B it would not work. Now many days later, I can delete them. What difference I have between now and them is I have an unique ID. *this seems* to perhaps be a potential solution to the issue (unsure why unless its required?)

> * Are you running into this on the hosted platform or local/self-hosted?

Hosted for now, plans to migrate to self-hosted eventually.

**Comment by jonathanlal** [comment] 2024-05-10 20:37
Constantly getting this error too - running supabase locally. Super frustrating

**Comment by AC40** [comment] 2024-05-11 10:57
For me, the issue was related to some PG on delete triggers I had set up. It was not necessarily my fault, just some weird interaction due to the existence of a trigger. Could that be cause of the issue for you? I figured it out by disabling triggers one by one until i found one that broke it
I can maybe go more into depth if this proves to be your issue as well when I have time.

**Comment by Lueton** [comment] 2025-01-29 13:35
I also run into this issues in combination with triggers. It would be really helpful if there was at least an error message somewhere. There is neither an error message at the table view nor in the logs.

**Comment by nazero3** [comment] 2025-06-12 11:16
cant delete row in users table 

![Image](https://github.com/user-attachments/assets/37148151-2ad5-46d5-9a3f-e4865130893b)

**Comment by moon-home** [comment] 2025-06-30 19:40
I got a slightly different issue. the delete button simply doesn't always appear. 
I say "doesn't" because if I go to a different table and select some rows that button will appear, then I came back to the table that I actually want to delete, the button will appear, so there is a workaround, but it's annoying.

<img width="178" alt="Image" src="https://github.com/user-attachments/assets/7d4f1795-a880-4a15-a047-3e3763b43ab9" />
