### ISSUE TITLE
Database Usage insanely high without much data

### ISSUE THREAD

**Issue by realmercy** [supabase/supabase#11580] opened 2023-01-11 04:19 UTC
# Bug report

## Describe the bug
Database usage shows very high space usage even though there's not much data on it.
--
Hello, I'm currently trying out supabase to use the postgres server in the free tier. I have 2 tables on the db namely "servers" and "roles". The "servers" table is just a list of discord server ids and it currently only has 2 rows, while the "roles" table has 4 columns and 2 rows. Going into /project/{projectid}/database/tables shows the estimated size as 24kb and 32kb 
![image](https://user-images.githubusercontent.com/90040892/211716100-138f89b4-c6ff-4b81-bb9a-9b5e72666cde.png)
but going into /project/{projectid}/settings/billing/usage it shows me I have used up 69.16 mb out of the free 512 mb 
![image](https://user-images.githubusercontent.com/90040892/211716274-c8b8c3ce-1bd7-4632-9897-53fca319e02f.png)
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Screenshots
I have uploaded screenshots in the "Describe the bug" section
## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by GaryAustin1** [comment] 2023-01-11 21:26
You can run this in the SQL editor to see all the tables in the database (internal Postgres tables, storage tables, auth tables, realtime tables, etc...
`SELECT pg_size_pretty(pg_total_relation_size(oid)), relname FROM pg_class WHERE relkind = 'r' AND NOT relisshared;`

**Comment by GaryAustin1** [comment] 2023-02-03 23:52
@realmercy 
A brand new instance currently has over 70MB used.  This is all overhead just in all the database internal tables, etc and some from realtime/auth/storage/etc.

![image](https://user-images.githubusercontent.com/54564956/216731797-fec96ceb-43f5-455c-b83e-99f602dedd21.png)

This is not a bug in that nothing is wrong with your particular instance.

Can you close this issue, or follow up with what you are looking for?   (I can't close issues but trying to help clean up backlog).

**Comment by realmercy** [comment] 2023-02-04 09:05
@GaryAustin1 thanks that clears up the confusion i had, sorry for not replying earlier, closing this 👍

**Closed** 2023-02-04 09:05 UTC
Labels: bug
