### ISSUE TITLE
signup without password?

### ISSUE THREAD

**Issue by ianstormtaylor** [supabase/supabase#3399] opened 2021-10-01 15:17 UTC
### Is your feature request related to a problem? Please describe.

It looks like there's the ability to use magic links to log in. But I can't figure out a way to have a user sign up without requiring a password in the beginning. If they provide and email, confirm it, and then always use magic links, why require a password at all?

### Describe the solution you'd like

Ideally the `password` option would be optional for sign up.

**Comment by bnjmnt4n** [comment] 2021-10-01 15:46
It's not very well documented, but you can use [`supabase.auth.api.sendMagicLinkEmail`](https://supabase.github.io/gotrue-js/classes/gotrueapi.html#sendmagiclinkemail) to send the link without requiring a password.

**Comment by ianstormtaylor** [comment] 2021-10-01 16:26
What if you want to allow them to enter their email to create an account without having to confirm it first though? 

In other words, I was hoping to accept an email, move on to other parts of a setup flow, and not require them going to confirm it until later.

**Comment by bnjmnt4n** [comment] 2021-10-01 16:49
So you'd like to have data associated with a certain user email even before the email is confirmed?

**Comment by kiwicopple** [comment] 2021-10-04 13:46
> a way to have a user sign up without requiring a password in the beginning

Hi @ianstormtaylor , in this case you can just use `signIn` without any password. If the account doesn't exist it will be created automatically.

I'll close this for now (since there's not technically a bug). Feel free to comment again if i misunderstood, and I'll reopen.

**Closed by kiwicopple** 2021-10-04 13:46 UTC
Labels: enhancement

**Comment by ianstormtaylor** [comment] 2021-10-04 16:48
@kiwicopple interesting. But then later on when someone comes back to sign in... if they mistype their email address (or forget which one they used to sign up) there's no way of knowing whether I'm signing them in to their existing account or accidentally creating a brand new account?

Having the `signIn` function be able to result in a new account being created seems off to me.

**Comment by songololo** [comment] 2021-12-23 12:46
I agree with @ianstormtaylor - this is pretty confusing behaviour and makes it difficult to handle user signIn vs. signUp logic.

**Comment by kiwicopple** [comment] 2021-12-23 13:53
We're discussing this one over here:

https://github.com/supabase/supabase/issues/1176#issuecomment-973894582

**Comment by guizoxxv** [comment] 2023-03-04 17:05
I understand that the `sendMagicLink` creates user if it one does not exists without password, but I don't want to send the magic link during the user creation. I want to create the user, and in a later moment when the user provide his email to sign in, then I'll send the magic link. Therefore I think it would be nice to be able to use `signUp` or another method without providing a password.
