### ISSUE TITLE
Impersonate user list limited to 10 records and search doesn't go beyond them 

### ISSUE THREAD

**Issue by themightychris** [supabase/supabase#27352] opened 2024-06-18 14:06 UTC
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

List of users to impersonate in Table Editor is limited to 10 and the search filter only filters the 10 already loaded. There is no way to impersonate users beyond the first 10 records

## To Reproduce

1. Have more than 10 users
2. Go to table editor
3. Try to impersonate a user who is beyond the first 10

## Expected behavior

While limiting the initial list to 10 is reasonable, when I type a search it should run a backend search so that I can find any user

## Screenshots

<img width="808" alt="Screenshot 2024-06-18 at 10 04 01 AM" src="https://github.com/supabase/supabase/assets/458494/db1c548a-f8bc-48bb-9f4c-cb33b8ad3a54">

**Comment by FatumaA** [comment] 2024-08-24 20:46
Hi,
Could you confirm if this is still an issue for you?

I can't reproduce it. It works as expected. Shows 10 users then search for the others, the results contain them and you can impersonate them.

**Comment by Hallidayo** [comment] 2024-09-24 19:59
Hi all, I also am unable to re-produce this issue so I am going to close this now. Please feel free to reopen if you’re still having issues here or open a new issue.

**Closed by Hallidayo** 2024-09-24 19:59 UTC
Labels: bug, frontend
