### ISSUE TITLE
resumable upload (TUS) return wrong upload URL (Flutter / Dart, self-hosted) 

### ISSUE THREAD

**Issue by lukkaempf** [supabase/supabase#15703] opened 2023-07-11 17:17 UTC
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I want to use the resumable upload feature in my self-hosted Supabase environment. 

I start the first POST request to the URL: http://localhost:8000/storage/v1/upload/resumable/
Then the server responds to this request with the upload URL, but in the wrong format. Incorrect URL: http://localhost/upload/resumable/bXlidWNrZXQvZXZlbnQuanBnLzE5OGExMTYwLTJhYjYtNDkxMS05MmZmLTllMjU4NDMyYjZkYQ
Following is the full response header after the first request with the wrong URL:
`{connection: keep-alive, location: http://localhost/upload/resumable/bXlidWNrZXQvZXZlbnQuanBnLzdhYTExODRkLWVlZTEtNDUyNC04YjkxLWJiY2I3MWQ5NWY5Yg, date: Tue, 11 Jul 2023 17:04:40 GMT, access-control-allow-origin: *, x-kong-proxy-latency: 3, content-length: 0, access-control-expose-headers: Authorization, Content-Type, Location, Tus-Extension, Tus-Max-Size, Tus-Resumable, Tus-Version, Upload-Concat, Upload-Defer-Length, Upload-Length, Upload-Metadata, Upload-Offset, X-HTTP-Method-Override, X-Requested-With, X-Forwarded-Host, X-Forwarded-Proto, Forwarded, Upload-Expires, tus-resumable: 1.0.0, via: kong/2.8.1, x-kong-upstream-latency: 47}`

BUT the strange thing is, it works with Javascript and the Uppy Library, but not with Dart / Flutter and the [TUS Client Library](https://pub.dev/packages/tus_client)

## To Reproduce

Start the initial POST request:
 ```
 final tusTestResponse = await http.Client().post(
                            Uri.parse(
                                'http://localhost:8000/storage/v1/upload/resumable/'),
                            headers: {
                              'x-upsert': 'true',
                              'authorization':
                                  'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q',
                              'Tus-Resumable': '1.0.0',
                              'Upload-Metadata':
                                  'bucketName bXlidWNrZXQ=,objectName ZXZlbnQuanBn,contentType aW1hZ2UvanBlZw==,cacheControl MzYwMA==,filename aW1hZ2UuanBlZw==',
                              'Upload-Length': '175011',
                              'Content-Type': 'application/octet-stream'
                            });

                        print(tusTestResponse.headers);
```
Then you will see in the headers that the URL is not correct.
Yes, I can change the upload URL manually, but the problem also exists in the [Dart TUS Client](https://pub.dev/packages/tus_client) Library.

## Expected behavior

Supabase should return the correct Upload URL. Like so:
http://localhost:8000/storage/v1/upload/resumable/bXlidWNrZXQvZXZlbnQuanBnLzdhYTExODRkLWVlZTEtNDUyNC04YjkxLWJiY2I3MWQ5NWY5Yg

## System information

- OS: macOS
- Supabase Versions:
<img width="763" alt="image" src="https://github.com/supabase/supabase/assets/64331815/c0ae72bd-a559-43c6-969d-0a3149b5ee9c">

**Comment by NicolasReibnitz** [comment] 2023-07-31 12:27
The same issue occurs using the TUS JavaScript library locally. I don't think this has anything to do with Flutter/Dart.

**Comment by Obeyed** [comment] 2023-08-07 13:34
I stumbled on the same issue. The upload url doesn't respect the given port. I tried wtih the tus-js-client. Haven't tried with uppyjs.

I can add that the protocol at some point in the upload process changes from https to http, giving the following error in the browser:

```
Mixed Content: The page at 'https://xxxx' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://<a-kong-gateway-domain>/upload/resumable/<some-resumable-upload-id>'. This request has been blocked; the content must be served over HTTPS.
```

which also strips the `storage/v1/` part of the url.

The funky thing is that it changes from uploading to the right url to this at some point.

I haven't looking any further into the cause.

I asked a [question on the storage repo](https://github.com/supabase/storage-api/issues/331#issuecomment-1667819822) before I noticed this open issue.

**Comment by fenos** [comment] 2023-08-08 12:23
Hello!

If you are using the supabase cli to startup your environment make sure you are on the latest version, since this issue should be fixed.

For self-hosting tips, have a look at the answer on the storage repo https://github.com/supabase/storage-api/issues/331#issuecomment-1669504402

**Closed** 2023-08-08 12:28 UTC
Labels: bug, storage
