### ISSUE TITLE
Email template doesn't allow body and head tag

### ISSUE THREAD

**Issue by orkeilius** [supabase/supabase#15454] opened 2023-06-29 14:09 UTC
# Email template doesn't allow body and head tag
## Describe the bug

If you add a body or head tag in your email it will be removed by the server when saving

## To Reproduce

Make a email template with a body or head tag

## Expected behavior

Allow head and body tag

### why ?
Because on gmail (probably other mail client as well), you must place your style tag in your head tag  
[source](https://developers.google.com/gmail/design/css)

So currently we can only use inline css that doesn't support hover state or complex css

## System information

- Version of supabase: current ( 0.22.03 ) on supabase.com
- Plan : free ( you can force the supabase branding even with a head/body tag )

**Comment by GaryAustin1** [comment] 2023-06-29 15:28
Seems a duplicate of this: https://github.com/supabase/supabase/issues/15408

**Closed** 2023-06-30 08:47 UTC
Labels: bug, duplicate
