### ISSUE TITLE
Logs suddenly unavailable

### ISSUE THREAD

**Issue by nehalist** [supabase/supabase#19227] opened 2023-11-25 23:11 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I've played around with functions today and all of a sudden my logs (all of them, from Kong API to Realtime) do not work anymore:

```
{
  "code": 500,
  "message": "An error has occurred: fetch failed",
  "requestId": "b9bf9437-a30b-4c70-a7d6-8f6f1c0c86e4"
}
```

I've completely re-initialized Supabase afterwards (stop with no-backup, delete supabase dir and run npx supabase init again).

Also tried to find the root of this error, but neither using `docker logs <container name>` nor entering the container and searching log files led to something.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. npx supabase init
2. go to logs
3. error

## Expected behavior

I'd see my logs.

## Screenshots

not relevant

## System information

- OS: linux
- Browser (if applies) [e.g. chrome, safari] chrome

```
361b7658414e   public.ecr.aws/supabase/studio:20231023-7e2cd92   "docker-entrypoint.s…"   17 minutes ago   Up 17 minutes (healthy)   0.0.0.0:54323->3000/tcp, :::54323->3000/tcp                            
f9f18cc2f52b   public.ecr.aws/supabase/postgres-meta:v0.68.0     "docker-entrypoint.s…"   17 minutes ago   Up 17 minutes (healthy)   8080/tcp                                                               
e7ee54b7fed3   public.ecr.aws/supabase/edge-runtime:v1.22.4      "sh -c 'mkdir -p /ho…"   17 minutes ago   Up 17 minutes             8081/tcp                                                               
a2975762308d   public.ecr.aws/supabase/imgproxy:v3.8.0           "imgproxy"               17 minutes ago   Up 17 minutes (healthy)   8080/tcp                                                               
ee73e4022b94   public.ecr.aws/supabase/storage-api:v0.40.4       "docker-entrypoint.s…"   17 minutes ago   Up 17 minutes (healthy)   5000/tcp                                                               
16325a785a4d   public.ecr.aws/supabase/postgrest:v11.2.0         "/bin/postgrest"         17 minutes ago   Up 17 minutes             3000/tcp                                                               
ecf2992296fc   public.ecr.aws/supabase/realtime:v2.25.27         "/usr/bin/tini -s -g…"   17 minutes ago   Up 17 minutes (healthy)   4000/tcp                                                               realtime-dev.
8199b2ccf3d4   public.ecr.aws/supabase/inbucket:3.0.3            "/start-inbucket.sh …"   17 minutes ago   Up 17 minutes (healthy)   1100/tcp, 2500/tcp, 0.0.0.0:54324->9000/tcp, :::54324->9000/tcp        
070c01a14a99   public.ecr.aws/supabase/gotrue:v2.99.0            "gotrue"                 17 minutes ago   Up 17 minutes (healthy)   9999/tcp                                                               
3b9fa79ec560   public.ecr.aws/supabase/kong:2.8.1                "sh -c 'cat <<'EOF' …"   17 minutes ago   Up 17 minutes (healthy)   8001/tcp, 8443-8444/tcp, 0.0.0.0:54321->8000/tcp, :::54321->8000/tcp   
c02ead7e5685   public.ecr.aws/supabase/postgres:15.1.0.117       "sh -c 'cat <<'EOF' …"   18 minutes ago   Up 18 minutes (healthy)   0.0.0.0:54322->5432/tcp, :::54322->5432/tcp                            
```

**Comment by SenneVanderAuwera** [comment] 2023-11-28 11:13
I'm having the same issue.

**Comment by AdamBuchweitz** [comment] 2023-11-28 22:31
Fresh Docker installation (Windows), same issue

**Comment by catchbox-software-team** [comment] 2023-11-30 09:54
Also experiencing the issue. Quite a blocker for my development.
Supabase team - you are amazing. Thanks for all the hard work and inovation!

**Comment by nehalist** [comment] 2023-11-30 20:59
For whatever reason the `config.toml` from the [init command](https://github.com/supabase/cli/blob/c600ca82b7d7219a7da4964ae737394d8d3cee02/internal/utils/templates/init_config.toml#L132) sets `enabled` of `analytics` to `false`. Analytics is just another name for logflare - which is responsible for logs. Setting `enabled = true` fixes unavailable logs - at least for me.

**Comment by Rudolf-Dudarev** [comment] 2023-12-01 08:47
> For whatever reason the `config.toml` from the [init command](https://github.com/supabase/cli/blob/c600ca82b7d7219a7da4964ae737394d8d3cee02/internal/utils/templates/init_config.toml#L132) sets `enabled` of `analytics` to `false`. Analytics is responsible for logs. Setting `enabled = true` fixes unavailable logs - at least for me.

Solved it for me too. Thanks a bunch!

**Comment by igorlanko** [comment] 2023-12-10 03:14
I have mine set to `true`, however still not seeing any logs in Postgres page 
```toml
[analytics]
enabled = true
port = 54327
vector_port = 54328
# Configure one of the supported backends: `postgres`, `bigquery`.
backend = "postgres"
```

macOS, CLI `1.115.5`.

**Comment by monicakh** [comment] 2023-12-10 08:57
I noticed in the screenshot that you have "postgres_logspostgres_logs" appended at the end of the query, which is causing the error. To resolve this, please modify the query as shown below:
```sql
select postgres_logs.timestamp, id, event_message, parsed.error_severity from postgres_logs
 cross join unnest(metadata) as m
 cross join unnest(m.parsed) as parsed

 order by timestamp desc
 limit 100
```

**Comment by igorlanko** [comment] 2023-12-10 16:17
Hey @monicakh, this seems to be happening regardless of that unfortunately. For example here's what I see if I just select postgres as a source.

![CleanShot 2023-12-10 at 11 15 39](https://github.com/supabase/supabase/assets/31314207/c3ac0aa5-cad0-48b9-8628-d047ea5865e9)
![CleanShot 2023-12-10 at 11 15 43](https://github.com/supabase/supabase/assets/31314207/5705b683-80ab-4a1b-a42f-40b8adeddc30)

**Comment by dsl400** [comment] 2023-12-29 17:29
not really  sure if it is related, I noticed that after I enabled analytics and ran `supabase start` I get a lot cpu usage caused by data being constantly inserted into `_analytics.log_events_0f697473_6cad_48c1_aab3_44ef06ca3ab1`. 
I truncated the table and after a few seconds it gathered more than 100Mb

`{
  "id": "59e2be13-6da8-400d-b516-f6f0eab2d95c",
  "appname": "supabase_db_mp",
  "project": "default",
  "metadata": {
    "host": "db-default",
    "parsed": {
      "timestamp": "2023-12-29T19:19:23Z",
      "error_severity": "WARNING"
    }
  },
  "severity": "err",
  "timestamp": 1703877563000000,
  "event_message": "192.168.0.4 2023-12-29 17:19:23.035 UTC [66] postgres@postgres LOG:  AUDIT: SESSION,62356,1,WRITE,INSERT,,,\"INSERT INTO \"\"_analytics\"\".\"\"log_events_0f697473_6cad_48c1_aab3_44ef06ca3ab1\"\" (\"\"body\"\",\"\"event_message\"\",\"\"id\"\",\"\"timestamp\"\") VALUES ($1,$2,$3,$4)\",<not logged>"
}`

**Comment by samrose** [comment] 2024-01-16 12:54
> For whatever reason the `config.toml` from the [init command](https://github.com/supabase/cli/blob/c600ca82b7d7219a7da4964ae737394d8d3cee02/internal/utils/templates/init_config.toml#L132) sets `enabled` of `analytics` to `false`. Analytics is responsible for logs. Setting `enabled = true` fixes unavailable logs - at least for me.

This resolved the issue for me too. It just took about 20 seconds or so for the logs to start showing in the dashboard

**Comment by encima** [comment] 2024-01-18 09:39
Closing this as analytics enabled is the solution and documentation is [here](https://supabase.com/docs/reference/self-hosting-analytics/introduction#getting-started)

**Closed by encima** 2024-01-18 09:39 UTC
Labels: bug

**Comment by g1ronn1mo** [comment] 2024-05-02 18:14
## 1. Enable Analytics in the config.toml

For whatever reason the `config.tom`, located in the supabase folder, from the init command sets `enabled` of `analytics` to false. 

```toml
[analytics]
enabled = false
```

Analytics is responsible for logs. Setting `enabled = true` fixes unavailable logs explained [here](https://supabase.com/docs/reference/self-hosting-analytics/introduction#getting-started).

## 2. Backup the Data

Follow the instructions [here](https://supabase.com/docs/guides/cli/getting-started#installing-the-supabase-cli) to make a logical backup. with:

```sh
supabase db diff my_schema
supabase db dump --local > supabase/seed.sql
```

## 3. Stop Your Docker Containers


```
supabase stop 
```

This command stops and removes all containers defined in the docker-compose.yml file but preserves your data.

## 4. Start Your Docker Containers
```bash
supabase start
```

This command starts the containers again.
