### ISSUE TITLE
Tables created via UI are not granted any access privileges 

### ISSUE THREAD

**Issue by zacatac** [supabase/supabase#3544] opened 2021-10-15 05:11 UTC
# Bug report

## Describe the bug

Tables created via the Supabase UI do not have any access privileges granted and cannot be accessed using either client or service credentials.

## To Reproduce

1. Create a new table via the supabase UI with default settings (autogen ID and created_at columns). Leave the RLS option deselected.

<img width="301" alt="Screen Shot 2021-10-14 at 10 06 35 PM" src="https://user-images.githubusercontent.com/2539469/137435243-a6a78887-eeb7-4af0-baa0-91466fb4c7bd.png">

2. Attempt to query the table via 
  a. supabase-js client with client keys
  b. supabase-js client with service keys
  c. psql 
in all cases you will get a permission denied error. 
```
{
  hint: null,
  message: 'permission denied for table test_table',
  code: '42501',
  details: null
}
```

## Expected behavior

I should be able to select from a table which has no RLS using both client and service keys.

## System information

- Version of supabase-js: `1.20.0`

## Additional context

psql output below shows that the newly created test_table has no access privileges, but a table created via the UI in the past does have access privileges.

```
postgres=> \z test_table
                                           Access privileges
 Schema |    Name    | Type  | Access privileges | Column privileges |            Policies             
--------+------------+-------+-------------------+-------------------+---------------------------------
 public | test_table | table |                   |                   | Enable access to all users (r):+
        |            |       |                   |                   |   (u): true
(1 row)

postgres=> \z profile
                                                           Access privileges
 Schema |  Name   | Type  |       Access privileges        | Column privileges |                       Policies                        
--------+---------+-------+--------------------------------+-------------------+-------------------------------------------------------
 public | profile | table | postgres=arwdDxt/postgres     +|                   | Profiles are viewable by users who created them. (r):+
        |         |       | anon=arwdDxt/postgres         +|                   |   (u): (auth.uid() = uid)
        |         |       | authenticated=arwdDxt/postgres+|                   | 
        |         |       | service_role=arwdDxt/postgres  |                   | 
```

**Comment by soedirgo** [comment] 2021-10-15 09:19
Hmm, just tried this on a new project and couldn't reproduce it. Here's the psql output (a little different than yours):
```
postgres=> \z t
                                      Access privileges
 Schema | Name | Type  |           Access privileges           | Column privileges | Policies 
--------+------+-------+---------------------------------------+-------------------+----------
 public | t    | table | postgres=arwdDxt/supabase_admin      +|                   | 
        |      |       | supabase_admin=arwdDxt/supabase_admin+|                   | 
        |      |       | anon=arwdDxt/supabase_admin          +|                   | 
        |      |       | authenticated=arwdDxt/supabase_admin +|                   | 
        |      |       | service_role=arwdDxt/supabase_admin   |                   | 
(1 row)
```

**Comment by soedirgo** [comment] 2021-10-16 16:24
Thanks, can you file a support request at https://app.supabase.io/support/new?

**Comment by kungpaogao** [comment] 2022-03-22 17:26
Was there a solution to this other than manually granting access? I also have a similar issue on my project.

**Comment by soedirgo** [comment] 2022-03-22 17:37
Currently you'd need to do it manually, but we're working on a solution that makes it work OOtB.

**Comment by egor-romanov** [comment] 2023-01-20 14:55
I am going to close this for now cause this seems to be fixed. Feel free to re-open if there are some issues left.

**Closed by egor-romanov** 2023-01-20 14:55 UTC
Labels: bug

**Comment by sir-script** [comment] 2024-09-20 13:03
Was it resolved? Does it work for you now? 
I’m having the same issue where no GRANT privileges are created for the authenticated role when I set up the policies through the interface. After manually running /inserting the SQL GRANT command, it works. 
I can reproduce this with every new table so far.

**Comment by sir-script** [comment] 2024-10-03 07:41
> Was it resolved? Does it work for you now? I’m having the same issue where no GRANT privileges are created for the authenticated role when I set up the policies through the interface. After manually running /inserting the SQL GRANT command, it works. I can reproduce this with every new table so far.

Update: It turns out this was not a bug on my end. The issue stemmed from my use of a custom “api” schema. Supabase documentation clearly states that when using an alternate schema, the permissions must be set manually. You can find more details in their guide here: [Supabase Documentation on API Schema](https://supabase.com/docs/guides/database/hardening-data-api#step-2-create-an-api-schema-and-expose-it).
