### ISSUE TITLE
doc search is broken

### ISSUE THREAD

**Issue by Vandivier** [supabase/supabase#4442] opened 2021-12-11 21:03 UTC
# Bug report

## Describe the bug

click any of the search results and receive a 404 page

![image](https://user-images.githubusercontent.com/5559355/145691556-be4ed1fa-bba8-4bdb-b821-20407712a2df.png)

**Comment by inian** [comment] 2021-12-14 07:55
Duplicate of https://github.com/supabase/supabase/issues/4317

**Closed by inian** 2021-12-14 07:55 UTC
Labels: bug
