### ISSUE TITLE
Wrong url is beeing inserted in emails

### ISSUE THREAD

**Issue by OceanTechnic** [supabase/supabase#7768] opened 2022-06-16 15:15 UTC
# Bug report

## Describe the bug
Supabase docker, is inserting `http://auth` into the url in emails as it should insert `GOTRUE_SITE_URL` from env

## To Reproduce
1. Install new supabase inside docker
2. Add email details into `.env`
3. Set `GOTRUE_SITE_URL` to something
4. Try sending your self an email

## Expected behavior
You should recieve this email which will be starting with `http://auth/v1/verify` in the recovery / invite / etc

## Screenshots
![image](https://user-images.githubusercontent.com/63557993/174101742-4aa4c909-18ef-49ce-8fd7-e9b870ab76e4.png)

## System information

- Client OS: Win11
- Server OS:  Ubuntu 20.04
- Browser all browsers
- Docker: 20.10.12
- Docker-compose: 1.25

**Comment by Obeyed** [comment] 2022-07-19 11:03
@OceanTechnic since this was reported a month ago I'm wondering if you found a workaround? I recently ran into this and am suspecting that the config is not being loaded properly for some reason. I haven't been able to find the issue yet, nor a solution.

**Comment by kiwicopple** [comment] 2022-07-20 14:02
Can I confirm what URL you have set for `SITE_URL` @OceanTechnic ? 

https://github.com/supabase/supabase/blob/1a9f74357421184e7a1fc0b0ae8add2c3fd9c992/docker/.env.example#L42

In theory, you can set that to whatever you want, and it will propogate through to your email

**Comment by OceanTechnic** [comment] 2022-07-20 16:17
> @OceanTechnic since this was reported a month ago I'm wondering if you found a workaround? I recently ran into this and am suspecting that the config is not being loaded properly for some reason. I haven't been able to find the issue yet, nor a solution.

I just used .Token variable to construct the link myself

**Comment by OceanTechnic** [comment] 2022-07-20 16:18
> Can I confirm what URL you have set for `SITE_URL` @OceanTechnic ? 
> 
> 
> 
> https://github.com/supabase/supabase/blob/1a9f74357421184e7a1fc0b0ae8add2c3fd9c992/docker/.env.example#L42
> 
> 
> 
> In theory, you can set that to whatever you want, and it will propogate through to your email

I tried SITE_URL and GOTRUE_ SITE_URL but no luck

**Comment by Obeyed** [comment] 2022-07-20 20:16
@kiwicopple The issue was reported by **OceanTechnic** on Discord (archived thread) the same day the issue was created on Github. The issue was verified by **silentworks** (_don't want to tag more people than necessary_) as he could reproduce this locally using `docker-compose up`.

**Comment by kiwicopple** [comment] 2022-07-21 11:34
hey @J0 - do you know why the ENV settings aren't propagating through to the email templates?

**Comment by J0** [comment] 2022-07-21 12:59
@kiwicopple not really but I have a hunch -- will take a look when I get back to computer in about 45 minutes

**Comment by J0** [comment] 2022-07-22 08:00
Solved with @kangmingtay 's help -- we are missing an env var 

```
API_EXTERNAL_URL=http://localhost:8000/
```

There also needs to be another two env vars updated -- we'll file a PR in a bit

Thanks @kangmingtay !

**Comment by J0** [comment] 2022-07-22 08:49
Should be fixed by the merged PR -- let me know if anyone is still facing issues though. Happy to help troubleshoot

**Closed** 2022-07-22 08:48 UTC
Labels: bug, auth, self-hosted
