### ISSUE TITLE
Supabase local development docker containers disconnect computer from internet

### ISSUE THREAD

**Issue by nathan-hello** [supabase/supabase#19645] opened 2023-12-13 00:01 UTC
# Bug report

About a minute after running `npx supabase start`, my entire machine loses internet.

## To Reproduce

1. `npx supabase init`
2. `npx supabase start`
3. Wait for the docker containers to build and start

This is docker ps when my internet is down. I don't see anything in the ports column that would suggest it taking all of the internet

```bash
$ docker ps
CONTAINER ID   IMAGE                                             COMMAND                  CREATED         STATUS                   PORTS                                                                  NAMES
d250e0ed445a   public.ecr.aws/supabase/studio:20231123-64a766a   "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes (healthy)   0.0.0.0:54323->3000/tcp, :::54323->3000/tcp                            supabase_studio_onpostdeliveries
517b05d1bd6b   public.ecr.aws/supabase/postgres-meta:v0.75.0     "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes (healthy)   8080/tcp                                                               supabase_pg_meta_onpostdeliveries
b471e62d2e94   public.ecr.aws/supabase/edge-runtime:v1.29.1      "sh -c 'mkdir -p /ho…"   2 minutes ago   Up 2 minutes             8081/tcp                                                               supabase_edge_runtime_onpostdeliveries
5cf37d0dc6d3   public.ecr.aws/supabase/imgproxy:v3.8.0           "imgproxy"               2 minutes ago   Up 2 minutes (healthy)   8080/tcp                                                               storage_imgproxy_onpostdeliveries
39057391c403   public.ecr.aws/supabase/storage-api:v0.43.11      "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes (healthy)   5000/tcp                                                               supabase_storage_onpostdeliveries
ce14c3c79d93   public.ecr.aws/supabase/postgrest:v11.2.2         "/bin/postgrest"         2 minutes ago   Up 2 minutes             3000/tcp                                                               supabase_rest_onpostdeliveries
7d08255536de   public.ecr.aws/supabase/realtime:v2.25.35         "/usr/bin/tini -s -g…"   2 minutes ago   Up 2 minutes (healthy)   4000/tcp                                                               realtime-dev.supabase_realtime_onpostdeliveries
edf12ff9187b   public.ecr.aws/supabase/inbucket:3.0.3            "/start-inbucket.sh …"   2 minutes ago   Up 2 minutes (healthy)   1100/tcp, 2500/tcp, 0.0.0.0:54324->9000/tcp, :::54324->9000/tcp        supabase_inbucket_onpostdeliveries
d2d54d99a513   public.ecr.aws/supabase/gotrue:v2.125.1           "gotrue"                 2 minutes ago   Up 2 minutes (healthy)   9999/tcp                                                               supabase_auth_onpostdeliveries
20978368438e   public.ecr.aws/supabase/kong:2.8.1                "sh -c 'cat <<'EOF' …"   2 minutes ago   Up 2 minutes (healthy)   8001/tcp, 8443-8444/tcp, 0.0.0.0:54321->8000/tcp, :::54321->8000/tcp   supabase_kong_onpostdeliveries
94cc489c4823   public.ecr.aws/supabase/postgres:15.1.0.117       "sh -c 'cat <<'EOF' …"   2 minutes ago   Up 2 minutes (healthy)   0.0.0.0:54322->5432/tcp, :::54322->5432/tcp                            supabase_db_onpostdeliveries
```

## System information

- OS: Debian 13
- Version of supabase-js: 1.123.4
- Version of Node.js: 21.2.0

## Additional context
Interestingly, I can't pull _any_ webpages during this time. But, I can `ping google.com`, but not `ping discord.gg`. I don't know what this means, maybe that's just what my computer has for dns cache, but it was interesting.

This bug was incredibly infuriating to the point where I switched to windows for a couple weeks. I was on another project when this started, and the docker containers were also booting on start. This meant that I would start my computer, start doing things, and then out of no where my internet goes out. I happened to have windows dual-booted as a saving grace. After my third or fourth troubleshooting session with ChatGPT, it suggested I look at docker containers and that's when I found the issue. Why I didn't spot it immediately? Not sure, maybe I was doing other things and went to bed. Why include this anecdote at all? Because I spent actual hours and my poor router suffered a dozen or more reboots during this, so I at least get to complain.

**Comment by encima** [comment] 2024-01-18 09:37
Firstly, thank you for the anecdote, you definitely should have included it and those hours spent were not wasted, I hope.

Second, while it is possible, I think I would complain to ChatGPT for this issue as I think it led you down a bit of a rabbit hole. Docker **could** be the cause of this, however. Supabase and the CLI are likely not the cause.

What could be happening is Docker has overlapping CIDRs with your router (You can check this in Docker's advanced settings).
An alternative would be to install podman and see if it occurs still. 

I will close this out as it is not really a Supabase issue but please do comment if you want a bit more help.

**Closed by encima** 2024-01-18 09:37 UTC
Labels: bug, cli
