### ISSUE TITLE
Date type values are stored or displayed as timestamps

### ISSUE THREAD

**Issue by ichbinedgar** [supabase/supabase#4076] opened 2021-11-26 07:51 UTC
# Bug report

## Describe the bug
Date type are stored or displayed as a timestamp. However, on pgAdmin the dates seems to be displayed correctly.
<img width="245" alt="Screen Shot 2021-11-26 at 0 56 01" src="https://user-images.githubusercontent.com/5431012/143545434-ad8a6a7d-b0a3-4233-a7db-81139ba29774.png">

## To Reproduce

Insert new data by using the [Sign up with additional user meta data.](https://supabase.com/docs/reference/javascript/auth-signup#sign-up-with-additional-user-meta-data) method, so basically we need to get the date value from the json data. Currently, I needed to cast the value like this:

```
(new.raw_user_meta_data->>'birthday'::text)::date
```

## Expected behavior

display regular date format (like YYYY-MM-DD)

<img width="265" alt="Screen Shot 2021-11-26 at 1 02 44" src="https://user-images.githubusercontent.com/5431012/143545459-cdc5484f-436d-4321-be73-c2b6d79e3d05.png">

## System information

- OS: Mac OS Monterey
- Browser Chrome Version 96.0.4664.55 (Build oficial) (x86_64)
- Version of supabase-js: 1.28.1
- Version of Node.js: v12.20.0

**Comment by soedirgo** [comment] 2021-11-26 08:55
The value should still be stored as a `DATE` in the db. The issue is the library used for displaying the date converts Postgres's `DATE` to a JS `Date` object, when then gets stringified into ISO8061 dates: https://github.com/brianc/node-postgres/issues/1844.

The fix should have landed by now, just waiting for a new release.

**Comment by ichbinedgar** [comment] 2021-11-26 15:50
Oh ok, got it! awesome!   :D

**Closed** 2021-12-28 16:24 UTC
Labels: bug
