### ISSUE TITLE
Supabase web dashboard buckets content not being returned

### ISSUE THREAD

**Issue by mashaole** [supabase/supabase#13083] opened 2023-03-18 20:08 UTC
# Bug report

## Describe the bug

Supabase dashbaord buckets page does not show my buckets  folders and files it sits in the loading state and when i inspect the page i see that the "list api" gives a error code 400 and response <code> "{"message":"id must match /^[a-z0-9-\.]+$/ regular expression"}"</code>

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://app.supabase.com/ and sign in
2. Navigate to  /storage/bucket'
3. And Then click on your bucket and 

## Expected behavior

The buckets folders and files will be in the loading state showing the"Skeleton Loading" 

## Screenshots
![Screenshot 2023-03-18 at 21 37 03](https://user-images.githubusercontent.com/40543693/226135335-88bc47da-9fd2-486b-8d0e-cb3c2141c309.png)

## System information

- macOS Ventura 13.2.1
- Brave Browser Version 1.49.120 Chromium: 111.0.5563.64 
- Not sure as its the the supabase dashboard

## Additional context

my buckets name is user_documents maybe thats the problem and i dont seem to be able to rename so my quick solution is to delete the bucket

**Comment by saltcod** [comment] 2023-08-28 18:44
Closing as I'm unable to reproduce this with a bucket name `user_documents`. 

Please feel free to reopen if you're still experiencing an issue here. 

<img width="643" alt="CleanShot 2023-08-28 at 16 14 15@2x" src="https://github.com/supabase/supabase/assets/105593/78017c30-ee5d-496a-9479-792d6c51f519">

**Closed by saltcod** 2023-08-28 18:44 UTC
Labels: bug, dashboard, storage

**Comment by alehano** [comment] 2024-05-28 08:05
I have the same issue. I installed two self hosted version: one of them with minimal changes works fine, but the second where I changed Postgres port, container names not loading buckets.
Endpoint /api/storage/default/buckets return 500 error.
All other components works fine.
