### ISSUE TITLE
signUp function error: Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by xiaooubai** [supabase/supabase#4577] opened 2021-12-20 07:49 UTC
# Bug report

## Describe the bug

When I use signUp based on Supabase's documentation, I get a SyntaxError that only comes up with dealing JSON. Extremely confused with why this is happening as I'm only following what the documentation is showing.

## To Reproduce

`
  const onSubmit = async data => {

    console.log(data.email)
    console.log(data.password)
    console.log(typeof(data.email))
    console.log(typeof(data.password))

    const {user, error} = await supabase.auth.signUp({
      email : data.email,
      password : data.password
    })
    console.log(error)
 
  
   
    console.log(error)
    console.log(user)

  }
`

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

I expected the signUp function to take in my two strings and register them as a user

## Screenshots

![image](https://user-images.githubusercontent.com/31837089/146731184-fa61a65a-0162-4ee1-9df4-6c9f45b47c36.png)

## System information

- OS: [e.g. macOS, Windows] Windows
- Browser (if applies) [e.g. chrome, safari] Chrome
- Version of supabase-js: [e.g. 6.0.2] latest version
- Version of Node.js: [e.g. 10.10.0] 14.15.3

**Comment by riancz** [comment] 2021-12-20 15:12
I have the same problem in my whole app. I think they have some problems on their end.

**Comment by anngbaum** [comment] 2021-12-22 00:02
I'm also reproducing this in our repository – our main branch is stable and not impacted, but seems to be caused by something in the latest version of the JS client (for us at least). I'm still debugging but this is causing some considerable issues with our current development.

**Comment by dthyresson** [comment] 2021-12-22 00:27
Hi @xiaooubai @riancz and @anngbaum I am trying to reproduce and have been testing with an existing project and the [following code](https://github.com/dthyresson/supagraphql/blob/5bd537bdb39a86102759994b2be149e21ecb016a/src/schema/resolvers/authentication.ts#L14) for my sign up:

```ts
export const signUp = async (
  email: string,
  password: string
): Promise<User> => {
  const { user, error } = await supabase.auth.signUp({
    email,
    password,
  })

  if (error) {
    throw new GraphQLError(`Unable to sign up: ${error.message}`)
  }

  return user as User
}
```

See: https://github.com/dthyresson/supagraphql/blob/5bd537bdb39a86102759994b2be149e21ecb016a/src/schema/resolvers/authentication.ts#L14

I am successfully registering a user (this is a hosted project) and can also sign in with the credentials and get an access token.

Currently am using:

```
├─ @supabase/gotrue-js@1.21.7
├─ @supabase/postgrest-js@0.35.0
├─ @supabase/realtime-js@1.3.3
├─ @supabase/storage-js@1.5.0
├─ @supabase/supabase-js@1.29.0
```

Could you share which supabase package versions you are using?

**Comment by dthyresson** [comment] 2021-12-22 00:32
One thing I do see @xiaooubai in your screenshot is that the POST is going to `localhost:3000` and the http status is `404` not found.

The JSON parse error is probably trying to parse the not found html vs JSON ... which I grant you is rather odd.

Is that the expected url?

For me,

<img width="779" alt="image" src="https://user-images.githubusercontent.com/1051633/147015095-6ec8a1b0-274e-4a3a-a524-aa16dc54bf7c.png">


Is what I use to serve my app.

**Comment by xiaooubai** [comment] 2021-12-22 04:06
Hey @dthyresson , that is indeed my expected url! I'll try what you have and see if it works. Thanks for your detailed response! I'll let you know what I get :)

**Comment by anngbaum** [comment] 2021-12-22 13:12
@dthyresson unfortunately as one part of debugging I went ahead and updated all of my packages, which did seem to resolve the issue. latest is working by using:

```
├─┬ @supabase/supabase-js@1.21.3
│ ├── @supabase/gotrue-js@1.17.0
│ ├── @supabase/postgrest-js@0.33.3
│ ├── @supabase/realtime-js@1.2.1
│ └── @supabase/storage-js@1.4.0
```

in case helpful, for more context we've had an iOS app in testflight using authentication with no problem whatsoever for quite some time now.

in our latest branch, we added the ability to switch between our supabase production database client vs. our test database client. I originally assumed that was the problem, but even when we hardcoded the new credentials we still hit the same unexpected token < error (another developer hit the identical error completely separately).

neither of us could identify the cause, until I saw the comments in this GH issue as well as the comment in Discord [here](https://discord.com/channels/839993398554656828/869406062036529193/922402842466201610), which made me think it's something package related. after rebasing (and manually updating the packages, at least for me) it seems to have resolved itself.

**Comment by dthyresson** [comment] 2021-12-22 13:28
> after rebasing (and manually updating the packages, at least for me) it seems to have resolved itself.

Glad to hear, @anngbaum. Let me know if you still have any issues and you can also find me on Discord.

**Comment by inian** [comment] 2021-12-23 04:47
This issue is because of a backend API call failing. This could be a storage, auth, realtime API call and will vary depending on each project, user. If you are facing this issue, it might be due to your project running out of its allocated resources. You can check your reports tab to get more insight there. 

Closing the issue here since we can't do much without knowing your project id etc. If you are facing this error, reach out to  us at https://app.supabase.io/support/new

**Closed by inian** 2021-12-23 04:47 UTC
Labels: bug
