### ISSUE TITLE
Search feature doesn't work (documentation page)

### ISSUE THREAD

**Issue by Gigusx** [supabase/supabase#5061] opened 2022-01-19 20:37 UTC
# Bug report

## Describe the bug

The search feature on Supabase's documentation page doesn't work - it doesn't return any results for any search query.

I came across this a few days ago and didn't think much of this back then, but the same happened today and I suspect that the issue isn't with Algolia. It is worth noting that using the search popup (the one triggered by ctrl+k) does work, and it also displays how many results in total have been found - the screenshots should illustrate what I mean. So it seems that the results are returned by Algolia but they're just not displayed on the page.

## To Reproduce

1. Go to https://supabase.com/docs/search
2. Search for anything

## Expected behavior

Existing results should be shown.

## Screenshots

I've taken two screenshots with the same search query, one using the search popup and another the global search (for lack of better word):

![supa1](https://user-images.githubusercontent.com/13439101/150208516-227989d2-e744-41c0-8aaf-e6da528620c4.png)

![supa2](https://user-images.githubusercontent.com/13439101/150208536-e74631da-b1fd-4d30-842f-6ebae1794ea2.png)

## System information

- Browser: Chrome / Firefox / Edge

**Comment by kiwicopple** [comment] 2022-01-20 14:21
Looks like a dupe of this one right? https://github.com/supabase/supabase/issues/5061

I'll close this in favor of that issue, although it looks like the resolution Inian mentioned didn't work. 🤔

**Closed by kiwicopple** 2022-01-20 14:21 UTC
Labels: bug
