### ISSUE TITLE
Shaking mobile document
In some point , when reading supabase documents on mobile all page start to shake .
It left user with bad experience 

### ISSUE THREAD

**Issue by mbaneshi** [supabase/supabase#8170] opened 2022-08-09 16:08 UTC
# Improve documentation

## Link 

Add a link to the page which needs improvement (if relevant)

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?

## Describe the improvement

A clear and concise description of the improvement.

## Additional context

Add any other context or screenshots that help clarify your question.https://user-images.githubusercontent.com/21130612/183741389-c70a4f4a-38b7-4319-b252-d4c45781486a.mp4

**Comment by Hallidayo** [comment] 2022-08-09 16:21
Hi @mbaneshi 

Was this happening on a specific section of the documentation?

I've just tried the auth section for example on a mobile and the page seems fine, Do you have a video that you could send over?

**Comment by mbaneshi** [comment] 2022-08-09 19:11
I face this problem many times , more around YouTube embeddd video  or near code block .
I record my screen

If you want more video please let me know 

https://user-images.githubusercontent.com/21130612/183740785-8cb94e89-7360-4bda-a30d-db4554af711f.mp4
 

If you need more video please let me know

**Comment by pucho** [comment] 2022-10-28 14:32
@mbaneshi hey, sorry for the late reply. Can we get some steps to reproduce? I tried this on a Samsung phone and Iphone and can't seem to reproduce this behaviour. That said, I've had this happen with other websites so this might be a more widespread issue.

Thanks!

**Comment by hf** [comment] 2023-01-21 13:56
Was not able to reproduce with Samsung Internet on the new docs site. Will close it.

**Closed by hf** 2023-01-21 13:56 UTC
Labels: documentation
