### ISSUE TITLE
user-management example/nextjs-ts-user-management - forgot password flow doesn't work in this example, as designed

### ISSUE THREAD

**Issue by eedeebee** [supabase/supabase#14890] opened 2023-06-08 05:12 UTC
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

This example is intended to show off signin/signup and also exposes password resets (aka forgot password).
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Build and deploy the example.  Sign up a user.  
2. Sign out.
3. Go back to Sign in but click forgot password.
4. Go to email and click the link
5. You are logged back in and can not get to the password reset form because of the way the example is built.  Basically, if you have a session, the auth UI is hidden and the profile is shown.  The example is basically faulty in its design, best I can tell.

## Expected behavior

I expect to see the Auth UI for password reset in this situation, some how.  And then after the password has been reset, I expect to be left at the profile page.

## System information

Suspect this doesn't matter, but 
- OS: MacOS
- Browser (if applies) : Arc
- Version of supabase-js: whatever the example calls for
- Version of Node.js:  whatever the example calls for

## Additional context

I don't know supabase well enough but I suspect this thread: https://github.com/orgs/supabase/discussions/3360 might help.  Perhaps a fix would be a separate page for password reset that you can land on (get redirected to) and then after a successful reset, get redirected back to the home page.  That perhaps the logic up top on whether to show the Auth UI can look at some additional state to make that call.

**Comment by mryechkin** [comment] 2023-06-10 20:15
I don't think this is an issue with Auth-UI per se, or even the example itself, but rather a regression that was introduced with Next.js Auth Helpers version `0.7.0`. I follow a very similar structure in [my example repo](https://github.com/mryechkin/nextjs-supabase-auth), and it's been working great up until `0.7.0` where they introduced some [breaking changes](https://github.com/supabase/auth-helpers/releases/tag/%40supabase%2Fauth-helpers-nextjs%400.7.0).

With release `0.7.0` my Reset Password flow stopped working, since the `PASSWORD_RECOVERY` even is never sent. It's why I've pinned my project to `0.6.1` for the time being, as that seems to be the last version where Reset Password flow worked as expected.

If I had to guess, this is coming downstream from `gotrue-js` or one of those other libraries.

**Comment by Bartel-C8** [comment] 2023-06-22 07:56
Up, same problem here...

**Comment by vincentjflorio** [comment] 2023-06-27 20:54
> I don't think this is an issue with Auth-UI per se, or even the example itself, but rather a regression that was introduced with Next.js Auth Helpers version `0.7.0`. I follow a very similar structure in [my example repo](https://github.com/mryechkin/nextjs-supabase-auth), and it's been working great up until `0.7.0` where they introduced some [breaking changes](https://github.com/supabase/auth-helpers/releases/tag/%40supabase%2Fauth-helpers-nextjs%400.7.0).
> 
> With release `0.7.0` my Reset Password flow stopped working, since the `PASSWORD_RECOVERY` event is never sent. It's why I've pinned my project to `0.6.1` for the time being, as that seems to be the last version where Reset Password flow worked as expected.
> 
> If I had to guess, this is coming downstream from `gotrue-js` or one of those other libraries.

Bless you; I was trying to be responsible and diligent and stay up to date, and followed the breaking changes, replacements, etc. but this all just sort of quietly stopped working -- I don't have a lot of time to treasure hunt but 0.6.1 and 2.21.0 at least got me back to automatically logging in correctly.

**Comment by Hallidayo** [comment] 2024-09-15 16:45
Hi all, due to recent changes in the `@supabase/ssr` I'm going to close this one. I've been looking at some examples and the forget password flow seems to work but if you are getting any issue please comment back on this issue or a create a new issue. Thank you all!

**Closed by Hallidayo** 2024-09-15 16:45 UTC
Labels: bug, example, auth, auth-helpers, needs-analysis
