### ISSUE TITLE
Unable to turn off Enable email confirmations when Enable Custom SMTP is on

### ISSUE THREAD

**Issue by freebasecomedy** [supabase/supabase#3010] opened 2021-08-30 16:12 UTC
## Unable to turn off Enable email confirmations when Enable Custom SMTP is on

Try to turn off Enable email confirmations while the custom SMTP is on and has my mail server info.
Looks like the save is working without error. 

But you navigate out of this page (or refresh), it has still old value, it is ON.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to config and auth setting page
2. Turn off Enable email confirmations
3. Save 
4. refresh screen

## Screenshots

<img width="1196" alt="supabase_save_config" src="https://user-images.githubusercontent.com/84099606/131369976-5cd39188-7c5a-4e90-b17c-c23d22e64886.png">

**Comment by w3b6x9** [comment] 2021-08-30 20:01
duplicate of https://github.com/supabase/supabase/issues/2959

**Closed by w3b6x9** 2021-08-30 20:01 UTC
Labels: bug
