### ISSUE TITLE
Supabase storage dashboard does not show subfolder structure

### ISSUE THREAD

**Issue by KrisCoulson** [supabase/supabase#2497] opened 2021-07-22 21:41 UTC
I think there might be a bug in the supabase storage dashboard unless I am doing something wrong.

I am uploading an image and I believe nesting it in a "folder" so all images get uploaded under the event they are assigned to.
```
 const { data, error } = await client.storage
      .from('team-logos')
      .upload(`${org}/${eventId}/${v4()}`, formData.logoFile[0], {
        cacheControl: 'no-cache',
        upsert: true,
      })
 ```
 
 When doing this there is no subfolder generated in the dashboard UI. The org "folder"(teamstream) got created. But the eventID subfolder does not display in the UI.
 
![image](https://user-images.githubusercontent.com/6943688/126708482-adba4ee8-f8a1-4b24-927d-85a1bda4d068.png)

With that being said. The client returns successfully with the correct URL to the image and the image is uploaded. And I can view the image correctly. There is just no UI that shows my image in the Supabase dashboard so I can't navigate the uploads

It might be worth noting creating a subfolder from the dashboard UI looks like it works and is properly displayed in the dashboard. One annoying thing though if you create a subfolder there doesn't seem to be a way to delete the subfolder. Clicking on the 3 ellipses just says "no options"

**Comment by joshenlim** [comment] 2021-07-26 17:43
Hey @KrisCoulson - gotcha on this! I've tried to reproduce your bug but unfortunately am unable to do so :/ Could I check a few details from you:

- Would you mind sharing what an example of the string `${org}/${eventId}/${v4()}` looks like?
- Could i also check what `key` did `.upload()` return
- Is the bucket that you're uploading to a public bucket? 

Thank you so much!

Also, you should notice now that you're able to delete folders via our dashboard now, along with renaming folders :)

**Comment by KrisCoulson** [comment] 2021-07-30 00:16
@joshenlim sorry for the late response I am going to close this issue for now. Those original uploads don't seem to be showing still but the subfolder structure is working for new things now. I am unsure why if it happens again ill make sure to reopen and ping you

**Comment by joshenlim** [comment] 2021-07-30 06:04
Gotcha on this no worries at all :)

**Comment by KrisCoulson** [comment] 2021-08-02 00:47
@joshenlim I re-opened as I figured out what the cause was and it continues to happen.

So on supabase I have 2 bucket
- event-logos
- team-logos

Both are public buckets. When I save the to event logos the path looks like this
`/event-logos/${eventCode}`

when I save to team logos 
`/team-logos/${eventCode}/${uuid}`

In `event-logos` the eventCode seems to overwrite the subfolder since they are the same name. The team-logos are obviously still stored in storage but they are not visible in the dashboard.

 I think an easy fix on my end for now which I wasn't currently doing is to append the file type to the end of the upload. That will at least allow the subfolders to show but not sure if this intended or a bug

**Comment by joshenlim** [comment] 2021-08-02 04:45
ahh okay gotcha on this! thank you so much for the reproduce steps @KrisCoulson, we'll look into a fix for this :)

**Closed** 2021-10-11 17:27 UTC
Labels: bug
