### ISSUE TITLE
buckets    "Internal Server Error"    by self-host

### ISSUE THREAD

**Issue by zuohuadong** [supabase/supabase#13441] opened 2023-04-05 02:42 UTC
## Describe the bug

"Internal Server Error" 

## To Reproduce

 Click on 'storage'

## Screenshots
![image](https://user-images.githubusercontent.com/11203929/229967680-0fac8374-6e2d-4359-aae3-3a8ab0d76ddb.png)

![image](https://user-images.githubusercontent.com/11203929/229967249-811b0ffb-41da-4048-8ea7-9db3fc33f0a4.png)

## System information

- OS: Almalinux 9.0
- Browser : EDGE
-  image: supabase/studio:20230330-99fed3d
- Version of supabase-js:  new
- Version of Node.js:none

**Comment by Silur** [comment] 2023-08-09 13:38
issue is present on supabase.com too

**Comment by saltcod** [comment] 2023-08-28 19:13
Is this still happening @Silur and @zuohuadong ?

**Comment by ivasilov** [comment] 2023-09-01 14:15
Tested and couldn't replicate by running `supabase start`. The studio image was `supabase/studio:v0.23.06`. Please provide more info.

**Comment by 032008** [comment] 2023-09-01 22:10
I had a similar issue, in my case it happened because I did not properly configure the JWT_SECRET, ANON_KEY and SERVICE_ROLE_KEY. I tried to manually come up with a JWT but it really did not like it, had to use a generated one.

Did you try to generate a proper set using the generator on this screen?
https://supabase.com/docs/guides/self-hosting/docker

**Comment by saltcod** [comment] 2023-09-12 19:31
Hey @zuohuadong — going to mark this as closed as we can't reproduce.  Please feel free to reopen if you're still experiencing this.

**Closed by saltcod** 2023-09-12 19:31 UTC
Labels: bug, dashboard, p1, self-hosted, storage
