### ISSUE TITLE
localhost:3000 www main website gives error 

### ISSUE THREAD

**Issue by AbhijeetBiswal** [supabase/supabase#18776] opened 2023-11-07 08:22 UTC
when i go to the main website www that is localhost:3000 on the local it gives an error
![www page error supabase](https://github.com/supabase/supabase/assets/144774379/91ca5540-7fae-481e-9ac2-82dcaed180b8) 
how can i fix this please help

**Comment by yousseefben** [comment] 2023-11-07 09:34
Hello @AbhijeetBiswal 
You should just add the values for the env variables in the .env file and it should work :) : 

![image](https://github.com/supabase/supabase/assets/34013486/9ad6ad59-15e6-43c4-8650-357f553a3245)

**Comment by fsansalvadore** [comment] 2023-11-07 10:15
@AbhijeetBiswal You should add an .env.local file in www with the Env variables

**Comment by fsansalvadore** [comment] 2023-11-07 10:27
Closing since this is not a bug.
Feel free to reopen if you think there's something else going on.

**Closed by fsansalvadore** 2023-11-07 10:27 UTC
Labels: bug
