### ISSUE TITLE
Bug: Constraints not well-handled by Studio

### ISSUE THREAD

**Issue by galenking** [supabase/supabase#7560] opened 2022-07-04 19:25 UTC
I am not sure if this is an issue with Prisma or Blitz or Supabase.

When I run `blitz prisma migrate dev`, the default value for `id` is set in Supabase to `extval('"User_id_seq"` (truncated—exactly like that).

This is the corresponding schema in Prisma: `id    Int    @id @default(autoincrement())`.

Is this a bug? Or am I doing something wrong?

**Comment by NanoCode012** [comment] 2022-07-09 03:53
I also got this value in my schema when running prisma introspection. My workaround which works for me is to switch to UUID instead. It would be great if I could use simple ID though as UUID is sometimes overkill.

**Comment by kiwicopple** [comment] 2022-07-09 13:03
Hey @galenking - Would you be able to share a bit more code which would allow use to reproduce the issue?

I don't think this is a supabase issue (since we are "just postgres") - but I could be wrong

**Comment by NanoCode012** [comment] 2022-07-10 01:46
Hi @kiwicopple , I reproduced it as below. It could also be more of Prisma error the more I see it.

1. Schema
```prisma
model Test {
    id BigInt @id @default(autoincrement())
}
```

2. `prisma migrate dev --name test`
```SQL
-- test/migration.sql
-- CreateTable
CREATE TABLE "Test" (
    "id" BIGSERIAL NOT NULL,

    CONSTRAINT "Test_pkey" PRIMARY KEY ("id")
);
```

3. Supabase Studio
![image](https://user-images.githubusercontent.com/9899957/178128108-7bf00437-e7e3-46cf-8355-041cad5688ee.png)

**Comment by kiwicopple** [comment] 2022-07-20 11:07
```
CREATE TABLE "Test" (
    "id" BIGSERIAL NOT NULL,

    CONSTRAINT "Test_pkey" PRIMARY KEY ("id")
);
```

I see - they are adding it as constraint, and it seems that Studio isn't great at handling constraints. This is a bug for us to fix! I'll edit the title and let the Frontend team know

**Comment by joshenlim** [comment] 2022-09-27 06:38
just fyi, this is happening as the dashboard is attempting to do some formatting against the default value of the column to remove the type cast incorrectly - i'll look into a temp fix for this, but the longer term fix that I'll look into as well is just have the Column side panel editor do formatting from PG's side (e.g formatting `'some text'::text` to `'some text'`)

**Closed** 2022-09-27 07:40 UTC
Labels: bug, dashboard
