### ISSUE TITLE
'Import data via spreadsheet' omits leading zeros

### ISSUE THREAD

**Issue by masa5714** [supabase/supabase#12666] opened 2023-02-25 02:09 UTC
# Bug report

I would like to use 'Import data via spreadsheet'.
In data where the first character is 0, there is a bug that causes the leading 0 to be omitted.

I have tried importing with varchar, int, and text types. 
All failed.

## Describe the bug

See screenshot.
In the 'postalcode' column, the first character, 0, is lost.

◆ Content Preview
![02fe9b111bb1383bdfe2d712653315ae](https://user-images.githubusercontent.com/7102373/221329932-9dcbe07c-1b60-4b0f-ae88-f98e1e6da572.png)

◆ Import Result
![d3b7a8660a219357905d7cc68f734c4a](https://user-images.githubusercontent.com/7102373/221329964-99253add-bae5-407b-b7c3-299acd6f70de.png)

## To Reproduce

Operate from New Table in the GUI.
You can reproduce the following data by pasting them in 'Import data via spreadsheet'.

Original Data ( csv )
```
postalcode,prefecture,city,town,section
0600000,北海道,札幌市中央区,,
0640941,北海道,札幌市中央区,旭ケ丘,
0640941,北海道,札幌市中央区,旭ケ丘,1丁目
```

## Expected behavior

Leading zeros do not disappear.

ex:
0600000 -> 0600000
0640941 -> 0640941
0640941 -> 0640941

## System information

- https://app.supabase.com/ (GUI.)
- OS: Windows 11
- Browser: Google Chrome 110.0.5481.105

Thank you.

**Comment by joshenlim** [comment] 2023-04-04 08:19
hey there @masa5714! For context as to why this might be happening, its because when you import the CSV, the dashboard tries to infer the column types based on the column values from the CSV. Since the values under 'postalcode' are numbers, the dashboard hence assigns the type of `int8` to it.

you can change this data type before the creation of the table after saving your imported content as such: by changing `int8` to `text` for example.
![image](https://user-images.githubusercontent.com/19742402/229731421-b4be71e7-c6fe-49af-b40a-f7e5d7ae458b.png)

i'm going to close this issue as such as this is not a bug with the dashboard but please do feel free to reach out if you need any further clarifications 🙏

**Closed by joshenlim** 2023-04-04 08:19 UTC
Labels: bug, dashboard

**Comment by masa5714** [comment] 2023-04-04 11:15
Hi @joshenlim.

I understood!

I apologize for any inconvenience caused by my lack of understanding.

Thank you for your support!

**Comment by jhaus** [comment] 2023-08-04 23:28
I have created the table and set the zip_code column to `text`. Upon import of CSV with leading zeros, they are removed.

Have I misunderstood your solution?
