### ISSUE TITLE
Creating Custom Role i try to Create user and Login

### ISSUE THREAD

**Issue by RamPolineni2021** [supabase/supabase#11276] opened 2022-12-26 17:30 UTC
## i created own Roles for my application client Admin, Client normal, Admin_Admin , Admin_normal, entire admin, i used 
this code let { data, error } = await supabase.auth.admin.createUser({
        email: useremail.current?.value,
        password: password.current?.value,
        role: 'entire_admin',
        aud:'entire_admin',
        email_confirm: true,
        phone_confirm: true,
        email_confirmed_at: new Date(),
        confirmed_at: new Date()
      })

## success full 200 responce get the data after i try to login the page Invalid login credentials it showing 

  const { data:{user}, error } = await supabase.auth.signInWithPassword({
        email: useremail.current?.value,
        password: password.current?.value
      })
   
## based on rloes creating profile table i created 2 polices 
1. every one read the data 
2. onely admin can add, update, delete the data

### Roles based creating users and login....?

**Comment by alaister** [comment] 2022-12-28 16:21
Hi @RamPolineni2021,

I will close this as it seems to be a duplicate of #11279.

**Closed by alaister** 2022-12-28 16:21 UTC
Labels: bug
