### ISSUE TITLE
Realtime for local dev broken on latest CLI (supabase start)

### ISSUE THREAD

**Issue by leerobert** [supabase/supabase#13523] opened 2023-04-07 19:39 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Realtime messages are not pushed on supabase local dev instance when spun up using the latest CLI. Downgrading CLI solves issue.

## To Reproduce

Install latest CLI (1.49.4)
`supabase start`
Enable realtime on a table. 
Use latest supabase-js to create a `postgres_changes` listener
No changes are published to channel.

Downgrade to CLI `1.40.1` and realtime changes are pushed. 

## Expected behavior

Realtime messages should be pushed to listeners.

## System information

- OS: [e.g. macOS, Windows] MacOS
- Browser (if applies) [e.g. chrome, safari] n/a
- Version of supabase-js: [e.g. 6.0.2] 2.15.0
- Version of Node.js: [e.g. 10.10.0] 19

**Comment by nith2001** [comment] 2023-04-07 22:44
Hi, new developer to Supabase. What would be the best way to reproduce this issue locally for the step where you said to _"Use latest superbase-js to create a postgres_changes listener"_?  

Basically, I just have the `supabase` codebase cloned, got the latest CLI version, and ran `supabase start` to boot up the studio locally and then I just picked some table and enabled Realtime on it. After that, do I need to create a local Supabase project and code up a listener that listens to the table in my dev Supabase studio? Seemed a bit long-winded, so I figure I should ask before I go down that path.

**Comment by leerobert** [comment] 2023-04-08 00:58
Hi @nith2001 

The set up you linked looks right. Then you could make a simple svelte/nextjs project to reproduce the issue by disabling RLS on the table (so you don't have to deal with any auth stuff). 

You just want in your javascript on some kind of test page:

```svelte
<script type="ts">
	import { onDestroy } from 'svelte';
	import { supabase } from '$lib/supabaseClient';

	let channel = supabase
		.channel('any')
		.on(
			'postgres_changes',
			{
				event: '*',
				schema: 'public',
				table: 'sample-table',
			},
			(payload) => {
				console.log(payload);
			}
		)
</script>

<div>{channel}</div>
```

When you are on the latest CLI you'll see the realtime doesn't do anything when you manually add a row to your local supabase table you are listening to. If you downgrade, it does. 

My guess the issue resides somewhere in the `realtime` code.

**Comment by nith2001** [comment] 2023-04-08 01:27
Awesome! I arrived at a similar conclusion as well and had a fun time figuring out how local Supabase development works. Anyways, here's what I've done. I made a table in local Supabase called `test` and set up Realtime and disabled RLS as such:
<img width="1440" alt="Screen Shot 2023-04-07 at 6 23 29 PM" src="https://user-images.githubusercontent.com/75632283/230697302-d377f3fd-bb37-4c58-894d-7550eeda9414.png">

Then, I made a local codebase where I set it up with `supabase init && supabase start` and a standalone npm project. My Supabase CLI is `1.49.4`. Here are the key files showing how it's structured. 

```
supabase-playground
- node_modules (folder)
- supabase (folder)
- index.js
- package.json
- package-lock.json
```

And, here's my `index.js` using ES6:
```
import { createClient } from '@supabase/supabase-js'
import dotenv from 'dotenv'
dotenv.config()

const supabaseUrl = 'http://localhost:54321'
const supabase = createClient(supabaseUrl, process.env.SUPABASE_KEY)

supabase
  .channel('any')
  .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'test' }, payload => {
    console.log('Change received!', payload)
  })
  .subscribe()

// To unsubscribe from the real-time subscription, call the `unsubscribe` method:
// subscription.unsubscribe()
```
Now, I just run `nodemon index.js` to get it started. Once I add a new row to the `test` table on the local dashboard, I get this printed out on my Terminal:

```
Change received! {
  schema: 'public',
  table: 'test',
  commit_timestamp: '2023-04-08T01:18:28.581Z',
  eventType: 'INSERT',
  new: { created_at: '2023-04-08T01:18:28.579049+00:00', id: 4 },
  old: {},
  errors: null
}
```
Now, I noticed that the main difference between your code snippet and mine is the `subscribe()` function call I appended to the end of my code. I included that at the suggestion of the Supabase OpenAI search engine. Should this be tested without it?

**Comment by nith2001** [comment] 2023-04-08 01:39
Also, I digged around for the function call to Realtime from Studio to update the table and I'm pretty sure it's this [one](https://github.com/supabase/supabase/blob/master/studio/stores/pgmeta/MetaStore.ts#L320).

**Comment by nith2001** [comment] 2023-04-09 02:07
How do you downgrade the CLI? I haven't found any good resources on it.

**Comment by leerobert** [comment] 2023-04-09 11:27
Hey @nith2001 you'll wanna put something like this in your package.json:

```
       "scripts": {
		"supabase-start": "supabase start",
		"supabase-stop": "supabase stop",
		....
	},
	"devDependencies": {
	      		"supabase": "1.40.1",
	}
```

Then run `supabase stop && pnpm run supabase-start`

**Comment by leerobert** [comment] 2023-04-09 11:28
I think the issue might be in creating a project in an earlier CLI then upgrading the CLI. Downgrading the CLI back makes realtime work again. I was able to replicate this locally.

**Comment by nith2001** [comment] 2023-04-11 16:58
@leerobert Sorry to be a nuisance, but I'm still having trouble replicating the bug via the Svelte app.

Here are the dependencies from my package.json:
```
"devDependencies": {
    "@rollup/plugin-commonjs": "^24.0.0",
    "@rollup/plugin-json": "^6.0.0",
    "@rollup/plugin-node-resolve": "^15.0.0",
    "@rollup/plugin-terser": "^0.4.0",
    "rollup": "^3.15.0",
    "rollup-plugin-css-only": "^4.3.0",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.1.2",
    "supabase": "1.40.1",
    "svelte": "^3.55.0"
  },
  "dependencies": {
    "@supabase/supabase-js": "^2.15.0",
    "circular-json": "^0.5.9",
    "dotenv": "^16.0.3",
    "sirv-cli": "^2.0.0"
  }
```

And here's my `App.svelte` code:
```
<script type="ts">
  import { createClient } from "@supabase/supabase-js";
  import CircularJSON from "circular-json";

  const supabaseUrl = "http://localhost:54321";
  const supabase = createClient(
    supabaseUrl,
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
  );

  let channel = supabase.channel("any").on(
    "postgres_changes",
    {
      event: "*",
      schema: "public",
      table: "test",
    },
    (payload) => {
      console.log(payload);
    }
  );
</script>

<main>
  <p>{CircularJSON.stringify(channel, null, 2, "[Circular]")}</p>
</main>
```
I did what you said by setting the dev dependency of `supabase` to `1.40.1`. Then I did `supabase init && supabase start`, setup table with RLS disabled/Realtime enabled, and it seems like nothing substantial is getting printed to the screen that wasn't already there in either version. I just get this JSON text block printed on the screen that doesn't change. 

<img width="1440" alt="Screen Shot 2023-04-11 at 9 56 28 AM" src="https://user-images.githubusercontent.com/75632283/231235325-54519711-7bd3-4101-b86a-cf12dfb3e66f.png">

It's very possible that I might've missed or swapped a step or two during this process despite trying several times :-(. If you have the time to spare, could you give a more detailed explanation on duplicating this issue? Or if you wanna just make a dummy repo that I can clone with some instructions on how to replicate.

**Comment by jamesthesken** [comment] 2023-04-20 02:40
Interesting, I am running to a similar issue using Supabase CLI `1.38.6`, and supabase-js `2.14.0`. I have not tried to upgrade the CLI yet however

**Comment by nith2001** [comment] 2023-04-20 18:15
That might be a slightly separate issue since the Realtime issues seem to be popping up when upgrading from a supabase project started with an earlier version CLI and then updated to the latest version CLI. The issue seems to either lie in `supabase-js` with how the channel is fetched and displayed or more likely within `realtime` with how the actual channel is displayed.

**Comment by jamesthesken** [comment] 2023-04-20 18:48
Okay, so after upgrading my CLI `1.50.9`, everything is working. Will try to see if I can break it by downgrading

**Comment by nith2001** [comment] 2023-04-20 18:56
Interesting. This issue started because upgrading to 1.49.4 (which was the lastest CLI) seemed to result in Realtime problems. Can you check that version?

**Comment by nith2001** [comment] 2023-05-03 23:35
Any updates on this issue?

**Comment by sweatybridge** [comment] 2023-06-06 10:47
Closing this as resolved in latest CLI. Feel free to reopen if it still persists.

**Closed by sweatybridge** 2023-06-06 10:47 UTC
Labels: bug, cli, self-hosted, realtime
