### ISSUE TITLE
Cannot delete an organization

### ISSUE THREAD

**Issue by zhaolinlau** [supabase/supabase#28848] opened 2024-08-23 16:29 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I wanted to delete an organization of my supabase account, but it says `Failed to delete organization: Internal Server Error`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [dashboard](https://supabase.com/dashboard/projects)
2. Select an organization
3. Click 'Delete organization'

## Expected behavior

The organization got deleted.

## Screenshots

![image](https://github.com/user-attachments/assets/0cdb0401-0e11-4217-9a19-677b1be0ad1d)

## System information

- OS: Windows
- Browser: Firefox
- Version of supabase-js: -
- Version of Node.js: -

**Comment by deezeddd** [comment] 2024-08-24 09:39
I can confirm this issue, this is what we get

<img width="713" alt="Screenshot 2024-08-24 at 15 08 14" src="https://github.com/user-attachments/assets/a5403e3d-58e3-4efd-a557-ffd35948c3b4">

**Comment by deezeddd** [comment] 2024-08-24 12:06
I researched it and got something: the issue is that all the db inside the org are getting deleted successfully but the **organization** specifically isn't getting deleted. I'll look into it more.

**Comment by sbmmahato** [comment] 2024-08-24 14:38
I am facing the same issue. Anyone found a solution yet?

**Comment by deezeddd** [comment] 2024-08-24 15:16
Not yet, I’m yet to find.

**Comment by Hallidayo** [comment] 2024-08-25 18:58
Hi all - Thank you flagging this issue up. I've tried the same and I am also getting the same error. I've flagged this internally with the guys who be looking into this and will update you as soon as.

**Comment by deezeddd** [comment] 2024-08-25 19:01
I couldn’t reproduce this on my local as there isn’t any option of organisation visible to me. Couldn’t find any. @Hallidayo

**Comment by Hallidayo** [comment] 2024-08-25 19:07
@deezeddd - I already had a test organisation in my supabase dashboard and was using the test org to try the delete.

**Comment by deezeddd** [comment] 2024-08-25 19:10
Oh! Just wanted to ask, are there some things which are handled by core team internally? This query would help to reproduce issues accordingly :)

**Comment by kevcodez** [comment] 2024-08-25 21:02
Hi folks - we are aware of the issue and should have a fix deployed within the next 24 hours, will keep you posted

**Comment by kevcodez** [comment] 2024-08-26 12:49
Fix has been rolled out to production just now - thanks for reporting!

**Closed by kevcodez** 2024-08-26 12:49 UTC
Labels: bug, internal-fix, external-issue
