### ISSUE TITLE
Insufficient contrast on UI

### ISSUE THREAD

**Issue by kaytwo** [supabase/supabase#1038] opened 2021-04-02 14:18 UTC
# Bug report

## Describe the bug

The contrast on UI elements in the web console is really bad.

## To Reproduce

Paste the colors for the primary button text color and background-color into your favorite contrast checker:

![image](https://user-images.githubusercontent.com/587187/113423390-013ab680-9394-11eb-9116-35c544e589cc.png)

## Expected behavior

I should be able to see the words on the screen.

## Screenshots

See above

## System information

Impacts all platforms

## Additional context

Super excited about the product and this would make it much easier to use for a lot more people!

**Comment by marcelobarreto** [comment] 2021-05-04 21:22
I really have some difficult to use the Supabase admin's because I can't read it very well.

:+1: for this

**Comment by kiwicopple** [comment] 2021-05-05 05:38
Hey all - we rolled out some UI updates yesterday as part of the Light Mode fix and it looks like we had a bit of regression on the dark mode contrast. We'll fix this up asap

**Comment by MildTomato** [comment] 2021-05-06 08:25
Hey @marcelobarreto - thanks for the feedback on this

> Super excited about the product and this would make it much easier to use for a lot more people!

We agree 😄   even though it may be an improvement in _some_ areas, it's still a bit hard to read in places. admittedly, they are still low contrast scores even with 'A' contrast ratings.

We'll lighten it up a bit and also also take more attention with the smaller fonts as they seem to certainly not work well with the secondary text color.

Current WebAIM ratings:
Currently (against the lighter background in dark mode) our secondary text has an [AA rating](https://webaim.org/resources/contrastchecker/?fcolor=878787&bcolor=1F1F1F) and the body text has an [AAA rating](https://webaim.org/resources/contrastchecker/?fcolor=878787&bcolor=1F1F1F).

**Comment by kiwicopple** [comment] 2021-06-20 11:09
We've made quite a few changes here so I'm going to close this. If there are any specific elements which don't have enough contrast, feel free to drop them here and we will revisit 👍

**Closed by kiwicopple** 2021-06-20 11:09 UTC
Labels: bug
