### ISSUE TITLE
Date Picker in create record broken

### ISSUE THREAD

**Issue by obrunsmann** [supabase/supabase#6065] opened 2022-03-25 09:47 UTC
# Bug report

## Describe the bug

When entering a date in the date picker manually via keyboard, the date gets cleared immediately when trying to add minutes to the time. The moment the date was cleared was when entering "3" key on the keyboard for the 30 mins...

## To Reproduce

Please refer to the video.

## Screenshots

https://user-images.githubusercontent.com/763812/160288165-cd5ef9d0-5443-4845-930c-79fb0ddfc84c.mov

## System information

- OS: macOS
- Browser (if applies) chrome

**Comment by Lexora** [comment] 2022-03-26 18:21
ze video did not uplods

**Comment by obrunsmann** [comment] 2022-03-27 15:13
Hmm I don't know why the upload fails... so uploaded it here: https://drive.google.com/file/d/16ITw1OYBdnPKZ2Ccspug-oWtGIyBashQ/view?usp=sharing

**Comment by Lexora** [comment] 2022-04-17 05:37
thanks @obrunsmann  -- so I reproduced in local dev-env on my ubuntu and pretty sure the issue is here -> studio/components/interfaces/TableGridEditor/SidePanelEditor/RowEditor/DateTimeInput/DateTimeInput.tsx
now I gotta go and learn some react stuff if I'm to try and fix this :P

**Comment by saltcod** [comment] 2022-05-03 19:49
Hey all — wondering if this is still an issue. I just tested this locally and was able to successfully enter a date. Hopefully the video will upload!

https://user-images.githubusercontent.com/105593/166554604-e4465cf9-e51e-4c0c-8511-944faa8b0b96.mp4

**Comment by CactusPuppy** [comment] 2022-05-06 21:59
I am having a similar, if not identical, issue in Firefox 100.0 on Windows 11.
![firefox_4A44nOzBw7](https://user-images.githubusercontent.com/10406383/167221613-446000ab-483a-494d-8571-8734e7aea928.gif)

**Comment by MildTomato** [comment] 2022-05-11 04:22
We're seeing a lot of issues with this date input across a lot of different browsers.

We're starting to lean towards just adding in our custom date picker for this so that we have a consistent experience for everyone and to eliminate all the quirks of `<input type="datetime>`, `<input type="datetime-local">`, `<input type="date">` which don't play nice with postgres formatting of dates (timestamp, timestampz and so on).

**Comment by joshenlim** [comment] 2022-05-12 08:50
hey all! this should now be fixed by https://github.com/supabase/supabase/pull/6766

re: customer date picker we'll look into this separately!

will close this ticket but feel free to open if the issue still persists! 🙏

**Closed by joshenlim** 2022-05-12 08:50 UTC
Labels: bug, help wanted, dashboard
