### ISSUE TITLE
I am not receiving password reset emails for Supabase dashboard

### ISSUE THREAD

**Issue by bensinclair1** [supabase/supabase#27625] opened 2024-06-28 17:44 UTC
I have tried resetting my password on my Microsoft email account and my gmail account, and on both i do not receive the password reset emails. Is there any alternative to reset my password?

**Comment by Hallidayo** [comment] 2024-06-30 14:07
Hi @bensinclair1 - Thank you for opening the issue, Have you had a check of the auth logs (Logs > Auth) in the Supabase studio?

**Comment by encima** [comment] 2024-07-03 06:36
I think we can close this as it is is likely related to your account. Please do open a [support ticket](https://supabase.help) if the issue is not resolved, though!

**Closed by encima** 2024-07-03 06:36 UTC
Labels: awaiting-details, external-issue

**Comment by raahimkhan** [comment] 2025-03-24 09:55
I am having same issue.
