### ISSUE TITLE
Prisma documentation is missing (404)

### ISSUE THREAD

**Issue by Xananax** [supabase/supabase#18570] opened 2023-10-29 23:14 UTC
The url https://supabase.com/partners/integrations/prisma leads to a 404.

The link still exists in the list on https://supabase.com/partners/integrations, so this doesn't seem to be purposeful.

**Comment by Hallidayo** [comment] 2023-10-30 12:21
Hi @Xananax - The links seems to be okay now. Is it okay on your side now?

**Comment by Xananax** [comment] 2023-10-30 12:43
Yes, I confirm the link works for me now.

**Comment by wontondon** [comment] 2023-10-31 03:24
I'm still seeing the 404 when accessing the prisma link from the documentation.  This is returning a  404 when clicking prisma on the integrations page - https://supabase.com/partners/prisma.

**Comment by GaryAustin1** [comment] 2023-10-31 03:26
I'll re-open as I can't see it now either.

**Comment by fernandosmither** [comment] 2023-11-13 17:51
Off for me too!

**Comment by charislam** [comment] 2023-11-14 17:44
Odd, I'm seeing it now: https://supabase.com/partners/integrations/prisma

Is it still not working for you?

**Comment by IzaakPrats** [comment] 2023-11-14 17:46
fwiw I've been following along for a few days since I also saw a 404 page. It's working now -- wonder what the root cause is? Seems like it's been off/on for past two weeks.

**Comment by fernandosmither** [comment] 2023-11-15 18:02
yeah,, it's back on again...

Issued a [today-up-to-date](https://web.archive.org/web/20231115180130/https://supabase.com/partners/integrations/prisma) backup for future reference on the wayback machine

**Comment by fernandosmither** [comment] 2023-11-15 18:03
I think we shouldn't close this issue until the team gets to the root cause, weird that a static link has been unreliable

**Comment by charislam** [comment] 2023-11-15 20:19
@kamilogorek I think you're in charge of integrations so maybe you have some idea why this is being flaky?

**Comment by encima** [comment] 2024-01-09 12:05
Closing due to age; it seems to be have been working for the past few months. Confirm that both links currently work.

**Closed by encima** 2024-01-09 12:05 UTC
Labels: documentation
