### ISSUE TITLE
Unexpected password being set on local DB

### ISSUE THREAD

**Issue by cco3** [supabase/supabase#19809] opened 2023-12-16 19:59 UTC
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

With CLI 1.123.4, a fresh db starts with a password other than `postgres`.  The documentation still records `postgres` as the default local password.

## To Reproduce

1. `supabase start`
2. `psql "postgresql://postgres:postgres@localhost:54322/postgres"`

## Expected behavior

The connection would work without a password problem.

**Comment by hyldmo** [comment] 2023-12-18 13:48
More context in https://discord.com/channels/839993398554656828/1184234600348790814

I'm not sure if it is any help, but i created a new project from scratch while trying to reproduce this and no longer got the error: https://github.com/hyldmo/supabase-repro
Ended up just moving all the code to that repo and then renaming it, which seemingly worked. Maybe there is something to do with some caching on docker / untracked files in my repo?

**Comment by KevinBrolly** [comment] 2024-01-17 10:48
Hey, I could not replicate this issue on latest CLI version (1.131.5) - following the instructions and starting a new project the default password is set to `postgres` and I can connect via psql.

Since we did not see any/many other reports of this, it is quite likely it may be an error with your local docker setup or the older CLI version.

I am going to close the issue, but if you are still experiencing this on the latest CLI version let me know and we can reopen.

**Closed by KevinBrolly** 2024-01-17 10:48 UTC
Labels: bug, cli, self-hosted
