### ISSUE TITLE
Triggers and functions in remote commits may be in the wrong order

### ISSUE THREAD

**Issue by IoriBranford** [supabase/supabase#14440] opened 2023-05-18 00:08 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In remote commits, `create trigger` statements may come before `create function` statements. If a trigger depends on a function which is defined later, the remote commit cannot be applied.

## To Reproduce

1. Clone the [Next.js example app](https://github.com/supabase/supabase/tree/master/examples/user-management/nextjs-ts-user-management)
1. Create a corresponding project in app.supabase.com
1. In the project SQL Editor, create storage management functions and triggers from the [tutorial](https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs#storage-management) in order
1. Start a [Local Development](https://supabase.com/docs/guides/getting-started/local-development) instance in the example app
1. Follow the steps to [link and sync](https://supabase.com/docs/guides/getting-started/local-development#link-your-project): `supabase link --project-ref <project-id> && supabase db remote commit`
1. Reset the local database `supabase db reset` to apply the new remote commit
1. See error

```
Error: ERROR: function delete_old_profile() does not exist (SQLSTATE 42883)
At statement 0: CREATE TRIGGER before_delete_user BEFORE DELETE ON auth.users FOR EACH ROW EXECUTE FUNCTION delete_old_profile()
```

The remote commit: [20230517222837_remote_commit.sql.zip](https://github.com/supabase/supabase/files/11503177/20230517222837_remote_commit.sql.zip)
If you manually move the `CREATE TRIGGER before_delete_user` statement *after* the `CREATE OR REPLACE FUNCTION public.delete_old_profile()` statement, the remote commit can be applied successfully.

## Expected behavior

The remote commit statements are in the correct order and the database migration succeeds.

## System information

- OS: Linux Mint Vera
- Browser: N/A
- Version of supabase-js: 2.22.0
- Version of Node.js: 18.16.0
- Version of Next.js: 13.4.2

**Comment by GaryAustin1** [comment] 2023-05-18 00:11
https://github.com/supabase/cli/issues/1113
Looks like a duplicate of this.

**Comment by GaryAustin1** [comment] 2023-05-18 00:12
I'm going to close this in favor of that in the CLI.
Feel free to comment if I am incorrect, or on that one if appropriate.

**Comment by IoriBranford** [comment] 2023-05-18 00:12
Understood. Sorry about that.

**Comment by GaryAustin1** [comment] 2023-05-18 00:13
No worries, this issues gets linked to that one to amplify...

**Closed by GaryAustin1** 2023-05-18 00:13 UTC
Labels: bug
