### ISSUE TITLE
Unable to Switch to Light Mode without Login.

### ISSUE THREAD

**Issue by prafulnigam** [supabase/supabase#16560] opened 2023-08-16 10:57 UTC
# Bug report - Unable to Switch to Light Mode without Login.

## Describe the bug

As I land on the homepage, the Theme Switch button is faded & I am unable to change it.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Scroll down to 'Bottom of the Page'
4. See error at the bottom- right corner

**Comment by faizanraso** [comment] 2023-08-17 02:59
Hey @ronit044 and @bePratham, just an FYI, as far as I know, for contributing to supabase open source, you don't need to be assigned an issue, you can just submit a PR.

**Comment by Nitin-Magdum** [comment] 2023-08-17 04:17
Hi @prafulnigam 
I believe that I can fix this issue, I request you Assign the issue to me so can start working on it

**Comment by KrishKuChhabra** [comment] 2023-08-17 07:49
I have solved this issue, I have also put a pull request to it 
![Screenshot 2023-08-17 131833](https://github.com/supabase/supabase/assets/123287035/4bf5dc1c-3eca-489b-b3a5-33625ffa628b)

**Comment by azr-arch** [comment] 2023-08-17 09:42
I think I have found the root cause. On line 20 of [this file](https://github.com/supabase/supabase/blob/master/apps/www/components/Footer/index.tsx), the condition will be evaluated to true every time when the user is on the homepage. I think it was made to disable the button on the 'launch-week' page (just an intuition). The solution would be to remove everything from the '||' condition to the last and just check if a page is 'launch-week' or not. Else, for now, the solution will be to remove the disable attribute from the button. What do you guys think? Note: I am a beginner to open source.

**Comment by inbuilt-aura** [comment] 2023-08-17 14:44
hey, is this issue open.If yes, i would like to work on it.

**Comment by po1so9** [comment] 2023-08-19 16:37
I managed to fix the issue, but I don't know how to push the changes(This is my first time working on an open-source project).
![Supabase _ The Open Source Firebase Alternative - Brave 19-08-2023 22_04_46](https://github.com/supabase/supabase/assets/97946804/92c4a2b5-2060-4707-9501-08bbcd66d160)
![Supabase _ The Open Source Firebase Alternative - Brave 19-08-2023 22_04_34](https://github.com/supabase/supabase/assets/97946804/2d3d3f89-5739-440e-84d5-f6394c4b0674)

**Comment by fsansalvadore** [comment] 2023-08-21 12:20
Hey thanks everyone for contributing here. This behaviour is actually intentional and will be kept this way until we remove the Launch Week 8 branding in the homepage hero. A matter of a few weeks, roughly.

Closing this for now since it's not a bug. Thanks again! ✌️

**Closed by fsansalvadore** 2023-08-21 12:20 UTC
Labels: bug
