### ISSUE TITLE
Column name change is cached. Cannot run sql queries & makes bug tracking impossible

### ISSUE THREAD

**Issue by jtkeyva** [supabase/supabase#14484] opened 2023-05-20 07:17 UTC
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If I have a CHECK constraint on a column and I rename the column...when I get an error, it references the old column name. 

## To Reproduce

1. create a Text column named "original_name" 
2. add a CHECK constraint: original_name ~ '^[a-zA-Z0-9._-]{1,30}$'::text3. 
3. rename the column "new_name"
4. try to add a row from your app with  "new_name" column value of "i have spaces"
5. you will see a Failure Exception error message in your app or print statement that references "original_name"

## Expected behavior

The failure exception should reference the "new_name"

## Additional context

I've noticed this issue before when changing column names. Supabase/postgres seems to keep the old names somewhere. this can make bug tracking impossible if it's not fixed.

**Comment by jtkeyva** [comment] 2023-05-20 07:35
it also shows the original_name when running sql query in supabase studio

ALTER TABLE hub ALTER COLUMN new_name TYPE citext;

throws this error:
Failed to run sql query: could not create unique index "original_name"

**Comment by GaryAustin1** [comment] 2023-05-20 14:39
Probably a duplicate of this (covers both table name and in followup column names.
https://github.com/supabase/supabase/issues/10668

**Comment by jtkeyva** [comment] 2023-05-22 02:56
@GaryAustin1 ah thanks. i reported that issue to you in discord long ago and forgot you made an issue. it's a pretty big deal, hopefully it will get addressed soon. cheers

**Closed** 2023-05-23 16:30 UTC
Labels: bug, dashboard
