### ISSUE TITLE
No storage/bucket option on self-hosted supabase

### ISSUE THREAD

**Issue by nandox5** [supabase/supabase#4440] opened 2021-12-11 16:53 UTC
Just installed supabase using docker on ubuntu 18 and i am unable to see the bucket/storage option when going to the localhost:3000

running docker ps gives the following

```

05637569f21b   supabase/storage-api:v0.10.0     "/bin/sh -c \"./stora…"   14 hours ago   Up 14 hours   5000/tcp                                                                                                   supabase-storage
d7123b2d9044   postgrest/postgrest:v9.0.0       "/bin/postgrest"          14 hours ago   Up 14 hours   3000/tcp                                                                                                   supabase-rest
6ba3a6501363   supabase/postgres-meta:v0.29.0   "postgres-meta"           14 hours ago   Up 14 hours   8080/tcp                                                                                                   supabase-meta
1471f3dce836   supabase/realtime:v0.19.3        "bash -c './prod/rel…"    14 hours ago   Up 14 hours                                                                                                              supabase-realtime
8d4fa115e08d   supabase/gotrue:v2.2.12          "gotrue"                  14 hours ago   Up 14 hours                                                                                                              supabase-auth
00f6c1617fa4   supabase/postgres:14.1.0         "docker-entrypoint.s…"    14 hours ago   Up 14 hours   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                  supabase-db
52e33eff20fc   kong:2.1                         "/docker-entrypoint.…"    14 hours ago   Up 14 hours   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 8001/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp, 8444/tcp   supabase-kong
31d1e08e3194   supabase/studio:latest           "docker-entrypoint.s…"    14 hours ago   Up 14 hours   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                  supabase-studio

```

Can't even seem to be able to create another project or delete the default project?

**Comment by kiwicopple** [comment] 2021-12-13 04:50
> Can't even seem to be able to create another project or delete the default project?

This is by design: https://github.com/supabase/supabase/tree/master/studio#whats-included

> It is not intended for managing the deployment and administration of projects - that's out of scope.

The Studio will not offer [creating/administrating projects](https://github.com/supabase/supabase/tree/master/studio#managing-project-settings). The rough rule of thumb is 

- if it's inside the database, it should be in studio
- if it's outside the database, it will not be in studio

I'll keep this open for tracking our progress towards adding Storage Buckets - that should definitely be added since the schema/data/policies live inside the database.

**Comment by rhit-fayoumoa** [comment] 2022-02-21 01:43
Are there any plans for this to be included on a future release? If so, is there timeline? Thanks!

**Comment by jackcaldwell** [comment] 2022-03-03 10:24
While Storage Buckets on self hosted Supabase is unavailable, would it be worth adding something to the documentation that makes it clear that this is the case? Possibly to this page https://supabase.com/docs/guides/storage? I spent quite a bit of time yesterday trying to figure out why the page did not appear for me locally as I was convinced that it must have been some kind of configuration issue.

**Comment by justinmoon** [comment] 2022-03-11 04:30
Is storage unavailable on self-hosted instances? Or do the configuration options just not show up in Studio when self-hosted?

**Comment by dlchet** [comment] 2022-03-11 04:32
> Is storage unavailable on self-hosted instances? Or do the configuration options just not show up in Studio when self-hosted?

storage is available via api, including bucket operations. so this is either about studio (which i agree, does not show anything about storage when in local mode) or a misconception/documentation issue.

**Comment by kiwicopple** [comment] 2022-03-21 12:48
@dlchet is correct - we haven't yet enabled the Storage interface on Studio - simply because we are busy - but it should still work 100% through the API

We'll get to storage within Studio asap

**Comment by Ultimatum22** [comment] 2022-05-10 11:47
I know this is an old ticket. But after extensive google search I found multiple questions about this topic but I couldn't find any answer to this. I am missing pointers to documentation on how I am able to add new projects in a local hosted docker instance.

**Comment by ImSingee** [comment] 2022-05-10 11:49
> I know this is an old ticket. But after extensive google search I found multiple questions about this topic but I couldn't find any answer to this. I am missing pointers to documentation on how I am able to add new projects in a local hosted docker instance.

In short, you can't

**Comment by 50l3r** [comment] 2022-05-10 19:20
> I know this is an old ticket. But after extensive google search I found multiple questions about this topic but I couldn't find any answer to this. I am missing pointers to documentation on how I am able to add new projects in a local hosted docker instance.

Yo need to create other stack with docker compose

**Comment by galatolofederico** [comment] 2022-06-24 12:23
> @dlchet is correct - we haven't yet enabled the Storage interface on Studio - simply because we are busy - but it should still work 100% through the API
> 
> We'll get to storage within Studio asap

Hi @kiwicopple great work with supabase!

Next semester I have to host a series of lectures about BaaS at my uni. I thought of using supabase for the lab part but the absence of a GUI for the storage is a huge deal-breaker.
Do you think that this issue will be solved by next September/October?

**Comment by J0** [comment] 2022-07-21 03:02
Hey @galatolofederico,

Sorry for the delay -- do you mind shooting us an email at support@supabase.io ? I'm not sure about the progress on self-hosted storage GUI but there's a chance that we have workarounds for your use case.

Thanks

**Comment by adityadhawan22** [comment] 2022-08-24 08:29
https://github.com/supabase/supabase/pull/8623

**Comment by brocococonut** [comment] 2022-08-25 16:43
> Created a PR for it #8623

It'd be awesome to see this merged in! Especially considering the age of this issue..

**Comment by globemediaofficial** [comment] 2022-10-15 04:04
I understand storage is not included in the studio when self-hosting but how can it be configured then? I need the Row Level Security to be disabled because it needs to be public. Right now, even if a user is authenticated, trying to create a bucket in the app gives an error `New row violates RLS`.

**Comment by kiwicopple** [comment] 2022-10-17 11:58
> storage is not included in the studio

It's hidden behind a flag, but the functionality is there. We recently hired a Storage Lead so I'll flag this up to remove the flag in Studio (after testing)

For now, you can edit any of the RLS policies using the SQL editor. 

```sql
-- This will allow any user access to the bucket named 'avatars'
create or alter policy "Public Access" 
  on storage.objects for all 
  using ( bucket_id = 'avatars' );
```

**Comment by Jahorse** [comment] 2022-10-29 22:14
Hi @fenos, I see you have been assigned to this issue, will you be picking up the PR from @adityadhawan22? It has been sitting for over a month now and I'd really like to use this feature with official support.

**Comment by thilojaeggi** [comment] 2022-11-10 08:29
Would also like this.

**Comment by globemediaofficial** [comment] 2022-11-14 03:09
What is the current workaround? I need to create a public bucket called 'posts'. How would I do this with the SQL Editor? Also it's been a few months short of a year since the Supabase team said they would add Storage to the dashboard, what's the holdup? There are even volunteers who did the work themselves but the team won't merge them.

**Comment by kiwicopple** [comment] 2022-11-15 01:13
Hey everyone - I've assigned this to @fenos , but also not that this is definitely something a community member can contribute without too much effort. It's a matter of updating some of the feature flags in the Studio. There might be a few things that you get stuck on, but we can help anyone who is attempting this (and I'm happy to give some swag + a shoutout for anyone willing to help out)

**Comment by globemediaofficial** [comment] 2022-11-15 01:20
@kiwicopple 

It looks like @adityadhawan22 has done the work already. They created a PR and it was rejected because off an issue with the URLs. They fixed the issue and requested for it to be reviewed again in early September. It looks like since then it has still not been reviewed again, the PR still says it’s waiting for review from a reviewer that has write access.

**Closed** 2022-11-17 06:11 UTC
Labels: enhancement, dashboard, self-hosted, storage

**Comment by KeyOnTech** [comment] 2023-03-28 15:52
> Hey everyone - I've assigned this to @fenos , but also not that this is definitely something a community member can contribute without too much effort. It's a matter of updating some of the feature flags in the Studio. There might be a few things that you get stuck on, but we can help anyone who is attempting this (and I'm happy to give some swag + a shoutout for anyone willing to help out)

are you guys still looking for help on this would love to get involved and get some Supabase SWAG lol  
I am currently running on Mac's M1 and Intel both doing the same
I am using Docker to run my Supabase instance
I changed the port for 3000 to 8020 so I dont conflict with React stuff along the way...
I am unable to create storage buckets, new users, new projects but wouldn't mind getting involved where I can help on the buckets issues running on localhost with docker

Thanks
