### ISSUE TITLE
Concurrent JSONB inserts result in incorrect data type via transaction-mode based pooler

### ISSUE THREAD

**Issue by alexcouper** [supabase/supabase#29090] opened 2024-09-04 15:06 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When performing inserts involving JSONB data using a connection pooler connection in transaction mode (6543), some of the inserts are string escaped. 

This does not happen when run serially, and it also doesn't happen if connecting in session mode  on the pooler (5432).

## To Reproduce

1. Create a table
```sql
create table "dodgy_json" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "dodgy" jsonb not null
);
```
2. Use this test:
```typescript
import postgres from "postgres";

let sql: postgres.Sql;

describe("dodgy sql json 1", () => {
  beforeAll(async () => {
    sql = postgres(process.env.DATABASE_URL!, { ssl: true });
  });
  afterAll(async () => {
    sql.end();
  });

  for (let i = 0; i < 20; i++) {
    it("tests dodgy json", async () => {
      const jsonReady = {
        foo: "bar",
      };
      const obj =
        await sql`INSERT INTO dodgy_json(dodgy) VALUES (${jsonReady as any}) RETURNING id;`;
      const check =
        await sql`SELECT jsonb_typeof(dodgy) from dodgy_json WHERE id=${obj[0]!.id};`;
      expect(check[0]!.jsonb_typeof).toBe("object");
    });
  }
});
```
3. See that it works when run individally (use the `6543` port on the pooler)
```
DATABASE_URL=postgres://... jest sql.test.ts
```
4. Copy this test file into 3 different files and run them concurrently using jest
```
cp sql.test.ts sql2.test.ts
cp sql.test.ts sql3.test.ts
DATABASE_URL=postgres://... jest sql*
```

5. See that you have errors
```
dodgy sql json 1 › tests dodgy json

    expect(received).toBe(expected) // Object.is equality

    Expected: "object"
    Received: "string"

      24 |         await sql`SELECT jsonb_typeof(dodgy) from dodgy_json WHERE id=${obj[0]!.id};`;
    > 25 |       expect(check[0]!.jsonb_typeof).toBe("object");
         |                                      ^
      26 |     });
      27 |   }
      28 | });

```
6. Note that the error is that sometimes the data ends up as a string in the database rather than an object (see screenshot)

7. Run against the `5432`  port, you should see success.

## Expected behavior

Running these tests in parallel should result in all rows having the same object.

## Screenshots

Example concurrent test run results in database:
<img width="756" alt="image" src="https://github.com/user-attachments/assets/be874e67-356e-4271-b5ea-a4875aeaa38e">

## System information

- Version of SupabaseJS: N/A
- Version of postgres: (https://github.com/porsager/postgres): ^3.4.4

## Additional context

I initially thought this was a bug in a client library I was using, and raised an issue there but have discovered that it is supabase, transaction mode specific (https://github.com/porsager/postgres/issues/937)

**Comment by nkalpakis21** [comment] 2024-09-05 03:20
built an app to get paid for this PR
https://www.n0va-io.com/discover/supabase/supabase

**Comment by encima** [comment] 2024-09-05 11:11
Hi @alexcouper 
Thanks for opening! Testing this on a project, I am unable to reproduce. From the looks of it, this could be some issue with jest or concurrency.

If you can provide a repo to easily reproduce this, that would be great. Trying with jest and also trying with multiple scripts running at the same time results in the record being saved in my tests

**Comment by alexcouper** [comment] 2024-09-05 11:23
Ok interesting. I'll try to create a repo where this is happening in the next few days and get back to you

**Comment by alexcouper** [comment] 2024-09-08 20:55
@encima I've created a repo where I get the same issue: https://github.com/alexcouper/supabase-jsonb-issue

**Comment by encima** [comment] 2024-09-19 12:56
Hi @alexcouper 
Sorry for the delay here! and thank you for the repo to reproduce! That was much easier to see!

The reason you see this is not (only) because of Supavisor but because of `postgres` using prepared statements by default. As shown in the connection pooling mode dialog (and the [docs](https://www.npmjs.com/package/postgres)), prepared statements are not supported in transaction mode for Supavisor.

![image](https://github.com/user-attachments/assets/2900171b-0127-411f-8d81-ffda07aa8b2c)


The best fix for this is to add `prepare:false` to the options when instantiating the [library](https://www.npmjs.com/package/postgres) (same place you add the SSL options).


Let us know if you have any issues there!

**Closed by encima** 2024-09-19 12:56 UTC
Labels: database, cannot-reproduce, awaiting-details, external-issue
