### ISSUE TITLE
Sign in with Google shows "continue to Supabase.co"

### ISSUE THREAD

**Issue by Saunved** [supabase/supabase#1798] opened 2021-06-02 13:25 UTC
# Bug report

## Describe the bug
After adding the Google client and secret, while testing out the registration flow, we realized that the Google sign in box says "Continue to supabase.co"
This is a big issue for us. It should show our website's URL. Is there a way to resolve this?
Do we need to edit something in the Google console?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

(1) Add Google client key, secret to Supabase
(2) Implement a social sign in with Google as the provider
(3) Try logging in with Google on the UI

## Expected behavior
The prompt above the log in should say "Continue to <SITE_URL>"
The privacy policy, TOS links, should be used from the data provided in our Google console.

## Screenshots

![supabase_signin](https://user-images.githubusercontent.com/16450673/120487720-d391de00-c3d3-11eb-9e6a-ae314279c9be.png)

## System information
NA

## Additional context
NA

**Comment by kiwicopple** [comment] 2021-06-03 04:10
Currently the way to handle this is to create a "proxy" route on your own domain.

1. Create a route on your domain
2. Use the `redirectTo` option when you are signing up the user: https://supabase.io/docs/reference/javascript/auth-signin
3. Google will redirect the user to the `redirectTo` URL.
4. You can extract all the Session information from the URL, same as what we are doing here: https://github.com/supabase/gotrue-js/blob/99a11bbdc62700dc2621f522ac1fea5d905c6cc6/src/GoTrueClient.ts#L316

In the future we will probably allow you to add your own domains, but it isn't on the backlog for this quarter (possibly the end of the year)

I'll close this for now @Saunved but if you have any comments/issues feel free to note them here. I can reopen if the workaround above isn't feasible

**Closed by kiwicopple** 2021-06-03 04:10 UTC
Labels: bug

**Comment by Saunved** [comment] 2021-06-03 09:55
Thanks for the response @kiwicopple 
I was wondering if there is any way for us to directly reuse the method used in (4)? Is it exported in the gotrue.js client by any chance?

Also, once I extract the session information, how can I ask the Supabase client to store it (in localStorage) like it currently does? Does that happen automatically? Just a bit confused here.

**Comment by Saunved** [comment] 2021-06-03 16:33
@kiwicopple 
I tried playing with the `redirectTo` option in Supabase.
This is the function I am calling when a user clicks on "Google" on our webpage.
```js
async social(provider) {
  const { user, session, error } = await this.$supabase.auth.signIn(
    {
      provider,
    },
    {
      redirectTo: 'http://localhost:3000/account',
    }
  )
  console.log(user, session, error)
}
```

When calling `social('google')` here, the console.log prints `null null null`, and the same page as before is shown.

Things I have done
(1) Added the redirect URL to Supabase redirect URL in settings
(2) Added the redirect URL in the Google client
(3) Double-checked that the redirect URLs are correct in all 3 places (Google, Supabase, and my code)

Please let me know if I've missed a step.

**Comment by kiwicopple** [comment] 2021-06-07 05:45
Hi @Saunved - this one seems like a slightly different issue - I can't tell what's happening yet based on this code. Would you mind creating a new issue and providing a small amount of code to reproduce the problem? Thanks!

**Comment by saampotter** [comment] 2021-06-30 08:40
> Currently the way to handle this is to create a "proxy" route on your own domain.
> 
> 1. Create a route on your domain
> 2. Use the `redirectTo` option when you are signing up the user: https://supabase.io/docs/reference/javascript/auth-signin
> 3. Google will redirect the user to the `redirectTo` URL.
> 4. You can extract all the Session information from the URL, same as what we are doing here: https://github.com/supabase/gotrue-js/blob/99a11bbdc62700dc2621f522ac1fea5d905c6cc6/src/GoTrueClient.ts#L316
> 
> In the future we will probably allow you to add your own domains, but it isn't on the backlog for this quarter (possibly the end of the year)
> 
> I'll close this for now @Saunved but if you have any comments/issues feel free to note them here. I can reopen if the workaround above isn't feasible

Hi @kiwicopple, I'm not sure how this addresses this issue at all?

Currently testing this and the flow that occurs is: (1) client -> (2) supabase -> (3) google -> (4) supabase -> client.

> 3. Google will redirect the user to the `redirectTo` URL.

So this just isn't occurring?

(3) is the reason it says "continue to supabase.co", and the current implementation of `redirectTo` has no impact on that that specific request (since the `redirectTo` param is only used in (4) to return the client to whatever URL was given).

This issue would be fixed if the implementation functionality of `redirectTo` was used to redirect directly back to the client. But right now that isn't happening, is it meant to?

**Comment by connorlindsey** [comment] 2022-02-27 14:02
Discussion around this issue continues on this issue in the GoTrue repo: https://github.com/supabase/gotrue/issues/142

**Comment by akinwol** [comment] 2023-04-25 00:20
So, I just started using supabase and ran into this issue.


To fix, I created a callback page that looks something like this.
```
const CallbackPage: NextPageWithLayout = () => {
  const router = useRouter();
  const path = router.query[redirectPathKey];

  React.useEffect(() => {
    if (path) {
      void router.push(path as string);
    }
  }, [path, router]);
  return (
    <div>
      <div className="flex justify-center">Loading....</div>
    </div>
  );
};

```


My signIn/signup function looks something like this 
```
const { data, error } = await supabase.auth.signInWithOAuth({
      provider: "twitter",
      options: {
        redirectTo: `${
          window.location.origin
        }/auth/callback?${redirectPathKey}=${redirectUri || routes.HOME}`,
      },
    });

```

After sign in the user will get redirected to the callback page. If I detect a redirect uri I will just redirect the user.



Also have this in my middleware. If a user hits the page without a valid redirect path, I redirect the user to the home page
```
 if (req.nextUrl.pathname.startsWith("/auth/callback")) {
      const path = req.nextUrl.searchParams.get(redirectPathKey);
      console.log({ path})
      if (!path) {
        return NextResponse.redirect(new URL(routes.HOME, req.url));
      }
  
    }
```

Hope this helps
