### ISSUE TITLE
Dashboard SQL editor crashes on query error

### ISSUE THREAD

**Issue by ShanArosh** [supabase/supabase#20053] opened 2023-12-29 10:30 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Dashboard SQL editor crashes on query error
```
Application error: a client-side exception has occurred (see the browser console for more information). 
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
Follow the [documentation](https://supabase.com/docs/guides/cli/local-development) for starting a local development instance.
## Expected behavior

Handle query errors gracefully and output without crashing

## Screenshots

![Screenshot 2023-12-29 155225](https://github.com/supabase/supabase/assets/96517136/5c14390f-70db-463d-a403-d228e8a000aa)
![Screenshot 2023-12-29 160020](https://github.com/supabase/supabase/assets/96517136/3e2995d7-1104-448a-be1b-5e1956e091c1)

## System information

- Version of supabase(cli): 1.123.4

**Comment by gfx687** [comment] 2023-12-30 07:02
I can confirm experiencing the same problem

Locally (and only locally, with `supabase start`) making any mistakes / typos in SQL results in page crashing
Remote (supabase.com) handles errors in SQL correctly - by displaying the problem in "Results" as expected

**Comment by igorlanko** [comment] 2023-12-30 20:53
Looks related https://github.com/supabase/supabase/issues/19227.

**Comment by ShanArosh** [comment] 2024-01-01 00:14
The object react complaining about is returned error  `{code,message,requestId}`.somewhere in the jsx react is trying to render out the error without reformatting it .

**Comment by saltcod** [comment] 2024-01-02 19:28
Hi all — investigating this. Marking it as a P1. This looks like a release issue. Will update as soon as I have more info.

**Comment by encima** [comment] 2024-01-05 20:46
Closing this in favour of #19035, please add discussions or feedback there

**Closed by encima** 2024-01-05 20:46 UTC
Labels: bug, dashboard
