### ISSUE TITLE
Internal server error during user signup authentication

### ISSUE THREAD

**Issue by milestones95** [supabase/supabase#1736] opened 2021-05-27 15:44 UTC
# Bug report![image](https://user-images.githubusercontent.com/47959617/119856247-6c51c680-bec7-11eb-8dab-9ed75c32b202.png)When I try to sign up a new user I receive an internal server error code: https://lutcrhnocwappsgimbuo.supabase.co/auth/v1/signup 500
## Describe the bug

I want the user to be able to signup and the data enter the authentication user table.
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

const SignUp = () => {
    const [helperText, setHelperText] = useState({ error: null, text: null });
    const emailRef = useRef();
    const passwordRef = useRef();
    const classes = useStyles();

    const handleLogin = async (type) => {
        const email = emailRef.current?.value;
        const password = passwordRef.current?.value;

        const { user, error } =
            type === "LOGIN"
                ? await supabase.auth.signIn({ email, password })
                : await supabase.auth.signUp({ email, password });

        if (error) {
            setHelperText({ error: true, text: error.message });
        } else if (!user && !error) {
            setHelperText({
                error: false,
                text: "An email has been sent to you for verification!",
            });
        }
    };
}

## Expected behavior

2 days ago it worked fine and user data was inserted into user table

## Screenshots

![image](https://user-images.githubusercontent.com/47959617/119856247-6c51c680-bec7-11eb-8dab-9ed75c32b202.png)

## System information

macOS
chrome
version of supabase: 0.4.0
npm version: 6.13.4

<img width="1123" alt="Screen Shot 2021-05-27 at 8 41 12 AM" src="https://user-images.githubusercontent.com/47959617/119856585-b2a72580-bec7-11eb-83e7-fb1653a17429.png">

**Comment by kiwicopple** [comment] 2021-05-28 11:50
Hi @milestones95 - it looks like your `/auth` route is returning a `500` error. Did you change anything in the `auth` schema of your database? 

Could you please email `beta@supabase.com` with your project details so that we can check?

I'll close this for now, because I suspect that's the cause and we'll need to help you  individually. If it turns out to be a problem generic to everyone we can re-open and then share the solution 👍

**Closed by kiwicopple** 2021-05-28 11:50 UTC
Labels: bug
