### ISSUE TITLE
Container supabase-anlythics error/failed to start 

### ISSUE THREAD

**Issue by ibroid** [supabase/supabase#20878] opened 2024-01-30 15:24 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I was following supabase self hosted documentation. at first install it was successful. after i try to customize the .env settings, then i docker compose up again, it was failed at supabase-analythics.  even i was following the analythics setup documentation.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```
# Get the code
git clone --depth 1 https://github.com/supabase/supabase

# Go to the docker folder
cd supabase/docker

# Copy the fake env vars
cp .env.example .env

# Pull the latest images
docker compose pull

# Start the services (in detached mode)
docker compose up -d

```

## Expected behavior

Supabase success mounted in docker at self hoster

## Screenshots

![Screenshot 2024-01-30 100943](https://github.com/supabase/supabase/assets/56104889/8727d76c-c87b-4e41-9d63-2bb1bf420caf)

![image](https://github.com/supabase/supabase/assets/56104889/40be4bce-de80-4757-8c78-3a59c9491073)

## System information

- OS: Debian (VPS. 2 Core. 5GB RAM). Fresh Installed
- Supabase Version : latest

**Comment by encima** [comment] 2024-02-01 06:50
More information is needed please, @ibroid 

To me, it seems like this is not a bug as you successfully got this running before editing the `env` file. What did you add/remove/update? Are you sure the formatting is correct and/or what was added is formatted correctly?

Thanks!

**Comment by ibroid** [comment] 2024-02-02 01:14
> More information is needed please, @ibroid
> 
> To me, it seems like this is not a bug as you successfully got this running before editing the `env` file. What did you add/remove/update? Are you sure the formatting is correct and/or what was added is formatted correctly?
> 
> Thanks!

i've adding some logflare api-key to .env file after that every time i start ```docker compose up``` , it stuck at supabase-analythic. and resulting error after minutes. 
iam sorry to tag it as a bug. i have no idea wich tag is more appropriate.
but still now, i havent figured it out.

**Comment by encima** [comment] 2024-02-02 07:03
Thanks for following up and no need to apologise! 

I removed the tag because it is attached to some workflows and I did not want it to be investigated before we know more. We can add it back once we confirm the issue.

Could you provide the `.env` file you have modified with please (hiding the secrets)? Can you also confirm if this works as expected by reverting to the default `.env` file?

**Comment by ibroid** [comment] 2024-02-02 07:30
> Could you provide the `.env` file you have modified with please (hiding the secrets)? Can you also confirm if this works as expected by reverting to the default `.env` file?

thanks for following up my issue.
i have no big changes to my .env file from the original (.env.example). i just add logflare api key

```
############
# Secrets
# YOU MUST CHANGE THESE BEFORE GOING INTO PRODUCTION
############

POSTGRES_PASSWORD=
JWT_SECRET=
ANON_KEY=
SERVICE_ROLE_KEY=

DASHBOARD_USERNAME=imal
DASHBOARD_PASSWORD=kuyabatok

############
# Database - You can change these to any PostgreSQL database that has logical replication enabled.
############

POSTGRES_HOST=localhost
POSTGRES_DB=postgres
POSTGRES_PORT=5432
# default user is postgres

############
# API Proxy - Configuration for the Kong Reverse proxy.
############

KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443


############
# API - Configuration for PostgREST.
############

PGRST_DB_SCHEMAS=public,storage,graphql_public


############
# Auth - Configuration for the GoTrue authentication server.
############

## General
SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
API_EXTERNAL_URL=http://localhost:8000

## Mailer Config
MAILER_URLPATHS_CONFIRMATION="/auth/v1/verify"
MAILER_URLPATHS_INVITE="/auth/v1/verify"
MAILER_URLPATHS_RECOVERY="/auth/v1/verify"
MAILER_URLPATHS_EMAIL_CHANGE="/auth/v1/verify"

## Email auth
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=false
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=supabase-mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=fake_sender

## Phone auth
ENABLE_PHONE_SIGNUP=true
ENABLE_PHONE_AUTOCONFIRM=true


############
# Studio - Configuration for the Dashboard
############

STUDIO_DEFAULT_ORGANIZATION=GNR
STUDIO_DEFAULT_PROJECT=GNR

STUDIO_PORT=3000
# replace if you intend to use Studio outside of localhost
SUPABASE_PUBLIC_URL=http://localhost:8000

# Enable webp support
IMGPROXY_ENABLE_WEBP_DETECTION=true

############
# Functions - Configuration for Functions
############
# NOTE: VERIFY_JWT applies to all functions. Per-function VERIFY_JWT is not supported yet.
FUNCTIONS_VERIFY_JWT=false

############
# Logs - Configuration for Logflare
# Please refer to https://supabase.com/docs/reference/self-hosting-analytics/introduction
############

LOGFLARE_LOGGER_BACKEND_API_KEY=my_key_after_i_changes_this_i_got_the_issue

# Change vector.toml sinks to reflect this change
LOGFLARE_API_KEY=my_key_after_i_changes_this_i_got_the_issue

# Docker socket location - this value will differ depending on your OS
DOCKER_SOCKET_LOCATION=/var/run/docker.sock

# Google Cloud Project details
GOOGLE_PROJECT_ID=GOOGLE_PROJECT_ID
GOOGLE_PROJECT_NUMBER=GOOGLE_PROJECT_NUMBER

``` 

i also reverting my .env file to the original one. after that i try remove all docker image and pull it again.
and this is the result when i try to ```docker compose up``` again
![image](https://github.com/supabase/supabase/assets/56104889/d0b586e4-4164-45be-a4ba-37db883b8a19)

**Comment by ibroid** [comment] 2024-02-02 07:42
![image](https://github.com/supabase/supabase/assets/56104889/0083d4fd-c201-4256-b105-a85a210645ea)

**Comment by encima** [comment] 2024-02-07 07:52
@ibroid did you mean to close this? If you solved your issue, could you please add a comment on what you found. Thanks!

**Comment by grimechristopher** [comment] 2024-02-12 05:21
I have this issue and cannot solve this

**Comment by ibroid** [comment] 2024-03-19 02:38
> @ibroid did you mean to close this? If you solved your issue, could you please add a comment on what you found. Thanks!

sorry i didnt notice for a while. i didnt fix it until now. no one solution that i found is work for me, so i close the issue because i thought it was a problem in my environment.

**Comment by encima** [comment] 2024-03-19 04:38
@raynic35 do you have special characters in your postgresql password?

**Comment by encima** [comment] 2024-03-20 04:56
I am unable to reproduce with the latest pull from the repo with the following image versions (arm).

<img width="452" alt="image" src="https://github.com/supabase/supabase/assets/517923/0bf1f7cf-c83f-4252-9893-d5aa81bfffb0">

Closing this for now but we can reopen if this is occurring on the same or newer versions in the CLI.

If you are not on OSX and using M1/2/3, please comment with your OS and Arch

**Closed by encima** 2024-03-20 04:56 UTC
Labels: self-hosted, needs-analysis
