### ISSUE TITLE
Add integration / partner gallery to sitemap 

### ISSUE THREAD

**Issue by saltcod** [supabase/supabase#13870] opened 2023-04-20 23:27 UTC
Sitemap generator needs to be updated to include pages in partner gallery

https://supabase.com/partners/integrations

https://github.com/supabase/supabase/blob/master/apps/www/internals/generate-sitemap.mjs

**Comment by MildTomato** [comment] 2023-04-21 04:44
duplicate of https://github.com/supabase/supabase/issues/12461

**Closed by MildTomato** 2023-04-21 04:44 UTC
Labels: bug, help wanted, supabase.com
