### ISSUE TITLE
Two different clock times in the same column

### ISSUE THREAD

**Issue by Cheizr** [supabase/supabase#28844] opened 2024-08-23 14:44 UTC
## Describe the bug

From the site dashboard when i double click in the date, the clock time display the correct time. Ii understand that maybe it could be related to UTC, my time zone is UTC−03:00

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Double click on selected timestampz column

## Expected behavior

Display the clock with the same timezone

## Screenshots
![Captura de pantalla 2024-08-20 072331](https://github.com/user-attachments/assets/e0f27c1f-a03b-40cb-ad2e-cd94d366a760)
![Captura de pantalla 2024-08-20 072337](https://github.com/user-attachments/assets/3b2ec9f5-c904-43f0-84da-9012063d199d)

## System information

- Web version

**Comment by neehhaa06** [comment] 2024-08-28 06:34
Hello @encima 

To fix the inconsistent clock times, convert UTC timestamps to the local timezone (UTC−03:00) before display. On the backend, use `moment-timezone` in Node.js or adjust your SQL query with `AT TIME ZONE`. On the frontend, use JavaScript’s `Date` object with `toLocaleString()` for conversion. This ensures consistent timezone display.

**Comment by iamabhshk** [comment] 2024-08-30 06:57
Hello, is this assigned to someone? If not can I work on this?

**Comment by encima** [comment] 2024-08-30 06:58
anyone is welcome to make a PR, yes. Just make sure to link to this issue when opening! 🙏

**Comment by aryan-mehrabi** [comment] 2024-09-03 19:50
Hi @encima,

I believe this issue could be handled more cleanly in the backend (Supabase Postgres-Meta), if possible.

**Comment by encima** [comment] 2024-09-03 20:01
@aryan-mehrabi sure, feel free to make a PR. This seems like a frontend issue and not an API one but I'll let the team decide on the best approach!

**Comment by Deepak22448** [comment] 2024-11-07 16:40
@encima if found that the issue is with **input type** =`datetime-local` it only supports `dd/mm/yyyy`.

**Closed** 2024-11-08 06:44 UTC
Labels: bug, help wanted, good first issue, frontend, external-issue
