### ISSUE TITLE
(Studio) Copy cell content in Table Editor not always working

### ISSUE THREAD

**Issue by ruggi99** [supabase/supabase#4453] opened 2021-12-12 20:45 UTC
# Bug report

## Describe the bug

"Copy cell content" button in context menu in table editor not always works as intended.
Also reported in #3467

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to "auth.users" table editor
2. Right Click on UUID of a user
3. Click on "Copy cell content"
4. In this case it copies "instance_id" of the same row

(If I try to copy "instance_id" cell it copies "UUID" content instead)

## Expected behavior

It copies UUID cell content

## Screenshots

Not needed

## System information

- OS: [Windows]
- Browser (if applies) [Chrome]
- Version of supabase-js: [Not involved]
- Version of Node.js: [Not involved]

## Additional context

Bug is probably due to how position of a cell is handled in `@supabase/grid` and `@supabase/react-data-grid` as it may be different cause of frozen columns.
In case of `auth.users`, in `@supabase/grid` "UUID" comes after "instance_id", but in `@supabase/react-data-grid` comes before because it's a primary-key, so a frozen column.

**Comment by joshenlim** [comment] 2021-12-13 08:16
might need your help to take a look at this @phamhieu

**Comment by burmecia** [comment] 2021-12-20 02:54
I think this issue is caused by `@supabase/grid` component. The item order of its state variable `state.gridColumns` is not in sync with `@supabase/react-data-grid`, especially after doing column freeze/unfreeze. The freeze/unfreeze will change columns order, but `state.gridColumns` didn't catch up with that change. So when you access an item in `state.gridColumns` by index, you won't get correct value. You can reproduce this bug by randomly picking some columns for freeze/unfreeze and then copying cell content.

I've raised this issue https://github.com/supabase/grid/issues/103, and will provide a PR later on.

**Comment by Isaiah-Hamilton** [comment] 2022-01-25 01:39
Fixed with https://github.com/supabase/grid/pull/104

**Closed by Isaiah-Hamilton** 2022-01-25 01:39 UTC
Labels: bug, help wanted
