### ISSUE TITLE
Supabase-Authentication: Documentation and use cases

### ISSUE THREAD

**Issue by Sesa1988** [supabase/supabase#5096] opened 2022-01-21 22:20 UTC
Hi,

I have multiple questions regarding authentication and cant really find anything that helps me.
Maybe its a bug maybe its missing documentation, an error on my part or just expected behavior, I don't know @kiwicopple 

**Token expiration and startup** 
If I set the expire token duration to 1 week I **can restore** the session within that week. 
If I set the expire token duration to 2 min and the user opens  the app after that duration no refresh is possible and **"Invalid JWT token"** error appears.

Thats my token with the Invalid JWT token error on my dev environment, not that critical to share.
`"{"currentSession":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjQyODA1ODIwLCJzdWIiOiIzMDc4ZjY2NS1jNjFiLTQ0Y2UtYjY3ZS1kNzIyOTNjMWFjMmMiLCJlbWFpbCI6InNlcmdlai5zYWNoc0BnbXguZGUiLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQifQ.QQaZpPDTy1urjbZNoMf88I15HIIHIoGRPJN152ht06U","expires_in":120,"refresh_token":"ybqC0YdCNlYxByvlQh5WQA","token_type":"bearer","provider_token":null,"user":{"id":"3078f665-c61b-44ce-b67e-d72293c1ac2c","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{},"aud":"authenticated","email":"anymail@provider.com","created_at":"2022-01-20T12:12:57.382314Z","confirmed_at":"2022-01-20T12:12:57.387309Z","last_sign_in_at":"2022-01-21T22:55:00.788920397Z","role":"authenticated","updated_at":"2022-01-21T22:55:00.790273Z"}},"expiresAt":1642805820}"`

If I set the expiration to 2 min and close my app for that time, should I be able to refresh my session? Because one week would be short for logout on users that does not open an app in that timeframe.

**Expired token while app is running**
I saw a property called "**autoRefreshTokens**" but this don't happen if my app is running and my token expires.
If I want to call any database API I get "**JWT token expired"** error back.

I tested it with 2 min JWT expiration duration and using the dart only library for this tests.

**Comment by SergejSachs** [comment] 2022-01-22 00:58
I open an bug for my issue:
https://github.com/supabase-community/supabase-dart/issues/91

**Comment by hf** [comment] 2022-09-09 09:49
Hey would you mind sharing the exact settings you're using? I'm having trouble tracking down the root cause of this.

Some notes tho: JWT expiration typically shouldn't be shorter than 5 minutes. At this time we don't (unless I'm mistaken) support controlling of the duration of a log-in session. We're going to be adding this as a feature in the coming months.

**Comment by Sesa1988** [comment] 2022-09-11 12:25
> Hey would you mind sharing the exact settings you're using? I'm having trouble tracking down the root cause of this.
> 
> Some notes tho: JWT expiration typically shouldn't be shorter than 5 minutes. At this time we don't (unless I'm mistaken) support controlling of the duration of a log-in session. We're going to be adding this as a feature in the coming months. 

Hey, I will share my settings and code the next days.

**Comment by J0** [comment] 2023-02-09 05:19
Hey @Sesa1988,

Sorry just bumping this issue again - wondering if you could let us know your settings when there's a free cycle.

Thanks!

**Comment by dshukertjr** [comment] 2023-02-14 03:45
Since we sorted out the issue here https://github.com/supabase/supabase-flutter/issues/83, I think we can close this issue, but feel free to reopen it if any of the issues persists.

**Closed by dshukertjr** 2023-02-14 03:45 UTC
Labels: documentation, auth
