### ISSUE TITLE
OpenAI edge function sample code failing with  `_computedKey` error

### ISSUE THREAD

**Issue by ashleymills** [supabase/supabase#27108] opened 2024-06-08 10:05 UTC
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Hi. I've followed the steps listed here https://supabase.com/docs/guides/ai/examples/openai to create an edge function to interact with OpenAI.

When running the edge function locally, and making a request, I get the follow output:

```
Setting up Edge Functions runtime...
Serving functions on http://127.0.0.1:54321/functions/v1/<function-name>
Using supabase-edge-runtime-1.53.4 (compatible with Deno v1.40.3)
serving the request with /home/deno/functions/openai
runtime has escaped from the event loop unexpectedly: event loop error: ReferenceError: _computedKey is not defined
    at https://deno.land/x/openai@v4.24.0/lib/ChatCompletionStream.ts:4:14
user worker failed to respond: event loop error: ReferenceError: _computedKey is not defined
    at https://deno.land/x/openai@v4.24.0/lib/ChatCompletionStream.ts:4:14
InvalidWorkerResponse: event loop error: ReferenceError: _computedKey is not defined
    at https://deno.land/x/openai@v4.24.0/lib/ChatCompletionStream.ts:4:14
    at async Promise.allSettled (index 1)
    at async UserWorker.fetch (ext:sb_user_workers/user_workers.js:77:21)
    at async Object.handler (file:///home/deno/main/index.ts:171:14)
    at async respond (ext:sb_core_main_js/js/http.js:162:14) {
  name: "InvalidWorkerResponse"
}
```

## To Reproduce

1. Follow steps in `https://supabase.com/docs/guides/ai/examples/openai`
2. Serve the edge function locally
3. Make the `POST` request as described in the guide

## Expected behavior

Edge function should return a valid response

## System information

- OS: macOS 14.4.1
- Version of supabase-js: _? - where do I find this?_
- Version of Node.js: _? - where do I find this?_

## Additional context

It seems that this issue has been fixed in Deno 1.41.0 (https://github.com/nberlette/deno_fmt/discussions/4#discussioncomment-9637013), so I assume this requires an update to the version of Deno Supabase uses.

I also raised this issue on the Discord: https://discord.com/channels/839993398554656828/1248713520833368114

_Apologies if I'm missing detail in this report, I'm a Swift dev by trade, so a lot of this is new to me!_

Cheers
Ash

**Comment by tonypee** [comment] 2024-06-10 05:52
I am experiencing this also

**Comment by tonypee** [comment] 2024-06-10 06:00
I have tried using the `brew install supabase-beta` but it also fails in the same way. It seems that supabase is using some old versions detailed here: https://github.com/nberlette/deno_fmt/issues/2. This really needs some attention.

**Comment by adamlamaa** [comment] 2024-06-10 14:10
I am having the same issue trying to test out open ai on an edge function.

supabase --version
1.172.2

Using supabase-edge-runtime-1.53.3 (compatible with Deno v1.40.3)

**Comment by adamlamaa** [comment] 2024-06-10 14:13
There is a workaround provided in https://github.com/supabase/supabase/issues/26875

Change the import to:
```
import OpenAI from "https://esm.sh/openai@4.47.2";
```

**Comment by nyannyacha** [comment] 2024-06-10 22:24
Hello everyone! 😋

This issue appears to be related to SWC's implementation of the tc39 decorator proposal.

I have recently enabled the tc39 decorator proposal in the cli, and it is only affected if this is enabled.

In the case of `esm.sh`, it appears that it was able to escape this impact because it is a service that pre-bundles packages.

This is an upstream issue that can only be resolved by the edge runtime versioning up the Deno codebase, and [a PR](https://github.com/supabase/edge-runtime/pull/352) has been submitted for this.

Have a great day!

**Comment by ashleymills** [comment] 2024-06-11 10:14
I have no idea what most of that means, but thank you anyway!!

**Comment by laktek** [comment] 2024-06-25 05:37
Duplicate of #26875 (original issue is fixed, updating Supabase CLI should give you the latest release)

**Closed by laktek** 2024-06-25 05:37 UTC
Labels: bug, pr-opened
