### ISSUE TITLE
cannot add rls in the dashboard

### ISSUE THREAD

**Issue by sjohns21** [supabase/supabase#22218] opened 2024-03-25 19:52 UTC
delimiter errors
even when copying straight from the examples

**Comment by GaryAustin1** [comment] 2024-03-25 21:55
Definitely seems messed up.
![image](https://github.com/supabase/supabase/assets/54564956/ac5babd3-f9e0-4640-ac04-77c29e420ef4)

**Comment by joshenlim** [comment] 2024-03-26 05:17
Hey there @sjohns21 - do you have some screenshots or reproducible steps to surface this issue?
Based on the screenshots from @GaryAustin1 - it seems like this is due to some fields being missing (e.g name and the USING statement specifically)

We've got some fixes [here](https://github.com/supabase/supabase/pull/22227) to add validations to the UI which should alleviate running into this error

But otherwise, is there a specific template that you're also running into issues? We've testing all the templates to the working except those that require a specific column in the table 🙏

**Comment by premiare** [comment] 2024-03-26 12:52
When trying to add a simple example:
![image](https://github.com/supabase/supabase/assets/64188227/1f98bc54-0a24-4b99-8ec0-1ab24206e5c7)

Which I then alter to suit my table:
```
create policy "Enable insert for authenticated users only"
on "public"."organizations"
for insert to authenticated 
with check (true);
```

I get a 404 error within the Network tab: 
`https://api.supabase.com/platform/integrations/github/authorization`
`{
    "message": "GitHub authorization not found"
}`
But no error / loading indicator inside the RLS editor

**Comment by gustavofjordao021** [comment] 2024-03-26 13:06
On a separate note, I can create RLS via SQL editor or UI but they end up showing different information on the UI altogether. Not sure if it is related, so see the attached video showing it.

https://github.com/supabase/supabase/assets/47228983/2cf18ecc-7db3-42fa-b92a-42850eca5208

**Comment by joshenlim** [comment] 2024-03-26 13:31
@premiare the 404 that you're seeing is a red herring and unrelated to the RLS editor - would you mind sharing a screengrab of what you're trying to do and the outcome as well? 🙏

**Comment by joshenlim** [comment] 2024-03-26 13:33
@gustavofjordao021 the issue you're running into should've been fixed by a [PR](https://github.com/supabase/supabase/pull/22228) earlier today - would you mind refreshing and trying once more?

**Comment by gustavofjordao021** [comment] 2024-03-26 13:37
hey @joshenlim, you're right -- i just logged into my Supabase instance and it is working fine. 

thank you!

**Comment by Gamekohl** [comment] 2024-03-26 13:41
Same behavior as described by @premiare. Using the template doesn't work, you receive this error:
`Please provide a SQL expression for the WITH CHECK statement`

![Screenshot 2024-03-26 143813](https://github.com/supabase/supabase/assets/108492240/6e801774-8d1c-4c8a-bd14-39c7f4839675)

 If you write your own policy statement in the SQL Editor the policy is being created successfully:
`create policy "Insert access for authenticated users" on public.designs for insert to authenticated with check(true);`

**Comment by adtm** [comment] 2024-03-26 22:35
I have the same Github not authenticated issue even though I logged with email / password

**Comment by joshenlim** [comment] 2024-03-27 04:23
hey everyone! the github network request error is not related to auth nor RLS - so please do ignore that as its a red-herring here 🙏

**Comment by joshenlim** [comment] 2024-03-27 04:24
hey @Gamekohl! the issue you reported should now be fixed via this [PR](https://github.com/supabase/supabase/pull/22260) :)

**Comment by joshenlim** [comment] 2024-03-27 04:25
> For me the new editor does not show up in Chrome

@micheltucker Could you elaborate on this sorry? Please do provide screenshots when reporting issues as it will help us identify issues better and faster 🙏

**Comment by joshenlim** [comment] 2024-03-27 04:29
@premiare just checked out your loom! you're currently using the feature preview version of the RLS actually
for now you could toggle it off via the user icon in the bottom left of the navigation bar, and click into "Feature Preview"

cc @micheltucker i'm guessing you might be facing the same thing as well

there'll be an option to toggle the RLS feature preview as such:
![image](https://github.com/supabase/supabase/assets/19742402/0348e6b5-79e3-40f2-b6f3-906a18ae46ef)

Apologies about that as feature previews are generally a little clunky - we'll look into fixing that up.

And while I've got you here actually - wanted to check on your opinion, do you prefer a open code editor for writing RLS policies like the feature preview, or a more guided UX like the new UI that we've just released?

**Comment by premiare** [comment] 2024-03-27 04:35
Thanks @joshenlim, I've had this turned on for a few months and it previously worked, just not with this new UI which I only noticed last night.

I like the new guided UX - just took a few minutes to familiarize myself with it. It would be cool if the examples given were tailored to the table you were on. For example, I went in to my `organizations` table to create a new RLS policy for that table, it would be cool if the examples were already tailored to that table, so the example code would pre-fill `tables.organizations`.

**Comment by joshenlim** [comment] 2024-03-27 04:41
> so the example code would pre-fill tables.organizations

ahhh you're referring to the example code when you hover over the templates right? definitely doable 🙂 i'll see if I can sneak something in today 😉

**Comment by joshenlim** [comment] 2024-03-27 04:51
@premiare will go out in a bit 🙂
![image](https://github.com/supabase/supabase/assets/19742402/f50ed894-bd4a-4849-a94e-0b3a7870f772)

**Comment by joshenlim** [comment] 2024-03-27 07:35
@premiare i've also just fixed the feature preview RLS editor in this [PR](https://github.com/supabase/supabase/pull/22263) too - i'll close this ticket once that PR goes through since it doesnt seem like there's any other issues

for anyone else coming across this thread and running into issues with the RLS editor - do start a new ticket with a clear description of the issue by following our bug report template 🙏

**Comment by premiare** [comment] 2024-03-27 07:40
![image](https://github.com/supabase/supabase/assets/64188227/39b8b0af-4d0f-4db2-8cbe-34592c8edd8d)

Does that PR fix this issue? This template is the default template for INSERT and I've altered the table name.
Also the "Fix with Assistant" button doesn't work here.

**Closed** 2024-03-27 07:43 UTC
Labels: bug, dashboard

**Comment by joshenlim** [comment] 2024-03-27 07:45
one second - the fix hasn't gone through to prod yet, its still deploying

**Comment by joshenlim** [comment] 2024-03-27 07:51
@premiare fix should be out now on production 🙂 could you refresh your browser and give it a go again?

**Comment by premiare** [comment] 2024-03-27 07:53
Magnifique @joshenlim thank you
![image](https://github.com/supabase/supabase/assets/64188227/4d074d14-2e05-41fa-b3bc-08021b02ccff)
