### ISSUE TITLE
getPublicUrl does not show updated image when a public storage file is update

### ISSUE THREAD

**Issue by engineerliz** [supabase/supabase#12662] opened 2023-02-24 22:58 UTC
# Bug report

## Describe the bug

`getPublicUrl` does not show updated image when a public storage file is updated. This can be seen from both the console UI and using the storage API to get the public url

## To Reproduce
- upload a file to a public storage bucket (image 1)
- update the same file in storage (image 2)
- click on 'Get URL' button on the console UI
- the url shows image 1

this happens both when I use the console UI to use `getPublicUrl` programmatically

## Expected behavior
expected: the public url shows updated image aka image 2

## System information

- Version of supabase-js: ^2.7.1
- Version of Node.js: 14.18.3

**Comment by GaryAustin1** [comment] 2023-02-24 23:10
This is not a bug, but the way caching works, particularly at the browser level.  
https://supabase.com/docs/guides/storage/cdn#cache-duration
Discusses what the CDN does and what the browser does.
Mentioned there is how to "bust" the browser cache.

I'm going to close this for now as not a bug.

**Closed by GaryAustin1** 2023-02-24 23:10 UTC
Labels: bug
