### ISSUE TITLE
Explore a different Default PK type

### ISSUE THREAD

**Issue by ftonato** [supabase/supabase#597] opened 2021-01-24 02:19 UTC
# Bug report

Hello @kiwicopple, how are you?

I find one potential problem, we're able to generate duplicate primary keys.

## To Reproduce

1. Create a table, in my case, `example`, with some fields ( `id` being the primary key and of type `int4` and `name` as being `varchar`).
2. Add a new row
**Note:** *As we can see in the image below, **we are not able** to say what the value of the primary key will be (it will be automatically generated by the database, as described).*

![image](https://user-images.githubusercontent.com/5417662/105619302-02c28e00-5de9-11eb-99da-a73997eb1460.png)

3. After inserting this line, we can view, edit and delete the information through the table.
4. We can even edit our primary key, see the _gif_ below.

![supabase-bug](https://user-images.githubusercontent.com/5417662/105619351-aa3fc080-5de9-11eb-9a4e-4131e4b875f6.gif)

## Expected behavior

**It should not be possible to edit a record's primary key, since it is automatically generated**

## Additional context

This bug allows serious problems to happen.

Imagine that we have 5000 records, and the administrator inadvertently changes the primary key value of the last record entered to 5001.

Every time he tries to insert a record he will receive an error message (`Error: Error: duplicate key value violates unique constraint "example_pkey"`), but he will have no idea how to fix the problem.

Thank you ৸

**Comment by kiwicopple** [comment] 2021-01-24 04:42
Hi @ftonato

> It should not be possible to edit a record's primary key, since it is automatically generated

it's worth noting that we are only providing a layer on top of Postgres's default behaviour, which DOES allow you to update a Primary Key if you wish.

This will NOT result in a Duplicate PK ever ( handled by Postgres):

![Kapture 2021-01-24 at 12 37 17](https://user-images.githubusercontent.com/10214025/105621290-f36f2f00-5e40-11eb-83b2-964dae66eab6.gif)


But as you say, it will cause problems if your Primary key is a sequence:

![Kapture 2021-01-24 at 12 39 04](https://user-images.githubusercontent.com/10214025/105621312-2ca79f00-5e41-11eb-990b-106f06666a7b.gif)


The user is expected to update the underlying sequence at the same time in these cases, but we could possibly provide some helpers in our dashboard, that will detect if the user is updating a PK field with a sequence and suggest that they update the sequence ## at the same time?

I was also thinking of moving our default ID generation to UUIDs - they take up slightly more space, but will mitigate headaches with sharding later on (and cases like this)

**Comment by ftonato** [comment] 2021-01-24 10:06
Hi

I think that for several scenarios it makes sense that the primary key can be edited, but it is not the case for an auto incremented field.

If there is no possibility for me to put the number I want during the insert, I must not let me change it to the number I want (Maintaining consistency, I guess)

I expressed myself badly when I said to duplicate a primary key, it is a scenario where I anticipate a control of the database itself only.

Perhaps, a correction could be:
  If the field is a primary key for a value that is automatically generated, I can only change it to values ​​less than my last entered.

So would avoid a problem like the current one, what do you think?

**Comment by soedirgo** [comment] 2021-01-24 10:44
I think a solution to this is to have the table editor make the column `GENERATED ALWAYS AS IDENTITY` instead of `GENERATED BY DEFAULT AS IDENTITY`. This way, editing a value on that column will throw an error (or we can gray it out, whichever works).

There was an issue in pg-api to support exactly this: https://github.com/supabase/pg-api/issues/69. cc @joshenlim

**Comment by kiwicopple** [comment] 2021-01-24 12:42
Yeah in this menu we could possibly provide clearer options:

![image](https://user-images.githubusercontent.com/10214025/105630347-9cd71480-5e83-11eb-8a08-7aed4890faf2.png)


Something like :

- `uuid` (generated by default) <- default option IMO for reasons stated above, no sequence management
- `int4` (generated by default)
- `int4` (generated always)
- ...
- all the usual options

We could also split it so that it is "field type" and "default expression", though it's probably not necessary right now.

cc J&J - this one could do with some UX love - probably as part of a larger table/column re-do. For now the proposal above seems like a small improvement

**Comment by kiwicopple** [comment] 2021-06-20 10:58
I'm going to close this one since we have improved the DX of the ID generation:

![image](https://user-images.githubusercontent.com/10214025/122671495-7b434480-d1f9-11eb-871b-e63009a50763.png)


If there are any other issue spotted with the current process just comment here and I can reopen (or open a new issue)

**Closed by kiwicopple** 2021-06-20 10:58 UTC
Labels: bug

**Comment by openworkwiki** [comment] 2021-07-14 21:54
@kiwicopple  hi there, found a problem with the current setup. 

### Steps to reproduce

1. Change the “Default” setting on an Id column that was created with default autoincrement to something else, e.g NULL or an empty default. 
2. Then try changing back again  
3. The client throws an error saying “Error: cannot read property ‘accept-version’ of undefined (see screenshot)

![671248C0-CDC8-4FAB-B4C7-3D8F5E66EF0F](https://user-images.githubusercontent.com/86159926/125698031-9f5bce77-cc97-428f-9bab-224402674e38.png)


### Expected behavior

The columns default should change back to autoincrementing behavior

Let me know if I should provide any more details on this! Thanks

**Comment by kiwicopple** [comment] 2021-07-15 05:39
I think this one is unrelated (but definitely a bug) @openworkwiki - would you mind creating a new issue?

**Comment by openworkwiki** [comment] 2021-07-18 16:43
> 
> 
> I think this one is unrelated (but definitely a bug) @openworkwiki - would you mind creating a new issue?

@kiwicopple  Done! Can we assign a "Bug" label to it? Will try to add default auto-increment using the SQL interface for now

**Comment by ptcampbell** [comment] 2021-08-18 22:07
> Error: Cannot read property 'accept-version' of undefined

I searched for this error message and wound up here. 

I'm trying to change the `id` column's type from `int8` to `uuid`. Not sure if this is the same thing.

**Comment by amirhosein5858** [comment] 2022-03-14 23:27
> I'm going to close this one since we have improved the DX of the ID generation:
> 
> ![image](https://user-images.githubusercontent.com/10214025/122671495-7b434480-d1f9-11eb-871b-e63009a50763.png)
> 
> If there are any other issue spotted with the current process just comment here and I can reopen (or open a new issue)

where can i see this? is it in paid plan?
<img width="677" alt="Screen Shot 2022-03-15 at 2 57 24 AM" src="https://user-images.githubusercontent.com/44944288/158277113-2da43f3f-96d9-4159-a337-8dfc4890d141.png">
