### ISSUE TITLE
Error: cannot read property „accept-version“ of undefined when setting a default for int column

### ISSUE THREAD

**Issue by joingardens** [supabase/supabase#2404] opened 2021-07-16 15:06 UTC
@kiwicopple  hi there, found a problem with the current setup. 

### Steps to reproduce

1. Change the “Default” setting on an Id column that was created with default autoincrement to something else, e.g NULL or an empty default. 
2. Then try changing back again  
3. The client throws an error saying “Error: cannot read property ‘accept-version’ of undefined (see screenshot)

![671248C0-CDC8-4FAB-B4C7-3D8F5E66EF0F](https://user-images.githubusercontent.com/86159926/125698031-9f5bce77-cc97-428f-9bab-224402674e38.png)

### Expected behavior

The columns default should change back to autoincrementing behavior

Let me know if I should provide any more details on this! Thanks

_Originally posted by @openworkwiki in https://github.com/supabase/supabase/issues/597#issuecomment-880235235_

**Comment by meghaboggaram** [comment] 2021-09-05 13:20
I'm facing the same issue.. any solution?

**Comment by subwaymatch** [comment] 2021-09-19 19:52
I see some activities to fix this error from the Supabase team. Mucho thanks as always!

I'll paste screenshots of the error message and the console messages in case it helps. 

```

![image](https://user-images.githubusercontent.com/1064036/133941057-2b35b184-121f-4cfc-802e-c90447c0bec3.png)

![image](https://user-images.githubusercontent.com/1064036/133941080-d81508d5-9802-4edf-bf5b-ee00958a7f98.png)

**Comment by darora** [comment] 2021-09-19 22:02
This is being fixed in https://github.com/supabase/postgres-meta/pull/149

This generally occurs when the underlying operation that was attempted is disallowed by Postgres. The fix linked should propagate the correct error message back; for now, you can try to execute the corresponding change in a psql session to understand why it's being disallowed. Most often, the cause is that Postgres isn't able to automatically coerce existing data for the attempted type change (e.g. text -> text[]), and can be addressed by manually instructing Postgres how to perform the coercion

**Closed** 2021-12-28 11:16 UTC
Labels: bug
