### ISSUE TITLE
Admin UI : React client page for the SQL Editor crashes on SQL error

### ISSUE THREAD

**Issue by victordelajarte** [supabase/supabase#19934] opened 2023-12-20 17:18 UTC
**Describe the bug**
In the Admin UI, when I type a query in the SQL Editor, if I make a mistake, the page crashes instead of showing an error.
Furthermore, the autocomplete does not seem too always work

The page only shows this text (from react): 
`Application error: a client-side exception has occurred (see the browser console for more information).`

The console shows some errors, with [a link to this page](https://legacy.reactjs.org/docs/error-decoder.html/?invariant=31&args%5B%5D=object%20with%20keys%20%7Bcode%2C%20message%2C%20requestId%7D)

**To Reproduce**
1. Go to the SQL Editor (locally)
2. Type `select toto` for instance (any invalid SQL query will work)
3. Submit the query

**Expected behavior**
It should not crash, and explain the error if possible.

**Screenshots**
<img width="1439" alt="Capture d’écran 2023-12-20 à 18 11 40" src="https://github.com/supabase/cli/assets/29466815/15d82e50-f629-430c-8c1f-568139b58735">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser : chrome, brave
 - Version of CLI : tested on 1.117.1, 1.119.1, 1.126.0 and 1.126.2 with the same issue
 - Version of Node.js: 18.19.0

**Additional context**
I think it was working a few weeks ago, we updated this dependency a few times since then so I'm not sure what version broke it.

**Comment by sweatybridge** [comment] 2023-12-21 05:44
I believe this is a duplicate of https://github.com/supabase/supabase/issues/19399

**Closed by sweatybridge** 2023-12-21 05:44 UTC
