### ISSUE TITLE
Unable to update table PK via dashboard after renaming table

### ISSUE THREAD

**Issue by jnorris441** [supabase/supabase#19341] opened 2023-11-30 20:26 UTC
# Bug report

## Describe the bug

Opening this issue because I ran into it again today #5549

After renaming a table, the _pkey constraint uses the old table name. This causes a problem if you try to change the primary key field.

For example, a table originally named "reporttype_report" was renamed to "report_reporttype".

When trying to change the primary key, It gives an error "constraint "report_reporttype_pkey" of relation "report_reporttype" does not exist" because the constraint is still named "reporttype_report_pkey"

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create a table
2. rename it in the admin console
3. add a new column
4. try to add the new column to the primary key

## Expected behavior
Should succeed. Instead you have to go find the constraint name and manually ALTER the table.

## System information
OS: macOS
Browser: Chrome

**Comment by Prakhar-FF13** [comment] 2023-12-17 11:42
Hi @GaryAustin1 @jnorris441 
I just made a PR for this. I linked it to the issue. Is there something more to be done from my end?

Thanks

**Comment by GaryAustin1** [comment] 2023-12-17 15:05
@Prakhar-FF13 Nothing else for you to do unless a Supabase dev asks for something in that PR.

**Comment by joshenlim** [comment] 2024-02-15 08:28
Hey guys! Renaming a table and not automatically renaming the pkey constraint is not a Postgres behaviour by default and hence this is not a bug on the dashboard. Based on this as well, I don't think this should be a default dashboard behaviour as  it may go against other developers' natural understanding of the database.

As such I'm going to close this ticket, but if we feel that this is a feature that many users would like to have as a convenience factor, please do open up a [GH discussion](https://github.com/orgs/supabase/discussions) where we can discuss the pros and cons of doing this 🙏

**Comment by joshenlim** [comment] 2024-02-15 08:57
Hey guys sorry - i just read the description a bit closer and realised that there's a bug with updating the PK of a table after renaming it, which is related but separate to the ticket title - apologies that I missed this!

**Closed** 2024-02-26 06:21 UTC
Labels: bug, dashboard, pr-opened
