### ISSUE TITLE
await supabase.storage.from('bucketname').download(filePath); sometimes shows outdated files

### ISSUE THREAD

**Issue by felix7700** [supabase/supabase#12173] opened 2023-02-04 21:34 UTC
# Bug report
on flutter: after updating a file in my bucket, await supabase.storage.from('bucketname').download(filePath) sometimes shows outdated files

## Describe the bug
Hello, I would like to use my flutter app to download images from my bucket and use the variant await supabase.storage.from('bucketname').download(filePath) instead of the download link. But now I have the following problem: if I update a jpg image in my bucked with
 await supabase.storage.from('bucketname').updateBinary(
          filePath,
          bytes,
          fileOptions: FileOptions(contentType: imageFileXFile.mimeType),
        );
 and then call it up via the download link, I see the new jpg image. So the update process worked. but when I download the just updated image via my flutter app via final Uint8List file = await supabase.storage.from('bucketname').download(filePath); Then I don't get an error, it seems to be working, but I get the old picture that was in the bucked before the update, as if there hadn't been an update, 
but the image file was updated correctly, i can download the new image via download-link if i try.

## To Reproduce

on flutter:

1. upload a new jpg-image into a bucket with:
await supabase.storage.from('bucketname').uploadBinary(
          filePath,
          bytes,
          fileOptions: FileOptions(contentType: imageFileXFile.mimeType),
        );

2.  load the updated image from bucket with:
final Uint8List file =
        await supabase.storage.from('bucketname').download(filePath);
and see the image with the widget:
Image.memory(file),

3. update the jpg-image with the same filePath with:
  await supabase.storage.from('bucketname').updateBinary(
          filePath,
          bytes,
          fileOptions: FileOptions(contentType: imageFileXFile.mimeType),
        );

4. try to load the updated image from bucket with:
final Uint8List file =
        await supabase.storage.from('bucketname').download(filePath);
and see the image with the widget:
Image.memory(file),

## Expected behavior
now it often happens that you see the old picture from before the update

## System information

- OS: macOS
- running app on flutter web: using chrome
- The same Problem on Android
- Version of supabase_flutter: ^1.2.2
- Version of image_picker: ^0.8.6

**Comment by GaryAustin1** [comment] 2023-02-04 22:13
https://github.com/supabase/supabase/issues/5119
https://github.com/supabase/supabase/issues/5430
https://supabase.com/docs/guides/storage/cdn#cache-duration

**Comment by dshukertjr** [comment] 2023-03-01 06:13
Hi @felix7700 ,

As Gary have pointed out, this is caused by the application hitting the cached version of the assets. There are a few techniques that you can use to avoid this outlined [here](https://supabase.com/docs/guides/storage/cdn#cache-duration). Also with pro project and above, we have [smart CDN caching](https://supabase.com/docs/guides/storage/cdn#smart-cdn-caching), which improves the caching strategy dramatically. 

I will close this issue for now, but if you feel that things are not working as intended, feel free to reopen it!

**Closed by dshukertjr** 2023-03-01 06:13 UTC
Labels: bug, storage
