### ISSUE TITLE
a hash character instead of a question mark in the {{ .ConfirmationURL }}

### ISSUE THREAD

**Issue by tof38** [supabase/supabase#8744] opened 2022-08-31 15:31 UTC
# Bug report

## Describe the bug
a hash character instead of a question mark in the {{ .ConfirmationURL }}

## To Reproduce

1. set Site Url
2. send a reset password recovery
3. look at the url in the email
4. A controller can't take the parameter in the request

## Screenshots

![image](https://user-images.githubusercontent.com/5406174/187716882-d7b5b3b1-5a83-43ad-93ee-78406beed5f4.png)

## System information

- OS: Ubuntu 22
- Browser chrome
- Version sAAs Supabase
- Symfony 6

thanks !

**Comment by GaryAustin1** [comment] 2022-08-31 19:57
That is the way it works.  If you search hash here and/or supabase gotrue you will see lots of the same question and answers.
https://github.com/supabase/supabase/issues/1698

**Comment by J0** [comment] 2022-09-01 09:42
Hey @tof38 ,

@GaryAustin1 is right -- this is intended behavior for security purposes --  we didn't want query params to be logged when the website URL was logged.

Closing for now but feel free to re-open if there are still issues

**Closed by J0** 2022-09-01 09:42 UTC
Labels: bug, auth
