### ISSUE TITLE
Using Supabase Admin Client from Local Edge Functions Gives OS Error 99

### ISSUE THREAD

**Issue by jquesada2016** [supabase/supabase#14134] opened 2023-05-04 16:45 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm  I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I am getting a strange error when trying to use the supabase admin client from within functions, mainly:

```
error sending request for url (http://localhost:54321/auth/v1/admin/users?page=&per_page=): error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run through WSL 2 (not sure if this matters)
2. Run `npm i -D supabase`
3. Run `npx supabase functions new list-users`
4. Run `npx supabase start`
5. Paste the following:
    ```javascript
    import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
    import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

    const supabase = createClient(
      "http://localhost:54321",
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU",
      {
        auth: {
          autoRefreshToken: false,
          persistSession: false,
        },
      },
    );

    serve(async (_) => {
      const res = await supabase.auth.admin
        .listUsers();

      return new Response(JSON.stringify(res), {
        status: 200,
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Access-Control-Allow-Headers":
            "authorization, x-client-info, apikey, content-type",
          "Content-Type": "application/json",
        },
      });
    });
    ```
6. Invoke the function, and note the above error returned in the response.

## Expected behavior

I expected the function invocation to run without error.

## Screenshots

N/A

## System information

- OS: Windows 11 through WSL2
- Browser: N/A
- Version of supabase-js: ^2.21.0
- Version of Node.js: 18.12.1

## Additional context

This error seems to have started happening recently seemingly out of nowhere. The issue persisted after restarting the computer (perhaps a port that was never freed?) as well as a fresh install of the local .development suite

**Comment by gregnr** [comment] 2023-05-04 17:10
Hey @jquesada2016! Can you confirm that you are running your local edge function server? You will need to run:
```shell
supabase functions serve
```

in addition to
```shell
supabase start
```

**Comment by jquesada2016** [comment] 2023-05-04 17:45
@gregnr I can confirm I am using `npx supabase functions serve`

**Comment by gregnr** [comment] 2023-05-04 18:00
Thanks @Koleok and @jquesada2016. I was able to reproduce this. Try using these environment variables instead:
```ts
const supabaseUrl = Deno.env.get('SUPABASE_URL')
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')

const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
})
```

When you serve an edge function locally, under the hood it is running in a Docker container which has a different network topology than your host (ie. no access to `http://localhost:54321`). Since your PG image is also a container, it does have access to it - just via a different path.

Thankfully edge functions abstract this logic from you and all you need to do is reference the above environment variables (`SUPABASE_URL` & `SUPABASE_SERVICE_ROLE_KEY`) which are injected for you (both locally and in cloud).

Let me know if this solves this for you.

**Comment by Koleok** [comment] 2023-05-04 18:02
Ah ok so no need to setup those env variables explicitly with an `--env-file`?

**Comment by gregnr** [comment] 2023-05-04 18:02
@Koleok correct

**Comment by Koleok** [comment] 2023-05-04 18:06
Ah I see, I was actually overriding them with my env file in an attempt to resolve this, thanks so much!

There was some clue to this, as when I try to set `SUPABASE_URL` or `SUPABASE_SERVICE_ROLE_KEY` in the env file, the runtime would bail saying that I could not use env vars prefixed with `SUPABASE_`. Am I correct also then in assuming that the reason for this is that they are reserved/provided by underlying container setup?

**Comment by gregnr** [comment] 2023-05-04 20:05
Yes that's right. On the underlying container when running locally/self-hosting and on the cloud hosted environment when deployed.

**Comment by Koleok** [comment] 2023-05-04 20:25
Awesome 👍 , this is resolved for me fwiw.

**Comment by magick93** [comment] 2023-05-06 06:55
I'm also facing the same error. 

I'm creating my supabase client like this, but still getting the error:

```
let options = {
    db: { schema: 'adls' },
    global: { headers: { Authorization: req.headers.get('Authorization')! } },
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  };

  const supabaseAdminClient = createClient(
    // Supabase API URL - env var exported by default when deployed.
    Deno.env.get('SB_URL') ?? '',
    // Supabase API SERVICE ROLE KEY - env var exported by default when deployed.
    Deno.env.get('SB_SERVICE_ROLE_KEY') ?? '',
    options
  )
  ```

The error is:
```
FetchError: error sending request for url (http://localhost:54321/rest/v1/rpc/insert_items_dynamic): 
error trying to connect: tcp connect error: 
Cannot assign requested address (os error 99)
```

**Comment by gregnr** [comment] 2023-05-08 17:30
@jquesada2016 can you confirm if this solved your issue?

**Comment by jquesada2016** [comment] 2023-05-08 19:15
@gregnr it's resolved for me. Thank you very much!

**Comment by gregnr** [comment] 2023-05-08 19:46
Great! Closing this.

**Closed by gregnr** 2023-05-08 19:46 UTC
Labels: bug, edge functions
