### ISSUE TITLE
Potential harmless request

### ISSUE THREAD

**Issue by JSmithOner** [supabase/supabase#11574] opened 2023-01-11 00:34 UTC
# Bug report

Able to retrieve all the public definitions,  from the database.

## To Reproduce

This has been done using a bad query

## Expected behavior

Even if public this data is sensitive as a possible attacker could retrieve all database definitions in one query which could be easily used to test the project for potential breaches

## System information

- Version of supabase-js:^2.0.0-rc.13

## Additional context

Should I MP to give my project id and request?

**Comment by GaryAustin1** [comment] 2023-02-07 23:13
You are probably referring to the OpenAPI support of the REST API.  
https://postgrest.org/en/stable/api.html#openapi-support

You used to be able to disable it with:
`ALTER ROLE authenticator SET pgrst.openapi_mode TO 'disabled';`
But this required superuser privilege to do, which is no longer available to the dashboard user.
For now you would have to contact support to turn it off.

I'm going to close this as it is by design.

**Closed by GaryAustin1** 2023-02-07 23:13 UTC
Labels: bug

**Comment by steve-chavez** [comment] 2023-02-08 17:16
> You used to be able to disable it with:
> ALTER ROLE authenticator SET pgrst.openapi_mode TO 'disabled';

Just to note this will be allowed again once https://github.com/supabase/supautils/pull/40 is finished
