### ISSUE TITLE
Error "Folder name contains invalid special characters" not displayed in the UI

### ISSUE THREAD

**Issue by onmax** [supabase/supabase#20822] opened 2024-01-29 10:57 UTC
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If you create a folder with a string like `2024-01-29T10:48:15.595Z`, the Dashboard will thrown an error in the console, but nothing in the UI happens and it looks like everything went ok.

The message in the console says:

```js
{
    "message": "Folder name contains invalid special characters"
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a bucket in your application
2. Open the console
3. Create a folder with a name with special character. e.g. `2024-01-29T10:48:15.595Z`
4. In the console the error appears but not in the UI

## Expected behavior

A toast with the error message

## System information

- OS: Windows
- Browser (if applies) chrome
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

https://github.com/supabase/supabase-js/issues/960

**Comment by Hallidayo** [comment] 2024-02-06 20:55
Hi @onmax, I've just tried the above and I seem to get a toast error when I try to create the folder, Are you experiencing the same now?

**Comment by onmax** [comment] 2024-02-07 03:14
Now it allows me to change the name. So there is no issue whatsoever. I will close it. Thanks 👍

**Comment by onmax** [comment] 2024-02-07 03:18
Sorry. I tried to create a folder inside a folder with a name with ':', but it failed:

<img width="766" alt="image" src="https://github.com/supabase/supabase/assets/22072217/a4cebc5b-7002-436d-9379-a4294bc0aad7">

**Comment by joshenlim** [comment] 2024-02-13 08:42
hey there @onmax - could you attach a screen recording for this bug? I tried to reproduce on production but can't seem to do so - the error message shows up properly
![image](https://github.com/supabase/supabase/assets/19742402/c6760fd5-0378-473e-b14e-62c9c572aff9)

**Comment by joshenlim** [comment] 2024-02-15 09:05
I'm gonna go ahead to close this ticket for now as I'm unable to reproduce this issue but please do feel free to let us know otherwise! 🙏

**Closed by joshenlim** 2024-02-15 09:05 UTC
Labels: bug, dashboard

**Comment by onmax** [comment] 2024-02-15 13:58
Hey, sorry, I missed your message:

Here you can see a screen recording on Brave


https://github.com/supabase/supabase/assets/22072217/77e1d0fc-56fc-4356-94f4-f6f4eeb79de2



In the video you can not see it, but I clicked 'Enter' a few times

**Comment by joshenlim** [comment] 2024-02-16 03:08
Ahh hmm okay this is a odd one, it seems like our usage of react-hot-toast isn't working for Brave browser so you probably aren't able to see any toast notifications at all with the browser - i'll see if there's any quick fix for this
