### ISSUE TITLE
Text overlapping in Supabase AI pop up

### ISSUE THREAD

**Issue by thara003** [supabase/supabase#14018] opened 2023-04-28 13:38 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In the input field of Supabase AI pop up the `submit message` text is overlapping with the input text.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to app.supabase.com
2. Open a project
3. Click on search button
4. Click on `Ask Supabase AI`
5. Type a long sentence in the input field
6. See the overlapping

## Expected behavior

There should not be any overlapping of texts. May be we could expand the input field height for long texts.

## Screenshots

<img width="817" alt="Screenshot 2023-04-28 at 7 01 51 PM" src="https://user-images.githubusercontent.com/79561774/235161305-3efab133-1f77-4315-8a6e-bcc1d40832c6.png">

## System information

- OS:  macOS
- Browser: Brave

**Comment by karthiknadar1204** [comment] 2023-04-28 15:11
I would like to work on this issue,please assign it to me

**Comment by gregnr** [comment] 2023-04-28 15:56
Thanks for reporting this @thara003!

@karthiknadar1204, that would be great! We had a similar issue with the AI SQL generator:
https://github.com/supabase/supabase/pull/13986

You can most likely do something similar to this.

**Comment by karthiknadar1204** [comment] 2023-05-07 10:20
@gregnr i have started working on the issue,will push changes within a few days,it is taking longer than usual for the project to get cloned on my local environment.

**Comment by karthiknadar1204** [comment] 2023-05-07 10:51
@gregnr i have cloned the project on the compiler but unable to set it up on my local server,i ran the  npm install and npm run dev commands
![Uploading Screenshot 202
<img width="1436" alt="Screenshot 2023-05-07 at 4 20 05 PM" src="https://user-images.githubusercontent.com/95973644/236673089-c1d33153-7223-49d6-b2af-c3d9c0e76899.png">
3-05-07 at 4.20.20 PM.png…]()


How do i proceed to make it go live on my local machine?

**Comment by karthiknadar1204** [comment] 2023-05-07 10:52
<img width="1434" alt="Screenshot 2023-05-07 at 4 20 20 PM" src="https://user-images.githubusercontent.com/95973644/236673147-629034be-d82b-4009-99c7-e086f66b3a26.png">
<img width="1436" alt="Screenshot 2023-05-07 at 4 20 05 PM" src="https://user-images.githubusercontent.com/95973644/236673152-3e45d855-f68e-42f0-9d1b-c32e0668aad3.png">

**Comment by gregnr** [comment] 2023-05-08 17:45
Hey @karthiknadar1204, I don't see any errors in your screenshots. What happens when you navigate to http://localhost:3001 (docs site)?

**Comment by karthiknadar1204** [comment] 2023-05-09 14:51
<img width="1154" alt="Screenshot 2023-05-09 at 8 18 47 PM" src="https://github.com/supabase/supabase/assets/95973644/3b6e6769-5379-45b5-9af1-d91a57eb59a3">

When i am trying to run npm run dev again,it is giving the port issue,i tried terminating it but the issue persists @gregnr

**Comment by karthiknadar1204** [comment] 2023-05-09 15:24
Have successfully setup the project @Isaiah-Hamilton ,  @gregnr ,Have confirmed the issue,will navigate the codebase and fix the codebase and fix the issue.
Thank you

**Comment by karthiknadar1204** [comment] 2023-05-09 17:22
The submit message seems to be wrapped inside of the input tag, tried wrapping the text but it is still over-lapping, will try to place the submit message button outside the input tag, apply some css to get in beside the container, that way the text doesn't overlap.

Will try this approach

**Comment by gregnr** [comment] 2023-05-09 17:29
@karthiknadar1204 just a reminder that [this PR](https://github.com/supabase/supabase/pull/13986) did something very similar for the SQL AI command, so we should follow a similar approach here.

**Comment by karthiknadar1204** [comment] 2023-05-09 17:50
have submitted pr for review @gregnr 
#14242

**Closed** 2023-05-12 01:52 UTC
Labels: bug
