### ISSUE TITLE
[AuthExeption](message : anonymous sign-ins are disabled ,statusCode:422)

### ISSUE THREAD

**Issue by hamzabouakoura** [supabase/supabase#22380] opened 2024-04-01 22:57 UTC
# Bug report

## Describe the bug

Hi , I'm new to supabase and i was trying to use it for authentication with my flutter app
Therefore i used signup() method to create a new user , but it is not working and I'm getting the exeption above .
But i'm trying to create a normal user and not an anonymous user 

Any ideas ?
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
This is my method : 

Future<Either<Failure, AuthResponse>> signUpUser(
      {required String email, required String password}) async {
    final response = await Supabase.instance.client.auth.signUp(
      email: email,
      password: password,
    );
    return Right(response);
  }

## Expected behavior

A successful user sign-up and move to the email verification step

## System information

- OS: [Windows]

**Comment by dshukertjr** [comment] 2024-04-02 06:27
Closing as duplicate of https://github.com/supabase/supabase-flutter/issues/877

**Closed by dshukertjr** 2024-04-02 06:27 UTC
Labels: bug
