### ISSUE TITLE
getaddrinfo EAI_AGAIN error while using supabase-js client in nodejs

### ISSUE THREAD

**Issue by andykais** [supabase/supabase#359] opened 2020-12-10 19:43 UTC
# Bug report

## Describe the bug
I have a long running data collection server running which calls once every second or so to insert a new row into my database. Occasionally, supabase will respond with a node-fetch `EAI_AGAIN` error. This is the error output:
```
FetchError: request to https://<my_supabase_url>.supabase.co/rest/v1/data_collection_logs?id=eq.12 failed, reason: getaddrinfo EAI_AGAIN scpjtuqjxrphrqlsfwio.supabase.co
    at ClientRequest.<anonymous> (/home/andrew/Code/development/telebum3/data-collection-server/node_modules/.pnpm/node-fetch@2.6.1/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:376:20)
    at TLSSocket.socketErrorListener (node:_http_client:490:9)
    at TLSSocket.emit (node:events:376:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
```

To the best of my knowledge, this is because the DNS server failed to properly resolve the supabase address. I do not know if this could have something to do with my laptop's hostname resolver, or if it has to do with how supabase resolves the urls on the server side. 

## To Reproduce
1. instantiate the supabase js client 
2. start making calls to supabase
3. eventually one of those calls will hit this `EAI_AGAIN` error (sometimes it can be after the task has ran for hours)

## Expected behavior

supabase should not error out on DNS lookups

## Screenshots

N/A

## System information

- OS: Arch Linux
- Browser (if applies) N/A
- Version of supabase-js: 1.0.7
- Version of Node.js: 15.3.0

## Additional context
I am running this task off of a laptop over wifi for testing purposes, not on a dedicated server. It is possible this error would not be present on a dedicated server

I am unsure if supabase urls are supposed to be treated like secrets or not. Let me know if it is helpful to include my supabase project url (or if I shouldn't)

**Comment by andykais** [comment] 2020-12-11 13:27
possibly related, I received a new error while leaving the process running overnight:
```
FetchError: request to https://<my_supabase_url>.supabase.co/rest/v1/data_collection_logs?id=eq.18 failed, reason: connect EHOSTUNREACH 104.18.27.86:443
    at ClientRequest.<anonymous> (/home/andrew/Code/development/telebum3/data-collection-server/node_modules/.pnpm/node-fetch@2.6.1/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:376:20)
    at TLSSocket.socketErrorListener (node:_http_client:490:9)
    at TLSSocket.emit (node:events:376:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}
```
which appears to be either a problem with my local OS failing to resolve a host, or the host being down. The process had been running for several hours without errors prior to receiving this error. I am going to attempt running this on heroku today and see if the problem goes away

**Comment by kiwicopple** [comment] 2020-12-14 09:44
Hey @andykais - for the `EAI_AGAIN` error, i believe it might be a local error (https://stackoverflow.com/questions/37811605/how-can-i-resolve-if-eai-again-error-happens-on-facebook-messenger-platform), where your own server isn't resolving your DNS server correctly.

The second error could be related, but very hard to know. We have customers doing something similar to your workload but this is the first time I've heard of the `EAI_AGAIN` error. 

If you poll a different service, are you seeing them drop at the same time that the Supabase connection drops?

**Comment by andykais** [comment] 2020-12-14 14:46
> If you poll a different service, are you seeing them drop at the same time that the Supabase connection drops?

No, I am also polling `https://api.themoviedb.org/3/` at the same time, but I have never seen network errors from their api. It could just be coincidence that all the errors are from supabase but I am unsure.

I also have deployed this app to heroku to attempt detecting if this is a local wifi problem, but there are new `ETIMEDOUT` errors (only with supabase). I need to do a bit more research before I consider these a problem on supabase's side though

**Comment by guicaro** [comment] 2021-02-21 22:57
I started gettint a similar error today, running my inserts via a lambda function in AWS. Still debugging as I am not able to get any errors from the Supabase JS client:

```2021-02-21T17:21:25.046Z	78640579-90ed-4210-a08f	INFO	error FetchError: request to https://YYY.supabase.co/rest/v1/table1 failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/opt/nodejs/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

**Comment by guicaro** [comment] 2021-02-21 23:35
In my case, this particular [thread from AWS](https://forums.aws.amazon.com/message.jspa?messageID=764136) solved my FetchError - ECONNRESET issues
>  Also, if you're using NodeJS, make sure that you have completed all asynchronous processing prior to returning from your request handler; otherwise, you may have a socket connection that is frozen (and subsequently thawed) across requests, which will often lead to a connection reset. Async processing in NodeJS is a frequent source of this type of error.

**Comment by kiwicopple** [comment] 2021-03-01 15:12
I'll close this for now, but if anyone finds a way to replicate this where Supabase is the cause/reason for the error, please feel free to re-open

**Closed by kiwicopple** 2021-03-01 15:12 UTC
Labels: bug

**Comment by code2k13** [comment] 2021-08-07 16:56
I have been getting this error

`
(node:4124) UnhandledPromiseRejectionWarning: FetchError: request to https://<<supabase_url>>/rest/
v1/<<tablename>>?columns=tid%2Clang failed, reason: getaddrinfo EAI_AGAIN <<supabase_url>> <<supabase_url>>:443
    at ClientRequest.<anonymous> (/scripts/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:4124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
 inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
(rejection id: 1)
(node:4124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejec
tions that are not handled will terminate the Node.js process with a non-zero exit code.
`

It comes intermittently. I have a nodejs program that reads line delimited json from stdin and inserts into supabase.  Not sure what is causing it. It generally occurs after my program is running for some time (maybe a couple of hours)

**Comment by kiwicopple** [comment] 2021-08-12 02:24
Hey @code2k13 - can you try changing your URL from `.io` to `.in` and see if you still see these intermittent errors?

**Comment by ShafSpecs** [comment] 2022-01-31 02:45
@kiwicopple I keep getting an `ECONNRESET` error from Supabase that happens randomly when trying to upload to buckets. I am using Remix framework and I have a server function that accepts multiple forms on that site's route. One of the forms submits a file to the server and because of that, I always parse the formData in the server:
```js
const formData = await unstable_parseMultipartFormData(
    request,                 // incoming request
    uploadHandler      // function to deal with incoming formData   
  );
```

The main function that deals with the file and supabase is:
```js
const uploadHandler: UploadHandler = async ({ name, stream, filename }) => {
    if (name !== "file") {              //checks wether the incoming data is a file                                               
      console.log("skipped!");
      stream.resume();           
      return;                                 // skips that form data value if it isn't
    }

    const fileExt = filename.split(".").pop();
    const fileName = `${Math.random().toFixed(10)}.${fileExt}`;
    const filePath = `${fileName}`;

    const { error: uploadError } = await supabaseClient.storage
      .from("public")
      .upload(`misc/${filePath}`, stream);     //uploads file to my bucket

    if (uploadError) {
      console.error(uploadError);
      throw new Error(uploadError.message);
    }

    const { publicURL, error } = await supabaseClient.storage
      .from("public")
      .getPublicUrl(`misc/${filePath}`);         // retrieve file URL from my bucket
    if (error) {
      console.error(error);
      throw new Error(error.message);
    }
    !publicURL && console.error(`No public URL for ${filePath}`);

    return publicURL;                                // return file url
  };
```

This function works times and I get the file URL, at times, the server throws a error 500 and an ECONNRESET error from Supabase: `could not get /* url of file */ from supabase, response terminated unexpectedly`

**Comment by ShafSpecs** [comment] 2022-01-31 04:04
I traced the source of the error to the upload handler, apparently, supabase randomly throws error when I try to upload images

**Comment by kiwicopple** [comment] 2022-01-31 09:32
hey @ShafSpecs - would you mind opening an issue in the storage-api repo with some steps to replicate? (or a demo/example) - https://github.com/supabase/storage-api
