### ISSUE TITLE
Studio crashes when navigating to API docs of a private table

### ISSUE THREAD

**Issue by hamza1311** [supabase/supabase#15602] opened 2023-07-06 17:24 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Supabase Studio crashes when pressing the "API" button[^1] in table editor for a table that is part of a private schema.
[^1]:  ![image](https://github.com/supabase/supabase/assets/47357913/d427cba3-b884-41e8-8cde-1402aee11eba)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to "Table Editor" page
2. Select a schema other than private
3. Select a table
4. Press the API Button[^1]
5. Observe

## Expected behavior

Application should not crash and instead helpfully point out that table can't be queried from the API

**Comment by GaryAustin1** [comment] 2023-07-06 18:49
This is a duplicate of https://github.com/supabase/supabase/issues/14766

**Closed** 2023-07-06 18:49 UTC
Labels: bug
