### ISSUE TITLE
Cannot edit auth user in studio 

### ISSUE THREAD

**Issue by riderx** [supabase/supabase#4237] opened 2021-12-02 04:21 UTC
## Describe the bug

<img width="1201" alt="Screenshot 2021-12-02 at 04 20 18" src="https://user-images.githubusercontent.com/4084527/144356998-5aecb0b9-5ea6-46b1-9e27-496633795a75.png">
In all table we can edit data but not in auth user, even metadata cannot be edited.

## Expected behavior

A least metadata should be editable from studio

**Comment by kiwicopple** [comment] 2021-12-02 05:34
You can only edit data inside the `public` schema at this stage - all other schemas are read-only. There isn't really a reason for this, except that we are making incremental changes to Studio. We will probably bring in edit functionality, although it should probably be coupled with some Access Controls

**Comment by riderx** [comment] 2021-12-02 15:47
Thanks, as alternative i will use sql snippet, but it look snippet are not shared between users, do it's in the roadmap ?

**Comment by joshenlim** [comment] 2022-05-10 06:25
hey @riderx sorry for the late reply on this one - we're definitely looking into having shared sql snippets between users but that won't be in anytime soon unfortunately.

i'll go ahead to close this ticket nonetheless as copple explained above ^ but feel free to reopen otherwise

**Closed by joshenlim** 2022-05-10 06:25 UTC
Labels: bug

**Comment by Crsk** [comment] 2025-01-28 04:44
I was experimenting this issue just now in a public schema, even after hard refreshing the browser. The solution was picking a random table then go back. As a context, only God knows how long the browser tab was there waiting to be noticed

**Comment by javiten** [comment] 2025-02-17 17:02
its just a refresh thing, end session then log in again, it works. Even though 3 years passed on these messages, the sup abase error was not corrected yet.

**Comment by santiarr** [comment] 2025-02-20 22:21
bumping this because it is happening super frequently for me

**Comment by javiten** [comment] 2025-02-20 22:50
> It's closed and labeled as `wontfix` because it's an intended behavior that non-public schemas are read-only, but as it also happens in the public schema, makes sense to reopen the issue

 I understand that it might be intended, but if signing off and singing in again corrects the issue, I don’t think it’s intended anymore. It might be happening for some kind of error.

**Comment by rhijjawi** [comment] 2025-03-06 19:53
This is new behavior - this has started happening to me more and more frequently and shouldn't be the "intended behavior". There is not indication that the tab is/was offline and at the very least should show a modal prompting for a refresh.
