### ISSUE TITLE
RLS using Enable insert for authenticated users only template not working for local development

### ISSUE THREAD

**Issue by emptytank** [supabase/supabase#22808] opened 2024-04-16 21:09 UTC
![supabase_rls_policy_error](https://github.com/supabase/supabase/assets/41249957/f4ecfdfe-c7c4-4047-920f-ceb20baed8eb)
## Describe the bug

Attempted to create a new policy based on the Enable insert for authenticated users only template, but was met with a "Please provide SQL expression for the WITH CHECK statement" even though the same template works outside of local development (http://localhost:54323/project/default/auth/policies).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table called "clients" with the following fields: "client_id" (uuid Data Type), "created_at" (timestamp with time zone Data Type), "email" (text Data Type), "is_active" (bool Data Type), and "user_id" (uuid Data Type). Ensure RLS is enabled.
3. Navigate to "Authentication" and create a new Policy.
4. Select "Enable insert for authenticated users only" template policy and click Save Policy.

## Expected behavior

The policy should save properly without any issue. The issue does not exist outside of local development when using supabase.com.

## Screenshots

![image](https://github.com/supabase/supabase/assets/41249957/39151e9d-7681-4ac0-939c-759d799f9a9c)

## System information

- OS: Windows 10 Enterprise

**Comment by Keagel** [comment] 2024-04-16 22:51
Make sure you've updated your containers, [this issue](https://github.com/supabase/supabase/issues/22580) was fixed in yesterday's release.

**Comment by encima** [comment] 2024-04-17 04:10
closing as dupe of referenced issue. please continue discussion there. as @Keagel said, this is fixed now too!

**Closed** 2024-04-17 04:10 UTC
Labels: bug
