### ISSUE TITLE
`http://public_ip:3000/api/profile/permissions 404 (Not Found)` error when connecting to supabase studio remotely (self-hosted)

### ISSUE THREAD

**Issue by Zedo9** [supabase/supabase#12702] opened 2023-02-27 15:14 UTC
# Bug report

## Describe the bug

When I connect to the Supabase Studio on my self-hosted instance, I keep getting the following error in my browser console:
```
GET http://my_public_ip:3000/api/profile/permissions 404 (Not Found)
```

## To Reproduce

1. Setup a basic self-hosted setup as described [here](https://supabase.com/docs/guides/self-hosting/docker) (Using the default setup, no changes were made to JWTs/secrets).
2. Change `SUPABASE_PUBLIC_URL` and `API_EXTERNAL_URL` to `http://your_public_ip:8000`.
3. Navigate to `http://your_public_ip:3000`.

## Expected behavior

I shouldn't be getting errors in my browser console.

## System information

- OS: Ubuntu 22.10
- Browser (if applies) Firefox

## Additional context

- I can access all pages on Supabase Studio with no problems.
- Firewall is disabled.
- No logs in the Kong or Studio containers related to this issue.

I'm using the newest images:
- supabase/studio:20230216-e731b77
- kong:2.8.1
- supabase/gotrue:v2.47.0
- postgrest/postgrest:v10.1.2
- supabase/realtime:v2.5.1
- supabase/storage-api:v0.28.2
- darthsim/imgproxy:v3.11
- supabase/postgres-meta:v0.60.7
- supabase/postgres:15.1.0.42-rc2

**Comment by ruggi99** [comment] 2023-02-27 19:36
Already fixed in #12659 
Next deployed docker image should contain this fix

**Comment by Zedo9** [comment] 2023-02-28 08:22
> Already fixed in #12659 Next deployed docker image should contain this fix

Great! Thank you.

**Comment by ruggi99** [comment] 2023-02-28 21:37
They have uploaded a new image (only for ARM because script partially failed) and can confirm the issue is gone

**Comment by DEPSTRCZ** [comment] 2023-03-02 11:56
Shoudlnt be the docker-compose file updated?

**Comment by ruggi99** [comment] 2023-03-02 18:12
Yes.
For some unknown reason they do not use latest tag like anyone else

**Comment by DEPSTRCZ** [comment] 2023-03-02 19:27
> Yes. For some unknown reason they do not use latest tag like anyone else

Caused new issues to appear :/

**Comment by ruggi99** [comment] 2023-03-02 19:37
Issues, as well as new features and bug fixes

**Comment by Chiggy-Playz** [comment] 2023-03-02 23:16
What issuse?

**Comment by Zedo9** [comment] 2023-03-03 13:53
> Caused new issues to appear :/

I tested the latest studio tag `20230228-029c7bd` and this issue seems to be resolved (Same for the issues that appeared in earlier versions). You can try it.

**Comment by njkhanh** [comment] 2023-03-03 18:40
I have also tried the latest version, and encountered a similar error.

**Comment by cristian-milea** [comment] 2023-03-12 02:24
still happening on `supabase/studio:20230216-e731b77`

**Comment by sweatybridge** [comment] 2023-03-15 00:54
While this console error is spammy and annoying, the studio dashboard is fully operational with it. There are a few other broken features with the latest studio image caused by some routes refactor. We will have to resolve these before updating the studio image to fix this issue.

Appreciate your patience.

For reference, the known broken routes are
- https://github.com/supabase/cli/issues/908
- https://github.com/supabase/cli/issues/904

**Comment by sweatybridge** [comment] 2023-04-03 09:07
This has been fixed in the latest studio image `supabase/studio:20230330-99fed3d`

**Closed by sweatybridge** 2023-04-03 09:07 UTC
Labels: bug, dashboard, self-hosted
