### ISSUE TITLE
Unable to add github oauth provider

### ISSUE THREAD

**Issue by binarytide** [supabase/supabase#1619] opened 2021-05-19 17:43 UTC
# Bug report

## Describe the bug
when trying to add a github oauth provider I receive the following message in the console(not on site)
`should have required property 'EXTERNAL_TWITTER_ENABLED'`

## To Reproduce
login to supabase,
go to project > authentication > settings
add github credentials
click save

## Expected behavior

registration of github as an oauth provider

## Screenshots
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/899298/118859325-1ae27f80-b8a8-11eb-8723-11145a1fd428.png">

## System information

- OS: osx big sur
- Browser: firefox
- Version of supabase-js:web dashboard(latest)
- Version of Node.js:na

## Additional context

toggling the twitter oauth and hitting save results in this: 
<img width="336" alt="image" src="https://user-images.githubusercontent.com/899298/118859215-fdadb100-b8a7-11eb-9c7f-346219687504.png">

**Comment by hilmanski** [comment] 2021-05-19 22:58
Also happen to me, 
Github is okay,
but after adding twitter it show "update config failed error..."

**Comment by w3b6x9** [comment] 2021-05-19 23:00
@binarytide @hilmanski thanks, i've told the team about this and we are investigating. We'll come up with a fix as soon as we can!

**Comment by awalias** [comment] 2021-05-20 01:50
apologies all, this was indeed a bug in our infra regarding the new twitter integration, it should be fixed now (although twitter auth itself won't work for older projects until we migrate them later today)

**Closed by awalias** 2021-05-20 01:50 UTC
Labels: bug

**Comment by hilmanski** [comment] 2021-05-20 02:06
@awalias  @w3b6x9 
thanks for working on this.

I can confirm bug is gone

**Comment by binarytide** [comment] 2021-05-20 02:09
working for me now as well. keep up the great work!

**Comment by hilmanski** [comment] 2021-05-20 04:02
Hi @w3b6x9 Did I miss something?
when I try to access via
https://myproject.supabase.co/auth/v1/authorize?provider=twitter

it shows
{
code: 400,
msg: "Unsupported provider: Provider twitter could not be found"
}

**Comment by inian** [comment] 2021-05-20 04:09
Hi @hilmanski, Twitter is a new provider which we haven't rolled out to everyone's projects yet. We will do this in the next 2 days.

**Comment by hilmanski** [comment] 2021-05-20 05:35
> Hi @hilmanski, Twitter is a new provider which we haven't rolled out to everyone's projects yet. We will do this in the next 2 days.

thanks inian, I though "old projects" mentioned above was alpha supabase. 
Okay, it's clear now

**Comment by hilmanski** [comment] 2021-05-25 04:37
To this day accessing
https://mdmynfcvivmskapfayvc.supabase.co/auth/v1/authorize?provider=twitter

return 
{
message: "no Route matched with those values"
}

is this still expected?

**Comment by kangmingtay** [comment] 2021-05-27 02:53
Hi @hilmanski, hmm I'm not exactly sure what the problem is but have you checked that you've added the correct callback / redirect URL to your twitter application on the developer portal?

**Comment by awalias** [comment] 2021-05-27 03:09
`no Route matched with those values` is actually a kong (api gateway) error 🤔 

@hilmanski  can you dm us the full url you're testing with on beta@supabase.io and reference this discussion, we can debug your endpoint then 👍

**Comment by awalias** [comment] 2021-05-27 04:02
@kangmingtay has just reminded me that we saw this bug internally, and it was indeed solved by adding the callback url to twitter developer dashboard (`https://<your-ref>.supabase.co/auth/v1/callback`)

**Comment by hilmanski** [comment] 2021-05-27 09:08
Hey @awalias thanks for the hint
I can confirm adding the correct url on twitter dashboard, resolve this issue
thanks for your time

**Comment by helloromero** [comment] 2022-05-07 19:37
I have `https://<project-ref>.supabase.co/auth/v1/callback` added.


Is there any other reason I could be getting the `{"message":"no Route matched with those values"}` error? it's not very clear what could be wrong. I have Twitter client ID and Twitter secret values added too.
