### ISSUE TITLE
Content on edge functions page overflow

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#6495] opened 2022-04-18 23:03 UTC
# Bug report

## Describe the bug

On smaller screens, the content on the [edge functions](https://supabase.com/edge-functions) page is overflowing.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to edge-functions
3. Scroll down to `Anatomy of an Edge Function` section
4. See overflow

## Expected behavior

Content not overflowing on smaller screens. Maybe make the content scrollable or just smaller.

## Screenshots

https://user-images.githubusercontent.com/70828596/163890503-76b25a67-be5a-4d88-a8d9-c88747929f88.mov

## System information

- OS: Any (test on mac)
- Browser: Any (test on firefox)
- Version of supabase-js: N/A
- Version of Node.js: N/A

## Additional context

Anyone is welcome to work on this issue.

**Comment by ganeshmani** [comment] 2022-04-19 08:48
@Isaiah-Hamilton can i work on this issue?

**Comment by Hallidayo** [comment] 2022-04-19 09:31
@Isaiah-Hamilton - I think this issue is related to #6401 ?

**Comment by kiwicopple** [comment] 2022-04-19 10:45
yeah, seems to be a duplicate of https://github.com/supabase/supabase/issues/6401

Let's use that one 👍

**Closed by kiwicopple** 2022-04-19 10:45 UTC
Labels: bug, help wanted, good first issue
