### ISSUE TITLE
Composite FK doesnt work in Studio (Insert Row Function)

### ISSUE THREAD

**Issue by logemann** [supabase/supabase#25849] opened 2024-05-07 16:35 UTC
## Describe the bug

suppose the following table structure:

table: test_parent
##############
id1 (int2) PK
id2 (int2) PK
foo (text) 

table: test_child
##############
id1 (int2) PK
id2 (int2) PK
foo (text) 
Composite FK on id1->id1 and id2->id2

When trying to insert via Studio, the second key part id2->id2 is interpreted as id2->id1. So selecting the foreign on insert doesnt work.

See the screenshots. Screenshots 1 shows the FK relationship. Screenshot 2 shows the broken "Insert Row" in Studio.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create two tables as outlines with composite FK
2. try to inserting via Studio "Insert Row" by selecting the foreign relation rows in the UI.

## Expected behavior

Lets say in my test_parent i have a row like "1;2;test". Now when i create a new row in test_child, i can select id1 without problems via Table Selection from foreign table. But clicking in the id2 field and selecting the same foreign row, he will give me "1" as value instead of "2". 

#### Screenshot1

<img width="668" alt="Bildschirmfoto 2024-05-07 um 18 22 28" src="https://github.com/supabase/supabase/assets/346353/fcb3da60-e5f6-4fa4-bb2c-4a25ed6f1889">

#### Screenshot2

<img width="671" alt="Bildschirmfoto 2024-05-07 um 18 14 32" src="https://github.com/supabase/supabase/assets/346353/d37a0286-5992-4673-a4c2-181c168cf8dc">

## System information

Tested on local studio installation which should be latest docker image.

- OS: MacOS
- Browser chrome
- CLI: 1.165.0
- studio docker: public.ecr.aws/supabase/studio:20240422-5cf8f30

**Comment by encima** [comment] 2024-05-08 09:00
Duplicate of https://github.com/supabase/supabase/issues/23485

**Closed by encima** 2024-05-08 09:00 UTC
Labels: bug, dashboard
