### ISSUE TITLE
Query Set Timezone is not changing the PostgresSQL default timezone

### ISSUE THREAD

**Issue by inbytesdevteam** [supabase/supabase#176] opened 2020-09-02 20:50 UTC
# Bug report
`Set Timezone` is not working

## Describe the bug
Unable to change timezone of the database. Querying of `SET TIMEZONE` is successful but when you do `SHOW TIMEZONE`, it is still UTC.

## To Reproduce

1. Go to the SQL Query Editor
2. Query `SET TIMEZONE='Asia/Manila'` or `SET TIMEZONE=-8` or `SET TIMEZONE=`PST`
3. Results: **Success. No rows returned**
4. Query `SHOW TIMEZONE`
5. Results is still **UTC** 

## Expected behavior

Result should be the newly changed timezone.

## Suggestion
Is it possible that when creating a new project, you can set the PostgresSQL default timezone of the database aside from the region of the project? Thanks.

**Comment by kiwicopple** [comment] 2020-09-06 04:22
Hey @inbytesdevteam can you try running this on your database?

```sql
SELECT pg_reload_conf();
```

**Comment by inbytesdevteam** [comment] 2020-09-24 15:51
Hi @kiwicopple, I tried this but it didn't work. Still UTC.

**Comment by kiwicopple** [comment] 2020-09-25 08:04
OK I suspect it needs a full server restart - I tried doing it myself with no luck. However you should be able to alter the timezone individual users/roles:

```
ALTER USER postgres SET timezone='Asia/Manila' ;
```

Can I ask what is the use case? I would highly recommend keeping the timezone at UTC, then always using the relevant timezone in the timestampz column. Here is a good article, all of which I agree with: https://justatheory.com/2012/04/postgres-use-timestamptz/

**Comment by kiwicopple** [comment] 2020-09-25 08:06
Also note that we have a special PG user for connecting to your database, so the command above won't actually reflect a change in time zone when you run `SHOW TIMEZONE` from the dashboard (but it will if you connect to your database as `postgres`)

**Comment by inbytesdevteam** [comment] 2020-09-25 13:44
In Firestore, if you'd be updating the date inside the Firebase Console (website), it automatically sets it's timezone based on your timezone. Making it easier for you to add the correct date and time you have in mind.

Now if we are going to use the TABLE in Supabase to add/update dates and i'm in a timezone that is not UTC, I need to compute it first to UTC before adding it in which is prone to error.

Maybe the DB can still be in UTC format, but when adding or updating dates using the TABLE, it is converted to the user's timezone for better UX experience?

**Comment by steve-chavez** [comment] 2020-12-10 01:54
Changing the timezone can be done with:

```sql
alter database postgres set timezone to 'Asia/Singapore';
```

This can be confirmed with a `show timezone`. Also by going to the `/project/{id}/database/config` page. It doesn't require a db restart.

However the db settings will only kick in at login time. So this might require a `pg-api` restart(I believe it persists the connection to the client db for making the queries? @soedirgo Can you confirm?).

So maybe the solution for this one is to allow changing the settings(that don't need restarting) through the `/project/{id}/database/config` page. Then that could instruct a pg-api connection restart.

**Comment by soedirgo** [comment] 2020-12-10 04:36
I think pg-api closes the connection right after executing the query, so doing `SET TIME ZONE` doesn't work since it only persists for the current session. Steve's solution above hits the nail, no restart needed 👍

**Comment by kiwicopple** [comment] 2020-12-10 04:47
That's great - thanks Steve, Bobbie

@inbytesdevteam I'll close this one now, but if that doesn't work feel free to re-open

**Closed by kiwicopple** 2020-12-10 04:47 UTC
Labels: bug

**Comment by TS200010** [comment] 2020-12-10 05:47
Not sure why I am getting these as I am not subscribed to this thread. Any assistance would be appreciated.

**Comment by kiwicopple** [comment] 2020-12-10 06:24
Are you "watching" the repo? You might want to just watch the releases

**Comment by inbytesdevteam** [comment] 2021-01-05 15:07
It's working now. Just want to say thanks @kiwicopple @steve-chavez @soedirgo 🙏🏻

**Comment by rafirh** [comment] 2024-08-21 06:54
ff
