### ISSUE TITLE
Duplication of table not working

### ISSUE THREAD

**Issue by goldenivan** [supabase/supabase#6892] opened 2022-05-19 17:18 UTC
# Bug report

## Describe the bug

I can't duplicate a table on a project.

## To Reproduce

Go to Table Editor
Right click on the table
Select "duplicate table entries"

When I validate, I've got the message `relation "activite" does not exist`. 

After that, my table is created, with all columns. But there is no data.

## Expected behavior

Allowed to duplicate a table.

**Comment by saltcod** [comment] 2022-05-20 14:43
Hey there!

Thanks for the report. 

I'm trying to reproduce this one, but it's successfully working for me. Is this the path you follow?

Is there anything else of note about the table? Is it really big? A lot of columns? Any triggers setup? RLS? 

<img width="415" alt="CleanShot 2022-05-20 at 12 10 37@2x" src="https://user-images.githubusercontent.com/105593/169551961-541fc486-26f2-4640-bc61-d9e2f2f7d066.png">

<img width="680" alt="CleanShot 2022-05-20 at 12 10 52@2x" src="https://user-images.githubusercontent.com/105593/169552062-bbbb9a6f-0aa4-4c6f-b1f4-151424b204f5.png">

**Comment by kiwicopple** [comment] 2022-05-23 09:57
I'll close this one for now @goldenivan , but feel free to comment if you can help us replicate and we can reopen. Thanks!

**Closed by kiwicopple** 2022-05-23 09:57 UTC
Labels: bug

**Comment by aPeoplesCalendar** [comment] 2023-02-01 01:12
I am also hitting this issue. Looks like the error message when attempting to duplicate is the same - `Failed to run sql query: relation "my_table_name" does not exist`. A new table with duplicate schema will be created, but it will _not_ contain duplicate entries.

My table has approximately 1200 rows and 11 columns, one of which is a fairly long string (~2000 characters). It has a few RLS policies, but nothing fancy, authenticated only for create, update, delete, public can read. (happy to elaborate if needed). No triggers. Highly motivated to solve this - please let me know what you need.

**Comment by aPeoplesCalendar** [comment] 2023-02-02 16:17
I was able to resolve my issue by downloading my table as a csv file and re-uploading it. The newly created table IS duplicate-able, but not the old one. While doing this, I attempted to narrow down what could have been causing it.

Even when creating a new table with the exact same schema and data values as the table I cannot duplicate, I can't reproduce the issue (new table IS duplicate-able). Not sure what the issue is, but wondering if it's something going wrong with the initial creation of a table.
