### ISSUE TITLE
Signup confirmation email link buggy on second click

### ISSUE THREAD

**Issue by laurentS** [supabase/supabase#504] opened 2021-01-10 22:33 UTC
# Bug report

## Describe the bug

if I click the account confirmation link again after confirming, I get an ugly JSON 404 response. Since this is user facing, it can be confusing.
The JSON response looks like this `{"code":404,"msg":"User not found"}`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. signup as a user of a supabase app (triggered by supabase.auth.signup())
2. open confirmation email and click the link, and find yourself in the app as expected
3. go back to mailbox and click the link again (say I forgot if I clicked it or not)
4. end up on the error message above

## Expected behavior

A proper HTML page with a meaningful message would be better. Maybe "you've already confirmed your account"?

**Comment by carlosstenzel** [comment] 2021-01-20 21:43
use

```
const { data, error } = await supabase.auth.signUp({
    email: email,
    password: password,
  });

  if (error) {
    toast.error(error.message, {
      position: toast.POSITION.TOP_RIGHT,
    });
    return false;
  }
```
and 

```
const { error } = await supabase.auth.signIn({
    email: email,
    password: password,
  });

  if (error) {
    toast.error(error.message, {
      position: toast.POSITION.TOP_RIGHT,
    });
  }

```

in https://app.supabase.io/project/<project>/auth/settings  config the field `Site URL`

and everything will work  :D

**Comment by laurentS** [comment] 2021-01-31 01:10
@carlosstenzel Thanks for sharing these, and sorry for not replying earlier. Unfortunately, I don't think these address my issue. I have configured the site url in settings, and everything works fine from clicking the signup confirmation link in the email until I'm back in my app. The email has a link like `https://<app_id>.supabase.co/auth/v1/verify?token=<the_token>&type=signup`. My error happens after clicking this link (a second time), not at the initial call to `supabase.auth.signUp`.
Is there something else I'm missing?

**Comment by carlosstenzel** [comment] 2021-01-31 01:23
understand 

double clicking to confirm it returns the error. 

```
{"code":404,"msg":"User not found"}
```

@kiwicopple . can we make a lake to deal with this error? 

** if the token does not exist, just redirect to the site

**Comment by laurentS** [comment] 2021-01-31 01:46
I was just looking at the code in gotrue to understand what is happening. I don't speak Go, but it seems that [this line](https://github.com/supabase/gotrue/blob/4c8a68ac058f518bd8c23ac95373b98064115a0e/api/verify.go#L138) is where the issue is. I'm seeing a 404 JSON, but maybe a more user friendly page that shows HTML instead of JSON would be easier. Or redirect to the siteURL with an extra param so we can handle it in the app.

**Comment by laurentS** [comment] 2021-02-06 22:35
Just found [this other issue](https://github.com/supabase/gotrue/issues/39) which seems to be the same

**Comment by awalias** [comment] 2021-03-10 07:20
ah! looks like we applied the fix only to recovery and not to signup: https://github.com/supabase/gotrue/pull/44/files

**Comment by AngeloAnolin** [comment] 2021-03-31 16:03
Attempt to fix via [https://github.com/supabase/gotrue/pull/82](url)

Sorry had to put the comment here as the fix was made in the gotrue repo but the issue is in this supabase repo.

**Comment by tylermercer** [comment] 2021-05-08 20:36
What is the status on this? The PRs mentioned above were merged but it still happens.

**Comment by janzheng** [comment] 2021-05-09 01:48
Is it possible to handle stale magic links w/ a redirect URL, e.g. to a signup page?

**Comment by awalias** [comment] 2021-09-22 11:37
appears to be fixed now, I get redirected to "<SITE_URL>/#error_code=404&error_description=Confirmation+Token+not+found"

**Closed by awalias** 2021-09-22 11:37 UTC
Labels: bug

**Comment by chrisguerrero** [comment] 2023-04-06 22:29
+1. Since the error data is prefixed with a `#`, how are we supposed to parse the URL to handle that case and show a user friendly message?

**Comment by Chippd** [comment] 2023-04-23 19:43
+1 I'm in the same boat as @peachp. I don't know if my auth flow is bad or what, I'm getting multiple reports of users being put in an endless loop where the magic links they're clicking from email are expired. This is also the only place I found via Google that mentions this.

**Comment by AdamBCo** [comment] 2023-06-28 04:56
+1

**Comment by xEverth** [comment] 2023-12-21 22:02
Also had some users report this issue. I'm trying to see if it's an email security setting that "clicks" on the links before the users are able to. Any updates from the team as how to handle invalid confirmation links?
