### ISSUE TITLE
Example: RedwoodJS

### ISSUE THREAD

**Issue by thorwebdev** [supabase/supabase#150] opened 2020-08-24 08:30 UTC
# Feature request

## Describe the solution you'd like

Add an example that shows how to use Supabase with [RedwoodJS](https://redwoodjs.com).

## Additional context

There is already some activity on this: https://community.redwoodjs.com/t/supabase-redwood-experiments/1088/9

**Comment by peterp** [comment] 2020-08-24 09:13
@Tobbe seems like you should contribute this in October!

**Comment by thorwebdev** [comment] 2020-08-24 09:17
Definitely no requirement to do this in October, just tagging it with the `hacktoberfest` label in case folks are looking for projects to do during Hacktoberfest :) But of course any and all contributions are welcome at any time of the year ❤️

**Comment by peterp** [comment] 2020-08-24 09:22
Ah, great point, I was just thinking about the cool internet points and swag that he could acquire... I also actually thought October was the upcoming month 🤦‍♂️

**Comment by Tobbe** [comment] 2020-08-24 11:14
I will PR it. Might get to it before October. But if not, I'll do it during Hacktoberfest for the extra internet points 🍺

**Comment by amorriscode** [comment] 2020-09-02 01:18
While it's not a Redwood/Supabase example, I did create an auth generator over here: https://github.com/redwoodjs/redwood/pull/1033

**Comment by duncanhealy** [comment] 2020-11-13 13:27
I've added a pr to redwood to update to v1 of supabase auth #redwoodjs/redwood/pull/1474

tracking issue there #redwoodjs/redwood/issues/1426

**Comment by kiwicopple** [comment] 2020-11-14 02:52
wow, that's great @duncanhealy - once they have merged I'd love to add `todo-redwood example` example.

![image](https://user-images.githubusercontent.com/10214025/99137512-3dc87880-2666-11eb-9cfa-7b5d12e50a58.png)

It looks like the redwood library is looking for the GoTrue user/session right? If that's the case we can export these from gotrue-js (and subsequently supabase-js): https://github.com/supabase/gotrue-js/blob/18859b3dc63fbf056f37ff80c33abc2d6acfa815/src/lib/types.ts#L5

**Comment by viperfx** [comment] 2020-11-14 04:30
Looking forward to when this lands on redwood 👍 

@kiwicopple do you provide email verification steps through Supabase? and does the login response prevent a user from logging in if the email is not verified?

**Comment by duncanhealy** [comment] 2020-11-14 06:27
> wow, that's great @duncanhealy - once they have merged I'd love to add `todo-redwood example` example.
> 
> ![image](https://user-images.githubusercontent.com/10214025/99137512-3dc87880-2666-11eb-9cfa-7b5d12e50a58.png)
> 
> It looks like the redwood library is looking for the GoTrue user/session right? If that's the case we can export these from gotrue-js (and subsequently supabase-js): https://github.com/supabase/gotrue-js/blob/18859b3dc63fbf056f37ff80c33abc2d6acfa815/src/lib/types.ts#L5

Yea it needs the types in supabase.ts

**Comment by duncanhealy** [comment] 2020-11-14 07:13
Have we added to https://github.com/DefinitelyTyped/DefinitelyTyped yet?

**Comment by kiwicopple** [comment] 2020-11-15 03:42
> Have we added to https://github.com/DefinitelyTyped/DefinitelyTyped yet?

We're native TS now so we should can bundle our types directly [from the library](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

> @kiwicopple do you provide email verification steps through Supabase? and does the login response prevent a user from logging in if the email is not verified?

@viperfx yes, you will just need to turn it on in the Dashboard. By default we have this turned off:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/10214025/99162326-71270800-2737-11eb-8118-34b5fc0841fd.png">

If this is enabled, then the users have to confirm or you will receive this response: `{"error":"invalid_grant","error_description":"Email not confirmed"}`

**Comment by Tobbe** [comment] 2020-11-16 08:15
Finally made some progress on updating the RW implementation of the slack clone. I've upgraded to the latest version of Redwood, and I'm now using RW's supabase auth integration.

The commit history is a pretty good overview of what I've done, and how someone might go about building something like this in Redwood (read it bottom-up)

```
$ git tree
* a83cd01 2020-11-16 Tobbe Lundberg (HEAD -> main, origin/main) MainLayout: useAuth logOut
* 2a638bd 2020-11-16 Tobbe Lundberg Store: For realtime messages and channels synced to supabase
* 030b385 2020-11-16 Tobbe Lundberg MainLayout: Link to channel
* f909c51 2020-11-16 Tobbe Lundberg HomePage: Redirect after auth
* a163915 2020-11-16 Tobbe Lundberg ChannelPage: Make private + Content
* 4f681fd 2020-11-16 Tobbe Lundberg yarn rw g page channel {id}
* e576516 2020-11-16 Tobbe Lundberg yarn rw g component message + Content
* 26d27cf 2020-11-16 Tobbe Lundberg yarn rw g component MessageInput + content
* 7032760 2020-11-16 Tobbe Lundberg HomePage: useAuth login and signup
* 8fa811d 2020-11-15 Tobbe Lundberg yarn rw g auth supabase + supabase downgrade to 0.36.5
* f688af2 2020-11-15 Tobbe Lundberg HomePage: Content
* 9fa124f 2020-11-15 Tobbe Lundberg yarn rw g page home /
* b75d140 2020-11-16 Tobbe Lundberg MainLayout: Content
* 44dbfde 2020-11-15 Tobbe Lundberg yarn rw g layout main
* 1e962bf 2020-11-15 Tobbe Lundberg yarn rw setup tailwind
* 5541776 2020-08-21 Tobbe Lundberg Initial commit
```

The one thing that I have left to do is to implement the `UserContext` stuff, so mainly updating the `users` table, and the localStorage stuff.

As soon a new RW release is out that uses supabase-js@1.0.x I'll update to that

https://github.com/Tobbe/supaslack/commits/main

**Comment by Rt19990000** [comment] 2020-12-04 18:07
Jjjjjjj

**Closed** 2021-03-01 15:14 UTC
Labels: example, good first issue, help wanted, javascript, redwood-js
