### ISSUE TITLE
typo in supabase/spec /supabase_py_v2.yml

### ISSUE THREAD

**Issue by mkandan** [supabase/supabase#13664] opened 2023-04-13 05:41 UTC
# Improve documentation

## Link 

[Link to list_buckets](https://supabase.com/docs/reference/python/storage-listbuckets)

## Describe the problem

Public documentation says `res = supabase.storage().list_bucke()` instead of what the documentation in the codebase has `res = supabase.storage().list_buckets()` on line 675 in `supabase/spec /supabase_py_v2.yml`

## Describe the improvement

Make public documentation at provided link match code base link.

## Additional context

n/a

**Comment by zaineb-damak** [comment] 2023-04-13 15:12
I'd like to correct it. Can you assign this to me.

**Comment by hindu-muppala** [comment] 2023-04-13 17:30
Can I solve this issue?

**Comment by MildTomato** [comment] 2023-04-17 09:26
This is due to some bad code in the reference doc templating.
It currently, and this is embarrassing, find and replaces `"ts"` with `""` in all code examples.

We need to change the documentation site to stop doing this.

Either, 

1. rewrite all the example code to no longer be in markdown codeblocks
2. rewrite the templating so that it doesn't need to remove the codeblock backticks from examples, and instead just render the markdown.

**Comment by silentworks** [comment] 2023-04-19 21:02
@MildTomato this looks like a regression because I've reported this issue before and we had fixed it if I remember correctly.

**Comment by ojasaklechayt** [comment] 2023-04-20 18:59
Hi! Can you please share the python docs file address ? I think I am unable to find it.

**Comment by zaineb-damak** [comment] 2023-04-20 19:29
@ojasaklechayt Hello, I think you're looking for this file: https://github.com/supabase/supabase/blob/master/spec/supabase_py_v2.yml

**Comment by ojasaklechayt** [comment] 2023-04-20 19:34
> @ojasaklechayt Hello, I think you're looking for this file: https://github.com/supabase/supabase/blob/master/spec/supabase_py_v2.yml

No, actually I am unable to find the python documentation file.

**Comment by kiwicopple** [comment] 2023-12-06 14:26
Closing the issue, as it seems like the original issue has been resolved.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

**Closed by kiwicopple** 2023-12-06 14:26 UTC
Labels: documentation
