### ISSUE TITLE
pg_cron / seems job never executed

### ISSUE THREAD

**Issue by pyoner** [supabase/supabase#1703] opened 2021-05-25 04:07 UTC
I tried to execute a simples CRON job with pg_cron by following the official tutorial https://supabase.io/blog/2021/03/05/postgres-as-a-cron-server and it's not working for me.

Where I'm now:
I have the pg_cron extension installed by supabase UI; I have the simplest CRON job which looks like
```
SELECT cron.schedule(
'* * * * *',
$$
  DELETE FROM data
  WHERE id=1
$$
);
```
if I execute `SELECT * FROM cron.job;` I will get it in the list of scheduled jobs.
But at the end of the day, it never will be executed.

What I already try to do:
- disable/enable extension
- create a brand new project and redo steps following the guide 

Any ideas on how I can handle this issue?

_Originally posted by @Miruzz in https://github.com/supabase/supabase/discussions/1628_

**Comment by dragarcia** [comment] 2021-05-25 04:41
Hi @pyoner & @Miruzz ! Thanks for pointing this out. There does seem to be an issue with pg_cron at the moment on our side and we are now looking into it.

**Comment by Miruzz** [comment] 2021-05-31 06:27
@dragarcia hey. Any news about the issue? Thanks!

**Comment by dragarcia** [comment] 2021-06-01 05:40
Hey guys! Not much at the moment but we are inching towards finding the root cause. Sorry about that. We'll update you on any major progress.

**Comment by nomanmurtaza786** [comment] 2021-07-02 06:08
> Hey guys! Not much at the moment but we are inching towards finding the root cause. Sorry about that. We'll update you on any major progress.

Hi, have tried as well it's working in test supabase project but not working in my main project. Here is the syntax 

`select
  cron.schedule(
    'reset_todays_counter', -- name of the cron job
    '* * * * *',  -- every 24 hour
    $$
     UPDATE public.coins_details SET today_votes = 0;
     SELECT content FROM http_get('https://hc-ping.com/7928f20f-0835-4ac8-b738-6d1a0fb0923a');
    $$
  );`

**Comment by dragarcia** [comment] 2021-07-02 17:24
Hey everyone 👋, finally found a quick remedy. Do follow this flow when using the `pg_cron` extension on the dashboard:

---

### 0. [_OPTIONAL_] Drop all scheduled jobs and the pg_cron extension itself
- This is important if you already have pg_cron enabled and have jobs set
```
-- repeat as much to clear all jobs
select cron.unschedule(<job id>); 

-- drop the extension
drop extension if exists pg_cron;
```
### 1. Enable pg_cron
```
create extension if not exists pg_cron;
```
### 2. [_IMPORTANT_] Provide the following grants to the user `postgres` (and in the future any other user that would be using the cron schema). At the baseline, it seems pg_cron uses the `postgres` user when executing its schedule.
```
grant usage on schema cron to postgres;
grant all privileges on all tables in schema cron to postgres;
```
### 3. Create sample table `test_table`
```
CREATE TABLE test_table (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text
);
```
### 4. Run a CRON job via pg_cron to add a row to this sample table
```
select
  cron.schedule(
    'whack-every-minute', 
    '* * * * *', 
    $$
    insert into test_table(name) values ('kek');
    $$
  );
```

### 5. Observe that the table `test_table` is now being populated every minute
```
select * from test_table;
```
![image](https://user-images.githubusercontent.com/26374889/124260236-0a3d4e80-db62-11eb-8398-c34eb415877d.png)

**Comment by dragarcia** [comment] 2021-07-02 17:25
Do tell us if these steps work for you guys. This won't be the long-term solution, however. This is instead a way to hopefully unblock you guys from this bug for the time being. We're now working on a way for **Step 2** to always be triggered automatically upon enabling the extension.

Thanks!

**Comment by nomanmurtaza786** [comment] 2021-07-04 20:58
> Do tell us if these steps work for you guys. This won't be the long-term solution, however. This is instead a way to hopefully unblock you guys from this bug for the time being. We're now working on a way for **Step 2** to always be triggered automatically upon enabling the extension.
> 
> Thanks!

Works for me thanks

**Comment by pyoner** [comment] 2021-07-05 05:47
> Do tell us if these steps work for you guys. This won't be the long-term solution, however. This is instead a way to hopefully unblock you guys from this bug for the time being. We're now working on a way for **Step 2** to always be triggered automatically upon enabling the extension.
> 
> Thanks!

These sql queries helped me!
```sql
grant usage on schema cron to postgres;
grant all privileges on all tables in schema cron to postgres;
```

@dragarcia thank you!

**Comment by Miruzz** [comment] 2021-07-05 11:55
Yeah! Works for me as well. Thank you

**Comment by emschwartz** [comment] 2021-07-05 19:15
I ran the exact commands listed above and didn't see any entries added to the `test_table`. 

In the `cron.job_run_details` table, I see when the cron job tried to run but each has a `status: failed` and `return_message: connection failed`. This is the case when I run the commands through the Supabase UI as well as through another client (logged in as the `postgres` user).

**Comment by dragarcia** [comment] 2021-07-06 01:12
Hey @emschwartz! That's odd 🤔. Could you send over your project ref over to beta@supabase.io? I'll check out what's wrong under the hood.

**Comment by dragarcia** [comment] 2021-07-09 11:15
Hey all. 👋 

Given that the solution outlined [above](https://github.com/supabase/supabase/issues/1703#issuecomment-873149639) is working well, I will be closing this issue. 

From now on, **newly** created projects on the dashboard should no longer have this bug. One should be able to immediately start scheduling jobs without having the need to run `step 2`. This is unless of course, you would want to grant access to newly created database users.

**Closed by dragarcia** 2021-07-09 11:15 UTC

**Comment by sduduzog** [comment] 2021-07-11 07:04
> > Do tell us if these steps work for you guys. This won't be the long-term solution, however. This is instead a way to hopefully unblock you guys from this bug for the time being. We're now working on a way for **Step 2** to always be triggered automatically upon enabling the extension.
> > Thanks!
> 
> These sql queries helped me!
> 
> ```sql
> grant usage on schema cron to postgres;
> grant all privileges on all tables in schema cron to postgres;
> ```
> 
> @dragarcia thank you!

Hi all, I ran into this issue today (at the dat of writing this comment) and the solution was to grant usage and privileges as with the quoted reply.

It then worked without having to go through the 5 step process

**Comment by MohamedLamineAllal** [comment] 2021-08-03 21:58
I'm having the problem! while insering a row using rpc through the nodejs library! with user service_role!

i gave permission to all roles! Without exception!

And for service_role i even gave it all priveleges in the whole database just for the sake of testing!

launching the cron from the dashboard editor! And after giving the permission to **postgres** as above!
It worked! The cron worked just right!

But then when i do it through **service_role**! From nodejs rpc insert! Which trigger a trigger procedure! Which run all right!

i made a command to ccheck which insert in a log table i created! In mean time! the job is added to the jobs table! And being active!

However no command run! (the mentioned user i gave him the privleeges for cron! But then after i gave him even access to all! Nothing works!

Any ideas or pointing!

Here my trigger function

![image](https://user-images.githubusercontent.com/20062543/128091819-e95dcdb5-0fc4-488d-8b3b-9c81785b02fb.png)

**Comment by MohamedLamineAllal** [comment] 2021-08-03 23:20
Update:

![image](https://user-images.githubusercontent.com/20062543/128097792-afe5184e-dab7-47dc-a8ce-8be04727bb19.png)

Checking the table as mentioned on the article! i found out that the command execution is failing! Because the connection failed!

![image](https://user-images.githubusercontent.com/20062543/128097944-fd28a3fb-59d5-4bfb-9954-2b93dec0c0c7.png)

I made the user a super user temporally! But then it seems not the thing!
And it's something that require Db Authentication config!

https://github.com/citusdata/pg_cron/issues/66

Anything that i can do! I'm inserting a row from nodejs (service_role)! Which trigger a function that schedule the cron! The cron schedule all right and work ! But fail at command execution! What can i do! And what is the detail of the why ?

**Comment by MohamedLamineAllal** [comment] 2021-08-04 02:30
I handled it! I ended up **creating a total new user** (role)! **With it's password!** And used that for the external connection! I gave the new user the **necessary priveleges**! And **all worked well**! (Using service_role was problematic! Even by giving it super user privileges! it didn't work! And fail by a 'connection failed' error!

**Comment by xavierchia** [comment] 2024-01-29 02:11
I managed to schedule jobs but they weren't running. Ended up restarting the project and project settings and the jobs started running.

**Comment by vineethvijayan314** [comment] 2025-02-09 19:00
I tried the same steps but still not able to run the cron jobs. I am using branches and I am trying in dev branch. does cron jobs run in dev branches?

**Comment by JL-D-coder** [comment] 2025-03-18 05:54
In my case I m running an edge function as cron, From the log I got success message, but nothing was reflected in the database.
Also have provided following permission. I have tested the edge function via postman its working fine.

grant usage on schema cron to postgres;
grant all privileges on all tables in schema cron to postgres;

**Comment by JL-D-coder** [comment] 2025-03-18 06:37
> In my case I m running an edge function as cron, From the log I got success message, but nothing was reflected in the database. Also have provided following permission. I have tested the edge function via postman its working fine.
> 
> grant usage on schema cron to postgres; grant all privileges on all tables in schema cron to postgres;

I was missing Header, I thought it was not necessary since it was runnig inside the same project.

**Comment by Bamorem** [comment] 2025-09-18 10:41
hey, I'm doing all those steps. even the example with the test_table.

i run
`
grant usage on schema cron to postgres;
grant all privileges on all tables in schema cron to postgres;
`

But nothing happened.

The cron.job_run_details is actually never populated.

A new record is been inserted in the test_table when i click on execute the job from the dashboard. but events like this the job_run_details is still empty....

**Comment by JL-D-coder** [comment] 2025-09-29 18:25
> hey, I'm doing all those steps. even the example with the test_table.
> 
> i run `grant usage on schema cron to postgres; grant all privileges on all tables in schema cron to postgres;`
> 
> But nothing happened.
> 
> The cron.job_run_details is actually never populated.
> 
> A new record is been inserted in the test_table when i click on execute the job from the dashboard. but events like this the job_run_details is still empty....

Add all the Authorization token like you are hitting an external API, The bearer token is your supabase anon key for the legacy version. Please double check this.

<img width="462" height="749" alt="Image" src="https://github.com/user-attachments/assets/9df9ae1b-1301-422c-88ca-b2816032fda6" />

**Comment by Bamorem** [comment] 2025-09-30 04:55
@JL-D-coder like i said event the example with test_table that doesn't imply edge function doesn't work....

the main issue is The cron.job_run_details is actually never populated.
