### ISSUE TITLE
Edge functions not serving correctly when trying to server "all"

### ISSUE THREAD

**Issue by dancrumb** [supabase/supabase#13108] opened 2023-03-20 14:49 UTC
# Bug report

I've written an function and am trying to test it locally, but the behavior doesn't seem right.

The function is at `supabase/functions/xyz/index.ts` (it was generated with the CLI).

```
supabase functions serve --env-file .env --no-verify-jwt
```

The only response is 

```
Serving supabase/functions
```

Then, when I try to `POST 'http://localhost:54321/functions/v1/xyz'` in another terminal, I get:

```
{
  "message":"An invalid response was received from the upstream server"
}
```

And

```
service does not exist
```

is shown in the terminal that I started serving functions from.

## Describe the bug

The basic description covers the whole bug description.

Some additional info:

1. When I navigate to the local Studio (http://localhost:54323/projects), I noticed that there's no icon for accessing Edge Functions
2. I'm on an M1 mac running 13.0.1 (22A400)
3. I'm on Supabase CLI version 1.42.7
4. I also noticed that the file watcher doesn't seem to be working either.

Here's my config:

```
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "supabase"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 seconds (one
# week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

```

## To Reproduce

See above

## Expected behavior

I would expect the functions to be served and the file watcher to work

## Sample output with --debug:

```
supabase functions serve --env-file .env --no-verify-jwt --debug
2023/03/17 16:49:44 Sent Header: Host [docker]
2023/03/17 16:49:44 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/17 16:49:44 Send Done
2023/03/17 16:49:44 Recv First Byte
Serving supabase/functions
2023/03/17 16:49:44 Sent Header: Host [docker]
2023/03/17 16:49:44 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/17 16:49:44 Send Done
2023/03/17 16:49:44 Recv First Byte
2023/03/17 16:49:44 Sent Header: Host [docker]
2023/03/17 16:49:44 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/17 16:49:44 Sent Header: Content-Length [306]
2023/03/17 16:49:44 Sent Header: Content-Type [application/json]
2023/03/17 16:49:44 Send Done
2023/03/17 16:49:44 Recv First Byte
2023/03/17 16:49:44 Sent Header: Host [docker]
2023/03/17 16:49:44 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/17 16:49:44 Sent Header: Content-Length [2788]
2023/03/17 16:49:44 Sent Header: Content-Type [application/json]
2023/03/17 16:49:44 Send Done
2023/03/17 16:49:45 Recv First Byte
2023/03/17 16:49:45 Sent Header: Host [docker]
2023/03/17 16:49:45 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/17 16:49:45 Sent Header: Content-Length [0]
2023/03/17 16:49:45 Sent Header: Content-Type [text/plain]
2023/03/17 16:49:45 Send Done
2023/03/17 16:49:45 Recv First Byte
2023/03/17 16:49:45 Sent Header: Host [docker]
2023/03/17 16:49:45 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/17 16:49:45 Send Done
2023/03/17 16:49:45 Recv First Byte
DEBUG edge-runtime is listening on 0.0.0.0:8081

service does not exist
```

## System information

- OS: macOS 13.0.1 (22A400)
- Browser: n/a
- Version of supabase-js: n/a
- Version of Node.js:  n/a

**Comment by dancrumb** [comment] 2023-03-20 19:53
I have recreated this in Github Codespaces as well as on two M1 laptops

**Comment by laktek** [comment] 2023-03-21 05:34
@dancrumb When you run `supabase functions serve`, are you running it from the project's root directory? ie. `supabase/functions/xyz` a descendant directory?

**Comment by dancrumb** [comment] 2023-03-21 11:13
Yep.

I'll put together a short video in a bit so that you can see what I am seeing

**Comment by dancrumb** [comment] 2023-03-21 12:09
Here's a Loom of things working for a single function but not all functions: https://www.loom.com/share/2d3143328e434a038fc45f93a628adb4

Here's the content of the terminal from the demo

```
❯ ls -ltar
total 24
drwxr-xr-x  35 dancrumb  staff  1120 Mar 19 20:17 ..
drwxr-xr-x  10 dancrumb  staff   320 Mar 19 20:22 supabase
drwxr-xr-x   7 dancrumb  staff   224 Mar 19 20:26 certbot
-rw-r--r--   1 dancrumb  staff   159 Mar 19 20:29 .gitignore
-rw-r--r--   1 dancrumb  staff   259 Mar 20 10:24 .env
drwxr-xr-x   3 dancrumb  staff    96 Mar 20 19:51 .vscode
drwxr-xr-x   5 dancrumb  staff   160 Mar 20 19:51 docs
drwxr-xr-x  10 dancrumb  staff   320 Mar 21 07:01 .
-rw-r--r--   1 dancrumb  staff  1370 Mar 21 07:01 README.md
drwxr-xr-x  14 dancrumb  staff   448 Mar 21 07:01 .git
❯ ls supabase/functions/open-ai
index.ts
❯ supabase functions serve open-ai --env-file .env --debug
2023/03/21 07:05:05 Sent Header: Host [docker]
2023/03/21 07:05:05 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:05 Send Done
2023/03/21 07:05:05 Recv First Byte
2023/03/21 07:05:05 Sent Header: Host [docker]
2023/03/21 07:05:05 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:05 Send Done
2023/03/21 07:05:05 Recv First Byte
2023/03/21 07:05:05 Sent Header: Host [docker]
2023/03/21 07:05:05 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:05 Sent Header: Content-Length [306]
2023/03/21 07:05:05 Sent Header: Content-Type [application/json]
2023/03/21 07:05:05 Send Done
2023/03/21 07:05:05 Recv First Byte
2023/03/21 07:05:05 Sent Header: Host [docker]
2023/03/21 07:05:05 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:05 Sent Header: Content-Length [2235]
2023/03/21 07:05:05 Sent Header: Content-Type [application/json]
2023/03/21 07:05:05 Send Done
2023/03/21 07:05:05 Recv First Byte
2023/03/21 07:05:05 Sent Header: Host [docker]
2023/03/21 07:05:05 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:05 Sent Header: Content-Length [0]
2023/03/21 07:05:05 Sent Header: Content-Type [text/plain]
2023/03/21 07:05:05 Send Done
2023/03/21 07:05:06 Recv First Byte
Starting supabase/functions/open-ai
2023/03/21 07:05:06 Sent Header: Host [docker]
2023/03/21 07:05:06 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:06 Sent Header: Content-Length [530]
2023/03/21 07:05:06 Sent Header: Content-Type [application/json]
2023/03/21 07:05:06 Send Done
2023/03/21 07:05:06 Recv First Byte
Download https://deno.land/std@0.168.0/http/server.ts
Download https://deno.land/std@0.180.0/log/mod.ts
Download https://deno.land/x/xhr@0.1.0/mod.ts
Download https://esm.sh/openai@3.2.1
Download https://esm.sh/v111/openai@3.2.1/deno/openai.js
Download https://esm.sh/v111/openai@3.2.1/dist/index.d.ts
Download https://esm.sh/v111/openai@3.2.1/dist/api.d.ts
Download https://esm.sh/v111/openai@3.2.1/dist/configuration.d.ts
Download https://esm.sh/v111/axios@0.26.1/deno/axios.js
Download https://esm.sh/v111/form-data@4.0.0/deno/form-data.js
Download https://deno.land/std@0.177.0/node/process.ts
Download https://esm.sh/v111/openai@3.2.1/dist/base.d.ts
Download https://esm.sh/v111/axios@0.26.1/index.d.ts
Download https://deno.land/std@0.168.0/async/mod.ts
Download https://deno.land/std@0.180.0/_util/asserts.ts
Download https://deno.land/std@0.180.0/log/handlers.ts
Download https://deno.land/std@0.180.0/log/levels.ts
Download https://deno.land/std@0.180.0/log/logger.ts
Download https://deno.land/x/media_types@v2.9.0/mod.ts
Download https://deno.land/std@0.177.0/_util/asserts.ts
Download https://deno.land/std@0.177.0/path/mod.ts
Download https://deno.land/std@0.177.0/node/_core.ts
Download https://deno.land/std@0.177.0/node/_next_tick.ts
Download https://deno.land/std@0.177.0/node/_process/exiting.ts
Download https://deno.land/std@0.177.0/node/_process/process.ts
Download https://deno.land/std@0.177.0/node/_process/streams.mjs
Download https://deno.land/std@0.177.0/node/_utils.ts
Download https://deno.land/std@0.177.0/node/events.ts
Download https://deno.land/std@0.177.0/node/internal/errors.ts
Download https://deno.land/std@0.177.0/node/internal/options.ts
Download https://deno.land/std@0.177.0/node/internal/process/per_thread.mjs
Download https://deno.land/std@0.177.0/node/internal/validators.mjs
Download https://deno.land/std@0.177.0/node/internal_binding/constants.ts
Download https://deno.land/std@0.177.0/node/internal_binding/mod.ts
Download https://deno.land/std@0.177.0/node/internal_binding/uv.ts
Download https://deno.land/std@0.168.0/async/abortable.ts
Download https://deno.land/std@0.168.0/async/deadline.ts
Download https://deno.land/std@0.168.0/async/debounce.ts
Download https://deno.land/std@0.168.0/async/deferred.ts
Download https://deno.land/std@0.168.0/async/delay.ts
Download https://deno.land/std@0.168.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.168.0/async/pool.ts
Download https://deno.land/std@0.168.0/async/retry.ts
Download https://deno.land/std@0.168.0/async/tee.ts
Download https://deno.land/std@0.180.0/fmt/colors.ts
Download https://deno.land/std@0.180.0/fs/exists.ts
Download https://deno.land/std@0.180.0/io/buf_writer.ts
Download https://deno.land/std@0.180.0/types.d.ts
Download https://deno.land/x/media_types@v2.9.0/db.ts
Download https://deno.land/x/media_types@v2.9.0/deps.ts
Download https://deno.land/std@0.177.0/_util/os.ts
Download https://deno.land/std@0.177.0/node/internal_binding/_libuv_winerror.ts
Download https://deno.land/std@0.177.0/path/_interface.ts
Download https://deno.land/std@0.177.0/path/common.ts
Download https://deno.land/std@0.177.0/path/glob.ts
Download https://deno.land/std@0.177.0/path/posix.ts
Download https://deno.land/std@0.177.0/path/separator.ts
Download https://deno.land/std@0.177.0/path/win32.ts
Download https://deno.land/std@0.177.0/node/internal/fixed_queue.ts
Download https://deno.land/std@0.177.0/node/buffer.ts
Download https://deno.land/std@0.177.0/node/internal/readline/callbacks.mjs
Download https://deno.land/std@0.177.0/node/stream.ts
Download https://deno.land/std@0.177.0/node/_process/stdio.mjs
Download https://deno.land/std@0.177.0/node/_events.mjs
Download https://deno.land/std@0.177.0/node/_events.d.ts
Download https://deno.land/std@0.177.0/node/internal/error_codes.ts
Download https://deno.land/std@0.177.0/node/internal_binding/node_options.ts
Download https://deno.land/std@0.177.0/node/internal/hide_stack_frames.ts
Download https://deno.land/std@0.177.0/node/internal/normalize_encoding.mjs
Download https://deno.land/std@0.177.0/node/internal/util/types.ts
Download https://deno.land/std@0.177.0/node/internal/util/inspect.mjs
Download https://deno.land/std@0.99.0/path/mod.ts
Download https://deno.land/std@0.180.0/bytes/copy.ts
Download https://deno.land/std@0.177.0/node/internal_binding/_winerror.ts
Download https://deno.land/std@0.177.0/node/internal/buffer.mjs
Download https://deno.land/std@0.177.0/node/internal/buffer.d.ts
Download https://deno.land/std@0.177.0/path/_constants.ts
Download https://deno.land/std@0.177.0/path/_util.ts
Download https://deno.land/std@0.177.0/node/_stream.mjs
Download https://deno.land/std@0.177.0/node/_stream.d.ts
Download https://deno.land/std@0.177.0/node/internal/readline/utils.mjs
Download https://deno.land/std@0.177.0/node/internal_binding/async_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/buffer.ts
Download https://deno.land/std@0.177.0/node/internal_binding/cares_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/config.ts
Download https://deno.land/std@0.177.0/node/internal_binding/contextify.ts
Download https://deno.land/std@0.177.0/node/internal_binding/credentials.ts
Download https://deno.land/std@0.177.0/node/internal_binding/crypto.ts
Download https://deno.land/std@0.177.0/node/internal_binding/errors.ts
Download https://deno.land/std@0.177.0/node/internal_binding/fs.ts
Download https://deno.land/std@0.177.0/node/internal_binding/fs_dir.ts
Download https://deno.land/std@0.177.0/node/internal_binding/fs_event_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/heap_utils.ts
Download https://deno.land/std@0.177.0/node/internal_binding/http_parser.ts
Download https://deno.land/std@0.177.0/node/internal_binding/icu.ts
Download https://deno.land/std@0.177.0/node/internal_binding/inspector.ts
Download https://deno.land/std@0.177.0/node/internal_binding/js_stream.ts
Download https://deno.land/std@0.177.0/node/internal_binding/messaging.ts
Download https://deno.land/std@0.177.0/node/internal_binding/module_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/native_module.ts
Download https://deno.land/std@0.177.0/node/internal_binding/natives.ts
Download https://deno.land/std@0.177.0/node/internal_binding/options.ts
Download https://deno.land/std@0.177.0/node/internal_binding/os.ts
Download https://deno.land/std@0.177.0/node/internal_binding/performance.ts
Download https://deno.land/std@0.177.0/node/internal_binding/pipe_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/process_methods.ts
Download https://deno.land/std@0.177.0/node/internal_binding/report.ts
Download https://deno.land/std@0.177.0/node/internal_binding/serdes.ts
Download https://deno.land/std@0.177.0/node/internal_binding/signal_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/spawn_sync.ts
Download https://deno.land/std@0.177.0/node/internal_binding/stream_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/string_decoder.ts
Download https://deno.land/std@0.177.0/node/internal_binding/symbols.ts
Download https://deno.land/std@0.177.0/node/internal_binding/task_queue.ts
Download https://deno.land/std@0.177.0/node/internal_binding/tcp_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/timers.ts
Download https://deno.land/std@0.177.0/node/internal_binding/tls_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/trace_events.ts
Download https://deno.land/std@0.177.0/node/internal_binding/tty_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/types.ts
Download https://deno.land/std@0.177.0/node/internal_binding/udp_wrap.ts
Download https://deno.land/std@0.177.0/node/internal_binding/url.ts
Download https://deno.land/std@0.177.0/node/internal_binding/util.ts
Download https://deno.land/std@0.177.0/node/internal_binding/v8.ts
Download https://deno.land/std@0.177.0/node/internal_binding/worker.ts
Download https://deno.land/std@0.177.0/node/internal_binding/zlib.ts
Download https://deno.land/std@0.177.0/node/internal/crypto/_keys.ts
Download https://deno.land/std@0.177.0/flags/mod.ts
Download https://deno.land/std@0.99.0/_util/os.ts
Download https://deno.land/std@0.99.0/path/_interface.ts
Download https://deno.land/std@0.99.0/path/common.ts
Download https://deno.land/std@0.99.0/path/glob.ts
Download https://deno.land/std@0.99.0/path/posix.ts
Download https://deno.land/std@0.99.0/path/separator.ts
Download https://deno.land/std@0.99.0/path/win32.ts
Download https://deno.land/std@0.177.0/encoding/base64.ts
Download https://deno.land/std@0.177.0/encoding/base64url.ts
Download https://deno.land/std@0.177.0/node/internal_binding/_utils.ts
Download https://deno.land/std@0.177.0/node/internal/util.mjs
Download https://deno.land/std@0.177.0/node/internal/streams/destroy.mjs
Download https://deno.land/std@0.177.0/node/internal/streams/end-of-stream.mjs
Download https://deno.land/std@0.177.0/node/internal/streams/utils.mjs
Download https://deno.land/std@0.177.0/node/string_decoder.ts
Download https://deno.land/std@0.177.0/bytes/index_of_needle.ts
Download https://deno.land/std@0.177.0/node/internal_binding/_node.ts
Download https://deno.land/std@0.177.0/node/_global.d.ts
Download https://deno.land/std@0.177.0/node/internal/net.ts
Download https://deno.land/std@0.177.0/node/internal_binding/ares.ts
Download https://deno.land/std@0.177.0/node/internal_binding/_timingSafeEqual.ts
Download https://deno.land/std@0.177.0/async/mod.ts
Download https://deno.land/std@0.177.0/node/internal_binding/_listen.ts
Download https://deno.land/std@0.177.0/node/internal_binding/connection_wrap.ts
Download https://deno.land/std@0.177.0/streams/write_all.ts
Download https://deno.land/std@0.177.0/types.d.ts
Download https://deno.land/std@0.177.0/node/internal_binding/handle_wrap.ts
Download https://deno.land/std@0.177.0/node/internal/crypto/constants.ts
Download https://deno.land/std@0.99.0/_util/assert.ts
Download https://deno.land/std@0.99.0/path/_constants.ts
Download https://deno.land/std@0.99.0/path/_util.ts
Download https://deno.land/std@0.177.0/node/internal/primordials.mjs
Download https://deno.land/std@0.177.0/node/internal_binding/node_file.ts
Download https://deno.land/std@0.177.0/crypto/timing_safe_equal.ts
Download https://deno.land/std@0.177.0/async/abortable.ts
Download https://deno.land/std@0.177.0/async/deadline.ts
Download https://deno.land/std@0.177.0/async/debounce.ts
Download https://deno.land/std@0.177.0/async/deferred.ts
Download https://deno.land/std@0.177.0/async/delay.ts
Download https://deno.land/std@0.177.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.177.0/async/pool.ts
Download https://deno.land/std@0.177.0/async/retry.ts
Download https://deno.land/std@0.177.0/async/tee.ts
2023/03/21 07:05:08 Sent Header: Host [docker]
2023/03/21 07:05:08 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:08 Send Done
2023/03/21 07:05:08 Recv First Byte
Serving supabase/functions/open-ai
2023/03/21 07:05:08 Sent Header: Host [docker]
2023/03/21 07:05:08 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:08 Sent Header: Content-Length [1094]
2023/03/21 07:05:08 Sent Header: Content-Type [application/json]
2023/03/21 07:05:08 Send Done
2023/03/21 07:05:08 Recv First Byte
Watcher Process started.
Check file:///home/deno/functions/open-ai/index.ts
Listening on http://localhost:8000/
^CStopped serving supabase/functions/open-ai
❯ supabase functions serve --env-file .env --debug
2023/03/21 07:05:23 Sent Header: Host [docker]
2023/03/21 07:05:23 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:23 Send Done
2023/03/21 07:05:23 Recv First Byte
Serving supabase/functions
2023/03/21 07:05:23 Sent Header: Host [docker]
2023/03/21 07:05:23 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:23 Send Done
2023/03/21 07:05:23 Recv First Byte
2023/03/21 07:05:23 Sent Header: Host [docker]
2023/03/21 07:05:23 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:23 Sent Header: Content-Length [306]
2023/03/21 07:05:23 Sent Header: Content-Type [application/json]
2023/03/21 07:05:23 Send Done
2023/03/21 07:05:23 Recv First Byte
2023/03/21 07:05:23 Sent Header: Host [docker]
2023/03/21 07:05:23 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:23 Sent Header: Content-Length [2870]
2023/03/21 07:05:23 Sent Header: Content-Type [application/json]
2023/03/21 07:05:23 Send Done
2023/03/21 07:05:23 Recv First Byte
2023/03/21 07:05:23 Sent Header: Host [docker]
2023/03/21 07:05:23 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:23 Sent Header: Content-Length [0]
2023/03/21 07:05:23 Sent Header: Content-Type [text/plain]
2023/03/21 07:05:23 Send Done
2023/03/21 07:05:23 Recv First Byte
2023/03/21 07:05:23 Sent Header: Host [docker]
2023/03/21 07:05:23 Sent Header: User-Agent [Go-http-client/1.1]
2023/03/21 07:05:23 Send Done
2023/03/21 07:05:23 Recv First Byte
DEBUG edge-runtime is listening on 0.0.0.0:8081
```

**Comment by laktek** [comment] 2023-03-21 23:29
@dancrumb Thanks a lot for recording the video and providing more details of your project. It looks like `edge-runtime` docker container cannot find the functions directory. It's mounted as a volume when `functions serve` command is run.

To further debug the issue, can you do the following steps:

* In your terminal run, `supabase functions serv`
* Open a second terminal window and run `docker ps | grep edge-runtime`
* This should output the details of currently running container. Grab the container ID (the first field of the output. should be something like `d8d34c049d3b`)
* Then run, `docker exec CONTAINER_ID ls /home/deno/functions`
* Do you see your functions in the output?

Also, can you share your OS and Docker version?

**Comment by dancrumb** [comment] 2023-03-22 03:29
Happy to do so.

For the record, here's what `docker ps` showed:

```
CONTAINER ID   IMAGE                                             COMMAND                  CREATED         STATUS                  PORTS                                                                       NAMES
5bb0ccee0397   public.ecr.aws/supabase/edge-runtime:v1.1.1       "edge-runtime start …"   9 seconds ago   Up 8 seconds                                                                                        supabase_deno_relay_supabase
```
Then:
```
❯ docker exec 5bb0ccee0397  ls /home/deno/functions
_shared
import_map.json
open-ai
sapp
sapp_versions
slack-notification-on-app-publish
```

So, yeah, I see my functions.

I also ran this:

```
❯ docker exec 5bb0ccee0397  ls -l /home/deno/functions
total 4
drwxr-xr-x 14 root root 448 Mar 21 21:22 _shared
-rw-r--r--  1 root root 455 Mar 21 21:21 import_map.json
drwxr-xr-x  3 root root  96 Mar 21 21:21 open-ai
drwxr-xr-x  4 root root 128 Mar 21 21:21 sapp
drwxr-xr-x  4 root root 128 Mar 21 21:22 sapp_versions
drwxr-xr-x  3 root root  96 Mar 21 21:21 slack-notification-on-app-publish
```

In case ownership is an issue.

**Comment by laktek** [comment] 2023-03-22 03:36
That looks correct. It's odd it cannot find the functions. 

What's the URL you'd use to access the functions? Is it `http://localhost:54321/functions/v1/open-ai`

**Comment by dancrumb** [comment] 2023-03-22 03:36
When I look at `/proc/1/cmdline`, I see:

```
edge-runtime start --dir /home/deno/functions -p 8081 --import-map /home/deno/functions/import_map.json
```

The import map exists at that location and contains:

```
{
  "imports": {
    "supabase": "https://esm.sh/@supabase/supabase-js@2",
    "axios": "https://esm.sh/v111/axios@0.26.1/index",
    "tsafe": "https://deno.land/x/tsafe@v1.6.0/mod.ts",
    "xhr": "https://deno.land/x/xhr@0.1.0/mod.ts",
    "http/": "https://deno.land/std@0.168.0/http/",
    "openai": "https://esm.sh/openai@3.2.1",
    "unique-names-generator": "https://esm.sh/unique-names-generator@4.7.1",
    "yup": "https://esm.sh/yup@1.0.2"
  }
}
```

**Comment by dancrumb** [comment] 2023-03-22 03:40
OK - so, something has changed, but I think it's a combination of me-error and unexpected behaviour.

I tried a new endpoint from the one I was working with earlier, and now, it seems to kind of load the functions on demand.

When I sent a request to `http://127.0.0.1:54321/functions/v1/sapp`, it showed

```
serving function sapp
Listening on http://localhost:9999/
[INFO]: Received request to Create a new App []
[ERROR]: [AgentRepository]: Received a DB error: JWT expired; code: PGRST301; hint: null []
[ERROR]: null []
```

The Error is expected, since I was using an old JWT...

So... maybe this is all working as designed, but the docs just need to be updated to say that it's not going to tell you that it's serving a specific function until you actually try to access it.

**Comment by dancrumb** [comment] 2023-03-22 03:41
When I send a request to a gibberish endpoint, I get a `502` error with the following body:

```
{
    "message": "An invalid response was received from the upstream server"
}
```

A `404` would seem to be a more appropriate response to me, to be honest, but 🤷

**Comment by laktek** [comment] 2023-03-22 03:42
Ah yeah, that's right! It won't serve all the functions upfront but will serve them on-demand when you make a request.

And yeah, we will update the invalid paths to return 404s.

**Comment by dancrumb** [comment] 2023-03-22 04:07
Thanks! 

From my perspective, I'm in good shape now. I do think a tweak to the docs and the status code will be helpful, but I'm no long blocked.

Cheers

**Comment by laktek** [comment] 2023-03-22 04:13
We will improve the documentation around edge-runtime. It's still in its early stages.

I will close this issue, feel free to report any other issues you'd run into.

**Closed by laktek** 2023-03-22 04:13 UTC
Labels: bug, edge functions

**Comment by mz1979** [comment] 2023-03-25 21:07
Hello, so I was looking at this bug thread because I am running into issues serving functions locally. I believe the global variable "self" does not exist when you serve ALL functions and it defaults to deno thinking window is available. The way to reproduce this issue is simply serving your [functions](https://github.com/supabase/supabase/tree/master/supabase/functions) locally with the serve all command:
- run `supabase functions serve`
- call the clippy-search function
- it will error out with the below error:
`worker thread panicked ReferenceError: window is not defined
    at https://esm.sh/v113/form-data@4.0.0/esnext/form-data.mjs:24:59
    at https://esm.sh/v113/form-data@4.0.0/esnext/form-data.mjs:6:27
    at https://esm.sh/v113/form-data@4.0.0/esnext/form-data.mjs:32:11`

If you serve the clippy-search function as standalone with `supabase functions serve clippy-search` then it won't error out.

**Comment by laktek** [comment] 2023-03-25 21:42
@mz1979 Can you try upgrading your Supabase CLI to the latest version ( 1.45.2+)? We recently posted a fix to solve this issue.

**Comment by mz1979** [comment] 2023-03-26 02:23
> @mz1979 Can you try upgrading your Supabase CLI to the latest version ( 1.45.2+)? We recently posted a fix to solve this issue.

Ok, upgrading the client is part of the solution. I also had to import OpenAI with target=deno in my import map:
`{
    "imports": {
        "openai" : "https://esm.sh/openai@3.2.1?target=deno"
    }
    
}`

Thank you!
