### ISSUE TITLE
Views Stuck "Loading" In Table Editor

### ISSUE THREAD

**Issue by jtkeyva** [supabase/supabase#8265] opened 2022-08-13 04:14 UTC
# Bug report

## Describe the bug

Most of my views aren't showing data in the dashboard anymore and are stuck "Loading".

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to Table Editor
2. Click on a view
3. Stuck "Loading records..."

## Expected behavior

Show a table with the data from the view.

## Screenshots

![image](https://user-images.githubusercontent.com/2954865/184467971-9462fd94-04a0-4f26-aaea-de3bd1c2e1eb.png)

## System information

- OS: macOS
- Browser (if applies) Safari

## Additional context

If I run the view in the SQL editor the table shows up immediately.  Everything was working fine last time I checked a week or 2 ago.

**Comment by Hallidayo** [comment] 2022-08-13 11:49
Hi @jtkeyva - Are you views running today? I noticed their was an outage yesterday on dashboard which could be related.

**Comment by jtkeyva** [comment] 2022-08-13 19:23
> 

Hi @Hallidayo thanks for the info but it's still stuck in Loading

**Comment by Hallidayo** [comment] 2022-08-13 21:39
@jtkeyva - I've just created a test view using the same Countries data provided by Supabase and everything seems to run fine.

Do you get any errors in your console on the browser?

Also you could try dropping the view and then re-creating the view to see if that works.

**Comment by jtkeyva** [comment] 2022-08-14 02:28
@Hallidayo 
I dropped the view and recreated it using the same original name and still broken with "Loading".

I used the EXACT SAME SQL and made a new view with a different name and it works perfectly.

Odd behavior, glad it's not a production view! Let me know if you want me to run any more tests.

**Comment by saltcod** [comment] 2022-08-16 15:01
Hey @jtkeyva! thanks for the report. I tried this a bunch of times locally and wasn't able to reproduce. Looks like things are resolved on your end though? I'll close this issue, but feel free to reply if you continue to experience issues!

**Closed by saltcod** 2022-08-16 15:01 UTC
Labels: bug

**Comment by jtkeyva** [comment] 2022-08-16 23:44
It's sort of resolved, but had to hack a work around with a new name which is far from ideal. Had I had a production app this would be big trouble as it would be pointing to a view name that doesn't work anymore. And can't get to work anymore even after deleting it and making a new view with the same name i want to use.
