### ISSUE TITLE
Self hosted studio always uses localhost:8000

### ISSUE THREAD

**Issue by supermar1010** [supabase/supabase#11892] opened 2023-01-24 12:57 UTC
# Bug report

## Describe the bug

If you self host studio it always tries to use port 8000 regardless of the env variables you set.

[This](https://github.com/supabase/supabase/commit/42cb1e680e1043a804f60577f1e6e2cce30076a7) is the change that was supposed to fix something but also broke it. 
## To Reproduce

1. Self host studio
2. Observer requests in developer tab

## Expected behavior

The values in .env should be used

## System information

- OS: fedora
- docker: every docker image that was built after the mentioned commit

**Comment by supermar1010** [comment] 2023-01-24 14:02
For anyone else having this problem, I "solved" it for now by just building a custom docker image, where I set `NEXT_PUBLIC_SUPABASE_URL` and `NEXT_PUBLIC_SUPABASE_PUBLIC_URL` to the right values. So I essentially hard coded them into my docker image.

For a real solution, one would need to figure out how to pass runtime environment variables to the next.js application, according to the [docs](https://nextjs.org/docs/basic-features/environment-variables). They state that everything to do with env variables happens at build time. So one might need to think about a different approach how to pass data to the studio.

But what I'm unsure about is, how the setting of the ANON_KEY works, as that seems to be evaluated at runtime.

**Comment by dzakyraf** [comment] 2023-01-25 03:40
I got same problem, can you specify how to set those two variables into custom docker images ?

**Comment by supermar1010** [comment] 2023-01-25 09:59
You can rebuild the docker container as described [here](https://github.com/supabase/supabase/blob/master/studio/Dockerfile) (You need to be in the root folder of the repo. I needed to pass the Dockerfile vie `-f studio/Dockerfile`). Then you just set the env variable "NEXT_PUBLIC_SITE_URL" to the one you want to use (I've put it in a gitlab-ci so I just set it there. but you can also put it in the .env file in the studio folder). Then you can use your selfbuild docker image.

**Comment by ruggi99** [comment] 2023-01-25 21:04
Duplicate of #11656 
Fix in progress in #11740

**Closed** 2023-01-26 15:39 UTC
Labels: bug
