### ISSUE TITLE
 Can not build project with V2 Typing.  Next js build shows  "Parsing error: Invalid character" with database.types.ts file.

### ISSUE THREAD

**Issue by roker15** [supabase/supabase#9215] opened 2022-09-28 18:17 UTC
Was experimenting old project with Supabase-V2 Typing.
Unfortunately stuck with Error in database.ts file which is database types generated by CLI tool.

Here is the error produced
```
./lib/database.ts
Error: Parsing error: Invalid character.

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
```

**Comment by soedirgo** [comment] 2022-09-29 07:42
Can you share (anonymized) snippets of where the error occurs? It's difficult to debug with nothing but this info.

**Comment by CreatorX64** [comment] 2022-11-03 09:25
The same error just happened to me. There are no line numbers present in the error message, also no visible errors are shown in the IDE (VS Code) in the `database.types.ts` file. But somehow the build fails due to this file. Here's the full build logs:

```
info  - Loaded env from C:\Users\creat\dev\work\hotelops\.env.local
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin

Failed to compile.

./src/lib/database.types.ts
Error: Parsing error: Invalid character.

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types .
```

**Comment by soedirgo** [comment] 2022-11-03 10:03
I'm suspecting it's something to do with Windows line endings - when you open `database.types.ts` in VS Code, at the bottom right corner, does it show `LF` or `CRLF`?

**Comment by CreatorX64** [comment] 2022-11-03 10:05
It currently says `CRLF`. Should I change it to `LF` & retry building the project?

**Comment by soedirgo** [comment] 2022-11-03 10:17
Nvm, might be unrelated. If you copy your `database.types.ts` to the TS playground, does it complain? Otherwise I'm not sure where to start debugging - I also couldn't find out where the error might be coming from (eslint?).

**Comment by CreatorX64** [comment] 2022-11-03 11:13
Sadly TS playground didn't complain.

Tried to alter my eslint config in different ways, but even the base config that Next.js generates causes this error.

However, **if I delete the eslint configuration file completely, the project builds without this error.**

For reference, this is my current eslint config (which causes the build to fail):

```
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "plugins": ["@typescript-eslint"],
  "extends": ["next/core-web-vitals", "plugin:@typescript-eslint/recommended"],
  "rules": {
    "@typescript-eslint/consistent-type-imports": "warn",
    "@next/next/no-img-element": "off"
  }
}
```

And below are the variations of config options I tried (all failed with the same error):

Variation 1:

```
{
  "extends": "next"
}
```

Variation 2:

```
{
  "extends": "next/core-web-vitals"
}
```

Variation 3:

```
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "plugins": ["@typescript-eslint"],
  "extends": ["plugin:@typescript-eslint/recommended"],
  "rules": {
    "@typescript-eslint/consistent-type-imports": "warn"
  }
}
```

At this point this seems like an issue with eslint rather than the `database.types.ts` file that Supabase generates. Will post an update if I find out the reason for this error.

Thanks a lot for your help @soedirgo 🙏

**Comment by CreatorX64** [comment] 2022-11-03 11:23
Btw this is my templorary fix (for anyone experiencing the same issue): Rather than deleting the whole eslint configuration file, I just added a `.eslintignore` file in my project and entered `database.types.ts` in it. Better than no configuration I guess 😄

**Comment by moha-fl-dev** [comment] 2022-12-10 17:13
i had the same issue. for some reason, if u look at right corner in vs code, it says something like **utf-16....** i coppied the content of **database.types.ts** to a regular ts file and coppied it back to database.types.ts. after that, build was successfull.

**Comment by bgdnvk** [comment] 2023-01-26 18:18
database.types.ts is generated in UTF 16 for some reason, you just need to encode it in UTF-8, if you are using VSC just click on the encoding type and encode again

**Comment by MAXOUXAX** [comment] 2023-01-30 19:55
> database.types.ts is generated in UTF 16 for some reason, you just need to encode it in UTF-8, if you are using VSC just click on the encoding type and encode again
> 
> context: I've had the same issue, using Windows 10

That indeed is the issue

**Comment by abedshaaban** [comment] 2023-02-24 13:05
@roker15 @CreatorX64  the problem is that windows for some reason read the .ts as a media player or something related to media or video. you can check it by going to the file location of the .ts file in file explorer and the icon of the file will be a media/ video player. my solution was to rename the file to .tsx since I was using React.js

hope this helps others.

**Comment by CreatorX64** [comment] 2023-02-25 11:45
@abedshaaban Thanks for the info. But I don't think the issue is related to how Windows reads the file. This seems like an issue with how the linter reads this specific file or how Supabase CLI generates this file. If the issue were with the `.ts` file extension, all files in my `/hooks` folder (which all have a `.ts` extension since they don't contain JSX code) would throw the same error.

**Comment by Hawaii66** [comment] 2023-03-29 19:07
Thanks, the fix with changing the encoding from UTF-16 to UTF-8 fixed it for me now in the latest release. Sadly still a bug

**Comment by gjohnsx** [comment] 2023-08-22 17:45
I had this same error and it was because the supabase cli created the database.types.ts file with utf-16 encoding.

Here was the command I used:
`npx supabase gen types typescript --project-id ${projectId} > lib/database.types.ts`

**Comment by akilesh-io** [comment] 2023-08-24 13:38
In the bottom bar of VSCode, you'll see the label UTF-16. Click it. A popup opens. Click Save with encoding. You can now pick UTF-8 encoding for that file.

https://stackoverflow.com/a/73393981/12800009

**Comment by masa5714** [comment] 2023-11-08 07:41
I have the same problem.
To solve it, I decided to write a process to automatically convert it in the prebuild of package.json.

npm install:
```bash
npm install iconv-lite chardet
```

convertSupabaseSchema.js:

```js
const fs = require("fs/promises");
const path = require("path");
const iconv = require("iconv-lite");
const chardet = require("chardet");

const inputFile = path.resolve("./src/components/Types/Supabase/schema.ts");
// Override
const outputFile = path.resolve("./src/components/Types/Supabase/schema.ts");

(async () => {
  const inputData = await fs.readFile(inputFile);

  // Convert to UTF-8 only when the character set is UTF-16 LE
  if (chardet.detect(inputData) === "UTF-16LE") {
    const outputData = iconv.decode(inputData, "utf16-le", "utf-8");
    await fs.writeFile(outputFile, outputData, "utf-8");
  }
})();
```

package.json:

```json
{
  "scripts": {
    "prebuild": "node convertSupabaseSchema.js"
  }
}
```

I am now free of this problem!!

**Comment by GaryAustin1** [comment] 2023-12-06 16:06
Going to close this out as there seems to be a solution.
If more is needed please comment and it can be reopened or start a new issue.

**Closed by GaryAustin1** 2023-12-06 16:06 UTC
Labels: bug
