### ISSUE TITLE
Database error saving new user when using trigger w/ public.users table

### ISSUE THREAD

**Issue by nickradford** [supabase/supabase#563] opened 2021-01-19 02:19 UTC
# Bug report

## Describe the bug

I created a `public.users` table, with id (`uuid`) and email (`varchar`) fields, and set up the trigger as mentioned [here](https://github.com/supabase/supabase/discussions/306#discussioncomment-138602). This results in being unable to create a user through "Authentication > Invite New User", and through a web app using `supabase.auth.signIn({ provider: "google" })`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create new project
2. Add public `users` table with id: uuid, and email: varchar
3. Execute the following SQL
```sql
CREATE OR REPLACE FUNCTION signup_copy_to_users_table()
RETURNS TRIGGER AS $$
  BEGIN
    INSERT INTO public.users (id, email)
    VALUES(new.id, new.email);
    RETURN NEW;
  END;
$$
LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS signup_copy on auth.users;
CREATE TRIGGER signup_copy
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE PROCEDURE signup_copy_to_users_table();
```
4. At this point, you will be unable to invite a user through the Authentication UI

**Comment by nickradford** [comment] 2021-01-20 03:19
I should note that it works fine if I don't include the user's email in this, it only fails in this rather opaque way when trying to add the user's email. Is there a way that I'm not seeing to see errors in Supabase -- something that may help a user debug issues like this?

**Comment by kiwicopple** [comment] 2021-01-20 04:40
Hey @nickradford - is it possible that your users aren't granting access to their emails, so the field is empty? what does your `public.users` table look like? Does it accept NULLs on the email field?

> Is there a way that I'm not seeing to see errors in Supabase

We are working on exposing some of these errors now - hopefully by the end of the month you will see them in the settings page

**Comment by sethburtonhall** [comment] 2021-02-03 19:52
@nickradford did you ever solve this? or do you have any insight?

I am having a similar issue. My user signup auth worked as expected, user signed up, auth.user was created ... then I followed [this example](https://supabase.io/docs/guides/auth#create-a-publicusers-table) in the docs and even tried also [this issue](https://github.com/supabase/supabase/discussions/306) and I am getting the "Error: Database error saving new user" blocking error.

I also see that I have these two stored procedures and I was going to delete them to see if either were causing issue, but no delete option is available. 

![image](https://user-images.githubusercontent.com/1033332/106800922-14990200-662f-11eb-9824-eea216952c46.png)

**Comment by jimmybisenius** [comment] 2021-02-03 23:49
Also having the same issue on fresh tables, been having to manually add users after first-time auth. Would love to see a fix in the near future.

**Comment by kiwicopple** [comment] 2021-02-04 01:27
Hi all - I just tried with a new project and didn't have any errors here. Here were the steps:

1. Create a public.users table:

```sql
create table users (
  id uuid references auth.users not null primary key,
  email text
);
```

2. create a trigger:

```sql
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.users (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;
```

3. Trigger the function on invite:

```sql
-- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
```

4. Invite a user via the UI

![image](https://user-images.githubusercontent.com/10214025/106831486-f7197600-66ca-11eb-89cd-085e9f6d8549.png)

5. See the user with email in the table:

![image](https://user-images.githubusercontent.com/10214025/106831537-0e586380-66cb-11eb-9a83-624e4f5e428f.png)


Let me know if I'm missing anything

**Comment by sethburtonhall** [comment] 2021-02-04 15:26
Thanks. All is well now. I can confirm that a user is created via both the UI and my client sign up form. Thanks @kiwicopple 

I nuked left over procedures with `DROP FUNCTION IF EXISTS handle_new_user cascade;` just to be safe and start from scratch.

**Comment by kiwicopple** [comment] 2021-02-05 01:14
That's great! I'll close this for now but feel free to reopen if there is anything I missed 👍

**Closed by kiwicopple** 2021-02-05 01:14 UTC
Labels: bug

**Comment by nickradford** [comment] 2021-02-10 01:31
Hey, sorry for the delay here - it seems as though I can't repro what I was experiencing before, and your post 2 comments up works perfectly for me. Sorry if this was a superfluous issue and I was just doing something incorrectly

**Comment by ethicnology** [comment] 2021-05-14 04:11
Hey, i've had the same issue and [this](https://github.com/supabase/supabase/issues/563#issuecomment-772954907) works for me, thanks.
It seems that the SQL function and trigger only works if the users table is created in pure SQL not via supabase Dashboard.
Should we update the documentation to avoid any other lost adventurers like us ?

**Comment by mike-wax** [comment] 2021-10-01 21:47
If you want to do it on insert or update:

```
create table users (
  id uuid references auth.users not null primary key,
  email text
);

create or replace function public.handle_new_user() 
returns trigger as $$
begin
  INSERT INTO public.users (id, email)
  values (new.id, new.email)
  ON CONFLICT (id) 
  DO 
    UPDATE SET email = new.email;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after update or insert on auth.users
  for each row execute procedure public.handle_new_user()
```

**Comment by selique** [comment] 2021-10-16 19:23
> Hi all - I just tried with a new project and didn't have any errors here. Here were the steps:
> 
> 1. Create a public.users table:
> 
> ```sql
> create table users (
>   id uuid references auth.users not null primary key,
>   email text
> );
> ```
> 
> 1. create a trigger:
> 
> ```sql
> create or replace function public.handle_new_user() 
> returns trigger as $$
> begin
>   insert into public.users (id, email)
>   values (new.id, new.email);
>   return new;
> end;
> $$ language plpgsql security definer;
> ```
> 
> 1. Trigger the function on invite:
> 
> ```sql
> -- trigger the function every time a user is created
> create trigger on_auth_user_created
>   after insert on auth.users
>   for each row execute procedure public.handle_new_user();
> ```
> 
> 1. Invite a user via the UI
> 
> ![image](https://user-images.githubusercontent.com/10214025/106831486-f7197600-66ca-11eb-89cd-085e9f6d8549.png)
> 
> 1. See the user with email in the table:
> 
> ![image](https://user-images.githubusercontent.com/10214025/106831537-0e586380-66cb-11eb-9a83-624e4f5e428f.png)
> 
> Let me know if I'm missing anything

won't working i try create same exemple

**Comment by mike-wax** [comment] 2021-11-15 13:15
And to "backfill" you can just "touch" all the records with a (hopefully) meaningless `update`

```
update auth.users
set role = 'authenticated'
```

**Comment by AminHero** [comment] 2021-11-22 17:07
Unfortunately, I'm still having this issue. I dropped all my functions and triggers and recreated @mike-wax solution. Afterwards I received the data error while saving new user again...

**Comment by mike-wax** [comment] 2021-11-22 20:02
@AminHero did you see [this](https://github.com/supabase/supabase/issues/563#issuecomment-840994087) comment? Did you create the table thru Supabase?

**Comment by AminHero** [comment] 2021-11-22 22:01
> @AminHero did you see [this](https://github.com/supabase/supabase/issues/563#issuecomment-840994087) comment? Did you create the table thru Supabase?

Thanks for your reply! Unfortunately I didn't create the users table via pure SQL - works now.

**Comment by fergusmeiklejohn** [comment] 2022-04-11 06:47
I'm using Prisma so I can't create a public.users table via SQL. This is still a bug and this issue shouldn't be closed.

**Comment by phillipphoenix** [comment] 2022-04-12 17:17
I had this problem, but it was solved by not using a capital starting letter in my table name.
I used `Profile` as my table name, but after switching to `profile` it suddenly worked.

And if you're using Prisma, then you can omit creating a reference between the profile and the auth user.

**Comment by fergusmeiklejohn** [comment] 2022-04-13 01:49
> I had this problem, but it was solved by not using a capital starting letter in my table name. I used `Profile` as my table name, but after switching to `profile` it suddenly worked.
> 
Yeah I always try to remember to `@@map(lower_case_name)`

> And if you're using Prisma, then you can omit creating a reference between the profile and the auth user.
This is a drawback to using Prisma with Supabase :-( We can't establish a FK relation between (eg) `public.user_profiles` and `auth.users`

**Comment by highRisk1** [comment] 2022-04-28 16:22
> Hi all - I just tried with a new project and didn't have any errors here. Here were the steps:
> 
>     1. Create a public.users table:
> 
> 
> ```sql
> create table users (
>   id uuid references auth.users not null primary key,
>   email text
> );
> ```
> 
>     2. create a trigger:
> 
> 
> ```sql
> create or replace function public.handle_new_user() 
> returns trigger as $$
> begin
>   insert into public.users (id, email)
>   values (new.id, new.email);
>   return new;
> end;
> $$ language plpgsql security definer;
> ```
> 
>     3. Trigger the function on invite:
> 
> 
> ```sql
> -- trigger the function every time a user is created
> create trigger on_auth_user_created
>   after insert on auth.users
>   for each row execute procedure public.handle_new_user();
> ```
> 
>     4. Invite a user via the UI
> 
> 
> ![image](https://user-images.githubusercontent.com/10214025/106831486-f7197600-66ca-11eb-89cd-085e9f6d8549.png)
> 
>     5. See the user with email in the table:
> 
> 
> ![image](https://user-images.githubusercontent.com/10214025/106831537-0e586380-66cb-11eb-9a83-624e4f5e428f.png)
> 
> Let me know if I'm missing anything

it worked for me too, after making table from sql editor error was not there

**Comment by zephaniahong** [comment] 2022-10-26 09:40
@fergusmeiklejohn Hi! May I know how you added a row to auth.users by yourself?

**Comment by fergusmeiklejohn** [comment] 2022-10-28 08:52
> 

I use Datagrip to inspect and mutate databases. The auth table is not in the public schema but you can load the Auth schema and manipulate the Auth table like any other table.

**Comment by fergusmeiklejohn** [comment] 2022-10-28 08:53
@zephaniahong I use Datagrip to inspect and mutate databases. The auth table is not in the public schema but you can load the Auth schema and manipulate the Auth table like any other table.

**Comment by moussa32** [comment] 2022-11-17 21:11
> Hi all - I just tried with a new project and didn't have any errors here. Here were the steps:
> 
> 1. Create a public.users table:
> 
> ```sql
> create table users (
>   id uuid references auth.users not null primary key,
>   email text
> );
> ```
> 
> 2. create a trigger:
> 
> ```sql
> create or replace function public.handle_new_user() 
> returns trigger as $$
> begin
>   insert into public.users (id, email)
>   values (new.id, new.email);
>   return new;
> end;
> $$ language plpgsql security definer;
> ```
> 
> 3. Trigger the function on invite:
> 
> ```sql
> -- trigger the function every time a user is created
> create trigger on_auth_user_created
>   after insert on auth.users
>   for each row execute procedure public.handle_new_user();
> ```
> 
> 4. Invite a user via the UI
> 
> ![image](https://user-images.githubusercontent.com/10214025/106831486-f7197600-66ca-11eb-89cd-085e9f6d8549.png)
> 
> 5. See the user with email in the table:
> 
> ![image](https://user-images.githubusercontent.com/10214025/106831537-0e586380-66cb-11eb-9a83-624e4f5e428f.png)
> 
> Let me know if I'm missing anything

I am getting error Failed to run sql query: trigger "on_auth_user_created" for relation "users" already exists while I tried to do the third step

**Comment by ethanfox** [comment] 2022-12-01 23:23
I followed @kiwicopple  steps and am still getting the error. Is there another way to save user data to a profile database without a trigger? How are we supposed to create functioning apps if the only thing we can reference from the users are an email address and maybe phone number?

**Comment by TradeUpCards** [comment] 2023-01-30 05:49
This is happening to me. I've gone and recreated the table, function, and trigger with SQL code but still getting the error

error_description=Database+error+saving+new+user

Also, if I'm not signed into twitter w/ the account that created the OAuth keys, it gives a diff error about not being able to retrieve the email.  Seems twitter auth only works for the account that created it.

**Comment by TradeUpCards** [comment] 2023-01-30 06:19
I figured out my issue. I wasn't setting one of the values I was inserting into the table in the function.

**Comment by swoppy** [comment] 2023-04-30 11:34
@moussa32 it is because it was already created before?

**Comment by dominic-schmid** [comment] 2023-06-27 14:40
> > I had this problem, but it was solved by not using a capital starting letter in my table name. I used `Profile` as my table name, but after switching to `profile` it suddenly worked.
> 
> Yeah I always try to remember to `@@map(lower_case_name)`
> 
> > And if you're using Prisma, then you can omit creating a reference between the profile and the auth user.
> > This is a drawback to using Prisma with Supabase :-( We can't establish a FK relation between (eg) `public.user_profiles` and `auth.users`

Renaming my `public.User` to `public.user` did the trick for me. How is this intended behavior?

**Comment by suroorwijdan** [comment] 2023-09-09 08:35
> Hey, i've had the same issue and [this](https://github.com/supabase/supabase/issues/563#issuecomment-772954907) works for me, thanks. It seems that the SQL function and trigger only works if the users table is created in pure SQL not via supabase Dashboard. Should we update the documentation to avoid any other lost adventurers like us ?

This issue still persists. Creating directly through SQL works.

**Comment by Xananax** [comment] 2023-10-31 21:01
I am not managing to fix this, on a local supabase install (deployed as described [in the docs](https://supabase.com/docs/guides/cli/local-development)).

I also use Prisma. I did not change my table names to use lowercase (because I am inheriting this project, and I do not want to refactor the names).

However, by setting the table name between quotes, creating a user works exactly once, then does not anymore. 
```sql
CREATE OR REPLACE FUNCTION public.create_profile_for_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public."Profile" (id, email)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$$
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
    EXECUTE FUNCTION public.create_profile_for_user();
```

If I use this, I can create one user. Then, I get again:

![image](https://github.com/supabase/supabase/assets/836082/7d5a71bc-f7c0-45ca-a528-fccdd73189d8)

However, creating a user through pgsql works:

![image](https://github.com/supabase/supabase/assets/836082/0dda745b-138d-4ffe-8fda-375393b54bfd)

The trigger works, and my `Profile` table is suitably updated:
![image](https://github.com/supabase/supabase/assets/836082/da8646ca-0417-4a81-a716-a730ea9fa344)

----

Other oddities that may warrant a separate bug report but may be related:

I cannot save SQL queries, I get: 
![image](https://github.com/supabase/supabase/assets/836082/c6c5ec45-570b-4c0d-8ce5-6c1db0d9816b)


I also cannot consult logs, I get:

![image](https://github.com/supabase/supabase/assets/836082/e971acf3-0ae3-443e-b77c-9738454a235a)

**Comment by Xananax** [comment] 2023-10-31 21:13
It seems @RilDev's recommendation works!

Leaving this here in case it helps anyone else:

```sql
CREATE OR REPLACE FUNCTION auth.create_profile_for_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public."Profile" (id, email)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$$
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
    EXECUTE FUNCTION auth.create_profile_for_user();

CREATE OR REPLACE FUNCTION auth.update_profile_for_user()
RETURNS trigger AS $$
BEGIN
  UPDATE public."Profile"
  SET email = new.email
  WHERE id = new.id::text;
  RETURN NEW;
END;
$$
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
;

CREATE OR REPLACE TRIGGER on_auth_user_updated
  AFTER UPDATE ON auth.users
  FOR EACH ROW
    EXECUTE FUNCTION auth.update_profile_for_user();
```

**Comment by Crayon-ShinChan** [comment] 2023-11-26 09:10
for me, I fixed it with two step:
1. delete table, create table by sql
2. specify the table `profile` is from public, which means I have to use `public.profile` (add `public` before table name)

here is my code

```sql
CREATE OR REPLACE FUNCTION public.insert_user_profile()
RETURNS TRIGGER AS $$
BEGIN
    -- Check if the provider in raw_app_meta_data is "Email"
    IF NEW.raw_app_meta_data->>'provider' = 'email' THEN
        INSERT INTO public.profile (user_id, email, created_at, first_name, last_name)
        VALUES (NEW.id, NEW.email, NEW.created_at, NEW.raw_user_meta_data->>'first_name', NEW.raw_user_meta_data->>'last_name');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql security definer;
```

**Comment by SnowmanlooksCool** [comment] 2024-06-18 08:55
> Hi all - I just tried with a new project and didn't have any errors here. Here were the steps:
> 
> 1. Create a public.users table:
> 
> ```sql
> create table users (
>   id uuid references auth.users not null primary key,
>   email text
> );
> ```
> 
> 2. create a trigger:
> 
> ```sql
> create or replace function public.handle_new_user() 
> returns trigger as $$
> begin
>   insert into public.users (id, email)
>   values (new.id, new.email);
>   return new;
> end;
> $$ language plpgsql security definer;
> ```
> 
> 3. Trigger the function on invite:
> 
> ```sql
> -- trigger the function every time a user is created
> create trigger on_auth_user_created
>   after insert on auth.users
>   for each row execute procedure public.handle_new_user();
> ```
> 
> 4. Invite a user via the UI
> 
> ![image](https://user-images.githubusercontent.com/10214025/106831486-f7197600-66ca-11eb-89cd-085e9f6d8549.png)
> 
> 5. See the user with email in the table:
> 
> ![image](https://user-images.githubusercontent.com/10214025/106831537-0e586380-66cb-11eb-9a83-624e4f5e428f.png)
> 
> Let me know if I'm missing anything

helps me alot

**Comment by aleksa-codes** [comment] 2024-07-03 18:15
I am getting this right now using Drizzle to create tables and after I added a trigger to update `public.profiles` table when a row into `auth.users` is inserted.

**Comment by aleksa-codes** [comment] 2024-07-03 18:39
I am getting this right now using Drizzle to create tables and after I added a trigger to update `public.profiles` table when a row into `auth.users` is inserted, works perfectly fine with github and google signin/login but not with email signup:

signup function:
```javascript
    const supabase = createSupabaseClient();
    const { data, error } = await supabase.auth.signUp({
      email: formData.email,
      password: formData.password,
      options: {
        data: {
          name: formData.name,
        },
        emailRedirectTo: getURL(),
      },
    });
```
schema.ts
```javascript
const authSchema = pgSchema('auth');

export const users = authSchema.table('users', {
  id: uuid('id').primaryKey().notNull(),
});

export const profiles = pgTable('profiles', {
  id: uuid('id')
    .primaryKey()
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  username: text('username').unique().notNull(),
  avatar_url: text('avatar_url').notNull(),
  created_at: timestamp('created_at', { mode: 'date', withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp('updated_at', { mode: 'date', withTimezone: true }).notNull().defaultNow(),
});
```

function and trigger:
```sql
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
  ```

**Comment by iDevBrandon** [comment] 2025-03-29 10:05
I restarted by deleting existing functions.

-- Step 1: Create the new function with SECURITY DEFINER
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, display_name, image_url)
    VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data->>'display_name', NEW.raw_user_meta_data->>'image_url');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Step 2: Create the trigger
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
