### ISSUE TITLE
Multiple policies

### ISSUE THREAD

**Issue by richcorbs** [supabase/supabase#180] opened 2020-09-05 03:22 UTC
# Question

Is it possible to have multiple separate policies on a single table?

## Additional context

- I tried to add separate policies for SELECT and for INSERT.
- The "Apply to SELECT' policy was added first and successfully saved.
- Adding the "Apply to INSERT" policy did not save.
- Both policies had policy rule of `(role() = 'authenticated'::text)`.

**Comment by richcorbs** [comment] 2020-09-05 14:40
A few more data points that might help narrow it down.

- Adding an "Apply to DELETE" policy worked.
- Adding an "Apply to UPDATE" policy worked.
- Both policies were added with a policy rule of `auth.role() = 'authenticated'`
- Adding an "Apply to INSERT" policy still does not work.

**Comment by richcorbs** [comment] 2020-09-05 14:42
Also, after clicking "Save" an empty red policy box is displayed in the Policies portion of the UI for a few seconds before disappearing.

**Comment by kiwicopple** [comment] 2020-09-06 02:46
Hey @richcorbs thanks for the detailed issue. We actually have a long-running internal task to overhaul the policies interface. We plan to make it much simpler. 

For the `select` clause, are you adding the `(role() = 'authenticated'::text)` to `POLICY` or to `CHECK`? Can you try adding it to `CHECK` and let me know if that works.  

This is caused by a hidden Postgres error. If you inspect the response in the network tab you might see this:

```
[{"error":"error: only WITH CHECK expression allowed for INSERT"}]
```


This is the way Postgres policies work 

- `CHECK` runs on "new data" 
- `POLICY` runs on "existing data". 

Since inserts don't have "existing data", it won't actually have an effect.


This probably seems confusing so don't worry - in the next UI overhaul we will remove the option of `POLICY` and `CHECK`, and we will handle it in the background.

Let me know if the problem is still happening after switching to `CHECK`! If not, I'll leave you to close this

**Comment by richcorbs** [comment] 2020-09-06 03:59
Adding the rule to the "Check" instead of to the "Policy" worked just like you suggested would. Thanks for the response!

Do you know a good resource for learning the ins and outs of Postgres? I had no idea that policies and checks worked that way. I looked at Udemy courses the other day and nothing jumped out to me.

An updated policies interface sounds great.

Also, I want to figure out how to use data from other tables in my policy/check rules. Like:

- `allow this if the current user's organization id matches the organization id of the record being operated on`
- `allow this if the current user's id matches the user id of the record being operated on`
- `allow this if the current user's role is 'admin'`

Thanks again for the response.

**Comment by kiwicopple** [comment] 2020-09-06 04:20
> Do you know a good resource for learning the ins and outs of Postgres?

Once you get your head around the format of the Postgres docs, it's an amazing resource: https://www.postgresql.org/docs/current/sql-createpolicy.html

Supabase will do a lot of work here to make Postgres more approachable. It's not too difficult to understand, but the concepts can be a bit foreign (Row Level Security in particular)

> how to use data from other tables in my policy/check rules

No probs! This is where policies really shine. Just imagine that a policy attaches a `where` clause to every statement. For example:

"allow this if the current user's organization id matches the organization id of the record being operated on"

You can do something like this:

```sql
create policy "Read messages if user is a member of the org" 
  on public.messages 
  for select using ( 
    auth.uid() in (
        select user_id from members where members.org_id = messages.org_id
    )
  );
```

(assuming you schema is something like this)

![image](https://user-images.githubusercontent.com/10214025/92318173-08d2f080-f03b-11ea-87e7-fa9bd5af674f.png)

**Comment by tconroy** [comment] 2021-07-11 20:14
Hi @kiwicopple ! Sorry to revive an old thread - I'm running into a similar issue described above, ""allow this if the current user's organization id matches the organization id of the record being operated on".

In my case, I'm trying to say, "Only allow user t select organizations of which they are a member".

I've tried this policy, but I'm getting an error, `Error updating policy: missing FROM-clause entry for table "organization"`:
```
ALTER POLICY "User can only Select organizations where they are member" ON public.organizations USING (
  auth.uid() IN (
    SELECT user_id
    FROM organization_memberships
    WHERE organization_memberships.organization_id = organization.id
  )
);
```

**Comment by kiwicopple** [comment] 2021-07-13 02:39
Hey @tconroy I think this might be caused because you're missing `for select`:

```sql
ALTER POLICY "User can only Select organizations where they are member" 
  on public.organizations 
  for select -- add this
  using ();
```

**Comment by tconroy** [comment] 2021-07-14 02:28
Hi @kiwicopple , thanks for getting back to me. I believe it was correctly a `SELECT` as that is what shows in the Supabase UI, but I did try recreating the policy (explicitly adding `FOR SELECT`), but running into the same issue. No results being returned. 

Not entirely sure how to debug these RLS policies..

**Comment by kiwicopple** [comment] 2021-07-14 08:28
In that case are you certain the correct JWT is being sent in the `Authorization` header @tconroy ? If you grab the JWT that is sent and put it into a [decoder](https://www.jstoolset.com/jwt) you should see the user's ID.

If that's not it, feel free to open a new issue or Discussion (so as not to keep this one running)

**Comment by tconroy** [comment] 2021-07-15 01:49
Sure thing @kiwicopple , I posted a discussion here a few days ago: https://github.com/supabase/supabase/discussions/2337

I am seeing the correct user id under the `payload.sub` property in the decoded JWT. 

Would love any help over in my discussion post. Apologies for reviving an old thread! And thank you for your help 👍

**Comment by kiwicopple** [comment] 2021-07-15 05:42
Just to

**Comment by tconroy** [comment] 2021-08-04 01:27
Hi @kiwicopple  - sorry for the late reply! I didn't see this notification. 

I ran the usage update and received:
```
Success. No rows returned
```

I'm still seeing the same issue, though: Getting `0` results when querying for `organiziations` that a user belongs to via a `organzation_memberships` table.

Appreciate your help, at this point I'm trying to figure out what it is I am doing wrong. If you have any debug tips, would be much appreciated.

**Comment by johnbellone** [comment] 2022-04-13 01:22
I seem to be running into this issue, too.

**Comment by joshenlim** [comment] 2022-05-04 11:07
Hey @tconroy, super late on getting back to this ticket but hopefully it'll be of some use (and to others perhaps)

> I've tried this policy, but I'm getting an error, Error updating policy: missing FROM-clause entry for table "organization":

There's a typo in your policy's USING statement - your table's name is `organizations` but you're doing the check on `organization.id`

> I'm still seeing the same issue, though: Getting 0 results when querying for organiziations that a user belongs to via a organzation_memberships table.

Hmm i'm actually unable to reproduce this unfortunately, here's how I reproduced your environment, maybe you could check if you might be missing any steps

1. Created the tables you mentioned and added some fake data
<img width="967" alt="image" src="https://user-images.githubusercontent.com/19742402/166669496-0c8be9a1-80b7-4164-b3c9-8d5df2ebcfb3.png">

2. Set up the policy on the `organizations` table and enabled RLS on the table
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/19742402/166669603-32375913-9a77-45e1-8ba3-28683c92e181.png">

3. Set up a demo app on codesandbox ([ref](https://codesandbox.io/s/stupefied-khayyam-8myqyd?file=/src/App.js))
I've added the code sandbox as a reference - it may/may not run successfully as I created a demo project just to test it, which I'm planning to remove soon
![image](https://user-images.githubusercontent.com/19742402/166669816-d021d64a-876d-4ac1-8d26-2f8027afa070.png)

4. Create a user via the demo app and also save the user in the `users` table of the `public` schema (under the `full_name` "Amanda")
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/19742402/166669908-0c0c862b-a4f7-4142-893d-6e1d7d414cea.png">
<img width="947" alt="image" src="https://user-images.githubusercontent.com/19742402/166670006-5aab2e8a-0f21-4b08-8112-efeda9039d16.png">

5. Manually added a record in `organization_memberships` to link "Amanda" to "Company A"
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/19742402/166670063-1e1e3607-f128-4a43-9ac1-7f2258004458.png">

6. Check on demo app to do a `select` on the `organizations` table while logged in as "Amanda", in which I correctly only receive 1 result instead of 4
![image](https://user-images.githubusercontent.com/19742402/166670150-1157fb1e-9f63-4f3e-8a53-785135876880.png)

i'll cross-post this in the discussions thread for visibility but I'll go ahead to close this ticket for now - we can continue chatting over there if you're still needing help!

**Closed by joshenlim** 2022-05-04 11:07 UTC
Labels: question

**Comment by rmonnier9** [comment] 2024-01-17 08:35
Hi,

I had the same problem and I've just fixed it.

[joshenlim](https://github.com/joshenlim), I had done everything in the steps you mentionned but I needed to add as well a policy on my organization_memberships table because now RLS is enabled by default.

I hope it will help others.
