### ISSUE TITLE
Default Edge Function breaks with request json call

### ISSUE THREAD

**Issue by jlow2397** [supabase/supabase#14114] opened 2023-05-04 00:55 UTC
# Bug report

## Describe the bug

When creating a new edge function via `supabase functions new <function-name>`, the default code does not run properly because the following line throws a JSON parsing error.

`
const { name } = await req.json()
`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a default function using `supabase functions new <function-name>`
2. Don't modify any code, then deploy the function to supabase project using `supabase functions deploy <function-name>`
3. Call the function using the [documented](https://supabase.com/docs/guides/functions/quickstart) invocation 
`
const { data, error } = await supabase.functions.invoke('function-name', {
  body: { name: 'Functions' },
})
`
4. See error:
```
Log Event Message
SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at packageData (ext:deno_fetch/22_body.js:368:14)
    at consumeBody (ext:deno_fetch/22_body.js:245:12)
    at eventLoopTick (ext:core/01_core.js:165:11)
    at async Server.<anonymous> (file:///src/index.ts:7:23)
    at async Server.#respond (https://deno.land/std@0.168.0/http/server.ts:221:24)
```
## Expected behavior

Following these steps should produce a returned response with `data: { message: "Hello Functions" }`

## System information

- OS: macOS
- Version of supabase-js: 2.20.0
- Version of Node.js: v19.6.0

Thank you!

**Comment by gregnr** [comment] 2023-05-04 16:55
Hey @jlow2397, thanks for reporting. I was able to reproduce this - looks like we need an update to the docs.

The error is caused by CORS. Edge functions leave CORS handling to the developer, so to make a request from the browser you can try something like this:
```ts
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

console.log('Hello from Functions!')

export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  const { name } = await req.json()
  const data = {
    message: `Hello ${name}!`,
  }

  return new Response(JSON.stringify(data), {
    headers: {
      ...corsHeaders,
      'Content-Type': 'application/json',
    },
  })
})
```

I've created an issue to track the docs update:
https://github.com/supabase/supabase/issues/14135

Let me know if this solves this for you.

**Comment by jlow2397** [comment] 2023-05-04 17:20
Hi Greg! Thank you that solved it for me.

When debugging earlier, I was passing similar CORS headers to the final Response returned, but adding them also to the first Response fixes the JSON parsing.

Thanks again for your quick help!

**Comment by gregnr** [comment] 2023-05-04 17:23
Great to hear it - yes the first response at the top is necessary since CORS will send a separate `OPTIONS` request prior to the actual request.

Closing this now and we'll track the docs update at #14135.

**Closed by gregnr** 2023-05-04 17:23 UTC
Labels: bug, edge functions

**Comment by danieldavies99** [comment] 2025-05-17 12:22
FYI the docs are still out of date regarding this, if following the edge function getting started guide you will not actually be able to call the function correctly. https://supabase.com/docs/guides/functions/local-quickstart
