### ISSUE TITLE
Failed to run sql query: invalid input syntax for type uuid: ""

### ISSUE THREAD

**Issue by alexauvray** [supabase/supabase#7452] opened 2022-06-27 07:00 UTC
This issue was marked as fixed, but it's not. I get it while using the UI on the basic plan of Supabase, exactly when I try to "view data" of a foreign key inside the "insert row" modal.

_Originally posted by @joshenlim in https://github.com/supabase/supabase/issues/6971#issuecomment-1136711818_

**Comment by alexauvray** [comment] 2022-06-27 07:01
<img width="656" alt="image" src="https://user-images.githubusercontent.com/28756458/175878869-76042eac-cc61-485e-8621-9f3214220672.png">

**Comment by joshenlim** [comment] 2022-06-30 06:05
hey there @alexauvray could you attach a screen recording of the replication of this issue on your end? i'm not able to reproduce it

**Comment by GaryAustin1** [comment] 2022-06-30 13:20
This occurs every time in the “add new row” side panel if you click on a foreign key column.  
![B17AFE65-73E8-4380-8D0E-19C6687A0833](https://user-images.githubusercontent.com/54564956/176687408-855ebaa9-0639-40ac-b738-84f2fe6b3519.jpeg)

**Comment by parker-sherrill** [comment] 2022-06-30 18:00
I am having the same exact issue when inserting data into Tables! 

Is this just a Supabase problem? Was working fine for me yesterday:(

![Screen Shot 2022-06-30 at 1 59 55 PM](https://user-images.githubusercontent.com/106558204/176746095-8ebf501a-ce9f-4155-a376-97343fc52acb.png)

**Comment by Perfecto-always** [comment] 2022-07-04 07:59
The error you provided shows that you are not passing uuid(the foregin key) from the client side. Try providing a valid uuid that exists in the table.

Suppose this is your main table: (e.g.: `user`)
![image](https://user-images.githubusercontent.com/74700079/177108267-f7dfa6e5-64c5-4aab-9d8f-12ed907fcbc9.png)

and this is the table that you have created foregin key: (e.g.: `product`)
![image](https://user-images.githubusercontent.com/74700079/177108457-e6244829-22ce-4540-a7c8-20d189b6c268.png)

Now if you add the key from the first screenshot in the `product` field
![image](https://user-images.githubusercontent.com/74700079/177108732-593cf865-5af9-4bb4-93a2-6c160e096b1c.png)
and click on `View Data` you can see the table details it is referring
![image](https://user-images.githubusercontent.com/74700079/177108909-89286dba-b81c-417d-afb4-8b1ef36449e5.png)

and if you try to pass "" (an empty string or null data) you will see the following error

![image](https://user-images.githubusercontent.com/74700079/177109360-0c24c2c7-0b90-4496-900f-48f83b4bf57e.png)

**Comment by ARMATAV** [comment] 2022-07-15 02:53
It's because the `default` on a foreign-keyed `uuid` column is set to an empty string when you declare it in the UI and subsequently link it to another table's column that is of type `uuid` - bugged in Supabase production as well, requires you to manually fire off the `CREATE TABLE` in SQL with associated foreign key references.

**Comment by joshenlim** [comment] 2022-09-27 05:05
hey everyone - @Perfecto-always is right here, based on the screenshots it's mainly cause the value for that particular field (which is of type uuid) is not a valid uuid, hence why those errors that you guys are seeing.

I'm going to add a small client side validation to only enable that "View data" button if the field has been filled which should alleviate this issue. But I'm guessing there's no other issue here then? Please do let me know anytime if I've missed out any other details here, but I'll close this issue once that fix gets merged in 🙏

**Closed** 2022-09-27 07:02 UTC
Labels: bug, dashboard
