### ISSUE TITLE
Bug Report: Email Rate Limit Setting Reverts to 3 When Set to 30 in Supabase Studio

### ISSUE THREAD

**Issue by gottu91-code** [supabase/supabase#20042] opened 2023-12-28 07:39 UTC
# Bug report

## Describe the bug

When setting the email rate limit to 30 in Supabase Studio, the value automatically reverts to 3 upon refreshing the page. This seems to occur specifically when the limit is set to 30, as other numerical values do not exhibit this behavior.

## To Reproduce

1. Go to the email settings in Supabase Studio.
2. Set the rate limit for sending emails to 30.
3. Refresh the page or navigate away and then return to the email settings page.
4. Notice that the rate limit setting has reverted to 3.

## Expected behavior

The expected behavior is for the email rate limit setting to remain as configured (30 in this case), even after refreshing the page or navigating away and returning.

## Screenshots

![スクリーンショット 2023-12-28 16 22 44](https://github.com/supabase/supabase/assets/86899640/f37cd3e4-2d2a-4296-b5d6-3f5f9f28869f)

## System information

- OS: macOS
- Browser: chrome
- Version of Supabase CLI:  1.115.5
- Version of supabase-js: 2.39.0
- Version of Node.js: 18.16.0

**Comment by Hallidayo** [comment] 2024-01-02 21:04
Hi @gottu91-code - Just tried this now and it seems okay, could you try your end? It may have been a temporary bug.

**Comment by gottu91-code** [comment] 2024-01-04 09:41
Hi @Hallidayo 

Thank you for getting back to me. I've retested the issue in my environment, and unfortunately, the same phenomenon is still occurring. While setting the value to something other than 30 works fine for operational purposes, I'm perplexed by this strange behavior.

Any further insights or suggestions would be greatly appreciated.

https://github.com/supabase/supabase/assets/86899640/35c5daf3-fa59-4118-a681-b2ad7b85d72f

**Comment by zeeshanbhati** [comment] 2024-01-11 22:07
I am trying to fix this bug but the problem is that I am not able to find the backend code that handles this request,the closest i have gone is that there is a service called `true` i, I checked the default values for these parameters and it's set to 30, surprisingly the value of SMS Rate Limit is also 30 but that is just working fine. 

@Hallidayo  can you tell where is the controller for the following endpoint ?

`/auth/{ref}/config`

![image](https://github.com/supabase/supabase/assets/151070488/b572ffe4-da7f-4f16-94c8-4e5e83bf6be2)

**Comment by encima** [comment] 2024-01-15 10:13
Can repro this, values other than 30 work as expected (35 stays as 35, 40 stays as 40 etc).
Config payload sends this as 3 when saving so it is a frontend issue ([here](https://github.com/supabase/supabase/blob/8e1bfc95828ddf9f5b32884d661e4bdeeefaed34/apps/studio/components/interfaces/Auth/RateLimits/RateLimits.tsx)

**Comment by zeeshanbhati** [comment] 2024-01-15 10:35
@encima Did you check it in the network logs , i tried to check that in network logs and it's sending the correct value 30
<img width="371" alt="Screenshot 2024-01-15 at 4 05 33 PM" src="https://github.com/supabase/supabase/assets/53969232/c420d577-2348-4939-b1c9-39e7ba411411">

**Comment by encima** [comment] 2024-01-15 10:48
@zeeshanbhati sorry, my bad, you are right. Correct value is sent: 
<img width="207" alt="image" src="https://github.com/supabase/supabase/assets/517923/282d914b-f522-45c0-92e9-661158fb373a">
but the response is 3
<img width="218" alt="image" src="https://github.com/supabase/supabase/assets/517923/9f5a9146-dc76-42f3-b601-a1c093587699">
so it is an API issue

**Comment by zeeshanbhati** [comment] 2024-01-15 11:04
@encima Yes , i tried to find the controller of that api , but i was unable to do so. however i figured out that the api is somekind of a platform only api , now i dont know what do they mean when they say platform only api .

**Comment by encima** [comment] 2024-01-15 11:24
@zeeshanbhati The API used there is for the hosted version of Supabase and is not a public repository. This is an issue for our Auth and/or Infra team. I have alerted them to the issue, thanks for reporting!

**Comment by Hallidayo** [comment] 2024-05-18 20:33
Hi all, I've just changed the rate limit to 30 on the dashboard and after refreshing the page the rate limit values does now stay at 30. I'll close this issue but if it does happen again please re-open this issue or create a new issue.

**Closed by Hallidayo** 2024-05-18 20:33 UTC
Labels: bug, auth
