### ISSUE TITLE
Missing `await` in samples cause node app to crash?

### ISSUE THREAD

**Issue by jonlivingstone** [supabase/supabase#26733] opened 2024-05-24 05:30 UTC
# Improve documentation

## Link 

https://github.com/supabase/supabase/blob/master/apps/docs/content/guides/auth/server-side/creating-a-client.mdx
https://github.com/supabase/supabase/blob/master/apps/docs/content/guides/auth/server-side/sveltekit.mdx

## Describe the problem

I had my node web app crash with the error message "Error: Cannot use cookies.set(...) after the response has been generated".

## Describe the improvement

The [sveltekit doc samples](https://kit.svelte.dev/docs/hooks) always show the call to `resolve` needs to be awaited.
However, in the supabase documentation for `hooks.server.ts`, this keyword is not present.

Since I added the `await` keyword before the `resolve`, I did not have a crash from my node webapp.

Suggested change to replace:
```
  return resolve(event, {
    filterSerializedResponseHeaders(name) {
      return name === 'content-range' || name === 'x-supabase-api-version'
    },
  })
  ```
  
 with:
 ```
   return await resolve(event, {
    filterSerializedResponseHeaders(name) {
      return name === 'content-range' || name === 'x-supabase-api-version'
    },
  })
  ```
  
and similar change in other instances.
 
## Additional context

I am a beginner in sveltekit. Apologies for the waste of time if there is no reason for the `await` keyword to be present here.

I'll gladly submit a PR to help if that change sounds relevant.

**Comment by Hallidayo** [comment] 2024-05-27 20:52
Hi @jonlivingstone - Thank you for opening this issue, please feel free to open a PR!  👍

**Comment by kRaviteja7** [comment] 2024-05-28 06:05
check out the pull request add the await . 

return await resolve(event, {
filterSerializedResponseHeaders(name) {
/**
* Supabase libraries use the content-range and x-supabase-api-version
* headers, so we need to tell SvelteKit to pass it through. */ return name === 'content-range' || name === 'x-supabase-api-version' }, })

**Comment by jonlivingstone** [comment] 2024-05-29 01:55
There are a few more occurences I have changed.
I have submitted a PR as suggested.
https://github.com/supabase/supabase/pull/26848

Thank you!

**Comment by Anubhavbaranwal** [comment] 2024-06-04 19:53
@jonlivingstone  can you assign this issue to me?

**Comment by charislam** [comment] 2024-06-04 21:44
Hi @Anubhavbaranwal, thanks for your interest in helping out! Just a warning that we don't believe this to be the cause of the issue (you can see the linked PR above for the discussion). If you want to try reproducing to discover the root cause, you're more than welcome! If you want a simpler first issue, feel free to submit a PR for another issue in the `help wanted` or `good first issue` sections!

**Comment by jonlivingstone** [comment] 2024-06-04 21:55
@Anubhavbaranwal I would suggest to have a minimal repro ready so the owners can root cause and reproduce the problem. Otherwise it won't get merged (and for good reason). I was not successful in doing that.
I thought that was the issue and it is apparently something else. I believe there was something in my code that messed up the page lifecycle and the `await` was only accidentally helping, if anything.

**Comment by Hallidayo** [comment] 2024-07-08 21:05
Hi all, We’re going to close this one due to inactivity. Please feel free to reopen if you’re still having issues here or open a new issue.

**Closed by Hallidayo** 2024-07-08 21:05 UTC
Labels: documentation, needs-analysis
