### ISSUE TITLE
Docker Compose not in Up and Running State 

### ISSUE THREAD

**Issue by mustafamizrak** [supabase/supabase#22017] opened 2024-03-14 08:43 UTC
Cloning master branch as well as the latest release branch and docker compose is not in up and running state.

## To Reproduce
Execution of the following steps resulted in several bug and errors:

```
git clone <repo>
cd docker
cp env.example .env
docker-compose up -d
```
Result: 
```
[+] Running 2/13
 ⠙ Network supabase_default                  Created                                                                                                                                                                                            1.2s 
 ✔ Container supabase-imgproxy               Started                                                                                                                                                                                            0.6s 
 ✘ Container supabase-vector                 Error                                                                                                                                                                                              1.1s 
 ⠙ Container supabase-db                     Created                                                                                                                                                                                            1.1s 
 ⠇ Container supabase-analytics              Created                                                                                                                                                                                            0.9s 
 ⠇ Container supabase-edge-functions         Created                                                                                                                                                                                            0.8s 
 ⠇ Container supabase-rest                   Created                                                                                                                                                                                            0.8s 
 ⠇ Container supabase-kong                   Created                                                                                                                                                                                            0.8s 
 ⠇ Container supabase-meta                   Created                                                                                                                                                                                            0.8s 
 ⠇ Container supabase-auth                   Created                                                                                                                                                                                            0.8s 
 ⠇ Container realtime-dev.supabase-realtime  Created                                                                                                                                                                                            0.8s 
 ⠇ Container supabase-studio                 Created                                                                                                                                                                                            0.8s 
 ⠧ Container supabase-storage                Created 
```

After those:
```
rm -rf volumes
sudo docker compose restart
```

finally with errors:

```
[+] Restarting 12/12
 ✔ Container supabase-imgproxy               Started                                                                                                                                                                                            1.3s 
 ✔ Container supabase-db                     Started                                                                                                                                                                                            0.7s 
 ✔ Container supabase-edge-functions         Started                                                                                                                                                                                            0.8s 
 ✔ Container supabase-analytics              Started                                                                                                                                                                                            0.3s 
 ✔ Container supabase-storage                Started                                                                                                                                                                                            1.2s 
 ✔ Container supabase-meta                   Started                                                                                                                                                                                            1.1s 
 ✔ Container supabase-kong                   Started                                                                                                                                                                                            0.8s 
 ✔ Container supabase-vector                 Started                                                                                                                                                                                            0.4s 
 ✔ Container realtime-dev.supabase-realtime  Started                                                                                                                                                                                            0.4s 
 ✔ Container supabase-studio                 Started                                                                                                                                                                                            1.0s 
 ✔ Container supabase-rest                   Started                                                                                                                                                                                            1.0s 
 ✔ Container supabase-auth                   Started
```

But exceptions and errors

on storage or supabase-storage container:

```
2024-03-14 09:25:23 error: password authentication failed for user "supabase_storage_admin"
2024-03-14 09:25:23     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
2024-03-14 09:25:23     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
2024-03-14 09:25:23     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
2024-03-14 09:25:23     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
2024-03-14 09:25:23     at Socket.emit (node:events:517:28)
2024-03-14 09:25:23     at addChunk (node:internal/streams/readable:368:12)
2024-03-14 09:25:23     at readableAddChunk (node:internal/streams/readable:341:9)
2024-03-14 09:25:23     at Readable.push (node:internal/streams/readable:278:10)
2024-03-14 09:25:23     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
2024-03-14 09:25:23   length: 118,
2024-03-14 09:25:23   severity: 'FATAL',
2024-03-14 09:25:23   code: '28P01',
2024-03-14 09:25:23   detail: undefined,
2024-03-14 09:25:23   hint: undefined,
2024-03-14 09:25:23   position: undefined,
2024-03-14 09:25:23   internalPosition: undefined,
2024-03-14 09:25:23   internalQuery: undefined,
2024-03-14 09:25:23   where: undefined,
2024-03-14 09:25:23   schema: undefined,
2024-03-14 09:25:23   table: undefined,
2024-03-14 09:25:23   column: undefined,
2024-03-14 09:25:23   dataType: undefined,
2024-03-14 09:25:23   constraint: undefined,
2024-03-14 09:25:23   file: 'auth.c',
2024-03-14 09:25:23   line: '326',
2024-03-14 09:25:23   routine: 'auth_failed'
2024-03-14 09:25:23 }
```

on auth or supabase-auth:
```
2024-03-14 09:25:45 {"level":"fatal","msg":"running db migrations: Migrator: problem creating schema migrations: couldn't start a new transaction: could not create new transaction: failed to connect to `host=db user=supabase_auth_admin database=postgres`: failed SASL auth (FATAL: password authentication failed for user \"supabase_auth_admin\" (SQLSTATE 28P01))","time":"2024-03-14T08:25:45Z"}`
```
on rest or supabase-rest:

```
2024-03-14 09:35:51 14/Mar/2024:08:35:51 +0000: {"code":"PGRST000","details":"FATAL:  password authentication failed for user \"authenticator\"\n","hint":null,"message":"Database connection error. Retrying the connection."}
2024-03-14 09:35:51 14/Mar/2024:08:35:51 +0000: {"code":"PGRST000","details":"FATAL:  password authentication failed for user \"authenticator\"\n","hint":null,"message":"Database connection error. Retrying the connection."}
2024-03-14 09:35:51 14/Mar/2024:08:35:51 +0000: FATAL:  password authentication failed for user "authenticator"
```
on kong or supabse-kong:
```
2024-03-14 09:38:50 stack traceback:
2024-03-14 09:38:50     [C]: in function 'error'
2024-03-14 09:38:50     /usr/local/share/lua/5.1/kong/init.lua:553: in function 'init'
2024-03-14 09:38:50     init_by_lua:3: in main chunk
2024-03-14 09:39:50 cat: read error: Is a directory
2024-03-14 09:39:50 2024/03/14 08:39:50 [warn] 1#0: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2024-03-14 09:39:50 nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2024-03-14 09:39:50 2024/03/14 08:39:50 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:553: error parsing declarative config file /home/kong/kong.yml:
2024-03-14 09:39:50 failed parsing declarative configuration: expected an object
2024-03-14 09:39:50 stack traceback:
2024-03-14 09:39:50     [C]: in function 'error'
2024-03-14 09:39:50     /usr/local/share/lua/5.1/kong/init.lua:553: in function 'init'
2024-03-14 09:39:50     init_by_lua:3: in main chunk
2024-03-14 09:39:50 nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:553: error parsing declarative config file /home/kong/kong.yml:
2024-03-14 09:39:50 failed parsing declarative configuration: expected an object
2024-03-14 09:39:50 stack traceback:
2024-03-14 09:39:50     [C]: in function 'error'
2024-03-14 09:39:50     /usr/local/share/lua/5.1/kong/init.lua:553: in function 'init'
2024-03-14 09:39:50     init_by_lua:3: in main chunk
```

and on edge-functions or supabase-edge-functions:

```
2024-03-14 09:39:43 Error: main worker boot error: channel closed
2024-03-14 09:40:43 thread '<unnamed>' panicked at /usr/src/edge-runtime/crates/sb_graph/graph_util.rs:357:52:
2024-03-14 09:40:43 called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
2024-03-14 09:40:43 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-03-14 09:40:43 Error: main worker boot error: channel closed
```

## Expected behavior

Simple `docker-compose up` command results in up and running state.

**Comment by talamaska** [comment] 2024-03-15 15:36
I'm here to confirm that on a fresh installation this fails. I tried to start supabase for the first time after running init, link, db pull and all that,
```
Status: Downloaded newer image for public.ecr.aws/supabase/storage-api:v0.48.2
/app/node_modules/pg-protocol/dist/parser.js:287
        const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^

error: password authentication failed for user "supabase_storage_admin"
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 118,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '326',
  routine: 'auth_failed'
}```

**Comment by RumosZin** [comment] 2024-03-21 06:06
Hi, did you resolve these problems? I have same errors......... please help me!!

**Comment by encima** [comment] 2024-03-22 02:16
1. Please check existing issues before opening
2. Please check for special characters in the password
3. Please post image versions and ensure they are the latest

Closing as there is not enough info to reproduce and cannot repro on the master branch using OSX M1

**Closed by encima** 2024-03-22 02:16 UTC
Labels: bug

**Comment by talamaska** [comment] 2024-03-22 15:52
There is a version that is broken for supabase/storage-api! It's in the top of my comment. 
Status: Downloaded newer image for public.ecr.aws/supabase/storage-api:v0.48.2 which is the latest
Some of the other are not. I'm confused, shouldn't the installation of the cli automatically pull the latest image configuration?

**Comment by talamaska** [comment] 2024-03-22 17:05
Upgraded manually the versions in the .temp folder
looking for the version from here https://gallery.ecr.aws/supabase

gotrue - 2.144.1
postgres - 15.1.1.30
rest - 12.0.2
storage - 0.48.2

Seems the issue is gone and now I'm able to run local supabase

I still think the supabase cli, should be released with a new version every time any of the docker images is update and this list of version should be updated when I run `brew upgrade supabase`

This file is not updated regularly
https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml

**Comment by mustafamizrak** [comment] 2024-03-27 17:49
> 1. Please check existing issues before opening
> 
>     2. Please check for special characters in the password
> 
>     3. Please post image versions and ensure they are the latest
> 
> 
> Closing as there is not enough info to reproduce and cannot repro on the master branch using OSX M1

People do report this issue. Why did you close this without further investigation?

**Comment by mustafamizrak** [comment] 2024-03-27 18:05
@talamaska Just upgraded image versions in this file https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml, still same error.

**Comment by talamaska** [comment] 2024-03-28 17:46
@mustafamizrak it's only postgres-meta updated. which is not exactly exposed in the .temp folder.
I don't see any of other images updated and I'm not sure which image version update that I did, helped.

**Comment by J4gQBqqR** [comment] 2024-03-30 02:16
@encima 
![图片](https://github.com/supabase/supabase/assets/77554817/d54e68a5-9161-46a3-a3f3-66b6c7e63654)
![图片](https://github.com/supabase/supabase/assets/77554817/1b507631-ae13-44ef-a1c8-c851ac43ee46)
And I checked my local drive, vector.yml is actually a folder, not a file.

**Comment by J4gQBqqR** [comment] 2024-03-30 02:17
I am using the latest master branch and latest Arch system: return of git log:

![图片](https://github.com/supabase/supabase/assets/77554817/572f2cd8-96a1-472e-819c-71514fdbf004)

**Comment by RumosZin** [comment] 2024-04-09 01:06
@mustafamizrak  Hi, did you resolve problems? I resolved kong's `init_by_lua:3: in main chunk` error. 

I don't know what's your OS setting. So I'll explain in macOS and linux. 

My problems
- macOS (local) : After `docker compose up -d --build` commands, all containers are running well.
- LInux (dev) : After `docker compose up -d --build` commands, kong:2.8.1 container has an error

```shell
```

**Comment by RumosZin** [comment] 2024-04-09 01:12
@mustafamizrak  Hi, did you resolve problems? I resolved kong's `init_by_lua:3: in main chunk` error. 

I don't know what's your OS setting. So I'll explain in macOS and linux. 

My problems
- macOS (local) : After `docker compose up -d --build` commands, all containers are running well.
- LInux (dev) : After `docker compose up -d --build` commands, kong:2.8.1 container has an error

```shell
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
2024/04/08 07:43:06 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:553: error parsing declarative config file /home/kong/kong.yml:
failed parsing declarative configuration: expected an object
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:553: in function 'init'
	init_by_lua:3: in main chunk
```

In this situation, I checked linux's {path}/volumes/api/kong.yml file. **If this `kong.yml` is not file but directory, remove the volumes/api directory.** Make a `kong.yml` file in local(macOS in my case), and send the file to linux by using `scp` command.

I resolved kong:2.8.1 containers error in this way.

I think there's something wrong with self-hosting supabase containers. I don't know your development environment, but I hope it helps you even if it's small.

**Comment by sanny-io** [comment] 2024-04-22 00:48
@J4gQBqqR I'm getting the same error, although I'm assuming you meant the reverse, cause it's definitely a file for me.

![image](https://github.com/supabase/supabase/assets/3054653/e408ab13-ad22-40c2-b486-99c412323681)

**Comment by mustafamizrak** [comment] 2024-04-29 20:42
@RumosZin Nope, I have not found any solution yet. I do not understand why people close issues without any proper solution.

**Comment by RumosZin** [comment] 2024-04-30 02:28
@mustafamizrak I resolve that error by doing change password. I'll upload tips soon!! (maybe afternoon...!)

**Comment by erdalgunes** [comment] 2024-06-18 13:36
I resolved the issue by changing the kong service in docker_compose.yml to


```yml


kong:
    container_name: supabase-kong
    image: kong:2.8.1
    restart: unless-stopped
    # https://unix.stackexchange.com/a/294837
    entrypoint: >
      bash -c '
      if [ ! -f "/home/kong/temp.yml" ]; then
        echo "Missing /home/kong/temp.yml file, creating a default kong.yml";
        echo "_format_version: \"1.1\"" > /home/kong/kong.yml;
        echo "services:" >> /home/kong/kong.yml;
      else
        eval "echo \"$$(cat ~/temp.yml)\"" > ~/kong.yml;
      fi;
      /docker-entrypoint.sh kong docker-start
      '
    ports:
      - ${KONG_HTTP_PORT}:8000/tcp
      - ${KONG_HTTPS_PORT}:8443/tcp
    depends_on:
      analytics:
        condition: service_healthy
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      # https://github.com/supabase/cli/issues/14
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
    volumes:
      # https://github.com/supabase/supabase/issues/12661
      - ./volumes/api/:/home/kong/temp.yml:ro
```

**Comment by pascalwhoop** [comment] 2025-04-08 17:47
For anyone ending up here, if you just took the `docker-compose.yml` file from the repo and thought you'd get away with it, that's why it doesnt' work. I created my own docker-compose.yml` with the content from the repo instead of cloning (as in the docs) and it then creates various files manually as folders instead of mounting existing ones.

**Comment by appscaptain** [comment] 2025-04-13 08:48
@RumosZin Could be great if you could share :-)
