### ISSUE TITLE
Monaco editor 

### ISSUE THREAD

**Issue by jaynguyens** [supabase/supabase#5945] opened 2022-03-17 10:01 UTC
# Bug report

## Describe the bug

Unable to edit due to the the SQL editor not loading the monaco property.

## To Reproduce

1. Go to the SQL editor
2. The screen only display Loading... text

## Expected behavior

I would expect it would show the editor up when I go to the SQL editor

## Screenshots

![Screenshot 2022-03-17 at 09 58 20](https://user-images.githubusercontent.com/74240381/158784644-74bf7d88-5d30-4ec9-a939-f8027c7db113.png)
## System information

- OS: Mac
- Browser (if applies) firefox

**Comment by kiwicopple** [comment] 2022-03-21 13:28
Interesting, thanks for reporting @jaynguyens . Do you have an extension which is blocking this? I'm also on Mac with Firefox and it's working for me

**Comment by unusec** [comment] 2022-04-13 13:03
the problem is on offline installs, where you cant reach the CDN to download the script, also stripe also tries to load some CDN content as shown in console
![monaco-editor](https://user-images.githubusercontent.com/2709040/163185968-5e0256ee-1959-4ffa-bc61-e8551d051cde.png)

**Comment by kiwicopple** [comment] 2022-10-17 13:23
Thanks for the additional info 🙏 

I'm going to close this one for now - we don't plan to support offline for a while, but definitely something we will consider for the future

**Closed by kiwicopple** 2022-10-17 13:23 UTC
Labels: bug
