### ISSUE TITLE
Updated documentation as requested in issue 18891

### ISSUE THREAD

**Issue by castortech** [supabase/supabase#27113] opened 2024-06-08 19:14 UTC
# Improve documentation

## Link 
https://supabase.com/docs/reference/self-hosting-analytics/introduction#getting-started

## Describe the problem
Comment from January on issue #18891 requested a documentation updated that is still not even acknowledged.

Is the documentation missing? Or is it confusing? Why is it confusing?
Wrong

**Comment by encima** [comment] 2024-06-11 08:14
Closing this issue as it is a duplicate of the linked issue. Please comment in there directly to keep conversations, and issues, focused on a single topic

**Closed by encima** 2024-06-11 08:14 UTC
Labels: documentation

**Comment by castortech** [comment] 2024-06-11 09:08
That issue has been closed and a post-closing comment has been ignored, so directed to the correct section which is documentation.
