### ISSUE TITLE
No way to resend verification email

### ISSUE THREAD

**Issue by rphly** [supabase/supabase#2613] opened 2021-07-28 12:45 UTC
# Bug report

## Describe the bug

Confirmation token expires, so will require a way to resend verification email. (I swear it was there before) but now it has disappeared.

![Screenshot 2021-07-28 at 8 44 53 PM](https://user-images.githubusercontent.com/23185489/127324197-2110d383-f353-4715-a03f-40c304b7765d.png)

**Comment by kiwicopple** [comment] 2021-12-28 11:19
duplicate of https://github.com/supabase/gotrue/issues/312

**Closed by kiwicopple** 2021-12-28 11:19 UTC
Labels: bug
