### ISSUE TITLE
Is it possible to link multiple auth methods to the same user?

### ISSUE THREAD

**Issue by mike-wax** [supabase/supabase#3288] opened 2021-09-22 12:05 UTC
If a user initially authenticates with email, but I want to add Twitter, is that possible? Any examples?

**Comment by mike-wax** [comment] 2021-09-22 12:07
I found this issue https://github.com/supabase/supabase/issues/2556, but it doesn't seem you have control over this unless they have the same email in both and for my case, it's possible it won't be the same email.

**Comment by eMeRiKa13** [comment] 2021-11-04 15:47
Yes it will be great to allow user, to connect other providers to their account (with or with not the same email adress). I think it's currently not possible.

**Comment by kiwicopple** [comment] 2021-12-28 15:32
Duplicate of https://github.com/supabase/gotrue/issues/313

**Closed by kiwicopple** 2021-12-28 15:32 UTC
Labels: enhancement
