### ISSUE TITLE
function slug name not verify on management api create function.

### ISSUE THREAD

**Issue by okxiaoliang4** [supabase/supabase#23754] opened 2024-05-04 02:58 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

function slug name not verify on management api create function.

## To Reproduce

1. using https://supabase.com/docs/reference/api/create-a-function created a function `test_0.0.0_functions_upload`
2. visit https://supabase.com/dashboard/project/{ref}/functions/test_0.0.0_functions_upload/details

## Expected behavior

throw an error when management api call

## Screenshots

<img width="1948" alt="image" src="https://github.com/supabase/supabase/assets/22525904/b5d73931-b213-41e1-b00d-39696229c322">

**Comment by simonha9** [comment] 2024-05-06 19:36
Hi! I can take a look at this, how exactly did you create the function? I tried https://api.supabase.com/v1/projects/gqthcogrgktnakhyrlvi/functions?slug=test_0.0.0_functions_upload as suggested by the docs and this gives me the error you're looking for.

![image](https://github.com/supabase/supabase/assets/45949251/bdde782d-50e9-4d1d-9792-1cdf4d9b613b)

**Comment by okxiaoliang4** [comment] 2024-05-07 02:02
I just call the post api to create this function. Maybe they already fixed.

**Comment by encima** [comment] 2024-05-07 09:36
Closing as the error shown correctly shows the regex required for a function name and cannot reproduce. Please comment if this still occurs and we can reopen

**Closed by encima** 2024-05-07 09:36 UTC
Labels: bug
