### ISSUE TITLE
Geometry column - invalid representation

### ISSUE THREAD

**Issue by lfreiredev** [supabase/supabase#3788] opened 2021-11-04 16:51 UTC
# Bug report

## Describe the bug

When creating a geometry data type column, its representation is looking odd.
It shows a random capital letter string such as: _0101000020E61000002C64AE0CAA0129409F1CAACE0FF34440_

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table
2. Add a geometry data type column with: `SELECT AddGeometryColumn ('','geometries','geom',4326,'POINT',2);`
3. Insert records to the table with the geometry column as `ST_SetSRID(ST_MakePoint(lng, lat), 4326)`
4. See the table editor in order to find the column representation.

## Screenshots

It shows like this: 
![image](https://user-images.githubusercontent.com/54550772/140382957-13ff4484-8b84-456a-8679-39bc5b74acc1.png)

But should show something like:
![image](https://user-images.githubusercontent.com/54550772/140383007-5c060ea6-a915-4487-993a-7ca955ce6c13.png)

## System information

- OS: Windows 10
- Browser: Chrome

## Additional context

Followed [this](https://geoexamples.com/svelte/2021/07/18/svelte-supabase-maps.html/) tutorial to get the column as I wanted.

**Comment by steve-chavez** [comment] 2021-11-04 17:57
You can use `SELECT st_asgeojson(location) * FROM tbl` to get the representation you want.

https://postgis.net/docs/ST_AsGeoJSON.html

>  invalid representation

Not really invalid, it's the `geometry` type default representation, which has to be converted to other formats to be human-readable.

http://postgis.net/workshops/postgis-intro/geometries.html#geometry-input-and-output

**Comment by kiwicopple** [comment] 2021-11-05 04:03
I'll look into this one - it looks like it was previously showing in human-readable format (according to this blog post: https://geoexamples.com/svelte/2021/07/18/svelte-supabase-maps.html/)

I'm interested to know what's changed here. It's not really a bug, but I think the DX could be improved if we want to make PostGIS a first-class citizen

**Comment by steve-chavez** [comment] 2021-11-05 05:16
> I'm interested to know what's changed here.

@kiwicopple It's related to moving the Table Editor from PostgREST to [postgres-meta](https://github.com/supabase/postgres-meta).

PostgREST uses `json_agg`, which for PostGIS 3, it automatically converts the geometry to json through `st_asgeojson`.

**Comment by kiwicopple** [comment] 2021-11-05 06:13
Aha, thanks Steve! Perhaps we can make the grid do some enrichment for PostGIS 🤔

**Comment by joshenlim** [comment] 2022-05-11 09:31
just to follow up here: i tried reproducing this bug again and i'm getting these from /query
![image](https://user-images.githubusercontent.com/19742402/167817959-217ab5fc-77ec-4a31-9277-5fd89829b583.png)

@soedirgo just to check if you might be familiar with this and what's happening in pg-meta?

**Comment by soedirgo** [comment] 2022-05-11 10:47
I think it's as Steve mentioned above, it's the default presentation for `geometry` (can be confirmed with `select st_point(1,1)::geometry` in psql).

Making it more user-friendly from the dashboard side might be a lot of work (e.g. need to parse the format) but as a user I would just add a generated column like so:
```sql
alter table geometries add column geom_display text generated always as (st_asgeojson(geom)) stored;
```

**Comment by hf** [comment] 2023-01-21 14:59
One possible fix on the dashboard is to modify the select to add virtual columns for all `geometry` columns. For example:

```sql
select *, st_asgeojson(location) as __v_location_geojson from table;
```

then show the value for `__v_location_geojson` for the `location` column instead of the original one (or show it in a tooltip, etc).

**Comment by hf** [comment] 2023-01-21 15:29
I believe that PR will likely fix the issue. I'll close the issue, but if the PR is not sufficient will re-open it.

**Closed by hf** 2023-01-21 15:29 UTC
Labels: enhancement
