### ISSUE TITLE
Unable to GET data points that contain a plus character "+"

### ISSUE THREAD

**Issue by williamgcarson** [supabase/supabase#28574] opened 2024-08-12 23:54 UTC
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have a database of entries I call Member Activities:
https://pyibwzgiyaocszruahfy.supabase.co/functions/v1/member-activity

The data has an attribute called memberuser in which I store the email address of the user. I'm attempting to display this data in my app on Bubble.io using a GET. The query for the GET is basically just asking for all Member Activities whose memberuser (email) is equal to the current user's email address.

This is a test database and some entries have a memberuser of william.carson@prentus.com and some have a memberuser of william.carson+demo@prentus.com

I am unsuccessful in getting the activities with the "+demo" version to come through in my GET (shown in screenshot where body yields 0).

## To Reproduce

Whenever I'm logged in on the +demo account, the Member Activities that have a memberuser of william.carson+demo@prentus.com don't come through. No Member Activities come through.

## Expected behavior

I'm expecting to see the corresponding activities.

## Screenshots

Pic of a Member Activity entry in Supabase
<img width="1299" alt="Screenshot 2024-08-12 at 9 54 59 AM" src="https://github.com/user-attachments/assets/f86a7e60-8df1-4106-a98d-0bd71d791111">

Pic of the Bubble.io debugger showing my GET URL and query and that it's showing body (0)
<img width="387" alt="Screenshot 2024-08-12 at 9 54 02 AM" src="https://github.com/user-attachments/assets/e137619c-d4c1-4b9e-9860-1d07230eb25f">

## Additional context

I can manually edit the memberuser field in Supabase from the +demo email to the william.carson@prentus.com email and it will appear in the GET when I'm logged in under that email address. Just not when I have the + in the email/memberuser.

**Comment by encima** [comment] 2024-08-13 06:38
Hi there,
thanks for opening. We cannot see the function you provide (or details about the project at all) and this is by design.

As you are providing a special character in the URL, you will need to [URL encode it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

I will close this but let us know if that does not work and we will reopen

**Closed by encima** 2024-08-13 06:38 UTC
Labels: bug, external-issue, to-triage
