### ISSUE TITLE
Auth Rate Limits page shows outdated value for email

### ISSUE THREAD

**Issue by tigger0jk** [supabase/supabase#26623] opened 2024-05-21 18:25 UTC
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On https://supabase.com/dashboard/project/__project_id__/auth/rate-limits for a recently created free account, the "Rate limit for sending emails" shows 30 (uneditable because no Custom SMTP provider is set).

However, the actual value is now 3, as per the documentation. https://supabase.com/docs/guides/platform/going-into-prod#auth-rate-limits

## To Reproduce

1. Have no Custom SMTP provider set
2. Go to Auth -> Rate Limits
3. Observe the incorrect rate limit of 30 for sending emails

## Expected behavior

The correct rate limit of 3 should be shown.

I was confused as to how I could possibly be hitting the rate limits as stated on the screen, this value being wrong caused me to suspect other problems until I found the correct documentation.

## Screenshots

<img width="894" alt="image" src="https://github.com/supabase/supabase/assets/5959234/99d1c169-bad5-448b-8fe6-956ed56d1ea7">

## System information

- OS: macOS
- Browser: Chrome

**Comment by Hallidayo** [comment] 2024-06-02 20:38
Hi @tigger0jk - Thank you for opening this issue, It seems that newer projects have 3 set:

<img width="828" alt="Screenshot 2024-06-02 at 21 36 42" src="https://github.com/supabase/supabase/assets/22655069/77de67c3-d449-46e0-bcad-b7108b23814b">

Is 30 still appearing under your project settings?

**Comment by tigger0jk** [comment] 2024-06-03 00:05
We have since configured SMTP since 3 was unworkable even for testing. So I still see 30, but now it is a configurable field. I don't believe we ever changed it after setting up a custom SMTP provider.

**Comment by Hallidayo** [comment] 2024-06-03 20:37
@tigger0jk - Cool thank you for the above. I'll close this one for now but if this happens again please feel free to reopen.

**Comment by GaryAustin1** [comment] 2024-07-19 00:45
This seems to be an ongoing issue for some users.
One user has speculated that maybe using local dev and syncing to a hosted instance might be the cause?
I don't do local dev so not sure.

**Comment by saltcod** [comment] 2024-07-30 00:37
@Hallidayo  — can you confirm your local? I'm getting the expected 3, so let's close this if you're also seeing 3.

**Comment by Hallidayo** [comment] 2024-07-30 15:10
@saltcod - tried locally and I am getting the same result as you where I see 3.

**Comment by encima** [comment] 2024-08-08 14:02
Could someone try to repro this or provide a project ref of those with it in so we can confirm this is happening the way @GaryAustin1 outlined? I am unable to repro on new projects or new local ones migrating

**Comment by GaryAustin1** [comment] 2024-08-08 14:10
I've asked a user I specifically reopened this for to comment here.  If he does not shortly then I'll close this again.  There have been other reports of this setting changing, but Discord search is not good enough to find and would be months old now.

**Comment by juanpujol** [comment] 2024-08-08 16:31
I still see 30 on my account.

<img width="937" alt="SCR-20240808-lsfn" src="https://github.com/user-attachments/assets/1e18219a-43b9-48f9-b23d-8af6fc532e0f">

**Comment by Hallidayo** [comment] 2024-09-09 19:21
Hi all - This one should be fixed now with [this](https://github.com/supabase/supabase/pull/28952) pull request. The rate limit has been increased to six. If anyone else is having the issue please feel free to comment. Thanks all!

**Closed by Hallidayo** 2024-09-09 19:21 UTC
Labels: bug, frontend, auth, needs-analysis, external-issue
