### ISSUE TITLE
Unable to create RLS from dashboard in local environment -> `Please provide a SQL expression for the WITH CHECK statement`

### ISSUE THREAD

**Issue by dninomiya** [supabase/supabase#22580] opened 2024-04-09 02:21 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

RLS creation fails from local dashboard in clean state.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `bunx supabase init`
2. `bunx supabase start`
3. create posts table on local supabase dashboard
4. try create RLS uses `Enable insert for authenticated users only` template -> error

error -> `Please provide a SQL expression for the WITH CHECK statement`

The template for `Enable read access for all users` is working

## Screenshots

![Export-1712628586563](https://github.com/supabase/supabase/assets/5842851/90e57791-bd42-47bc-9720-ec19f1a2c0e2)

I just set up the environment and created a simple posts table. I haven't done anything else. (I haven't changed the environment file either)

<img width="864" alt="image" src="https://github.com/supabase/supabase/assets/5842851/d43756e7-1dfe-4f9d-ae11-3b5f3d50b603">

## System information

- OS: macOS
- Browser Safari

**Comment by encima** [comment] 2024-04-09 07:57
HI there, thanks for opening!

I am unable to reproduce on the latest. Can you list the image versions you have so we can reproduce please?

**Comment by dninomiya** [comment] 2024-04-09 12:21
Thank you for your support! This is the version of the image. Initialized with `bunx supabase init`.

<img width="744" alt="image" src="https://github.com/supabase/supabase/assets/5842851/9000af31-893b-486c-9fe7-8a51809b8839">

<img width="771" alt="image" src="https://github.com/supabase/supabase/assets/5842851/e2394beb-8e9f-4664-9241-2aa8c423b9c6">

**Comment by saltcod** [comment] 2024-04-10 00:01
Hi @dninomiya — a fix for this should have gone out in yesterday's release. Could you check that you're on the latest version? 

thanks for the report!

**Comment by dninomiya** [comment] 2024-04-10 06:01
@saltcod 
Thank you for your support! However, it seems like I'm still getting the same error. Is my understanding correct that images are created with the latest version by bunx supabase init?

1. bunx supabase init
2. bunx supabase start
3. go to local dashboard
4. create simple posts table
5. add insert RLS from local dasoboard -> same error

<img width="778" alt="image" src="https://github.com/supabase/supabase/assets/5842851/cbf630c7-5462-4742-920a-154a5bf96e00">

<img width="1151" alt="image" src="https://github.com/supabase/supabase/assets/5842851/0223a843-1dba-4a5f-b6c9-87558ab84a66">

**Comment by encima** [comment] 2024-04-10 08:23
@dninomiya not if it is within an existing project. You can do that in a new directory or you can remove `supabase/.temp` and run the command again.

**Comment by dninomiya** [comment] 2024-04-10 08:41
@encima 
This example is a new project with zero-based settings. 🤔

https://github.com/supabase/supabase/issues/22580#issuecomment-2046595602

**Comment by encima** [comment] 2024-04-10 08:45
Noted, thanks. Maybe clear your docker cache and remove the images locally in that case

**Comment by dninomiya** [comment] 2024-04-10 10:32
@encima 
Thanks you for your support!
I removed all images, but it has same error.

By the way, when I try to create RLS using SQL, I get the following error. 🤔

<img width="1035" alt="image" src="https://github.com/supabase/supabase/assets/5842851/56d022e0-10b1-4ec7-bfa5-ed196ef760a0">

`Failed to generate title: No OPENAI_KEY set. Create this environment variable to use AI features.`

**Comment by encima** [comment] 2024-04-10 12:16
That error is because the policy does not exist, it should be a `create` statement and not `alter`.

**Comment by encima** [comment] 2024-04-12 07:18
hey @dninomiya 
this should be fixed now as far as I know, could you try again and report back please?

**Comment by dninomiya** [comment] 2024-04-12 07:21
I started with a clean install of Docker on another Mac and run `bunx supabase init & bunx supabase start` but got the same error.

I didn't do anything particularly tricky, I just tried initializing it, creating a table with default settings, and adding an insert policy using a template.

**Comment by encima** [comment] 2024-04-12 07:22
ack, thanks. I cannot reproduce on OSX but lemme try on a clean system and see if I can get the same results. If not, I will ask a member of the frontend to check this.

**Comment by dninomiya** [comment] 2024-04-12 07:29
@encima 
Thank you your support! My Mac OS is 14.4.1（23E224）.

It may be unrelated, but I will try using npx without using bun.

**Comment by rdsants** [comment] 2024-04-13 12:53
I'm having the same problem using the latest version.

However, I can create the policy through the SQL Editor. The error `Failed to generate title: No OPENAI_KEY set...` appears but when you press f5 on the policies page it will be created.
![image](https://github.com/supabase/supabase/assets/81252176/47f51611-2369-4af4-8efb-d86aec3ec231)

Policy appearing created in the panel (despite the SELECT visualization bug on line 7):
![image](https://github.com/supabase/supabase/assets/81252176/2dbfff9d-9324-4854-a800-3886678478a1)

**Comment by Keagel** [comment] 2024-04-14 10:52
I'm also encountering the same issue. I started using the local development setup for the very first time two days ago so everything was freshly installed after the mentioned fix.

**Comment by dninomiya** [comment] 2024-04-16 02:28
Perhaps because of yesterday's update, I tried it now and it worked properly! thank you. I will close this issue if others have solved it as well.

**Comment by Keagel** [comment] 2024-04-16 22:49
Can confirm it's fixed for me too. Thank you!

**Closed** 2024-04-17 04:10 UTC
Labels: bug, dashboard, needs-analysis

**Comment by stefan-girlich** [comment] 2024-05-10 14:51
Issue still exists for me, using Supabase CLI:
```
public.ecr.aws/supabase/studio:20240326-5e5586d
public.ecr.aws/supabase/postgres-meta:v0.80.0
public.ecr.aws/supabase/edge-runtime:v1.41.3
public.ecr.aws/supabase/imgproxy:v3.8.0
public.ecr.aws/supabase/storage-api:v1.2.1
public.ecr.aws/supabase/postgrest:v12.0.2
public.ecr.aws/supabase/realtime:v2.27.5
public.ecr.aws/supabase/inbucket:3.0.3
public.ecr.aws/supabase/gotrue:v2.150.1
public.ecr.aws/supabase/kong:2.8.1
public.ecr.aws/supabase/logflare:1.4.0
public.ecr.aws/supabase/postgres:15.1.1.19
public.ecr.aws/supabase/vector:0.28.1-alpine
```

I updated just now using `supabase link && supabase start` as advised by the CLI.
Is there another way to update I should try?
