### ISSUE TITLE
"Failed to retrieve Postgres version  Error: <!DOCTYPE html>" when running locally as Studio settings tries to call Management API endpoints

### ISSUE THREAD

**Issue by sxiii** [supabase/supabase#20402] opened 2024-01-13 11:01 UTC
# Bug report

- [+] I confirm this is a bug with Supabase, not with my own application. 
- [+] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After deploying Supabase via docker-compose, the admin UI works, but PostgreSQL DB is semi-broken. Several problems occur, maybe all due to lack of correct PostgreSQL deployment, maybe due to something else:
1. Navigating to http://service-url.xxx:8000/project/default/settings/infrastructure - pages load but has this error in "Service Versions" block: Failed to retrieve Postgres version Error: <!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><title>Supabase</title><meta name="viewport" content="initial-scale=1.0, width=device-width"/> ... and a lot of HTML code afterwards (note: github truncates DOCTYPE html blocks, check the screenshot below to see the actual error)
2. Navigating to http://service-url.xxx:8000/project/default/settings/addons - similar error: Failed to retrieve project addons also with the same DOCTYPE html code in it as in point 1.
3. http://service-url.xxx:8000/project/default/settings/database - Connection Pooling - Failed to retrieve pooling configuration. Try refreshing your browser, but if the issue persists, please reach out to us via support.
4. supabase-rest and supabase-edge-functions containers are up, but they doesn't show "healthy" status (maybe it's ok)
5. supabase-studio shows "unhealthy status", but in the "docker compose logs studio" I don't see any problems. Says ready in 431 ms, Local & Network addresses looks unknown to me, but I guess that's expected as they are internal docker addresses?
6. supabase-analytics contains a lot of this error: [error] Cluster size is 1 but expected 3
7. Weirdness with PostgreSQL:

I can connect to PSQL with `psql -h 127.0.0.1 -p 5432 -d postgres -U postgres:
psql (16.1, server 15.1 (Ubuntu 15.1-1.pgdg20.04+1))

`And I see 2 databases there - pg_default and pg_global. But when I'm trying to connect to either of them, I'm getting connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "pg_default" does not exist

I have tried deploying into 2 different servers

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Used a default docker-deployment procedure from help.
2. Adjusted the keys, passwords, logins, and deployment URL addresses in .env, nothing else.
3. Run `docker-compose up -d`
4. Seen the errors mentioned above.

## Expected behavior

Working Supabase and PSQL.

## Screenshots

![image](https://github.com/supabase/supabase/assets/575925/74efad03-1062-4632-9d6d-4442b44a451b)

## System information

- Local OS: Garuda Linux
- Deployment OSes: 
- 1. Linux 6.6.5-arch1-1 (Arch Linux rolling)
- 2. Linux 6.6.2-arch1-1 (Arch Linux rolling)
- Version of supabase-js: supabase/studio:20240101-8e4a094
- Version of Node.js: v21.4.0

**Comment by immocalcul** [comment] 2024-01-13 12:03
i have the same trouble

**Comment by sxiii** [comment] 2024-01-14 18:10
@encima - doing `docker compose ps` instead as there are some other things running also:
```
NAME                             IMAGE                              COMMAND                   SERVICE     CREATED        STATUS                    PORTS
realtime-dev.supabase-realtime   supabase/realtime:v2.25.50         "/usr/bin/tini -s -g…"    realtime    32 hours ago   Up 32 hours (healthy)     
supabase-analytics               supabase/logflare:1.4.0            "sh run.sh"               analytics   32 hours ago   Up 32 hours (healthy)     0.0.0.0:4000->4000/tcp, :::4000->4000/tcp
supabase-auth                    supabase/gotrue:v2.132.3           "auth"                    auth        32 hours ago   Up 32 hours (healthy)     
supabase-db                      supabase/postgres:15.1.0.147       "docker-entrypoint.s…"    db          32 hours ago   Up 32 hours (healthy)     0.0.0.0:5432->5432/tcp, :::5432->5432/tcp
supabase-edge-functions          supabase/edge-runtime:v1.29.1      "edge-runtime start …"    functions   32 hours ago   Up 32 hours               
supabase-imgproxy                darthsim/imgproxy:v3.8.0           "imgproxy"                imgproxy    32 hours ago   Up 32 hours (healthy)     8080/tcp
supabase-kong                    kong:2.8.1                         "bash -c 'eval \"echo…"   kong        32 hours ago   Up 32 hours (healthy)     0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 8001/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp, 8444/tcp
supabase-meta                    supabase/postgres-meta:v0.75.0     "docker-entrypoint.s…"    meta        32 hours ago   Up 32 hours (healthy)     8080/tcp
supabase-rest                    postgrest/postgrest:v12.0.1        "postgrest"               rest        32 hours ago   Up 32 hours               3000/tcp
supabase-storage                 supabase/storage-api:v0.43.11      "docker-entrypoint.s…"    storage     32 hours ago   Up 32 hours (healthy)     5000/tcp
supabase-studio                  supabase/studio:20240101-8e4a094   "docker-entrypoint.s…"    studio      32 hours ago   Up 32 hours (unhealthy)   3000/tcp
supabase-vector                  timberio/vector:0.28.1-alpine      "/usr/local/bin/vect…"    vector      32 hours ago   Up 32 hours (healthy)
```
And doing `docker compose logs meta`:
```
supabase-meta  | > @supabase/postgres-meta@0.0.0-automated start
supabase-meta  | > node dist/server/server.js
supabase-meta  | 
supabase-meta  | (node:19) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
supabase-meta  | (Use `node --trace-warnings ...` to show where the warning was created)
supabase-meta  | (node:19) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
supabase-meta  | {"level":"info","time":"2024-01-13T10:23:24.690Z","pid":19,"hostname":"4b03f7f571e8","msg":"Server listening at http://0.0.0.0:8080"}
supabase-meta  | {"level":"info","time":"2024-01-13T10:23:24.696Z","pid":19,"hostname":"4b03f7f571e8","msg":"Server listening at http://0.0.0.0:8081"}
```

**Comment by encima** [comment] 2024-01-16 10:04
Thanks for this, @sxiii 

Looks like there is no issue with your containers coming up. Also, this may seem odd, but this is (semi) expected behaviour.

The settings page is not shown in the local version of Supabase as the majority of the settings use our management API that is specifically for the hosted version of Supabase

So, good news, your project is running fine! You can still use supabase, the studio, the database, the API and everything else. You will notice things like `addons` in the Settings page will show that error but it is not a problem as you do not need them locally. 

As for the failing call, we should handle that error better in the UI. 

We could:
1. Either modify the response type to be JSON and check for an error
2. Not make this call when running locally
3. Catch the error but not render the HTML.

I will pass this to the frontend team to triage.

**Comment by sxiii** [comment] 2024-01-16 21:26
Hmmm, interesting. Okay. I will test it out soon then :)

**Comment by joshenlim** [comment] 2024-02-15 09:08
hey guys! just to check - this is from the local version of the Supabase Studio right? The pages you mentioned (basically all the settings pages) should not be available on the local version - I'm curious how you navigated to those pages, were they available as button links in the UI? Or did you manually visit those links?

As such this isn't a FE bug so I'll go ahead to close this ticket, but please do feel free to let us know otherwise! 🙏

**Closed by joshenlim** 2024-02-15 09:08 UTC
Labels: bug, dashboard, self-hosted
