### ISSUE TITLE
Can't use supabase.insert() on a table without Supabase generated primary key

### ISSUE THREAD

**Issue by noconsulate** [supabase/supabase#1165] opened 2021-04-15 19:04 UTC
I wanted to try using turbo/pg-shortkey as my primary IDs and Supabase.insert() never works unless I leave my primary key as the default created by the Supabase editor. I'll skip details of my various attempts and provide you with the final attempt. I thought making the table in SQL and not letting the editor touch the table might help the problem. 

Here is the table:

create table match (
  id shortkey primary key,
  players int2,
  points int,
  is_18_holes bool,
  is_classic_scoring bool,
  players_joined int2,
  creator uuid
  );

I then follow the instructions for [pg-shortkey](https://github.com/turbo/pg-shortkey).

I am perfectly able to insert via sequel:

insert into match (players, points, is_18_holes, is_classic_scoring, players_joined, creator)
values (33, 33, false, false, 1, 'b48b6829-5a93-40df-b8a0-ec6f7cdb0911')

And it shows up as expected in the editor:
![supa](https://user-images.githubusercontent.com/47261707/114921396-c307b300-9de7-11eb-9d13-75f1aafa62ab.png)

However when I use the SDK to call with a basic insert:

const { data, error } = await supabase
    .from("match")
    .insert({ players, points, is_18_holes, is_classic_scoring, creator });

I get this error:
**code: "42883", message: "function gen_random_bytes(integer) does not exist" }**

I have use the exact same JS to call my old Supabase generated table and it works. 

I haven't tried revising the RPC I am using for this operation and I assume it will work. 

***

I also tried doing a very simple test of this. I fololwed the pg-shortkey exactly, creating a table "test" that generates a short UUID type primary key upon insert. I can successfully make SQL inserts but the SDK doesn't do anything. In this case `window.supabase.from('test').insert('lasdfd')` returns an empty arrow but no error.

OTOH I have no trouble with a "user_details" table that has UUID as it's primary key. It would seem as though the SDK only has a problem when there is third-party extension assigning primary keys.

**Comment by steve-chavez** [comment] 2021-04-15 19:20
@noconsulate Can you check the `EXTRA SEARCH PATH` field on `/settings/api`?

It should contain `public, extensions`. If not, try to change it to that value and retry the insert with supabase-js.

If that doesn't work, you might have to change `gen_random_bytes` on this [line](https://github.com/turbo/pg-shortkey/blob/master/pg-shortkey.sql#L37) to `extensions.gen_random_bytes`.

**Comment by noconsulate** [comment] 2021-04-15 20:59
`public, extensions` was already there and have replaced the shortkey_generate() function with the updated line. Now I'm getting **code: "42501", message: "permission denied for schema extensions", … }**.  I tried doing at insert on my **match** table and also `let res = await window.supabase.from("test").insert({name: "sam"})` on the **test** table that I copy and pasted from the pg-shortket git. 

So something changed!

**Comment by steve-chavez** [comment] 2021-04-15 21:23
> code: "42501", message: "permission denied for schema extensions", … 

@noconsulate For clearing that, try doing:

```sql
grant usage  on schema extensions to anon, authenticated, service_role;
```

**Comment by noconsulate** [comment] 2021-04-15 21:43
Great! It works now. I'll add this to my own personal FAQ. :) Thank you.

**Comment by steve-chavez** [comment] 2021-04-16 01:00
Cool. I'll close this one since it's fixed. Will keep tracking on https://github.com/supabase/supabase/issues/1154, which has the same underlying issue.

**Closed by steve-chavez** 2021-04-16 01:00 UTC
Labels: bug

**Comment by akoskm** [comment] 2025-04-16 20:22
> [@noconsulate](https://github.com/noconsulate) Can you check the `EXTRA SEARCH PATH` field on `/settings/api`?
> 
> It should contain `public, extensions`. If not, try to change it to that value and retry the insert with supabase-js.
> 
> If that doesn't work, you might have to change `gen_random_bytes` on this [line](https://github.com/turbo/pg-shortkey/blob/master/pg-shortkey.sql#L37) to `extensions.gen_random_bytes`.

I've just run into this issue `function gen_random_bytes(integer) does not exist`, despite this: `SELECT gen_random_bytes(32);` working form the SQL editor and having `public, pgcrypto, extensions` in search path.

Why the `extensions` is required in this case?

**Comment by laurenceisla** [comment] 2025-04-17 23:41
> I've just run into this issue `function gen_random_bytes(integer) does not exist`, despite this: `SELECT gen_random_bytes(32);` working form the SQL editor

Yes, the SQL Editor has those schemas in its search path already as seen when executing `SHOW search_path;`. But this is different to the API REST search path.

> and having `public, pgcrypto, extensions` in search path.
> 
> Why the `extensions` is required in this case?

I couldn't reproduce this, perhaps it has to do with the PostgREST version? Can you check it in " Logs > PostgREST " and then typing `Starting PostgREST` in the "search events" bar. Also try restarting the configuration by setting the " Data API > Extra search path" to only `public, extensions` (without `pgcrypto`) then Save the changes and try again.

**Comment by hasaanIdeofuzion** [comment] 2025-07-30 11:52
Hey, I got an issue. Whenever i try to insert row into my table it says table doesnot exists but returns all the data when i call select query.
