### ISSUE TITLE
On the mobile documentation site, the menu doesn't always close after tapping on an item

### ISSUE THREAD

**Issue by j4w8n** [supabase/supabase#14533] opened 2023-05-23 10:08 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On mobile browsers - Firefox and Chrome anyway - after opening the menu, then tapping on an item, the menu sometimes only half closes. If you refresh the page, it clears.

## To Reproduce

(Described above)

## Expected behavior

For the mobile menu to fully close.

## Screenshots

![Screenshot_20230523_054200_Firefox~2.jpg](https://github.com/supabase/supabase/assets/25783093/ff3be103-fe3f-4417-b83d-507b9c44510f)

## System information

- OS: Android
- Browser (if applies) tested on chrome and firefox
- Version of supabase-js: n/a
- Version of Node.js: n/a

**Comment by gregnr** [comment] 2023-05-31 17:19
Thanks for reporting @j4w8n. I was able to reproduce - looks like this happens primarily on reference docs:
https://supabase.com/docs/reference/javascript/introduction

**Comment by pcmourya** [comment] 2023-06-11 17:20
Is it done, can I pick this issue @gregnr .

**Comment by gregnr** [comment] 2023-06-12 16:43
@pcmourya, yes please! This is still open.

**Comment by haszankauna** [comment] 2023-06-16 16:29
Hello @gregnr I was able to reproduce this error. But for clarification will you want the sidebar to be only visible without the blur background on mobile?

**Comment by gregnr** [comment] 2023-06-16 16:51
Hey @haszankauna! I think we can keep the background blur as is - let's just try to fix that half-close issue.

**Comment by haszankauna** [comment] 2023-06-16 17:28
Okay that works @gregnr. If I'm getting you right, the side bar should be completely closed right?

**Comment by gregnr** [comment] 2023-06-16 17:50
You got it 👍 As @j4w8n mentions above, clicking one of the nav items sometimes only half-closes the menu, but we would expect it to full close.

**Comment by nick-krantz** [comment] 2023-07-09 02:03
👋 I took a shot at this one and opened a PR #15588

**Comment by AbhijeetBiswalCodes** [comment] 2023-08-17 06:14
Is it done, can I pick this issue @gregnr  .

**Comment by Gingaaa** [comment] 2023-08-17 20:02
Hey I have worked on around 7-8 company based project, but never countribute to open source, this is my first time can you assign me this task.

**Comment by krmayur** [comment] 2023-08-28 15:40
can you assign this to me @saltcod

**Comment by shiivamtaneja** [comment] 2023-08-30 15:34
@saltcod Is this issue fixed? I just went to this [link](https://supabase.com/docs/reference/javascript/introduction) and I could see the issue.
![image](https://github.com/supabase/supabase/assets/79853285/bb2f4e04-67f5-41be-be42-72b16d94c1ab)

**Comment by akoolarni** [comment] 2023-09-12 13:33
Is this issue still open for contributions ? 
If yes , then I can help.

**Comment by Bayyana-kiran** [comment] 2023-11-10 10:14
is issue still open?

**Comment by j4w8n** [comment] 2023-11-10 11:51
Yes, it's still open. Looks like there's two PRs, but both of them have failing checks. I'd imagine the team isn't going to consider merging either of them until all checks pass.

**Comment by j4w8n** [comment] 2023-11-10 12:18
@Bayyana-kiran I've never contributed to this repo before. I tried setting it up several months ago, but never got it working on Windows.

https://github.com/supabase/supabase/blob/master/DEVELOPERS.md

**Comment by Bayyana-kiran** [comment] 2023-11-10 12:33
@j4w8n I'm not able to run the application even after downloading all the dependencies? and what is the main think to resolve?

**Comment by j4w8n** [comment] 2023-11-10 12:38
I'm no help with getting the dev environment working.

**Comment by Bayyana-kiran** [comment] 2023-11-10 12:39
what is the main thing to resolve?

**Comment by j4w8n** [comment] 2023-11-10 13:06
> what is the main thing to resolve?

If you're referring to the checks failing, that's only something the other people can resolve on their PRs. And it looks like those checks have nothing to do with the actual fix they're proposing, so I may just be mistaken.

**Comment by charislam** [comment] 2023-11-13 17:30
Hello all, thanks for your interest in contributing to Supabase! It looks like there is an [open PR](https://github.com/supabase/supabase/pull/15588) in the mentions that is close to completion, so on the basis of first-come first-serve, I'm going to leave it with the first mentioned PR.

There are always plenty of [good first issues](https://github.com/supabase/supabase/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and [help wanted](https://github.com/supabase/supabase/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues, so please check those out if you'd like to contribute!

**Comment by Nayanchandrakar** [comment] 2024-01-03 03:37
I check its working fine no problem is there

**Comment by j4w8n** [comment] 2024-01-03 17:26
Yes, thanks for the reminder. I meant to come back and close this.

**Closed** 2024-01-03 17:26 UTC
Labels: bug, documentation, help wanted, good first issue, hacktoberfest
