### ISSUE TITLE
Supabase local development error - database is not healthy 

### ISSUE THREAD

**Issue by marcbejar** [supabase/supabase#19905] opened 2023-12-20 11:31 UTC
# Bug report

## Describe the bug
Supabase CLI command `npx supabase db reset` fails under the error _database is not healthy_ in local development.

This error ONLY occurs when a project has been linked with the command `npx supabase link`. If this command is not executed, the command `npx supabase db reset `works fine.

## To Reproduce

1. Init supabase with `npx supabase init`
2. Start supabase `with npx supabase start`
3. Link an empty project with `npx supabase link`
4. Create a migration file with `npx supabase migration new filename`
5. Run `npx supabase db reset`

## Expected behavior

![image](https://github.com/supabase/supabase/assets/18014598/577be976-f61f-46e2-8e74-0fff19d735eb)

## Screenshots

![image](https://github.com/supabase/supabase/assets/18014598/3b62417c-949a-4eb4-9992-8bd4918237a0)

## System information

- OS: Ubuntu 22.04.3 LTS
- Version of supabase-js: 1.123.4
- Version of Node.js: v18.18.0
![image](https://github.com/supabase/supabase/assets/18014598/b866df22-d98d-4358-bd73-7ed00905d834)

**Comment by swyxio** [comment] 2024-01-04 23:42
i started and stopped a few times to get it finally working
![image](https://github.com/supabase/supabase/assets/6764957/55eca8ed-da55-4444-a25e-17461dc867d0)

**Comment by Mohammed-Yasin-Mulla** [comment] 2024-01-12 05:35
You can get around with this by exicuting the command when stoping you local instance by adding `--no-backup` flag
```bash
supabase stop --no-backup
```
then the next time you start your local instance, the warning `database is not healthy` should be resolved.

Hope it helps

**Comment by encima** [comment] 2024-01-19 08:00
I will close this as the workaround seems valid and is likely caused by an unclean shutdown of the DB.

However, please comment if this is still occurring (with system information, versions and if the stop was unclean) and we will reopen.

Also, if anyone wants to open a PR to document this, please link to this issue 🙏

**Closed by encima** 2024-01-19 08:00 UTC
Labels: bug, cli, database, migrations

**Comment by Greyvend** [comment] 2024-02-24 13:14
I'm getting the same error, restarting multiple times doesn't help. I also tried using the beta release, `npx supabase@beta`, no luck.

**Comment by haydn** [comment] 2024-05-10 04:44
@rienheuver This might help: https://github.com/supabase/cli/issues/2252#issuecomment-2103853071

**Comment by ChuckJonas** [comment] 2024-05-20 15:26
> You can get around with this by exicuting the command when stoping you local instance by adding `--no-backup` flag
> 
> ```shell
> supabase stop --no-backup
> ```
> 
> then the next time you start your local instance, the warning `database is not healthy` should be resolved.

Probably worth mentioning that this will drop your entire database (I know it's kinda obvious based on the parameters but still)
