### ISSUE TITLE
[Error]: Dynamic server usage: Route couldn't be rendered statically because it used cookies.

### ISSUE THREAD

**Issue by leonardoparisii** [supabase/supabase#22718] opened 2024-04-14 21:30 UTC
Hi, I'm experiencing this build error in my application,

![image](https://github.com/supabase/supabase/assets/140561519/3bb964a1-62d6-462c-a7bf-ce7b21741484)

### **To Reproduce**

1.  -Use auth with cookies and supabase
2.  -Got this error

### **Additional context**

**middleware.ts**

```
export async function middleware(req: NextRequest) {
  const res = NextResponse.next();
  const supabase = createMiddlewareClient({ req, res });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return res;
}
```

**app/api/auth/callback/route.ts**
```

import { createRouteHandlerClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";

export async function GET(request: Request) {
  const requestUrl = new URL(request.url);
  const code = requestUrl.searchParams.get("code");

  if (code) {
    const supabase = createRouteHandlerClient({ cookies });
    await supabase.auth.exchangeCodeForSession(code);
  }

  return NextResponse.redirect(requestUrl.origin);
}

```

**app/utils/supabase.ts**

```
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";

const supabaseServer = () => {
  cookies().getAll();
  return createServerComponentClient({ cookies });
};

export default supabaseServer;
```

description: "Route /<NAME_ROUTE>couldn't be rendered statically because it used cookies. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",

I'm getting this in every route where I have something like this:

```
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();
```

**Comment by jblewnormal** [comment] 2024-04-24 22:55
@leonardoparisii Hey, have you made any progress on this? I've run into the same issue and spent hours looking for solutions with no success.

**Comment by leonardoparisii** [comment] 2024-04-25 09:39
Actually yes, using @supabase/ssr package instead of using @supabase/auth-helpers-nextjs!

You can find everything on how to use @supabase/ssr with nextjs here, which is the guide I followed:

[https://supabase.com/docs/guides/auth/server-side/nextjs](url)

**Comment by jblewnormal** [comment] 2024-04-25 23:06
@leonardoparisii Yeah I've been following that guide as well - but for some reason the behavior is different in my project. If I try using the `createClient()` server version in any component, or even in a util function and then use that in a component, it throws the error about cookies or headers.

Did you have to do anything beyond that guide?

**Comment by leonardoparisii** [comment] 2024-04-26 09:11
Nope, I just fixed it by sticking to the guide:

I have this folder structure for the supabase init files:

![image](https://github.com/supabase/supabase/assets/140561519/604b630e-25cd-4e99-8cc3-2e514a63750b)

and the auth route for the code param under /app:

![image](https://github.com/supabase/supabase/assets/140561519/86d758c7-db98-45f8-8b56-910ddb28df8d)

everything with the same content of the docs, I only added a couple of checks on the protected routes inside of the middleware.ts file, (the one at the /src level).

**Comment by leonardoparisii** [comment] 2024-04-26 14:56
I'm on version 14.2.2. Yeah, you can try downgrading Next and see what happens. Let me know when you find out what the problem is because I'm pretty curious now lmao.

**Comment by Hallidayo** [comment] 2024-06-03 20:43
Hi both - just checking in, is everything working your end now?

**Comment by jblewnormal** [comment] 2024-06-03 20:50
> Hi both - just checking in, is everything working your end now?

Hey, yep! I was eventually able to solve it by recopying everything from the Supabase Next SSR guide, and had accidentally left `--debug` in my build command so the warnings continued to show. Once removed, builds went smoothly.

**Comment by Hallidayo** [comment] 2024-07-01 20:59
Hi @jblewnormal - thanks for confirming, I'm going to close this one but if this issue is still happening please feel free to reopen.

**Closed by Hallidayo** 2024-07-01 20:59 UTC
Labels: bug

**Comment by joncoronel** [comment] 2024-07-09 18:03
> Hi @jblewnormal - thanks for confirming, I'm going to close this one but if this issue is still happening please feel free to reopen.

Hey there. I am getting a similar issue to this. Get the following error: `[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: 'DYNAMIC_SERVER_USAGE',
  page: '/'
}`

This occurs after the login server action is called and the user is redirected to the `/` route. I followed the nextjs supabase ssr auth docs exactly. I narrowed down the cause of the error being the use of `createClient()` within a route. 

Here is the my `/` route: `
import { createClient } from "@/utils/supabase/server";

export default async function Home() {
  const supabase = createClient();

  return (
    <main className="flex h-screen flex-col items-center justify-center">
      <h1 className="text-6xl font-bold">Welcome to your app</h1>
      <p className="mb-4 mt-4 text-lg">
        Get started by creating an account or signing in.
      </p>

    </main>
  );
}

export const dynamic = "force-dynamic";
`

Once the createClient() function is removed, the error no longer happens.

**Comment by sachintha180** [comment] 2024-08-29 19:15
Hi, I got it to work by getting rid of the `try-except` statements I'd put around a bunch of Server Actions (Next.js) which internally use `createClient` from `@/utils/supabase/server`. 

So for example - instead of:

```typescript
try {
  const response = await checkOAuthIdentity("azure");
  if (response && response.error) {
    throw new Error(response.error);
  }
} catch (e) {
  console.error(e);
  provider.notLinked = true;
}
  ```
... where `checkOAuthIdentity` is a Server Action that checks whether the user has an OAuth identity linked to them and calls the `createClient` method within it - you can do:
 
 ```typescript
 const checkResponse = await checkOAuthIdentity("azure");
  if (checkResponse && checkResponse.error) {
    console.error(checkResponse.error);
    provider.notLinked = true;
  }
  ```

The reason for this was described really well here: https://stackoverflow.com/questions/78010331/dynamic-server-usage-page-couldnt-be-rendered-statically-because-it-used-next

**Comment by joshberc** [comment] 2024-12-04 19:36
If anyone is still running into this issue, I resolved it by adding `export const dynamic = 'force-dynamic'` to the page that was throwing this error in the build. I am using `Next: 14.1.0` with `@supabase/ssr: 0.5.2`.

**Comment by albertocubeddu** [comment] 2025-01-02 03:52
I spent 2 hours trying to understand what's wrong; 

Check how this error are managed by NextJS
https://github.com/vercel/next.js/blob/96d384712432450a83d8b510fd32f1758f24e0df/packages/next/src/client/components/hooks-server-context.ts

If you're using try-catches (and yeah, you should!) that's the fix: 

`export async function getTotalAssessmentsCountActive() {
  try {
    const currentUser = await getCurrentUser();

    const supabaseAdmin = createADMINClient();
    const { count, data } = await supabaseAdmin
      .from("assessments_voice")
      .select("id, assistants!inner(id, timer_end)", {
        count: "exact",
      })
      .eq("fk_accounts_id", currentUser?.account_id)
      .not("assistants.timer_start", "is", null)
      .is("assistants.timer_end", null);

    return count;
  } catch (error) {
    if (isDynamicServerError(error)) {
      throw error;
    }
    console.error("Error getting total assessments count:", error);
    return null;
  }`
  
  Throwing the error, will help the builder to understand how to build the page (in this case dynamically)

**Comment by marcusklausen** [comment] 2025-02-13 15:44
I have abstraction factories for server functions and actions which call the supabase client.
All I had to do was call `unstable_noStore()` in the factory before the returned server action or function.

So if you have an abstraction layer this is probably what you need
