### ISSUE TITLE
Cannot Login 

### ISSUE THREAD

**Issue by Demoevery** [supabase/supabase#4448] opened 2021-12-12 04:29 UTC
# Bug report
After sign in with GitHub I only get this page 
![image](https://user-images.githubusercontent.com/95992350/145700065-f77e458f-41b2-438b-a951-237b635480e8.png)

## Describe the bug
After hitting F12 I see CORS error like this
![image](https://user-images.githubusercontent.com/95992350/145700040-92131a0a-4c96-42e7-8b93-a0c8788b7462.png)

## Steps to reproduce

1. Go to https://app.supabase.io/
2. Click on sign in > sign in with GitHub> allow account info from GitHub 
4. See error hitting F12 after loading animation

## Expected behavior

See the Supabase console

## System information

- OS: Windows
- Browser: chrome
- Version of supabase-js: unknown
- Version of Node.js: na

## Additional context
I use Ublock origin and some other extensions. So I tried using incognito and Edge still facing same issue.

**Comment by digitalml** [comment] 2021-12-12 06:36
I also tried the steps above and get this error.
![image](https://user-images.githubusercontent.com/1479241/145703005-2f191f9e-605f-4bc5-83c2-d41bd9ecf29f.png)

**Comment by Isaiah-Hamilton** [comment] 2021-12-12 15:48
@digitalml and @Demoevery It works perfectly fine for me. Try deleting your local storage, cache, cookies, or any other thing that might be stopping it from working.

**Comment by digitalml** [comment] 2021-12-12 18:08
Works fine for me now.. Definitely there was something wrong last night.

**Comment by codeswithroh** [comment] 2021-12-13 03:49
While logging in for the first time, the above error was recreated. But as @Isaiah-Hamilton mentioned after clearing the cookies and trying to login again, this worked. But this behaviour needs to be fixed.

**Comment by Demoevery** [comment] 2021-12-13 15:44
> Try deleting your local storage, cache, cookies, or any other thing that might be stopping it from working. And then try again.

I tried another browser without any previous history still no progress.

**Comment by Isaiah-Hamilton** [comment] 2021-12-13 16:39
> I tried another browser without any previous history still no progress.

Trying another browser won't work because supabase is still adding information to local storage or cookies that is causing this bug.

**Comment by Isaiah-Hamilton** [comment] 2021-12-13 16:41
I'm working on a fix for this bug, but anyone can pick it up if they want.

**Comment by c00ler82** [comment] 2021-12-17 09:52
I was logged in an hour ago and everything was fine. Suddenly now I can't sign in. Also tried incognito mode but still can't sign in.

**Comment by ynamite** [comment] 2021-12-20 11:05
Same here, was working fine yesterday evening, now today I can't get past the login screen.

**Comment by inian** [comment] 2021-12-20 11:24
Hi @ynamite, can you verify your email in Github and then try to login to Supabase again? With our migration to Gotrue, we are tightening up security where possible.

**Comment by inian** [comment] 2021-12-20 13:12
Hi @ynamite, I have reset your account, can you retry now? If you are still unable to login, please reach out to support via https://app.supabase.io/support/new

**Comment by rynpatk** [comment] 2021-12-20 19:32
I'm trying to use Supabase for the first time as well and cannot get past the same "Sign in With Github" screen. My email is verified in Github and I have cleared cookies and browser data in multiple browsers. I see the same 401 from the original post in my console.

**Comment by meyerworks** [comment] 2021-12-20 20:54
@inian me as well please

**Comment by meyerworks** [comment] 2021-12-21 19:30
@inian any chance at a little help?

**Comment by meyerworks** [comment] 2021-12-22 18:04
I can't reach out to support, since I'm not logged in :(

**Comment by inian** [comment] 2021-12-23 04:22
@meyerworks I have reset your account, you should be able to login now. 

@rynpatk i wasnt able to find your Github username in our records, can you reach out to us at support@supabase.io and we will get you sorted

**Comment by FredBouillon** [comment] 2021-12-23 22:23
@inian Could you reset my account as well? Thx!

**Comment by meyerworks** [comment] 2022-01-02 23:02
@inian thank you so much for the response!  I didn't see it I've been out of town.  Still having the same login failure.  Any suggestions?

**Comment by Isaiah-Hamilton** [comment] 2022-02-02 04:27
This issue has been inactive for a while and I will be closing. Please feel free to reopen this issue, and keep discussing it.

**Closed by Isaiah-Hamilton** 2022-02-02 04:27 UTC
Labels: bug

**Comment by Praesum** [comment] 2022-04-13 04:30
definitely a regular problem for me since I started using supabase several days ago. Happened at least 4 times on different days with the following console log. 
![Screen Shot 2022-04-12 at 10 28 53 PM](https://user-images.githubusercontent.com/17322191/163100329-75b98573-6650-4235-84d6-17843bd5e5d2.png)


Executing on Brave with Brave Shield disabled. I've been able to successfully log in a few times, but it makes me relogin daily and this has plagued me every time.

**Comment by szulcus** [comment] 2022-11-07 03:02
Also, I can't log in. Interestingly, it works on the computer, the problem is only on the phone (Xiaomi 12 Pro). Could I please for help? 🙏

**Comment by raf-avag** [comment] 2022-11-17 19:19
Same here, can't login with my GitHub account! But I'm getting a 504 Gateway Time-out

**Comment by johnmboardem** [comment] 2023-01-20 16:25
I have this problem and it is really annoying. It should be reponed

**Comment by inian** [comment] 2023-01-22 09:58
@johnmboardem if you are having issues logging in, please open email support@supabase.io. Think this affects only your account and we will need more information to debug.
