### ISSUE TITLE
Issue with Supabase Starter deployed on Vercel, cashes 404 page as home page after visit.

### ISSUE THREAD

**Issue by killacan** [supabase/supabase#20281] opened 2024-01-09 19:23 UTC
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After deploying to Vercel when navigating to a page that does not exist and encountering a 404, using a Next Link on the page to "/" does not redirect to home page unless page refreshes. Other Next Links are taken to the correct page, ex "/models" or "/photos" but when going "/" it shows the 404. Does not happen on local host. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. clone starter project. 
2. add Nav component with Next Link home, (<Link href={"/"}>Share Diffusion</Link>). 
3. put Nav in layout above children.
4. manually navigate to non-existent page to trigger 404.  
5. click Next Link for home.

## Expected behavior

I would expect to be taken to my home page, not back to the 404. 

## System information

- OS: Linux
- Browser (if applies) Firefox, Brave
- Version of supabase-js: just says "latest"
- Version of Node.js: 20.3.1

## Additional context

Bug does not happen on local host, after a refresh works as intended, when replaced with an <a> works just fine (i think because the triggered refresh). In vercel on the logs and when looking at the network activity, looks like it is not doing a get request.

**Comment by killacan** [comment] 2024-01-09 19:33
also here is a link to the repo with minimum changes to show issue https://github.com/killacan/supabasenextroutertest and it is currently deployed on Vercel.

**Comment by encima** [comment] 2024-01-15 09:54
Hi @killacan 
This is reproducible, thank you for the example repo. This seems to be an issue with `next`, as the Link functionality is independent of Supabase (see https://next-link-mmknzsem5-encima.vercel.app/)

Could you open this on the `next` repo and link to this one. I will close this one out.

**Closed by encima** 2024-01-15 09:54 UTC
Labels: bug, example
