### ISSUE TITLE
Supabase dashboard: old SQL queries are executed occasionally

### ISSUE THREAD

**Issue by bnjmnt4n** [supabase/supabase#3199] opened 2021-09-14 15:06 UTC
# Bug report

## Describe the bug

When executing SQL queries on the dashboard, on occasion older SQL queries are executed instead of what's currently in the dashboard.

## To Reproduce

I don't have concrete steps to reproduce, as it seems intermittent, but sometimes after pasting in a new SQL snippet into the dashboard and executing via `Ctrl+Enter`, the results of the query are from the old snippet.

## Expected behavior

The current SQL query in the dashboard is run instead.

## System information

- OS: Windows
- Browser (if applies): Firefox 92

**Comment by kennethcassel** [comment] 2021-09-14 18:04
I'm experiencing the same issue. I think I found reproducible steps. Seems to happen every time with me. [I created an issue with the steps to reproduce](https://github.com/supabase/supabase/issues/3200)

**Comment by w3b6x9** [comment] 2021-09-15 00:14
@bnjmnt4n i'm going to close this ticket since @kennethcassel created a similar one with reproducible steps.

**Closed by w3b6x9** 2021-09-15 00:14 UTC
Labels: bug
