### ISSUE TITLE
npx supabase start with Cannot find module error.

### ISSUE THREAD

**Issue by Probmkr** [supabase/supabase#22418] opened 2024-04-03 05:02 UTC
# Bug report

## Bug

`Cannot find module: '../util/template'` error will occur when I run `npx supabase start` command from npm package.

## To Reproduce

It occurs after a few times `npx supabase start --ignore-health-check` and `npx supabase stop`. It won't occur when the first time run `npx supabase start` command after `npx supabase init` or cloning git repository.

Also `npx supabase db reset` and `npx supabase db start` cause this error.

## System information

- OS: Ubuntu Server 22.04.4 LTS
- Version of supabase-js: 1.151.1
- Version of Node.js: 20.11.0

## Result without --debug

```
% npx supabase start -x storage-api
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '../util/template'
Require stack:
- /app/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js
- /app/node_modules/knex/lib/migrations/migrate/Migrator.js
- /app/node_modules/knex/lib/knex-builder/make-knex.js
- /app/node_modules/knex/lib/execution/transaction.js
- /app/node_modules/knex/lib/client.js
- /app/node_modules/knex/lib/knex-builder/Knex.js
- /app/node_modules/knex/lib/index.js
- /app/node_modules/knex/knex.js
- /app/dist/database/multitenant-db.js
- /app/dist/database/index.js
- /app/dist/scripts/migrate-call.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/app/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js:2:38)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/knex/lib/migrations/migrate/MigrationGenerator.js',
    '/app/node_modules/knex/lib/migrations/migrate/Migrator.js',
    '/app/node_modules/knex/lib/knex-builder/make-knex.js',
    '/app/node_modules/knex/lib/execution/transaction.js',
    '/app/node_modules/knex/lib/client.js',
    '/app/node_modules/knex/lib/knex-builder/Knex.js',
    '/app/node_modules/knex/lib/index.js',
    '/app/node_modules/knex/knex.js',
    '/app/dist/database/multitenant-db.js',
    '/app/dist/database/index.js',
    '/app/dist/scripts/migrate-call.js'
  ]
}

Node.js v20.11.1
error running container: exit 1
Try rerunning the command with --debug to troubleshoot the error.
```

Sometimes, the container starts in spite of this error occurs.

**Comment by encima** [comment] 2024-04-03 09:18
Please update to the [latest](https://github.com/supabase/cli/releases/tag/v1.153.1) version of the CLI and confirm this is still occurring.

**Comment by encima** [comment] 2024-04-03 09:19
Unable to reproduce on the version specified (or latest) so it could be some project config that interferes. If you can add any details on changes you have made (if any) from the default 🙏

**Comment by Probmkr** [comment] 2024-04-03 11:44
> Please update to the [latest](https://github.com/supabase/cli/releases/tag/v1.153.1) version of the CLI and confirm this is still occurring.
I updated but nothing changed.

**Comment by encima** [comment] 2024-04-03 11:47
Thanks for doing it! Could you also try to use the locally installed package instead of `npx` to remove that as the issue? You could also try to reinstall all node modules for the project

**Comment by Probmkr** [comment] 2024-04-03 12:14
I have to apologize to you that maybe I found the reason.

This error may have been caused because I was developing two Supabase projects at the same time.

After I made this issue, I tried removing both projects' directories and git cloned again. And this time, the error never happened. I tried this once before. But that time I removed one project and started the local environment and it successfully started. And I tried the same thing on the other project but the error still occurred. But this time, I removed both project directories at the same, so maybe because of this the error has been resolved.

**Comment by encima** [comment] 2024-04-03 12:17
No need to apologise, that still sounds like an issue!

Do you know what was causing the issue with both projects installed? Were you using a different access token for each project?

I will leave this open and see if I can reproduce your issue.

**Comment by Probmkr** [comment] 2024-04-03 12:30
There is no error for now so I will add some information if the error occurs again.

**Comment by Probmkr** [comment] 2024-04-07 10:39
It might be because I keep my development environment running for more than a day.

**Comment by encima** [comment] 2024-04-08 19:40
Could be but I often have Supabase environments running for multiple days or weeks and have not come across this. I will close this but we can definitely reopen if you (or others) experience this again

**Closed by encima** 2024-04-08 19:40 UTC
Labels: cli, needs-analysis

**Comment by Probmkr** [comment] 2024-04-23 00:04
I found the reason. It was because I ran `supabase start` with `--ignore-health-check`
