### ISSUE TITLE
Slow query when using order by

### ISSUE THREAD

**Issue by Jcaster99** [supabase/supabase#15336] opened 2023-06-24 23:51 UTC
# Bug report
I have chat message table with 15k record

when i select using order by with created at will be take 5 - 10s so when remove order by take ~ 90ms

**Comment by GaryAustin1** [comment] 2023-06-25 01:38
Not sure why you are reporting this as a bug, especially as not much Supabase has to do with the Postgres database.  

Seems like you need to work on your query, indexing and probably RLS if you have it.  When you do order by, the query has to has to process all rows and RLS on those rows if you have it.
You probably should seek help in discussions or Supabase Discord.

RLS can make a huge difference, although that is very slow for a 15k row table...
https://github.com/orgs/supabase/discussions/14576  has some tips on RLS if you have that on.

**Comment by saltcod** [comment] 2023-06-26 14:04
Thanks all. Going to close this one as it's not a bug per se.

**Closed by saltcod** 2023-06-26 14:04 UTC
Labels: bug

**Comment by sanskar-19** [comment] 2024-09-04 11:49
Facing similar issue @Jcaster99, checked on the db side, ran the query, infact moving the sort to the db side, fixes the problem, but when adding the sort back to client-side, it becomes very slow.

Any findings? I did checked the query for indexes and other params, all looks good with the query since it is working good under `70ms` when on db side with sorting.
