### ISSUE TITLE
Prettier solution

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/supabase#4224] opened 2021-12-01 23:16 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

The Prettier code check has been failing recently and we have to fix it down the line.

## Describe the solution you'd like

Have `npm run prettier` in [package.json](https://github.com/supabase/supabase/blob/master/package.json) that checks and edits all of the files that Prettier would check on Github. Also adding into [DEVELOPERS.md](https://github.com/supabase/supabase/blob/master/DEVELOPERS.md) on all the steps you need to do before opening a PR. This would be best because people would only have to run once and we will stop having to fix it later down the line.

## Additional context

let me know what you think.

**Comment by MildTomato** [comment] 2021-12-02 02:56
@Isaiah-Hamilton are you using prettier?
there's an [extension in vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) which is worth installing.

And then make sure 'Format on paste' and 'Format on save' are both enabled in VScode settings.

We should update DEVELOPERS md (good idea!) like you say to include this.

I don't think we have a package.json file in the root of supabase/supabase so I'm not sure where to put an `npm run prettier`, since we would want it run on all the folders.

Maybe the best workaround, for now, is just including instructions to have prettier installed so at least changes anyone makes are good to go as soon as they are checked in.

**Comment by bobTheHands** [comment] 2021-12-02 03:52
> I don't think we have a package.json file in the root of supabase/supabase so I'm not sure where to put an `npm run prettier`, since we would want it run on all the folders.

you could do that with a pre-commit git hook,

**Comment by darora** [comment] 2021-12-02 03:59
I'd really rather not add a pre-commit hook. The simple solution here imo is to enable requiring PRs to pass the prettier checks (which is already being executed) before it can be merged.

**Comment by kiwicopple** [comment] 2021-12-02 05:28
I haven't dug into the cause, but I saw these errors happening in some of my branches and ran prettier, but the code wasn't updated. Perhaps too many prettier configs in our repo?

**Comment by Isaiah-Hamilton** [comment] 2021-12-03 00:11
> The simple solution here imo is to enable requiring PRs to pass the prettier checks (which is already being executed) before it can be merged.

The problem with this is that we are still merging the code even though Prettier failed the code check.

**Comment by Isaiah-Hamilton** [comment] 2021-12-03 00:26
> Perhaps too many prettier configs in our repo?

When you mean prettier configs, do you mean in `package.json` or in the Github workflows.

**Comment by Isaiah-Hamilton** [comment] 2021-12-03 01:12
> @Isaiah-Hamilton are you using prettier? there's an [extension in vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) which is worth installing.
> 
> And then make sure 'Format on paste' and 'Format on save' are both enabled in VScode settings.

Yes, I'm using the prettier vscode extension but I have it turned off. what I do is, before I commit is I run
```
npx prettier --write '<FOLDER>/**/*.{js,jsx,ts,tsx,css,md,json}'
```
The reason why I do this is because the prettier vscode extensions is broken and I need to fix it.

**Comment by darora** [comment] 2021-12-03 01:31
> The problem with this is that we are still merging the code even though Prettier failed the code check.

Sure-I'm saying that once the repo is fixed we can throw the Github settings flag that disallows failing PRs from being merged.

**Comment by genzyy** [comment] 2021-12-03 06:42
> @Isaiah-Hamilton are you using prettier? there's an [extension in vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) which is worth installing.
> 
> And then make sure 'Format on paste' and 'Format on save' are both enabled in VScode settings.


This is actually a good way to solve the issue temporarily. I can give you steps to set it up as it works great on vscode for me.

1. Install the `prettier` extension in vscode.
2. Now open your JSON settings by <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> `OR`<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>.
3.  Add the following rules or settings there,

```JSON
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
```
In this way you don't have to run `npm run prettier`, because it will format the code accordingly, when you write the code.

**Comment by Isaiah-Hamilton** [comment] 2021-12-03 07:06
@genzyy I have the prettier vscode extension installed and have all the settings already. The problem is that when some people commit to the repo they fail the code check and we push the code to master. Which makes all future commits also fail even though they might have passed the code check.

**Comment by genzyy** [comment] 2021-12-03 07:37
> @genzyy I have the prettier vscode extension installed and have all the settings already. The problem is that when some people commit to the repo they fail the code check and we push the code to master. Which makes all future commits also fail even though they might have passed the code check.

So, if we add a pre-commit hook, will it be fine?

**Comment by darora** [comment] 2021-12-03 07:46
I've configured the repository to disallow merges to master that don't pass the prettier check-I believe this covers all the scenarios raised thus far on this thread.

Going to close this out-lmk if there are cases that haven't been handled.

**Closed by darora** 2021-12-03 07:46 UTC
Labels: enhancement

**Comment by darora** [comment] 2021-12-03 08:21
I've also opened #4266 which should ensure consistency between the github checks and the behaviour of locally running prettier (whether from a shell or your editor).
