### ISSUE TITLE
When using storage UI in the dashboard an error occurs during first load, refreshing reproduces error

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/supabase#16413] opened 2023-08-10 14:27 UTC
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
This error occurs when going to the storage UI or refreshing the screen on the current bucket. 
![image](https://github.com/supabase/supabase/assets/54564956/62b1bd7e-5da9-4ecf-b390-56e15ddadb62)
Everything seems to work, ignoring the error.
Several users are reporting this.

## To Reproduce
Open the storage UI in the dashboard and or refresh it.

## System information

Firefox, latest dashboard.

**Comment by shrigharat** [comment] 2023-08-19 08:11
I would like to work on this issue. Can you kindly assign this issue to me @GaryAustin1 ?

**Comment by saltcod** [comment] 2023-08-23 10:14
We don't have an assignment process @shrigharat but please feel free  to have a go at it!

**Comment by saltcod** [comment] 2023-08-23 10:14
Duplicate of https://github.com/supabase/supabase/issues/16656
closing that one ^ but worth noting that this seems to be a Firefox-only issue.

**Comment by shrigharat** [comment] 2023-08-23 10:54
Sure @saltcod will do my best.

**Comment by joshenlim** [comment] 2023-08-25 06:38
hey all! apologies this is just a red herring, there's actually nothing wrong with the project nor storage.

For context - we've got an abort signal tied to the request that fetches the contents of your folders, mainly to prevent duplicate requests. When the request gets aborted, it throws an error which then in this case incorrectly gets shown as a toast notification on the dashboard. In fact if you check our code in StorageExplorerStore [here](https://github.com/supabase/supabase/blob/e54acff76c11d951b399913c14555b353716b9ea/studio/localStores/storageExplorer/StorageExplorerStore.js#L1127), we actually do ignore the errors thrown from the abort request

But in this case, Firefox (and Opera I presume) returns a different message "The operation was aborted" - and hence ends up showing a toast message instead.

the linked PR makes this check more generic and not incorrectly show error messages from aborting requests

**Closed** 2023-10-18 07:31 UTC
Labels: bug, dashboard, storage
