### ISSUE TITLE
Tenant config for ID not found.

### ISSUE THREAD

**Issue by peterkimzz** [supabase/supabase#3351] opened 2021-09-29 03:16 UTC
My storage bucket has been removed..
Currently all of my resources are not loaded.

Unknown error popup is shown when I enter storage page in Supabase web dashboard.
And same error popup is shown when I try to create a new bucket. Nothing happened.

What happened?!

My project id is "lenrbceeiwftzaihjita"

![image](https://user-images.githubusercontent.com/20244536/135196713-80582e12-c4eb-4afb-904a-716e78ce7fee.png)

![image](https://user-images.githubusercontent.com/20244536/135197024-44fec470-566a-4173-a605-4e03b8d89dd2.png)

**Comment by inian** [comment] 2021-09-29 03:21
Hi @peterkimzz, investigating

**Comment by inian** [comment] 2021-09-29 04:39
Hi Peter, this issue has been fixed now. Sorry about this!

**Comment by Sholamide** [comment] 2022-08-16 11:55
Having the same issue,  my id is gyickivuzpdbmzfsigcx

**Comment by ibrahimsezer** [comment] 2022-08-16 14:53
Having the same issue, can you help me @inian ? my id: nhfkpakkhntozuxabevk

**Comment by jjrise** [comment] 2022-08-16 15:46
same...

**Comment by GaryAustin1** [comment] 2022-08-16 18:26
This is a known issue:
https://status.supabase.com/

**Comment by w3b6x9** [comment] 2022-08-16 19:49
Hello everyone, we have discovered the root cause of this issue and will deploy a fix to existing projects in the next few hours. We are in the process of deploying the fix and once it's out there you can create another Supabase project and get storage working immediately. I will come back here soon and provide another update on that.

**Comment by GaryAustin1** [comment] 2022-08-16 20:17
@w3b6x9 
I see the status mentions a change to an extension and uuid type...
There is another customer with a new install trying to use uiud_generate_v4() and it is not working....

|function uuid_generate_v4() does not exist

Could this be related?

**Comment by jjrise** [comment] 2022-08-16 20:19
> @w3b6x9 I see the status mentions a change to an extension and uuid type... There is another customer with a new install trying to use uuid_generate_v4() in a script and it is not working....
> 
> _function uuid_generate_v4() does not exist_
> 
> Could this be related?

https://status.supabase.com/
in their update they mentioned the uuid issue

**Comment by w3b6x9** [comment] 2022-08-16 21:15
> _function uuid_generate_v4() does not exist_
> 
> Could this be related?

@GaryAustin1 yes, that's exactly the issue.

**Comment by inian** [comment] 2022-08-16 21:46
Hi, I fixed the issue for new projects just now. If you are able to, create a new project. Will be working on a fix for affected projects next.

**Comment by GaryAustin1** [comment] 2022-08-16 21:48
@inian Just got a user with a project coming back from pause with the uuid_generate_v4() issue.  So not just "new" projects.

**Comment by inian** [comment] 2022-08-16 21:50
Yup, restores will be affected too. I will roll out the fix to them as well.

**Comment by jjrise** [comment] 2022-08-16 22:54
Works great now. Thanks for the quick fix!

**Comment by inian** [comment] 2022-08-17 04:10
If anyone else has this issue, please open a support ticket.

**Closed by inian** 2022-08-17 04:10 UTC
Labels: bug

**Comment by JasonChiu-dev** [comment] 2023-02-06 11:55
> 

Having the same issue. Tenant config for ID not found.

At first, I got "Internal Server Error" error message.  I report to supabase technical team: Support Ticket ID: 1412931335.
**I'm still waiting for a solution to this problem.**

I try to do a project restore, and get "Tenant config for ID not found" error message.

How can I solve this problem??

**Comment by ricardosikic** [comment] 2023-03-23 00:03
Hi, i have the same issue here. yesterday i ran a new project to configure snaplet. Today i went to the bucket view and the error came out

**Comment by inian** [comment] 2023-03-23 01:53
This particular issue is tied to an individual project on the hosted platform, please [send a support ticket](https://app.supabase.com/support/new) from your dashboard for us to triage this better. Going to lock this issue.
